### ISSUE TITLE
ERROR: InterpreterNotFound: python3

### ISSUE THREAD

**Issue by 1049965823** [tox-dev/tox#1010]
Python 2.7.5 and Python 3.6.6 on my Centos7 OS.

That's the Probelms:
[root@node01 python-novaclient]# tox -e pep8
pep8 create: /home/brin/python-novaclient/.tox/pep8
ERROR: InterpreterNotFound: python3
______________________________________________________________ summary _______________________________________________________________
ERROR:   pep8: InterpreterNotFound: python3

tox.ini is:
[root@node01 python-novaclient]# cat tox.ini 
# noted to use py35 you need virtualenv >= 1.11.4
[tox]
envlist = py35,py27,pep8,docs
minversion = 2.0
skipsdist = True

[testenv]
usedevelop = True
# tox is silly... these need to be separated by a newline....
whitelist_externals =
  find
  rm
......

**Comment by 1049965823** [comment]
``# noted to use py35 you need virtualenv >= 1.11.4
[tox]
envlist = py35,py27,pep8,docs
minversion = 2.0
skipsdist = True

[testenv]
usedevelop = True
# tox is silly... these need to be separated by a newline....
whitelist_externals =
  find
  rm
passenv = ZUUL_CACHE_DIR
          REQUIREMENTS_PIP_LOCATION
install_command = pip install {opts} {packages}
deps =
  -c{env:UPPER_CONSTRAINTS_FILE:https://git.openstack.org/cgit/openstack/requirements/plain/upper-constraints.txt}
  -r{toxinidir}/test-requirements.txt
  -r{toxinidir}/requirements.txt
commands =
  find . -type f -name "*.pyc" -delete
  stestr run {posargs}

[testenv:pep8]
basepython = python3
commands = flake8 {posargs}

[testenv:bandit]
basepython = python3
commands = bandit -r novaclient -n5 -x tests

[testenv:venv]
basepython = python3
deps =
  -c{env:UPPER_CONSTRAINTS_FILE:https://git.openstack.org/cgit/openstack/requirements/plain/upper-constraints.txt}
  -r{toxinidir}/test-requirements.txt
  -r{toxinidir}/requirements.txt
  -r{toxinidir}/doc/requirements.txt
commands = {posargs}

[testenv:docs]
basepython = python3
deps =
  -c{env:UPPER_CONSTRAINTS_FILE:https://git.openstack.org/cgit/openstack/requirements/plain/upper-constraints.txt}
  -r{toxinidir}/requirements.txt
  -r{toxinidir}/doc/requirements.txt
commands =
  rm -rf doc/build
  sphinx-build -W -b html doc/source doc/build/html

[testenv:releasenotes]
basepython = python3
deps =
  -c{env:UPPER_CONSTRAINTS_FILE:https://git.openstack.org/cgit/openstack/requirements/plain/upper-constraints.txt}
  -r{toxinidir}/requirements.txt
  -r{toxinidir}/doc/requirements.txt
commands =
  sphinx-build -a -E -W -d releasenotes/build/doctrees -b html releasenotes/source releasenotes/build/html

[testenv:functional]
basepython = python2.7
passenv = OS_NOVACLIENT_TEST_NETWORK
commands =
  stestr --test-path=./novaclient/tests/functional run --concurrency=1 {posargs}
  python novaclient/tests/functional/hooks/check_resources.py

[testenv:functional-py35]
basepython = python3.5
passenv = OS_NOVACLIENT_TEST_NETWORK
commands =
  stestr --test-path=./novaclient/tests/functional run --concurrency=1 {posargs}
  python novaclient/tests/functional/hooks/check_resources.py

[testenv:cover]
basepython = python3
setenv =
    PYTHON=coverage run --source novaclient --parallel-mode
commands =
    stestr run {posargs}
    coverage combine
    coverage html -d cover
    coverage xml -o cover/coverage.xml
    coverage report

[flake8]
# Following checks should be enabled in the future.
#
# H404 multi line docstring should start without a leading new line
# H405 multi line docstring summary not separated with an empty line
#
# Following checks are ignored on purpose.
#
# Additional checks are also ignored on purpose: F811, F821
ignore = F811,F821,H404,H405
show-source = True
exclude=.venv,.git,.tox,dist,*lib/python*,*egg,build,doc/source/conf.py,releasenotes

[hacking]
import_exceptions = novaclient.i18n

[testenv:bindep]
basepython = python3
# Do not install any requirements. We want this to be fast and work even if
# system dependencies are missing, since it's used to tell you what system
# dependencies are missing! This also means that bindep must be installed
# separately, outside of the requirements files.
deps = bindep
commands = bindep test

[testenv:lower-constraints]
basepython = python3
deps =
  -c{toxinidir}/lower-constraints.txt
  -r{toxinidir}/test-requirements.txt
  -r{toxinidir}/requirements.txt

**Comment by gaborbernat** [comment]
Given it's said in our documention that you need to separate it by newline I would not call it sillyhttps://tox.readthedocs.io/en/latest/config.html#conf-whitelist_externals

**Comment by 1049965823** [comment]
Bad character, strong ability and how？
