### ISSUE TITLE
Improve dependency validation for environment reuse

### ISSUE THREAD

**Issue by janhn** [tox-dev/tox#1018]
When a virtual environment already exists, tox performs some validation steps to decide whether it can be reused. One of the steps seems to be a comparison of the dependencies (deps= clause). Currently this seems to be done by comparing the entry lists, including file paths.

When executing tox to work on the same environments from different directories, this tests will always fail, resulting in a rebuild of the virtual env.

An example:
```
py27 cannot reuse:                                                                                                 
 {('00000000000000000000000000000000', '-r/original/build/path/requirements.txt')}                            
 !=                                                                                                                 
 {('00000000000000000000000000000000', '-r/different/execution/path/requirements.txt')}
```

This may be improved for example by comparing file checksums, instead of paths.

(This issue came from #410)

**Comment by gaborbernat** [comment]
I would say we first want to resolve to absolute paths and then also add checksums.

**Comment by janhn** [comment]
I think the paths are already being resolved to absolute.

It also seems this might help solve #149 (even already suggested in https://github.com/tox-dev/tox/issues/149#issuecomment-247789722).

**Comment by gaborbernat** [comment]
This now has been implemented in tox 4 alpha.
