### ISSUE TITLE
Intermittent failures when using --parallel--safe-build with parallel builds

### ISSUE THREAD

**Issue by lkollar** [tox-dev/tox#1026]
When using `--parallel--safe-build` option in Jenkins as described in the [documentation](https://tox.readthedocs.io/en/latest/example/jenkins.html#running-tox-environments-in-parallel) sometimes one of the builds fails when tox is generating the sdist.

It seems that the sdist is being generated in the source directory which is shared across the builds.

```
running sdist
running egg_info
writing <redacted>.egg-info/PKG-INFO
writing dependency_links to <redacted>.egg-info/dependency_links.txt
writing requirements to <redacted>.egg-info/requires.txt
writing top-level names to <redacted>.egg-info/top_level.txt
reading manifest file '<redacted>.egg-info/SOURCES.txt'
writing manifest file '<redacted>.egg-info/SOURCES.txt'
running check
warning: check: missing required meta-data: url

copying files to <redacted>-0.3.0...
copying setup.py -> <redacted>-0.3.0
copying <redacted>.egg-info/PKG-INFO -> <redacted>-0.3.0/<redacted>.egg-info
error: could not create '<redacted>-0.3.0/<redacted>.egg-info/PKG-INFO': No such file or directory
```

OS: RHEL 6.8 amd64
`pip list` output:
```
Package        Version
-------------- -------
<redacted>  0.3.0
pip            18.0
pluggy         0.7.1
py             1.6.0
setuptools     39.2.0
six            1.11.0
toml           0.9.6
tox            3.4.0
virtualenv     16.0.0
```

**Comment by gaborbernat** [comment]
Mangling with the dist/distshare folders turned out to be incorrect; as they may be other intermediate folders that can still conflict. The proper solution will be to hold a file lock onto the build env all throughout performing the build. We'll do this in the next release. Thanks for reporting!
