### ISSUE TITLE
tox >= 3.2.0 breaks module import

### ISSUE THREAD

**Issue by ThomasWaldmann** [tox-dev/tox#1037]
After working ok for a long time, suddenly our build on travis-ci (linux) started to fail, having troubles importing the "main" module `borg.archiver`.

I had the suspicion that it might be due to a tox change / regression, so i downgraded tox and it worked again.

See there for details / links to travis:

https://github.com/borgbackup/borg/issues/4094

**Comment by gaborbernat** [comment]
Can you investigate and find the actual problem?

**Comment by ThomasWaldmann** [comment]
The problem is that the import is not working.

I tried to reproduce it locally, but failed to (works ok). Don't feel like debugging this on travis.

**Comment by obestwalter** [comment]
Hi @ThomasWaldmann I saw you "fixed" it, by freezing the tox version. Did you try again with a recent version of tox? If that problem still occurs it might be worth having a closer look.

**Comment by ThomasWaldmann** [comment]
@obestwalter I am doing some experiments right now, see issue link above.

**Comment by obestwalter** [comment]
Still broken then ... https://travis-ci.org/borgbackup/borg/jobs/479214516

What changed between 3.2 and 3.3 [was mainly adding pep 517 support](https://github.com/tox-dev/tox/compare/3.2.0...3.3.0), so my hunch is that it has to do with that, but I have no time to look further atm.

**Comment by ThomasWaldmann** [comment]
IIRC, it was the change to 3.2.0 (not: 3.3.0) that broke it.

**Comment by obestwalter** [comment]
oh `<=` :). that looks much less suspicious even ...

https://github.com/tox-dev/tox/compare/3.1.0...3.2.0

**Comment by ThomasWaldmann** [comment]
https://github.com/tox-dev/tox/compare/3.1.3...3.2.0 3.1.3 work, 3.2.0 not, so this is the suspicious diff.

not sure how the dependencies/requirements of tox changed, whether we need to search there also.

**Comment by rpkilby** [comment]
> I can remember dimly that we tried to change from pip to python -m pip during the sprint in 2016 and had weird effects in one package, so it really might have to do with that.

I commented on additional `pip` vs `python -m pip` weirdness [here](https://github.com/tox-dev/tox/pull/935#issuecomment-415365371). I don't know if it's related/helpful, but your comment jogged my memory.

**Comment by jugmac00** [comment]
The OP has moved away from Travis and the affected branch is out of maintenance.

**Comment by ThomasWaldmann** [comment]
Right, borg 1.0-maint branch won't see updates. Also, we do not currently see this tox issue.
