### ISSUE TITLE
do not use setup.cfg file that does not have tox:tox namespace

### ISSUE THREAD

**Issue by williamjamir** [tox-dev/tox#1045]
Hi,

I would like to suggest a check to ensure that a `tox.ini` file is present when calling the `tox` command.

I'm saying this because by mistake I've named the file `tox.ini` as `.tox.ini` and took me a time to figure it out the problem.

The build had five stages:
```
py27, py36, py37, linting, docs
```
[Link for the Travis build with all stages listed](https://travis-ci.org/williamjamir/test-cookiecutter/builds/438427625)

The stages py27, py36, py37 was marked as "successful", even though nothing was tested.
[Link for the job py37](https://travis-ci.org/williamjamir/test-cookiecutter/jobs/438427637)

While the stages `linting` and `docs` were raising an `Error`
```
ERROR: unknown environment 'linting'
```

I believe that this type of information leads to misinterpretation since the user could believe that the configuration is ok (because the py* was marked as successful) and the problem is related with the "linting/docs" stage.

**Comment by gaborbernat** [comment]
@williamjamir at the moment if we fail to find a configuration fail we stop with error and the message:

```
tox
ERROR: tox config file (either pyproject.toml, tox.ini, setup.cfg) not found
```

If you did not get it means you most probably had a tox.ini file discovered by following the rules from https://tox.readthedocs.io/en/latest/config.html#configuration-discovery. 

Furthermore, if you call tox with a verbose flag you'll see explicitly stated what config is used:

```
tox -v
using tox.ini: /home/bernat/git/tox/tox.ini
using tox-3.5.0 from /home/bernat/.local/lib/python3.7/site-packages/tox/__init__.py
```

The tools/checks are already there I think, you just need to use it. Let me know if you need anything else.

**Comment by williamjamir** [comment]
Thanks for the answer @gaborbernat =)
I've added the flag `-v` and as you have mentioned, another file was being used as the configuration for `tox`.

```
$ tox -v
using tox.ini: /home/travis/build/williamjamir/test-cookiecutter/setup.cfg
ERROR: unknown environment 'linting'
```

On the documentation the following note is added:
> Note that setup.cfg requires the content to be under the tox:tox section. 

Perhaps the existence of the `tox:tox` section inside the `setup.cfg` should not be verified as well?

**Comment by gaborbernat** [comment]
Indeed it should, not sure how trivial it is to added will have a look. Feel free to shoot a pr if you have time for it.

**Comment by hroncok** [comment]
This now surprised me as well. In Fedora, we promote the use of `tox` in RPM tests and "no tests found, but exit code 0" is something I'd like to avoid because it creates a false sense of being tested ("oh, this package runs tox and the build passed, all is :unicorn: :rainbow:").

I'll try to have a look on how to solve this, no timeline thou.

**Comment by hroncok** [comment]
Here https://github.com/tox-dev/tox/pull/1642

**Comment by gaborbernat** [comment]
Released via https://pypi.org/project/tox/3.19.0/

**Comment by devmcp** [comment]
This update breaks system.cfg files that use [tox], rather than [tox:tox], giving the following error:

```ERROR: tox config file (either pyproject.toml, tox.ini, setup.cfg) not found```

Was this intentional?

**Comment by hroncok** [comment]
I was following the documentation in here.

**Comment by hroncok** [comment]
Sorry for the brief comment previously. According to the docs, the configuration in `setup.cfg` must be namespaced as `[tox:tox]`. If that was not the case, we can certainly allow `[tox]` as well and document it.

**Comment by gaborbernat** [comment]
I think it's intentional breaking here.
