### ISSUE TITLE
sdists are hardlinked into a temp directory, which fails in some environments (e.g. Vagrant)

### ISSUE THREAD

**Issue by samdbmg** [tox-dev/tox#1050]
Hi,

After creating an sdist in tox >= 3.5.0, the resulting file is hardlinked into a temp directory. Unfortunately this doesn't work on some filesystems; notably inside a Virtualbox shared folder. For example when running in Vagrant's `/vagrant` directory under Virtualbox; symlinks are possible but it seems hardlinks have never been.

`create_session_view()` attempts to check if we can do hardlinks, but only in that `os.link()` exists, which of course it does if the guest OS is Unix-based, regardless of what the filesystem supports. See https://github.com/tox-dev/tox/blob/3e56c9db524d9634bfb0782e06923c5a1f4db4b1/src/tox/package.py#L72

Perhaps it would be better to wrap the `os.link()` call in a `try...except` and fall back to copy on `OSError` or `AttributeError`? I would submit a PR, but I'm not sure how to test all three cases.

Pip list output:
```
Package         Version
--------------- ----------------------
ansible         2.7.0
asn1crypto      0.24.0
awscli          1.16.28
bcrypt          3.1.4
boto3           1.9.18
botocore        1.12.18
cffi            1.11.5
colorama        0.3.9
configparser    3.5.0
cryptography    2.3.1
detox           0.15
dnspython       1.15.0
docutils        0.14
enum34          1.1.6
eventlet        0.24.1
filelock        3.0.9
flake8          3.5.0
futures         3.2.0
greenlet        0.4.15
idna            2.7
ipaddress       1.0.22
Jinja2          2.10
jmespath        0.9.3
MarkupSafe      1.0
mccabe          0.6.1
monotonic       1.5
paramiko        2.4.2
passlib         1.7.1
pip             18.1
pluggy          0.7.1
py              1.6.0
pyasn1          0.4.4
pycodestyle     2.3.1
pycparser       2.19
pyflakes        1.6.0
PyNaCl          1.3.0
pyOpenSSL       18.0.0
python-apt      1.1.0b1+ubuntu0.16.4.2
python-dateutil 2.7.3
PyYAML          3.13
rsa             3.4.2
s3transfer      0.1.13
setuptools      40.4.3
simplejson      3.8.1
six             1.11.0
toml            0.10.0
tox             3.5.1
urllib3         1.23
virtualenv      16.0.0
wheel           0.32.1
```

Guest OS: Ubuntu 16.04.5 LTS
Host OS: macOS High Sierra 10.13.6

Thanks for submitting an issue!

If submitting a BUG please provide:

- [] Minimal reproducible example or detailed description, assign "bug"
- [✅] OS and `pip list` output

**Comment by samdbmg** [comment]
...and I've just seen this is probably fixed by 3.5.2 in #1049 - see https://github.com/tox-dev/tox/blob/1cb19873d14f8ed5137716b4aadced0f5a47882a/src/tox/package.py#L77

**Comment by gaborbernat** [comment]
Done via https://github.com/tox-dev/tox/pull/1046, just releasing via https://github.com/tox-dev/tox/pull/1049. Feel free to test it :+1:

**Comment by samdbmg** [comment]
Looks good to me, and resolves the problem I was having, cheers. 👍

**Comment by gaborbernat** [comment]
Enjoy and thanks for the report!
