### ISSUE TITLE
How to choose python version used for packaging?

### ISSUE THREAD

**Issue by paternal** [tox-dev/tox#1060]
Since version 40.1.0, setuptools provides a [`find_namespace_packages()`](https://setuptools.readthedocs.io/en/latest/setuptools.html#find-namespace-packages) function to work with [PEP420](https://www.python.org/dev/peps/pep-0420/) namespace packages. The problem is that:
- this function is only available with Python3;
- as far as I can tell, tox uses Python2 for packaging, and one cannot specify which python version to use.

This leads to fails like [this one](https://framagit.org/spalax/sphinxcontrib-proof/-/jobs/242678): before even testing the package (where I can choose which python version to use), tox tries to build the package (`python setup.py sdist`), but it uses python2, which does not include `find_namespace_package()`. Thus, packaging fails.

To solve this, a new [global setting](https://tox.readthedocs.io/en/latest/config.html#tox-global-settings) could be defined, defining the python binary to use for packaging.

Thanks for your work,
Louis

**Comment by gaborbernat** [comment]
@paternal this has already be done, see  https://tox.readthedocs.io/en/latest/config.html#conf-isolated_build and https://tox.readthedocs.io/en/latest/example/package.html

Otherwise tox does not use Python 2 only for packaging. If no isolated build is specified then it uses the python under what tox is installed.

**Comment by paternal** [comment]
Great! Sorr

**Comment by gaborbernat** [comment]
No worries; hope it works great for you. If not give us a follow-up shoutout.
