### ISSUE TITLE
Isolated build option hard to find

### ISSUE THREAD

**Issue by tonybaloney** [tox-dev/tox#1077]
I'd heard tox supported pyproject.toml, i'm working on a project using flit for build + publishing and have all my dependancies in the pyproject.toml file.

Steps I took:

```
 > pip install tox
 > tox -e py37
ERROR: tox config file (either pyproject.toml, tox.ini, setup.cfg) not found
```
This is confusing, since pyproject.toml does exist (but I don't have any tox configuration in there).

That's issue 1.

So then I ran `tox-quickstart`

```console
 > tox-quickstart
Welcome to the tox 3.5.3 quickstart utility.
... (removed for brevity)
Finished: ./tox.ini has been created. For information on this file, see https://tox.readthedocs.io/en/latest/config.html
Execute `tox` to test your project.
(venv) ➜  wily git:(master) ✗ tox -e py37   
ERROR: No setup.py file found. The expected location is:
  /Users/anthonyshaw/PycharmProjects/wily/setup.py
You can
  1. Create one:
     https://packaging.python.org/tutorials/distributing-packages/#setup-py
  2. Configure tox to avoid running sdist:
     https://tox.readthedocs.io/en/latest/example/general.html#avoiding-expensive-sdist
```

This is confusing for users

After some reading of pull requests to tox I found https://tox.readthedocs.io/en/latest/example/package.html?highlight=flit#flit

I'm not really sure what I'm suggesting here, but maybe a step in `tox-quickstart`? or a suggestion in the error message for the `sdist` issue, that spots the existence of pyproject.toml and says the `isolated_build` option is available?

**Comment by tonybaloney** [comment]
@gaborbernat @asottile

**Comment by asottile** [comment]
hmmm indeed, quickstart definitely should mention something here.  Or maybe we should auto-detect if `pyproject.toml` exists and has the appropriate pep 518 metadata?  what're your thoughts here @gaborbernat ?

**Comment by tonybaloney** [comment]
1st prize would be auto-detecting the setup and enabling isolated build

**Comment by gaborbernat** [comment]
I'm happy with auto-detect -> auto-enable if it's behind a flag to disable this auto feature (can be on by default).

**Comment by NameArtem** [comment]
You can write only basic params (for testing) and It should be work

```
[tox]
envList = MyEnvName
skipsdist = True
```

Save and run:
```
tox
```

**Comment by gaborbernat** [comment]
tox 4 solves this for what it's worth (see rewrite branch).
