### ISSUE TITLE
isolated build should validate dependencies are PEP-440 compatible

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/tox#1086]
And if not throw an error. See #1085 for a such case.

**Comment by pquentin** [comment]
It's surprising that inheritance is the default behavior. Since the dependencies are already specified in the pyproject.toml file, I don't actually know in which cases we don't want to use this workaround mentioned in #1085:

```
[testenv:.package]
 # no additional dependencies besides PEP 517
deps =
```

Maybe this should be the default behavior?

**Comment by gaborbernat** [comment]
The main problem with making it the default is that it would have to be a special case now, and can throw off people expecting us to follow the usual rules. Also not clear how this should interact with our more advanced features such as factor dependencies 🤔

**Comment by pquentin** [comment]
Maybe tox should not use inheritance for isolated builds in the first place? There are probably many problems with this suggestion too.

**Comment by gaborbernat** [comment]
Again the main argument against is that now we have separate rules for just one type of environment. Forking the logic and introducing new env types feels at the moment the greater evil, but I'm open to suggestions. Again we need to think about the entire system as a whole not just for one edge case.

**Comment by gaborbernat** [comment]
I think this should now be fixed with version 4 (rewrite branch). If still reproducible please post it and we'll reopen it.
