### ISSUE TITLE
Consider linking to Nox & other related projects

### ISSUE THREAD

**Issue by theacodes** [tox-dev/tox#1088]
Hey foiks,
I'm the maintainer of [Nox](http://nox.thea.codes/en/stable/), a tool that is similar to Tox in purpose but different in spirit. One of the things we found to be really useful was to tell our users about [other projects](http://nox.thea.codes/en/stable/#other-useful-projects) that they might be interested in looking at if they're considering our using Nox.

I'm wondering if Tox would be interested in likewise linking to Nox (& possibly PyInvoke). I think our projects could benefit from more cross-linking. For example, it seems that some of the feature requests here are already possible with Nox's approach (and vice-versa). We could point our users to each other in those cases so that they can get unblocked quickly and we can better prioritize requests.

I'm more than happy to write a pull request to add this to the docs, I just wanted to reach out and make sure that this would be a welcome addition. If not, that's totally fine. :)

Thanks!

**Comment by theacodes** [comment]
Excellent!

> Note tox is always written with lowercase, no capitalization should be applied to it, similar to pytest.

I seem to remember doing some research and couldn't figure out one way or the other on the casing, so I erred on the side of using uppercase. Thanks for clarifying, I've sent https://github.com/theacodes/nox/pull/160 to fix that. :)

> while at it py.test is also nowadays dropped the dot and they prefer just pytest

Also fixed that, good call out. I thought we'd gotten all of them but a few always slip by.

> Just keep it short and explain briefly why one would want to use over the other. 

Great, I'll put together a PR soon. Do you have a preference for where such a section would go? I would like to link to both Invoke and Nox if that's oaky.

**Comment by gaborbernat** [comment]
I'm okay with end of index page.Yeah it's ok.
