### ISSUE TITLE
using computed value based on env var if set, with default if not

### ISSUE THREAD

**Issue by freddrake** [tox-dev/tox#1094]
I've been using **tox** with a ``coverage-report`` environment run after all my other tests are run, so I can collect coverage across Python versions.  This looks like this:

~~~~~~~~~ ini
[testenv:coverage-report]
commands =
    coverage combine
    coverage html --directory {env:COVERAGE_PATH:htmlcov}
~~~~~~~~~

This use of ``{env:...}`` let's me store all my coverage reports in a common location (easily served by a web server), and keeps the surprise level down for devs who don't want to set up their environment down.

But I have to set the environment variable differently for each project I want to do this for, which is error-prone.  I'd like to set my environment variable to some directory that contains directories for each package, otherwise use some default:

* If set, use ``{env:COVERAGE_PATH}/my.package``, otherwise

* use ``{env:COVERAGE_PATH:htmlcov}`` as a default.

Extending the ``{env:...}`` syntax further sounds like opening the door to a nightmare, and would have severe compatibility issues for anyone with a colon in their default values.

I can imagine a **tox** plugin that hooks ``tox_addoption`` and mutates ``os.environ`` instead of actually adding an option.  Is there a better approach that I've missed?

**Comment by gaborbernat** [comment]
I cannot clearly understand what you're trying to achieve here, can you try to rephrase? we ourselves use a coverage env to sum up, can you have a look toxs tox.ini and CI?

**Comment by gaborbernat** [comment]
isn't this just an en var with a default?

**Comment by freddrake** [comment]
Not quite; the nuance is that the computed value is needed when the value *is set*, rather than when it is not.

Playing around a bit more, it turns out that **coverage** doesn't replace the ``htmlcov`` directory itself; it only replaces the contents.  Creating a symlink does the job just fine (so long as I remember), and doesn't require anything special in the **tox** configuration at all.

(I'd also tried using a hateful ``.env`` file or a wrapper command, but didn't really like those options either.)

The symlink for ``htmlcov`` will suffice, and is certainly better than hacking something into **tox** via a plugin.
