### ISSUE TITLE
why the arguments are changed?

### ISSUE THREAD

**Issue by Huarong** [tox-dev/tox#1095]
When using the *posargs*， the path in the argument is changed with no reason. Why ?

tox.ini
```
[tox]
envlist=py27,py36
skipsdist=True

[testenv]
deps = pytest
commands=pytest -s tests {posargs}
```

![image](https://user-images.githubusercontent.com/1487879/49358412-8dc60300-f70d-11e8-890e-7559e484b4ab.png)

**Comment by asottile** [comment]
hmmm wow yeah there appears to be something seriously wrong here.

Here's another fun one:

```ini
[tox]
skipsdist = True

[testenv]
changedir=../
commands =
    python -c 'import sys; print(sys.argv[1:])' {posargs}
```

```console
$ tox -e py36 -- $PWD/tox.ini
py36 runtests: PYTHONHASHSEED='659093790'
py36 runtests: commands[0] | python -c 'import sys; print(sys.argv[1:])' x/tox.ini
['x/tox.ini']
___________________________________ summary ____________________________________
  py36: commands succeeded
  congratulations :)
```

it appears to be attempting to normalize paths to account for `changedir` -- but doing so incorrectly.

Thanks for the report! 🎉

**Comment by asottile** [comment]
There's this relevant bit [from the docs](https://tox.readthedocs.io/en/latest/config.html#substitutions-for-positional-arguments-in-commands) indicating the adjustment is intentional, at least for relative paths:

> `tox` rewrites each positional argument if it is a relative
> path and exists on the filesystem to become a path relative to the
> `changedir` setting.
