### ISSUE TITLE
Is there an easy way to read a `.env` file? (setenv, dotenv)

### ISSUE THREAD

**Issue by bittner** [tox-dev/tox#1104]
I've recently stumbled across Pipenv's [automatic reading of `.env` files](https://pipenv.readthedocs.io/en/latest/advanced/#automatic-loading-of-env). It was a huge surprise to see this convention integrated so tightly. But now that I've become used to the idea I'm missing the same feature in Tox.

Hence my question: Is there an easy way for reading the contents of a `.env` file into the execution environment that run the tests (the "tox environments")?

The only sensible solution I found so far is prefixing the executed command with `env $(grep -v '^#' .env | xargs)` (courtesy of [StackOverflow](https://stackoverflow.com/questions/19331497/set-environment-variables-from-file-of-key-pair-values/20909045#20909045)). It would be nice, though, to have a more explicit, configuration-based approach to solve this.

Maybe I'm missing something, but I don't see anything related to this idea neither [in the docs](https://tox.readthedocs.io/en/latest/config.html) nor in the issues here on GitHub.

**Comment by obestwalter** [comment]
Is there anything that pipenv doesn't do? Joking aside: I think this should be implemented as a plugin, but I am pretty sure there needs to be added a new hook then for injecting environment variables into the subprocess.

**Comment by gaborbernat** [comment]
This is just loading the env file and adding into the environments ``setenv``. That will make it work. The request is just to support env files for setenv I believe, in the spirit of having one place specified these. I personally would argue against setting env vars at tox level in case you're using pytest, https://pypi.org/project/pytest-env/ is a much better solution in such case and a better place of abstraction.

**Comment by bittner** [comment]
@gaborbernat I can't see what problem pytest-env is solving that would cover execution environment specific values (aka `.env`). According to its README it's again [hardcoding key-value pairs](https://github.com/MobileDynasty/pytest-env#usage). Can you help me understand?

The specific problem I'm currently facing is that I run tests (for a Django project) locally and on a CI service (GitLab CI). The `DJANGO_DATABASE_URL` that I need to set for running the (functional) tests contains `localhost` for the tests that I run locally and should have `postgres` as a hostname on GitLab CI.

Maybe I can use [passenv](https://tox.readthedocs.io/en/latest/config.html?highlight=passenv#conf-passenv) to pass values from "outside", i.e. the CI configuration, and that would override the values in the `setenv` section? I have to try.

**Comment by obestwalter** [comment]
> Maybe I can use passenv to pass values from "outside", i.e. the CI configuration, and that would override the values in the setenv section? I have to try.

passenv passes through whatever you ask it to. This is the standard approach to handling this.

Using a tool that automatically activates environment variables when changing into a directory (e.g. https://direnv.net/) and pass through whatever is needed with setting passenv would also be a convenient workflow for something like that.

**Comment by bittner** [comment]
That sounds like a good idea. My approach is still flawed, though. I'm trying to - optionally - override an environment value that I first _declare_ in `setenv` in `tox.ini`. That doesn't seem to work.

The [documentation](https://tox.readthedocs.io/en/latest/config.html?highlight=passenv#conf-passenv) confirms that it's the other way around: "You can override these variables with the `setenv` option" referring to the always passed through variable `PATH`, `LANG`, etc.

I solved my problem with a variable substitution [default value](https://tox.readthedocs.io/en/latest/config.html?highlight=passenv#environment-variable-substitutions-with-default-values):
```ini
[testenv]
setenv =
    DATABASE_URL={env:DATABASE_URL:postgres://foo:bar@localhost/database}
 ```

That works out. It would still be nice to have a way to read a `.env` file (like Docker Compose and other tools do it---not only Pipenv :smile:). Why? Because this way I could have a single source of truth for these values (I need the same values in, e.g., `docker-compose.yml` and `tox.ini`).

That could be a setting called `readenv`, `dotenv` or simply `env`, e.g.

```ini
[testenv]
env = {toxinidir}/.env
setenv =
    FOOBAR=overriding-value
 ```

**Comment by obestwalter** [comment]
> I'm trying to - optionally - override an environment value that I first declare in setenv in tox.ini. That doesn't seem to work.

True that doesn't work. setenv wins over passenv. I am not aware if this was ever an explicit design decision, but I guess this is just how it happens to work and no one ever had an issue with it, but now I understand where you are coming from.

**Comment by obestwalter** [comment]
Just did a bit of reading.

`setenv` was added in 0.9 and `passenv` was added in 2.0.

In passenv it [says explicitly](https://tox.readthedocs.io/en/latest/config.html#conf-passenv):

> You can override these variables with the setenv option.

So this is by design after all and makes sense looking at how those features grew. I would not mind having an explicit third option to populate the testrun with variables from `.env` though.

Having all these options then though, I feel, that it would start to make sense to have the concept of mutual exclusivity for certain keys (e.g. in this case - if you use `readenv` you mustn't use `passenv` and `setenv` or something like that). 

I think this does not exist yet and in general the whole configuration is much too forgiving, which makes debugging harder, but this would be something for another issue.

**Comment by bittner** [comment]
> Having all these options then though, I feel, that it would start to make sense to have the concept of mutual exclusivity for certain keys (e.g. in this case - if you use readenv you mustn't use passenv and setenv or something like that).

I don't think this would be necessary. At least not for `setenv`.

The way `passenv` and `setenv` work together, currently, seems perfectly fine. Sure, with a new `readenv` (or `env`) option we _could_ enforce the use of either `passenv` or `readenv` (a rather arbitrary restriction) to avoid confusion. But it's okay if `setenv` always overrules.

Alternatively, we would need to define the order of precedence for `readenv` and `passenv`, i.e. which one is evaluated before the other, which one overrides the values of the other. That should then probably look at how other tools handle the same situation.

**Comment by obestwalter** [comment]
> That should then probably look at how other tools handle the same situation.

Sounds like a good idea.

**Comment by gaborbernat** [comment]
I still think this should be done at the tool level, rather than tox level so will close until we come up with something actionable.

**Comment by seanh** [comment]
I've written a tox plugin to read envvars from env files and inject them into the environment that tox runs your commands in: https://github.com/seanh/tox-envfile (_Very_ new, "seems to work" based on barely any testing.)

For now it's more basic than the `readenv = {toxinidir}/.env` setting in `tox.ini` that was suggested above, but I think it meets my immediate needs. Could be improved later.

**Comment by kojiromike** [comment]
I was able to load the environment in tox by adding `python-dotenv` as a dep and making my command `dotenv -f .env.example run pytest`.
