### ISSUE TITLE
Fix indentation in our tox.ini and the docs

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#1110]
Going through the docs I saw this:

```ini
[tox]
minversion = 2.0
envlist = py{27,36}-{mylinux,mymacos,mywindows}

[testenv]
sys.platform string
platform = mylinux: linux
           mymacos: darwin
           mywindows: win32

# you can specify dependencies and their versions based on platform filtered environments
deps = mylinux,mymacos: py==1.4.32
       mywindows: py==1.4.30

# upon tox invocation you will be greeted according to your platform
commands=
   mylinux: python -c 'print("Hello, Linus!")'
   mymacos: python -c 'print("Hello, Steve!")'
   mywindows: python -c 'print("Hello, Bill!")'
```

there are two different ways of indenting multi-line values used here and all over the docs:

```ini
somekey = foo = BAR
          bar
          baz
somothermuchlongerkey = foo = BAR
                        bar
                        baz
```

vs

```ini
somekey = 
    foo = BAR
    bar
    baz
somothermuchlongerkey = 
    foo = BAR
    bar
    baz
```

I strongly prefer variant two not just for aesthetical reasons. I find it much easier to read. Especially for things like

```ini
deps = mylinux,mymacos: py==1.4.32
       mywindows: py==1.4.30
```

```ini
deps = 
    mylinux,mymacos: py==1.4.32
    mywindows: py==1.4.30
```

the second variant is much clearer and easier to read.

**Comment by gaborbernat** [comment]
I personally prefer the smaller number of lines. It's more compact and I find there's plenty of wide space on today's monitors.

**Comment by gaborbernat** [comment]
I also think having a single indentation by the equal sign makes things more readable, but that could be just me.

**Comment by obestwalter** [comment]
> It's more compact and I find there's plenty of wide space on today's monitors.

My personal experience is that I prefer shorter line lengths independent of how wide my monitor is. I was really happy with Pythons PEP 8 limitation of 79 chars per line. Even with a line length of 88 a side by side diff is breaking up already if your eyesight is not that great (like mine) and need a bigger font. The even longer line length of the code in the tox project feels really unwieldy to me and that is also something I would like to address, but not in this issue.

**Comment by gaborbernat** [comment]
I've personally like 120, but decided to meet you half way at 99 back when we introduced black. I guess this is the place where we diverge on opinions on what is easy to read. I myself find hard to read when we try to squeeze stuff into 88 characters.

**Comment by obestwalter** [comment]
> that is also something I would like to address, but not in this issue.

-- me further above :)

**Comment by gaborbernat** [comment]
Well I was just putting it out that we probably would have a sharp difference of opinion would you open that issue, as it would feel like you're opening issues already discussed and settled a few months back.

**Comment by asottile** [comment]
@obestwalter strong agree from my end on your preference of format.  Avoids manual 13-space indents and is much easier to separate key from value.

**Comment by jugmac00** [comment]
At least the upcoming version 4 uses `tox-ini-fmt` via `pre-commit` which autoformats `tox.ini`.

Issue can be closed as soon as we support `tox4`.

**Comment by jugmac00** [comment]
I just skimmed the documentation for tox4, and the indentation looks good!

Though, the example section has not been moved over to the tox4 documentation.

@gaborbernat What are your plans for https://tox.readthedocs.io/en/3.24.1/examples.html ? Will we have an example section for tox4, too? I am all in favor, but we'd need to go through all examples and check whether they are still valid (e.g. the subsection on nose can be omitted).

**Comment by gaborbernat** [comment]
Yeah, basically those :+1: will create a new ticket for the examples :+1:

**Comment by gaborbernat** [comment]
See https://github.com/tox-dev/tox/issues/2143
