### ISSUE TITLE
Filelock with NFS fails

### ISSUE THREAD

**Issue by ooglek** [tox-dev/tox#1115]
File locking fixed in Issue #1026 ( PR https://github.com/tox-dev/tox/pull/1032 ) now creates an issue when the filesystem is mounted via NFS.

https://stackoverflow.com/questions/37633951/python-locking-text-file-on-nfs

Situation:

1. Vagrant-started VM in VMWare Fusion on MacOS running CentOS Linux release 7.5.1804 (Core)
2. Filesystem on MacOS is mounted inside the VM via NFS
3. Running "tox" hangs on a filesystem file lock file forever

Versions:
- Python 2.7.5
- tox 3.6.1
- CentOS Linux 7.5.1804

Output:
```
(.venv) [root@hal api]# rm -rf .tox
(.venv) [root@hal api]# tox
lock file /vagrant/proj/python/api/.tox/.package.lock present, will block until released
```
and hangs forever. If I `chmod 000 .tox/.package.lock` tox will exit:
```
OSError: [Errno 13] Permission denied: '/vagrant/proj/python/api/.tox/.package.lock'
```

##### pip list
```
filelock (3.0.10)
pip (9.0.1)
pluggy (0.8.0)
py (1.7.0)
setuptools (40.6.3)
six (1.12.0)
toml (0.10.0)
tox (3.6.1)
virtualenv (16.2.0)
wheel (0.29.0)
```

### Possible Solutions
1. Use `flufl.lock` https://flufllock.readthedocs.io/en/latest/
2. Use the stackoverflow code (and write a lot of tests!)

### Caveats
We use Python 2.7 for reasons that might not make sense outside of the bubble we exist in, but likely isn't going to change.

**Comment by gaborbernat** [comment]
``flufl.lock`` does not support Python 2, so not likely we'll switch to that. The second seems a lot of burden to take on within this project. If anything I would mark it as a filelock bug.

**Comment by ooglek** [comment]
You're using [filelock](https://github.com/benediktschmitt/py-filelock). From their docs:

> The FileLock is platform dependent while the SoftFileLock is not. Use the FileLock if all instances of your application are running on the same host and a SoftFileLock otherwise.
> 
> The SoftFileLock only watches the existence of the lock file. This makes it ultra portable, but also more prone to dead locks if the application crashes. You can simply delete the lock file in such cases.

FileLock will use UnixFileLock on Linux which attempts to open an exclusive lock, which fails with NFS.

https://github.com/benediktschmitt/py-filelock/blob/master/filelock.py#L377-L392

SoftFileLock only creates the file but does not attempt to create an exclusive lock using `flock`

https://github.com/benediktschmitt/py-filelock/blob/master/filelock.py#L408-L421

Replacing FileLock with SoftFileLock should accomplish the same goal while doing so in an NFS-safe and cross-platform way.

I'll test and push a PR if I can get it working.

**Comment by gaborbernat** [comment]
Go ahead and let us know 👍

**Comment by jamieluckett** [comment]
Did this ever go anywhere? This issue still exists

**Comment by ooglek** [comment]
I never had a chance to test changes and make a PR. My need for this fix has departed with the wind, and thus my motivation to fix it is also dead and gone with it.

You are welcome to pick it up and run with it! It seems like an easy change.

**Comment by jamieluckett** [comment]
@ooglek I'll probably end up having a look tomorrow, it (hopefully) shouldn't be too painful!

**Comment by gaborbernat** [comment]
The fix would be upstream in filelock, so closing this issue.
