### ISSUE TITLE
Conflicting basepython check fails for factor+testenv combination

### ISSUE THREAD

**Issue by ionelmc** [tox-dev/tox#1124]
For this given `tox.ini`:
```ini
[tox]
envlist =
    {py27,py34,py35,py36,py37}-{cover,nocov}

[testenv]
basepython =
    py27: {env:TOXPYTHON:python2.7}
    py34: {env:TOXPYTHON:python3.4}
    py35: {env:TOXPYTHON:python3.5}
    py36: {env:TOXPYTHON:python3.6}
    py37: {env:TOXPYTHON:python3.7}
commands =
    python -c 'import sys; print(sys.version_info)'

[testenv:py27-cover]
usedevelop = true

[testenv:py34-cover]
usedevelop = true

[testenv:py35-cover]
usedevelop = true

[testenv:py36-cover]
usedevelop = true

[testenv:py37-cover]
usedevelop = true
```
I get this sort of output:
```
> tox --version                                                                                                                                                       3.6.1 imported from /usr/local/lib/python3.6/dist-packages/tox/__init__.py

> TOXPYTHON=$(which python3.7) tox -e py37-cover                                                                                                                      /usr/local/lib/python3.6/dist-packages/tox/config.py:569: UserWarning: conflicting basepython version (set 37, should be 27) for env 'py27-cover';resolve conflict or set ignore_basepython_conflict
  proposed_version, implied_version, testenv_config.envname
/usr/local/lib/python3.6/dist-packages/tox/config.py:569: UserWarning: conflicting basepython version (set 37, should be 34) for env 'py34-cover';resolve conflict or set ignore_basepython_conflict
  proposed_version, implied_version, testenv_config.envname
/usr/local/lib/python3.6/dist-packages/tox/config.py:569: UserWarning: conflicting basepython version (set 37, should be 35) for env 'py35-cover';resolve conflict or set ignore_basepython_conflict
  proposed_version, implied_version, testenv_config.envname
/usr/local/lib/python3.6/dist-packages/tox/config.py:569: UserWarning: conflicting basepython version (set 37, should be 36) for env 'py36-cover';resolve conflict or set ignore_basepython_conflict
  proposed_version, implied_version, testenv_config.envname
py37-cover create: /home/ionel/.tox/py37-cover
py37-cover develop-inst: /home/ionel
....
```

This only happens if I have those `[testenv:pyXX-cover]` sections.

Now why do I do it like that you might ask? Well ... on Windows I can specialize on different builds for the same python versions, eg, I want to test both 32bit and 64bit pythons, thus I run with both  `TOXPYTHON=C:\Python37-x64\python.exe` and `TOXPYTHON=C:\Python37\python.exe` (32bit).

So after writing all that bugreport I realized I can just use factors for usedevelop but I'm submitting anyway, maybe someone has the same problem or you want to fix the check 😅 . Eg:
```
usedevelop =
    cover: true
    nocov: false
```

**Comment by phdru** [comment]
@obestwalter Run `TOXPYTHON=python3.5 tox --showconfig` to see the problem.

**Comment by takluyver** [comment]
We have a similar issue on h5py, where we're also trying to test with 32-bit and 64-bit Python. To avoid telling tox that every Python is now the one we want to test on, I've had a go at writing a tiny plugin that uses an environment variable to control which one you use:

https://github.com/takluyver/tox_appveyor

https://github.com/h5py/h5py/pull/1196

This may change completely or be abandoned if we don't take this approach for h5py.

**Comment by gaborbernat** [comment]
Feel free to open a PR against master and fix it. My available efforts at the moment are aimed at fixing this as part of https://github.com/tox-dev/tox/issues/1394, but that probably will take a while (ETA September).

**Comment by schlamar** [comment]
@takluyver Your feature request is already discussed at #1149

**Comment by gaborbernat** [comment]
I think this should work now fine on tox 4, so closing as such.
