### ISSUE TITLE
tox4: turn non whitelisted warning into error

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#1127]
At the moment we show this warning if we call to a tool from the parent env:

```
WARNING: test command found but not installed in testenv
  cmd: /home/ob/.virtualenvs/play/bin/pytest
  env: /home/ob/do/play/.tox/python
Maybe you forgot to specify a dependency? See also the whitelist_externals envconfig setting.
```

I am working on documentation improvements for #461 and my current feeling is that we should start throwing an error if somebody does not whitelist an external command from tox 4 on. From 3.7 on we should show an enhanced warning that will announced that the warning will be an error from tox 4 on - like:

```
WARNING: test command found but not installed in testenv
  cmd: /home/ob/.virtualenvs/play/bin/pytest
  env: /home/ob/do/play/.tox/python
Maybe you forgot to specify a dependency? See also the whitelist_externals envconfig setting.

DEPRECATION WARNING: this will be an error in tox 4 and above
```

**Comment by gaborbernat** [comment]
Sure 👍

**Comment by obestwalter** [comment]
One thing to keep in mind is that this is true for all commands that are not known inside the env (e.g. system `echo` and `ls`) so we should definitely have a proper deprecation period but I think tox 4 is still a while away :)

**Comment by gaborbernat** [comment]
Yeah, I'm fine with starting to emit warnings and remove with tox 4 (maybe next year at earliest) if we have enough breaking changes.

**Comment by tucked** [comment]
With 3.7.0, I get a warning for `commands = bash` but not for `commands = /bin/bash`. Is this expected?
(FWIW, I'm actually using `commands =  dev: {posargs:python}` and `tox -e py35-dev -- bash` vs. `tox -e py35-dev -- "$SHELL"`.)

**Comment by hexagonrecursion** [comment]
Note that tox4 currently does not even issue a warning in this case. See https://github.com/tox-dev/tox/issues/1946

**Comment by jugmac00** [comment]
In the current tox4 rewrite documenation, you can read:
> In general, all executables in the path are available in ``commands``, but
tox will emit a warning if it was not explicitly allowed via ``whitelist_externals``.

So we need to update the `user_guide.rst` once this issue gets resolved.

**Comment by gaborbernat** [comment]
I haven't started yet to dive deep into the documentation, so likely a lot of things will be out of date for now.

**Comment by jugmac00** [comment]
> I haven't started yet to dive deep into the documentation, so likely a lot of things will be out of date for now.

I am currently working my way through it and note obvious things which needs to be addressed.
