### ISSUE TITLE
Buffer parallel output to prevent interleaving

### ISSUE THREAD

**Issue by macbeth322** [tox-dev/tox#1143]
I have been using detox for a while and am happy to see parallel test running reach main tox!

It would be really nice if you could run tox in parallel mode and still get all the normal output. You can do this with the `-o` flag but the output is interleaved between all the processes. A different option that lets you get all the output buffered by process to prevent interleaving would be awesome. It's really convenient to have all the output available as part of a CI system so that if you need to debug something you can look at past builds to see exactly what happened.

**Comment by gaborbernat** [comment]
This is true. We'll move the child calls into actions after #1145, which will allow us to have the output as a log file (we can then serve on demand or just point your CI to it).

**Comment by jooon** [comment]
I prefer parallel logs be printed like this: https://apenwarr.ca/log/20181106

Basically, order is already defined, same order as environment list. All output is buffered and you follow the each entire buffer in order until completion. Then the first environment will be printed live and the next environments might have completed and will print fast.

**Comment by gaborbernat** [comment]
In general, I'm still not convinced about the usability of parallel outputs, buffered or not. The reason we added the -o is mostly as was low cost and allows some kind of debug-ability until we implement environment output to file logging. Wouldn't it be preferable that at the end of CI you just cat the content of the log file? Easier to group things together I feel like.
