### ISSUE TITLE
Logo on VectorLogoZone

### ISSUE THREAD

**Issue by pawamoy** [tox-dev/tox#1147]
Hi! Just wanted to crosslink [this issue](https://github.com/VectorLogoZone/vectorlogozone/issues/23) :slightly_smiling_face: 

By chance, would you be able to provide an SVG logo? I couldn't find one.

**Comment by obestwalter** [comment]
Ah our vector beachball ny @hazalozturk :) - the full logo is here: https://github.com/tox-dev/tox/blob/3.7.0/docs/_static/img/tox.svg

**Comment by pawamoy** [comment]
Weird, I don't see the logo. Just the transparent background. Tried in Markdown file, same result.

**Comment by obestwalter** [comment]
Yes. I was also wondering, but if I open it in inkscape it looks fine.
