### ISSUE TITLE
Allow ranges in generative envlists

### ISSUE THREAD

**Issue by andrew-vant** [tox-dev/tox#1161]
Suppose I'm writing a package that depends on library `somelib`, and I support `somelib >=1,<2.` Suppose further that `somelib` updates fairly frequently and is up to something like 1.30.0.

I want to detect cases where updates to my code break on supported versions of `somelib`. I'd also like to detect cases where an update to `somelib` breaks my own code. So I need tox to build/test an env for each version.

In principle I can do this with existing generative envlists, like this:

```
[tox]
envlist = py27,py27-somelib{1}.{1,2,3,4,5,6...}

[testenv]
deps =
    pytest
    somelib1.1: somelib>=1.1,<1.2
    somelib1.2: somelib>=1.2,<1.3
    # ...and a lot more like this.
```

But that can get onerous when there are a lot of versions. It would be nice if I could instead use a range, like this:

```
[tox]
envlist = py27,py27-somelib1.{0..30}

[testenv]
deps =
    pytest
    somelib1.{i}: somelib>={i},<{i+1}
```

**Comment by andrew-vant** [comment]
After opening this issue I noticed I may be having an XY problem. I actually want a convenient way to test against all supported versions of dependencies when there are too many to list explicitly. Numeric range generation seems like one way to do that, but maybe not the best way. It would be better if I could do something like this...

```
[tox]
envlist = py27,py27-somelib{depversions:somelib:>=1,<2}

[testenv]
deps =
    pytest
    somelib{depversions:somelib:>=1,<2}: somelib == {version}
```

Where `{depversions:pkgname:versionspec}` queries pypi for available versions of `pkgname` matching `versionspec`, and `{version}` substitutes the one currently being generated.

I am pretty sure that strays into magic-pony territory, but I'd be willing to try to implement it if somebody thinks it's feasible and can point me to the relevant parts of the code.

**Comment by gaborbernat** [comment]
I would envision this as a plugin that generates the environment, I don't think it's reasonable to be a core feature, as the number of possible versions is runtime dependent. You'll need to query upstream for list of possibles, and what passed yesterday might fail today. Maybe it's more reasonable to have a command that writes the list of possible versions into a file, and the plugin would expand from that. This way periodically you can start supporting new versions by manually updating to expand to list of new versions (this would avoid the need to reach out to pypi at every invocation which may be expensive).

**Comment by gaborbernat** [comment]
For now, due to my unaddressed concerns above, I'll close this. If we find any deliverables down the line we'll reopen this.
