### ISSUE TITLE
Interrupting tox with ^C^C leaves the test process running

### ISSUE THREAD

**Issue by mgedmin** [tox-dev/tox#1172]
I ran `tox`, saw some errors, hit ^C to stop the test run.  That didn't work so I hit ^C a couple of times more.\

Now I'm looking at

```
...................................................................................................................................................................................................................................................^CERROR: KEYBOARDINTERRUPT
Exception KeyboardInterrupt in <function remove at 0x7fa81be1e140> ignored
....^CERROR: keyboardinterrupt

[1m55s, exited with 2]
mg@platonas: ~/src/ivija [git:py3 *$=] $ ........
```

and while `tox` itself exited, the zope-testrunner process spawned by tox keeps running, spewing output to my terminal.

I'm on Ubuntu 18.10 with tox 3.7.0.

It would be nice if tox killed all the child processes (with SIGKILL) if the user presses ^C enough times, instead of leaving them running.

(Perhaps Unix process groups or terminal sessions could help?  My Unix-fu is too weak to suggest a concrete solution.)

**Comment by gaborbernat** [comment]
We'll need to try to reproduce this, and then try to find a fix if possible.

**Comment by asottile** [comment]
Here's an easy reproduction:

```python
import time

while True:
    try:
        time.sleep(1)
    except KeyboardInterrupt:
        print('haha you cannot kill me')
    print('.')
```

```ini
[tox]
skipsdist = true

[testenv]
commands = python t.py
```

```console
$ tox
python create: /tmp/x/.tox/python
python run-test-pre: PYTHONHASHSEED='1672853450'
python runtests: commands[0] | python t.py
.
.
^Chaha you cannot kill me
.
ERROR: KEYBOARDINTERRUPT
.
.
.
.
^Chaha you cannot kill me
.
ERROR: keyboardinterrupt
$ .
.
.
.
.
.
.
pk.
ill tp.
.py
$ .
.
pkil.
l ^C
$ p.
grep t..
py
$ p.
grep -.
f t.py
5202
$ .
p.
kill -f.
 t.py
```

(also included: my struggle to type `pkill -f t.py`)

**Comment by gaborbernat** [comment]
Thanks!
