### ISSUE TITLE
tox and pytest problem when using custom interpreter

### ISSUE THREAD

**Issue by martinlanton** [tox-dev/tox#1175]
Hi!

Maybe there is a known solution to this, but so far I have not been able to find it.

I need to run my tests in a tox environment using a custom interpreter (mayapy), the interpreter shipped with the software that I am using (Autodesk Maya).

I am using Windows 10 as OS (I know, not ideal, but one does not always choose his tools ^^').

My tox.ini looks like this:

[tox]
envlist = my_pytest
skipsdist = True

[testenv:my_pytest]
passenv = PYTHONPATH
deps =
    pytest
    pytest-cov
    pytest-xdist
    pytest-mock
commands = C:\Program Files\Autodesk\Maya2018\bin\mayapy -m pytest

This actually finds the test, but unfortunately returns the following error:

C:\Program Files\Autodesk\Maya2018\bin\mayapy.exe: No module named pytest
ERROR: InvocationError for command 'C:\\Program Files\\Autodesk\\Maya2018\\bin\\mayapy -m pytest' (exited with code 1)

From what I understand, the error comes from the fact that tox is unable to find the pytest module, unfortunately, when running with a standard python interpreter, it finds the pytest module, but does not find the maya.cmds module available in the custom interpreter.

I am fairly certain that there are ways to  avoid that, but I have not managed to make it work yet. Any help would be very much appreciated.

Regards,

Martin

**Comment by daa** [comment]
I think setting ``basepython`` option can help: https://tox.readthedocs.io/en/latest/config.html#conf-basepython

**Comment by gaborbernat** [comment]
Yeah, exactly that. You can either hard  code the full path or just use mayapy in case you added it to your systems path environment variable the bin folder.

**Comment by martinlanton** [comment]
Awesome, I will try that as soon as I can!

Thank you very much guys for the quick answer!

**Comment by gaborbernat** [comment]
Let us know if it solves your problem or otherwise.

**Comment by martinlanton** [comment]
I will!
Thanks again!

**Comment by martinlanton** [comment]
Hi again guys, I don't know if this solves the problem or not (at least not yet) as this triggers another error.

Here's the tox.ini:
`[tox]
envlist = my_pytest
skipsdist = True



[testenv:my_pytest]
passenv = PYTHONPATH

basepython = E:\development\mla_marTool\mayapy.exe

deps =
    pytest
    pytest-cov
    pytest-xdist
    pytest-mock
commands = pytest`


And here's the error:
`ERROR:   my_pytest: Error creating virtualenv. Note that some special characters (e.g. ':' and unicode symbols) in paths are not supported by virtualenv. Error details: InvocationError('Failed to get version_info for E:\\development\\mla_marTool\\mayapy.exe: ', None)`

**Comment by gaborbernat** [comment]
can you post here the output of https://github.com/tox-dev/tox/blob/master/src/tox/helper/get_version.py by feeding it to mayapy, thanks!

**Comment by gaborbernat** [comment]
I tried to do it on MacOs but failed a bit further ahead, probably blocked on https://github.com/pypa/virtualenv/issues/1328; but let us know what's your failure

**Comment by martinlanton** [comment]
Will do tonight! 
Thanks for the continued help!

**Comment by martinlanton** [comment]
Hi gaborbernat!

Here's the output you requested:

> {"sysplatform": "win32", "executable": "C:\\Program Files\\Autodesk\\Maya2017\\bin\\maya.exe", "version": "2.7.11 (default, Dec 21 2015, 22:48:54) [MSC v.1700 64 bit (AMD64)]", "version_info": [2, 7, 11, "final", 0]}

**Comment by gaborbernat** [comment]
Can you post the output of ``tox -rvve my_pytest``, thanks!

**Comment by martinlanton** [comment]
Will do that asap!

**Comment by martinlanton** [comment]
Hi gaborbernat!

Here's the output you requested: 

>  removing E:\development\mla_marTool\tests_suite\test_Maya_setup\.tox\log
> using tox.ini: E:\development\mla_marTool\tests_suite\test_Maya_setup\tox.ini
> using tox-3.5.2 from c:\python27\lib\site-packages\tox\__init__.pyc
> skipping sdist step
> my_pytest start: getenv E:\development\mla_marTool\tests_suite\test_Maya_setup\.tox\my_pytest
> my_pytest cannot reuse: -r flag
> my_pytest create: E:\development\mla_marTool\tests_suite\test_Maya_setup\.tox\my_pytest
> ERROR: Error creating virtualenv. Note that some special characters (e.g. ':' and unicode symbols) in paths are not supported by virtualenv. Error details: InvocationError('Failed to get version_info for E:\\development\\mla_marTool\\mayapy.exe: ', None)
> my_pytest finish: getenv after 0.02 seconds
> ___________________________________ summary ___________________________________
> ERROR:   my_pytest: Error creating virtualenv. Note that some special characters (e.g. ':' and unicode symbols) in paths are not supported by virtualenv. Error details: InvocationError('Failed to get version_info for E:\\development\\mla_marTool\\mayapy.exe: ', None)

**Comment by gaborbernat** [comment]
Can you please upgrade to latest tox release and rerun?

**Comment by martinlanton** [comment]
Sure, sorry about that!
Here's the output:

>   removing E:\development\mla_marTool\tests_suite\test_Maya_setup\.tox\log
> using tox.ini: E:\development\mla_marTool\tests_suite\test_Maya_setup\tox.ini
> using tox-3.7.0 from c:\python27\lib\site-packages\tox\__init__.pyc
> skipping sdist step
> my_pytest start: getenv E:\development\mla_marTool\tests_suite\test_Maya_setup\.tox\my_pytest
> my_pytest cannot reuse: -r flag
> my_pytest create: E:\development\mla_marTool\tests_suite\test_Maya_setup\.tox\my_pytest
> ERROR: Error creating virtualenv. Note that some special characters (e.g. ':' and unicode symbols) in paths are not supported by virtualenv. Error details: InvocationError('Failed to get version_info for E:\\development\\mla_marTool\\mayapy.exe: ', None)
> my_pytest finish: getenv after 0.02 seconds
> ___________________________________ summary ___________________________________
> ERROR:   my_pytest: Error creating virtualenv. Note that some special characters (e.g. ':' and unicode symbols) in paths are not supported by virtualenv. Error details: InvocationError('Failed to get version_info for E:\\development\\mla_marTool\\mayapy.exe: ', None)

**Comment by gaborbernat** [comment]
Eh, this tells us not much. From all you told the erorr should not be happening, but it does. Can we setup some remote screening session for next week? So we can do a more hands on debugging.

**Comment by martinlanton** [comment]
Sure! How would you like to proceed?

**Comment by martinlanton** [comment]
Quick update on that thing, I found a work around by installing pytest in the custom interpreter I am using, and then running it without specifying a basePython and using a command to execute my tests with the right interpreter.

It is far from ideal, but it is, so far, the only work around I have found.

**Comment by martinlanton** [comment]
Hi again!

It seems there are other problems related to the python interpreter I am using with tox, so maybe someone here might have an idea.
Quite a few of my tests are failing (but not all of them) because of them same error, which seems related to this one.
Those tests are passing fine when executing from pycharm, so I assume there is something in the way tox and the mayapy interpreter are communicating that is messing things up.

Here's the traceback:

> SyntaxError: Non-ASCII character '\xf3' in file E:\development\mla_marTool\MayaPipe\modules\__init__.pyc on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

In this case, the file E:\development\mla_marTool\MayaPipe\modules\__init__.py is actually an empty init file (does not contain a single character) which is why I thought that it might be related to the communication between tox and mayapy as this is a very similar problem as previously mentionned.

I'd be happy to help if I can! Remote screening session or anything that can help :)

Let me know what you think!
(Also let me know if you want a more complete traceback

Thanks!

**Comment by gaborbernat** [comment]
hmmm, this seems 

```
 python                                                                                                                                                                                22.9m  Fri 17 May 10:29:49 2019
Python 3.7.1 (default, Dec 14 2018, 13:28:58)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> u'\xf3'
'ó'
```

You sure the init is empty, maybe try to remove the pyc file and rerun. Or add to the inits start: ```# -*- coding: utf-8 -*-```

**Comment by martinlanton** [comment]
I'm sure the init is empty, and it does that on some other files too, none of which contains non ascii characters.
It does work when removing the pyc files and rerunning tox in the same shell (without closing it), but since the pyc are being generated everytime I run tox for the first time, I can't delete all the pyc files every time I run tox as it completely defeats the purpose of it. There are quite a few pyc files generated when I run tox, if I have to delete every single one of them every time, I might as well not use tox at all.

I should not have to use any encoding for files that do not contain any specific character.
In this case I will have to use a few different interpreters and OSs, I don't want to add any encoding for tests that do not require it when run out of tox.

**Comment by martinlanton** [comment]
Removing the .pyc file works, but everytime I run the tests, it gets recreated, with or without tox.
It turns out I ahve the same problem by using pytest by itself without tox.
Also, specifiying the encoding does not seem to change anything, so I guess I'll start looking somewhere else.
The error being relatively close to the one previously mentioned, I thought it might be related to tox, but as it turned out it isn't, I'm sorry for the inconvenience ^^'

**Comment by gaborbernat** [comment]
I'll like to get this added on virtualenv side. I'm caught up with other things at the moment sadly, but I'll reach out when I have some availability. Thanks for the understanding!

**Comment by martinlanton** [comment]
Sounds good! Let me know if I can be of any assistance when you get to this! :D
