### ISSUE TITLE
Problems with Python 3.7.1 and AppVeyor

### ISSUE THREAD

**Issue by Peque** [tox-dev/tox#1178]
It seems Tox is failing when using Python 3.7.1 in Windows or, at least, in AppVeyor:

https://ci.appveyor.com/project/osbrain-ci/osbrain/builds/22655380

In Linux (Travis and also my local machine), everything seems to work as expected:

https://travis-ci.org/opensistemas-hub/osbrain/builds/498658451

I first asked in AppVeyor:

https://help.appveyor.com/discussions/problems/20809-python-37-stopped-working

And it seems they can reproduce it for Python 3.7.1. If they roll back to 3.7.0 everything seems to work as expected.

Any ideas on what could be happening or how to solve it?

**Comment by gaborbernat** [comment]
If anything is a virtualenv bug, that part seems to fail but will need to look into it deeper 🤔

**Comment by Peque** [comment]
@gaborbernat Should I open an issue in [virtualenv](https://github.com/pypa/virtualenv) instead?

**Comment by gaborbernat** [comment]
I'm maintainer for that project too 😄 so no need, interestingly it does not manifest on Azure Pipelines 🤔 the ci there for virtualenv succeeds

**Comment by Peque** [comment]
@gaborbernat Just to confirm: were your Azure Pipelines running Windows and Python 3.7.1?

Also, I tried downgrading Tox (3.5.0) and virtualenv (16.1.0) and retriggered AppVeyor pipelines, without success:

https://ci.appveyor.com/project/osbrain-ci/osbrain/build/job/nt09n1vc64mcc2ov

**Comment by Peque** [comment]
@gaborbernat Friendly ping. :blush:

**Comment by gaborbernat** [comment]
Sorry this will require significant investigation time which I don't have at the moment, but will come back to this.

**Comment by asottile** [comment]
I wonder if this is related to https://bugs.python.org/issue31047 (which caused issues for several projects that used `abspath` or `join` in 3.7.1 -- fixed in 3.7.2)

**Comment by gaborbernat** [comment]
I have a strong feeling it's @asottile's hinted issue in which case this is a won't fix, as it's upstream bug.
