### ISSUE TITLE
[question] "indexservers" option deprecation status

### ISSUE THREAD

**Issue by un-def** [tox-dev/tox#1180]
According to the changelog, "indexservers" option was deprecated a long time ago (more precisely, since version 2.3.0 released on 2015-12-09) but still exists.

Are there any plans to remove this option in the future?

---

### Context
I am working on an in-house automation tool where `tox` is one of the core components. The `indexservers` option seems pretty convenient and easily solves one specific infrastructure-related problem, but I feel uncomfortable relying on the deprecated feature that may be removed soon.

**Comment by gaborbernat** [comment]
Yes with 4.0 in a few months 👍

**Comment by un-def** [comment]
Thank you for the rapid reply!
