### ISSUE TITLE
option to disable parallel spinner for CI envs

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/tox#1184]
In some cases (CIs mostly) it makes sense to not pollute the output with the progress bar, let's allow somehow to disable it in such rare cases 👍 #1142 An environment variable will suffice.

**Comment by webknjaz** [comment]
N.B. Place in code: https://github.com/tox-dev/tox/pull/1102/files#diff-fa162e4b845a9c35e2b680c199480dc6R634

**Comment by ssbarnea** [comment]
@gaborbernat Can you pleaseedi the  bug description to make it easier to read? A link to another issue does not help much.

PS. I cannot edit it myself.

**Comment by gaborbernat** [comment]
@ssbarnea addressed

**Comment by ssbarnea** [comment]
Thanks. Indeed the progress-bar (or keep-alive) may find useful to indicate to ci or humans that the task is not stuck. At the same time it could only be seen as a source of spam for both ci (where it can create undesired extra logs) or for users, where it can set the modified flags in the terminal windows, without real reasons (I seen this with iterm tabs too).

Being able to tune it is highly desired.

**Comment by rpkilby** [comment]
Maybe something similar to unittest's dot output per test case? However, we'd have to iterate on something else. e.g., maybe output a dot every second or so when a subprocess has written to stdout?

This should reduce spam, while still enabling keep-alive.
