### ISSUE TITLE
language agnostic tox

### ISSUE THREAD

**Issue by italomaia** [tox-dev/tox#1190]
I was coding a library in lua and noticed I wanted to test my library against multiple versions of the programming language. As a python developer, tox came to my mind, but tox is not agnostic, correct?

What if tox was language agnostic? If it could be possible to just write a plugin or configuration file for it and make it work with a new set of tools? Would that be desired?

**Comment by gaborbernat** [comment]
Desirable? Yes! Possible? Perhaps. One would need to try to write a plugin for a language and let us know what gaps we are missing. Easy as of today? Probably non trivial at least.

**Comment by gaborbernat** [comment]
As the question has been answered and we don't have any actionable items on this I'll close it. If you start creating this plugin let us know if you run into blockers by creating dedicated issues for those. Thanks!
