### ISSUE TITLE
lazy configuration evaluation

### ISSUE THREAD

**Issue by gyermolenko** [tox-dev/tox#1191]
Trying to run command for particular python3.7 testenv (by `tox -e env37`) I get error related to another testenv:
`"execution failed:  -- pyenv: python2.7: command not found`

Got same results for travis-ci and local env with `pyenv`.

Seems like using `{envsitepackagesdir}` in one testenv influences all other testenvs.

Files to reproduce:

```
from setuptools import setup
setup()
```
```
[tox]
envlist = env27,env37

[testenv:env27]
basepython = python2.7
commands =
    python -c 'print {envsitepackagesdir}'
    
[testenv:env37]
basepython = python3.7
commands =
    python -V
```

**Steps to reproduce:**  run `tox -e env37`

**Expected:** 
```
$ tox -e env37
GLOB sdist-make: /home/gy/code/temp/toxer2/setup.py
env37 inst-nodeps: /home/gy/code/temp/toxer2/.tox/.tmp/package/1/UNKNOWN-0.0.0.zip
env37 installed: UNKNOWN==0.0.0
env37 run-test-pre: PYTHONHASHSEED='1503595934'
env37 runtests: commands[0] | python -V
Python 3.7.2
_______________________________________________________ summary ________________________________________________________
  env37: commands succeeded
```

**Actual:**
```
$ tox -e env37
execution failed:  -- pyenv: python2.7: command not found

The `python2.7' command exists in these Python versions:
  2.7.15

GLOB sdist-make: /home/gy/code/temp/toxer2/setup.py
env37 inst-nodeps: /home/gy/code/temp/toxer2/.tox/.tmp/package/1/UNKNOWN-0.0.0.zip
env37 installed: UNKNOWN==0.0.0
env37 run-test-pre: PYTHONHASHSEED='3600038053'
env37 runtests: commands[0] | python -V
Python 3.7.2
_______________________________________________________ summary ________________________________________________________
  env37: commands succeeded
```

Not reproduced with `{envname}` or `{toxinidir}`

**Comment by gaborbernat** [comment]
This is valid, we parse the entire configuration file at once, not just on demand the one you want to invoke. So if any data can't be deduced and configuration parsing (such as here the envsitepackagesdir) you'll see this error.

> Not reproduced with {envname} or {toxinidir}

Those are easily satisfied (deduced) hence why you can't see errors with that.

Generally, as things stand today, things work as designed/expected. What you're asking here is lazy configuration evaluation which would probably require a bottoms-up reorganization of the configuration system, highly non-trivial.

**Comment by gyermolenko** [comment]
@gaborbernat thanks for reply

Since tox commands succeed in the end (and travis job doesn't fail) - I don't mind to ignore that.
Just seems weird to me that one testenv run gives output for overall tox.ini parsing. The most misleading here is "execution failed:  " phrase at the very beginning of output.

**Comment by takluyver** [comment]
I also just ran into this. Would you be open to a PR to adding note in the docs to say that substituting `{envsitepackagesdir}` in the config file is best avoided if possible, because it tries to run Python in every environment?

**Comment by gyermolenko** [comment]
@takluyver  could be relevant:
 [This section](https://tox.readthedocs.io/en/latest/example/pytest.html?highlight=pytest#known-issues-and-limitations) advices: 
"a safe and explicit option is to give the explicit path {envsitepackagesdir}/mypkg to pytest."

**Comment by gaborbernat** [comment]
I would really not, if anything let's make evaluation sort of lazy, mind you not an easy issue.

**Comment by gaborbernat** [comment]
This has been added in tox 4.
