### ISSUE TITLE
--force-dep does not install a package if not in deps

### ISSUE THREAD

**Issue by blueyed** [tox-dev/tox#1199]
It would be useful if `--force-dep` could be used to install a package always, e.g.:

> tox -e py37 --force-dep pytest-cov -- --cov

It appears to only affect versions of already existing deps.

My usual workaround is using an extra env ("%s-coverage"), or env variables for this.

**Comment by gaborbernat** [comment]
We'll remove this flag with tox 4, so this becomes not needed.
