### ISSUE TITLE
Update docs to make it clear that negated factor conditions were introduced in 3.0

### ISSUE THREAD

**Issue by OddBloke** [tox-dev/tox#1201]
The [documentation for conditional settings](https://tox.readthedocs.io/en/latest/config.html#generating-environments-conditional-settings) doesn't make it clear that negated factor conditionals weren't introduced along with everything else in this section (which suggests it was all "New in version 1.8."). It would be better if there were a clearer breakdown of when specific syntax support was introduced.

I'm in a situation where I have to support multiple versions of tox, so I was relying on the (in my experience, very reliable!) version markers in the documentation to guide me as to what features I could or couldn't use, and this bit me.

(Thanks for such a useful project!)

**Comment by gaborbernat** [comment]
Closing due to lack of interest and contribution.
