### ISSUE TITLE
sha support for dependencies

### ISSUE THREAD

**Issue by jazzblue** [tox-dev/tox#1205]
Currently tox does not support specifying dependencies pinned to a version and having a hash. It would be useful to have support in `tox.ini` the following:

```
deps =
    twisted==18.9.0  --hash=sha256:294be2c6bf84ae776df2fc98e7af7d6537e1c5e60a46d33c3ce2a197677da395

```

**Comment by gaborbernat** [comment]
tox supports whatever https://www.python.org/dev/peps/pep-0440/ does. Unless PEP-440 allows such this will be most likely not supported at the core level (so maybe at plugin level).

**Comment by Julian** [comment]
So, FWIW, without this, you can't really use `tox`'s `dep` section anytime you have a requirements file with hashes (because pip refuses to leave some deps un-hashed).

**Comment by apljungquist** [comment]
@jazzblue 

The error message that you are getting, is it `no such option: --hash`? If so you can work around it by putting the requirement in a file and putting that file in the reps variable like

```txt
# requirements.txt
twisted==18.9.0  --hash=sha256:294be2c6bf84ae776df2fc98e7af7d6537e1c5e60a46d33c3ce2a197677da395
```

```ini
# tox.ini
[testenv]
deps =-rrequirements.txt
```

What is your goal with specifying the hash?

I am currently trying to figure out a good way to make tox tests a bit more deterministic. My current solution is a simple [plugin](https://github.com/apljungquist/tox-constraints). It is very much experimental but you are nonetheless welcome to give it a try or look at it for inspiration.

**Comment by Zac-HD** [comment]
I don't personally use hashes, but [the `pip-tools` project](https://github.com/jazzband/pip-tools) provides some very nice tooling for compiling a list of top-level dependencies to the full transitive set - optionally with hashes.

IMO this is complex enough that it should be left out of `tox` proper, though better support for `requirements.txt` files (#149) would be welcome.
