### ISSUE TITLE
[BUG] using -v and -e connected (as -ve) fails in 3.8.0

### ISSUE THREAD

**Issue by harpaj** [tox-dev/tox#1218]
In our CI environment, we start tox like `tox -vve py27`.
This worked before the release of 3.8.0 without problems, but now fails with this error:

```bash
$ tox -vve py27
usage: tox [-v] [-q]
tox: error: argument -v: ignored explicit argument 'e'
```

`tox -vv -e py27` still works without problem, so it's not a big issue; but as it breaks backwards compatibility, it might at least warrant a message in the release notes.

**Comment by gaborbernat** [comment]
😢 seems https://docs.python.org/3.4/library/argparse.html#argparse.ArgumentParser.parse_known_args is not smart enough to parse that; we'll need to catch the error and ignore it (while redirecting the output to null - as the error message is non optional)

**Comment by rpkilby** [comment]
The prefix matching behavior can be disabled in Python 3.5+ with `allow_abbrev=False`. Of course, this doesn't help Python 3.4 and earlier, but Python 3.4 is now EOL and Python 2.7 is EOL at the end of the year? Meh? ¯\\\_(ツ)_/¯

**Comment by gaborbernat** [comment]
@rpkilby sadly that does not help us, disable-ing the abbreviation will also disable detecting the -v flags passed in the above which is the whole goal. At that point, we might just suppress the error.
