### ISSUE TITLE
[BUG] Tox>=3.8.1 writes different json output than 3.7.0

### ISSUE THREAD

**Issue by r2dan** [tox-dev/tox#1242]
In the json report test/setup command result stored in `retcode` variable is of `int` type (used to be the `str`). It was introduced by the following pull request:
https://github.com/tox-dev/tox/pull/1216/files#diff-cd9687d8265ea997c80a7401bf5c7c85L12 
File: src/tox/logs/command.py, line:12

Json content tox==3.7.0:
`"retcode": "0"`
Json content tox==3.8.4:
`"retcode": 0`

If the change above is intentional I'd suggest releasing it as a new major version of tox, if not, it would be great to revert this one to not break the compatibility.

**Comment by gaborbernat** [comment]
@r2dan feels 0 to be more accurate, as it is an error code number (I considered it having string to be a bug). How is breaking your flow with having it string?

**Comment by r2dan** [comment]
I think that fixing it on a devpi side is one thing to do, but I'd consider such change as backwards incompatible (and include it only in a major release). Does it make sense?

**Comment by gaborbernat** [comment]
I'll close this as we'll fix this on devpi side. Sorry for the breakage.

**Comment by gaborbernat** [comment]
I'll close this as we'll fix this on devpi side. Sorry for the breakage.
