### ISSUE TITLE
[BUG] sys.executable set to executable outside of venv in some circumstances since tox 3.8

### ISSUE THREAD

**Issue by glyph** [tox-dev/tox#1252]
I've only seen this happen in CircleCI's Python 3.7.0 environment, nowhere else.  Testing locally with Python 3.7.3 I don't see the problem.

Discovered due to this issue:

https://twistedmatrix.com/trac/ticket/9615#comment:6

"broken" tox output from `tox -rvv` in 3.8.0: https://gist.github.com/glyph/f30698432f5bca8dce4da1c8211acaff

"working" output from 3.7.0

(the tests are still failing here, but this is expected because the system under test has been hacked up to print out the name of the executable)

https://gist.github.com/glyph/b5aa35b69b64d448b7d407a1fd4129bd

**Comment by asottile** [comment]
this looks like macos?  I've hit this before -- it's the silly "framework builds" and poor interaction with that.

Here's the fix I'm using in pre-commit: 

https://github.com/pre-commit/pre-commit/blob/b33f2c40d8de0cd2c55a9b637773172198962832/pre_commit/resources/hook-tmpl#L10-L11

https://github.com/pre-commit/pre-commit/blob/b33f2c40d8de0cd2c55a9b637773172198962832/pre_commit/main.py#L31-L35

**Comment by gaborbernat** [comment]
Is this a virtualenv bug?

**Comment by asottile** [comment]
I can't remember what I concluded last time other than my workaround -- this seems to be the bottom of the rabbit hole: https://bugs.python.org/issue22490

**Comment by gaborbernat** [comment]
Closing as haven't been reported again since, and likely fixed since then with tox 4.
