### ISSUE TITLE
[FEATURE] Provide -v switch as variable (verbosity)

### ISSUE THREAD

**Issue by bittner** [tox-dev/tox#1267]
I'd like to run Pytest in --verbose mode from the command line when I run `tox -v`, and "normal" when I run just `tox`.

This doesn't seem possible, currently. There is [no configuration variable](https://tox.readthedocs.io/en/latest/config.html) or environment variable set that I could use, isn't it?

Something like a `{verbosity}` variable would be nice that one could use in the tox.ini file.

**Comment by gaborbernat** [comment]
This is the kinda thing you would do with a plug-in 👌So j would suggest to write one, with 3.8.0 autoprovisioning should be easy to ensure its presence.

**Comment by rpkilby** [comment]
Is passing non-tox args with `--` insufficient? e.g., `tox -- -v -k some_test`. 
Note that your command would look something like...

```ini
[testenv]
commands = pytest {posargs}
```

**Comment by gaborbernat** [comment]
Thanks for the issue and let me know if you need help creating the plugin!

**Comment by bittner** [comment]
I actually envisioned this more like a built-in feature; something like, when Tox is verbose commands operated by Tox can also be more verbose. A bit like [the integration of pip](https://tox.readthedocs.io/en/latest/config.html#cmdoption-tox-v):

> increase verbosity of reporting output.-vv mode turns off output redirection for package installation, above level two verbosity flags are passed through to pip (with two less level)

Much like leveraging internal execution values, allowing to align with the behavior the user asks Tox for. Technically, this is possible with a plugin, but it defeats the whole purpose if it's not commonly usable without additional effort.

**Comment by gaborbernat** [comment]
while we do know the tool interface this is not true about user  command, pytest is just an example command, some commands might have different verbose flags so cannot be uniformly implemented. A plug-in with 3.8 auto provisioning takes little to no effort.
