### ISSUE TITLE
Builds a broken virtualenv

### ISSUE THREAD

**Issue by cglacet** [tox-dev/tox#1280]
When I run tox (`rm -rf .tox; tox`) on the following configuration file (_tox.ini_): 

```
[tox]
envlist = py37

[testenv]
deps =
  pytest
  cython
commands =
  python -m pytest --version
```

It ends up with the following error:

```python
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
```

I tried to dig a little bit and I found that adding `python3 -m ensurepip --upgrade` solved this issue. I don't find this very satisfying and I was curious about why this happens?

Some additional information just in case, 

+ On my machine I have:
  - python 3.7.0
  - tox 3.9.0
  - pip 19.1
  - setuptools 41.0.1
+ Tox creates a virtual environment with:
  - python 3.7.0
  - pip 19.1
  - setuptools 3.3  (? that's odd, no?)

Note that if I run: 

```sh
virtualenv .my_tox
. .my_tox/bin/activate
pip install   pytest cython
python setup.py install 
python -m pytest --version
```

Everything works just fine. But if I create the virtualenv using tox, then run:

```sh 
. .tox/py37/bin/activate
python setup.py install 
```

This crashes the same way as when running `tox`.

**Comment by gaborbernat** [comment]
tox creates virtualenv with whatever version of virtualenv you have alongside it, if it's an old virtualenv it's going to have old setuptools/wheel etc. Upgrade virtualenv and you should be fine . Consider using isolated build too https://tox.readthedocs.io/en/latest/example/package.html#setuptools

**Comment by cglacet** [comment]
I'm not sure what you mean by "you have alongside it", but I had _virtualenv 16.1.0_, I upgraded to _16.5.0_ and still got the problem. 

Using the `pyproject.toml` file with build requirements didn't seem to solve the problem either:

```TOML
[build-system]
requires = [
    "setuptools >= 41.0.1"
]
build-backend = "setuptools.build_meta"
```

On the other hand, I noticed that there are two virtualenv created and if I manually run the install in the second one, it seems to work fine:

```sh 
. .tox/.package/bin/activate
python setup.py install
```

This virtualenv has `pip show setuptools | grep Version` on `Version: 41.0.1`. 
While the one in _py37_ has `.tox/py37/bin/pip show setuptools | grep Version` on `Version: 3.3`.

**Comment by gaborbernat** [comment]
output of tox -rvv?

**Comment by cglacet** [comment]
Which part (it's a huge output ^^)?

**Comment by cglacet** [comment]
At some point I have this error: 

```
ERROR: tox 3.9.0 has requirement setuptools>=30.0.0, but you'll have setuptools 3.3 which is incompatible.
```

I have the following lines involving __py37__:

```
py37 finish: installpkg .tox/.tmp/package/1/kune_server-0.0.1.zip after 42.65 seconds
py37 start: envreport
```
```
py37 finish: envreport  after 0.69 seconds
py37 installed: ... <some packages>
py37 start: run-test-pre
py37 run-test-pre: PYTHONHASHSEED='3733462753'
py37 finish: run-test-pre  after 0.00 seconds
py37 start: run-test
py37 run-test: commands[0] | python -m pytest --version
```

**Comment by gaborbernat** [comment]
I would like the entire output.

**Comment by cglacet** [comment]
Ok (in the meantime I found a minimal value for `install_requires` in _setup.py_ for which it fails, the package that seems to be problematic is `socketio >= 0.1.7`.

The output is not so big now:

```
GLOB sdist-make: /Users/cglacet/test/tox/setup.py
py37 create: /Users/cglacet/test/tox/.tox/py37
py37 installdeps: pytest
py37 inst: /Users/cglacet/test/tox/.tox/.tmp/package/1/Tox Test-0.0.1.zip
py37 installed: atomicwrites==1.3.0,attrs==19.1.0,more-itertools==7.0.0,netifaces==0.10.6,pluggy==0.9.0,py==1.8.0,pytest==4.4.1,six==1.12.0,socketio==0.1.7,Tox-Test==0.0.1
py37 run-test-pre: PYTHONHASHSEED='859956160'
py37 run-test: commands[0] | python -m pytest --version
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/cglacet/test/tox/.tox/py37/lib/python3.7/site-packages/pytest.py", line 89, in <module>
    raise SystemExit(pytest.main())
  File "/Users/cglacet/test/tox/.tox/py37/lib/python3.7/site-packages/_pytest/config/__init__.py", line 60, in main
    config = _prepareconfig(args, plugins)
  File "/Users/cglacet/test/tox/.tox/py37/lib/python3.7/site-packages/_pytest/config/__init__.py", line 201, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/Users/cglacet/test/tox/.tox/py37/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/cglacet/test/tox/.tox/py37/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/cglacet/test/tox/.tox/py37/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/cglacet/test/tox/.tox/py37/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/Users/cglacet/test/tox/.tox/py37/lib/python3.7/site-packages/_pytest/helpconfig.py", line 93, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/Users/cglacet/test/tox/.tox/py37/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/cglacet/test/tox/.tox/py37/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/cglacet/test/tox/.tox/py37/lib/python3.7/site-packages/_pytest/config/__init__.py", line 679, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/cglacet/test/tox/.tox/py37/lib/python3.7/site-packages/_pytest/config/__init__.py", line 896, in parse
    self._preparse(args, addopts=addopts)
  File "/Users/cglacet/test/tox/.tox/py37/lib/python3.7/site-packages/_pytest/config/__init__.py", line 835, in _preparse
    self._checkversion()
  File "/Users/cglacet/test/tox/.tox/py37/lib/python3.7/site-packages/_pytest/config/__init__.py", line 872, in _checkversion
    from pkg_resources import parse_version
  File "/Users/cglacet/test/tox/.tox/py37/lib/python3.7/site-packages/pkg_resources.py", line 1479, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
ERROR: InvocationError for command /Users/cglacet/test/tox/.tox/py37/bin/python -m pytest --version (exited with code 1)
_______________________________________________________ summary ________________________________________________________
ERROR:   py37: commands failed
```

Complete input files are: 

__tox.ini__
```ini
[tox]
envlist = py37

[testenv]
deps =
  pytest
commands =
  python -m pytest --version
```

__setup.py__
```python
import setuptools

setuptools.setup(
    name='Tox Test',
    version='0.0.1',
    description='testing',
    install_requires=["socketio >= 0.1.7"],
    setup_requires=["pytest-runner"],
)
```

**Comment by gaborbernat** [comment]
``Collecting setuptools==3.3 (from socketio>=0.1.7->Tox-Test==0.0.1)``

eh, that packages is badly packaged, requires a setuptools old as age, which breaks pytest.

**Comment by cglacet** [comment]
I probably can get rid of this package, but what would be the correct way to deal with this kind of problem? Shouldn't tox guarantee that everything will work well even if packages are old? Maybe "guarantee" is a strong word, but isn't that the general goal?

**Comment by gaborbernat** [comment]
tox guarantees to install your packagea and run tests that will allow you
to spot the problem. Which it did in this case too, hence the error you're
seeing. We cannot fix bad packages for you though. In this case you're
installing a package that requires setuptools 30+, and another that
requires exactly 3.3. There's no fix for this, we have a single virtualenv,
we cannot satisfy these two contrary requirements at the same time. In the
world of Python in a single environment only one version of a package is
allowed. In this case socketio in simple terms is not compatible with
pytest, and there's no way to make them compatible without either of the
packages fixing the contradiction. Ideally pip should error out doing the
installation, as you request to install two packages that have
contradictory requirements. This would require pip to have a dependency
resolver which is in works and may be available at around end of year.
