### ISSUE TITLE
Question about tox

### ISSUE THREAD

**Issue by vinay-is** [tox-dev/tox#1281]
I have a question about tox and I am not sure if this is the right way (by logging an issue) of asking it. 

My requirement is that I want to invoke tox on python36 and python37, so it is possible to invoke on on both py36 and py37. 

Earlier I was invoking tox on py27 and py36 and it was working fine. Before attempting above (36 and 37 together) want to get your feedback.

**Comment by gaborbernat** [comment]
tox -e py36,py37 should work great, you can even run them in parallel if you add -p auto
