### ISSUE TITLE
Using skip_missing_interpreters doesn't work with pyenv

### ISSUE THREAD

**Issue by gangefors** [tox-dev/tox#1289]
Using pyenv together with tox and skip_missing_interpreters fails when interpreter is missing.

To reproduce this issue use the following tox.ini
```
[tox]
envlist = py{36,37}
skip_missing_interpreters = True
skipsdist = True
```

Setup pyenv with both interpreters.
`pyenv shell 3.6.8 3.7.3`

Execute tox.
```
$ tox -r
py36 recreate: /home/stefanga/projects/platformci/bitbake-cache/src/.tox/py36
py36 installed: bitbake-cache==0.1.3.dev0+g64a9b58.d20190508
py36 run-test-pre: PYTHONHASHSEED='1750284650'
py37 recreate: /home/stefanga/projects/platformci/bitbake-cache/src/.tox/py37
py37 installed: bitbake-cache==0.1.3.dev0+g64a9b58.d20190508
py37 run-test-pre: PYTHONHASHSEED='1750284650'
_______________ summary _______________
  py36: commands succeeded
  py37: commands succeeded
  congratulations :)
```

Now disable one of the python interpreters and run tox again.
```
$ pyenv shell 3.6.8
$ tox
py36 installed: bitbake-cache==0.1.3.dev0+g64a9b58.d20190508
py36 run-test-pre: PYTHONHASHSEED='2672614782'
py37 recreate: /home/stefanga/projects/platformci/bitbake-cache/src/.tox/py37
ERROR: InvocationError for command Failed to get version_info for python3.7: pyenv: python3.7: command not found

The `python3.7' command exists in these Python versions:
  3.7.3

_______________ summary _______________
  py36: commands succeeded
ERROR:   py37: InvocationError for command Failed to get version_info for python3.7: pyenv: python3.7: command not found

The `python3.7' command exists in these Python versions:
  3.7.3
```

Making sure that pyenv isn't in use I get the correct behaviour from tox when using python3.5 installed on the system.
```
$ tox
py36 recreate: /home/stefanga/projects/platformci/bitbake-cache/src/.tox/py36
SKIPPED: InterpreterNotFound: python3.6
py37 recreate: /home/stefanga/projects/platformci/bitbake-cache/src/.tox/py37
SKIPPED: InterpreterNotFound: python3.7
___________________________ summary ___________________________
SKIPPED:  py36: InterpreterNotFound: python3.6
SKIPPED:  py37: InterpreterNotFound: python3.7
  congratulations :)
```

I've tracked the problem down to how this method.
https://github.com/tox-dev/tox/blob/f3489306de87d04d3d903683dd839c7af9ec7125/src/tox/config/__init__.py#L944
Instead of going into the first if statement and raising InterpreterNotFound it continues and raises an InvocationError instead.

I think this is due to pyenv shims and how it responds when it can't find the requested interpreter version.
```
$ python3.7
pyenv: python3.7: command not found

The `python3.7' command exists in these Python versions:
  3.7.3
```
Pyenv returns error code 127 when it can't find the interpreter.

Is there a workaround to this problem? Would it be easy to fix? Should it be fixed in tox?

**Comment by gaborbernat** [comment]
We don't support at the moment out of box pyenv (however might still work if pyenv generates Linux compatible solutions). I see this more like a feature request but accepted.

**Comment by mehdy** [comment]
@gaborbernat Would you mind if I work on this?

**Comment by gaborbernat** [comment]
Sure 👍

**Comment by mehdy** [comment]
@gangefors @gaborbernat I wasn't able to reproduce the error as described. I debugged the code very closely and it seems to work correctly. I think you could close the issue :)
