### ISSUE TITLE
Workflow: Changelog Fragments management proposal

### ISSUE THREAD

**Issue by webknjaz** [tox-dev/tox#1291]
TL;DR @ewdurbin can deploy a changelog fragment checking GitHub App on the PSF infrastructure and is open to providing that to the tox org.

It's another instance of https://github.com/pypa/pip/issues/6475. All details are there but @gaborbernat and @asottile should've already seen my demos.

In order to proceed, we just ask that tox maintainers would express their interest in doing this :)

**Comment by gaborbernat** [comment]
We're interested.

**Comment by webknjaz** [comment]
There's still one sprints day left. So if you **all** agree on this, I think @ewdurbin could get it deployed.
Is there anyone else I should ping wrt approving this?

**Comment by asottile** [comment]
:shipit:

**Comment by webknjaz** [comment]
Alright, it looks like Ernest needs to recover for a week at least and then we'll get back to it :)

**Comment by webknjaz** [comment]
@gaborbernat @asottile hey plz install https://github.com/apps/psf-chronographer on `tox-dev/tox` only.
Don't enforce this check in branch protection. It should work in general but needs testing.
You'll see some updates in PRs after related events get triggered. It doesn't mutate anything other than its own Checks page/status.
It's currently deployed on the free tier of Heroku (so can freeze and you may observe other related errors), once we're happy with the quality we'll proceed with transferring this to the PSF's account.

**Comment by gaborbernat** [comment]
done last night 😁

**Comment by webknjaz** [comment]
So let's see how it goes and send your suggestions to https://github.com/sanitizers/chronographer-github-app/issues/new or post them right here.

I think you @gaborbernat were unhappy with the Checks page contents. Maybe we could improve it + maybe make it more customizable on a per-repo basis via `.github/config.yaml` config file.

**Comment by webknjaz** [comment]
New edge-case: release PRs remove changelogs, not add them. Currently, this means a failed status reported by the bot.

Ref: https://github.com/tox-dev/tox/pull/1362#issuecomment-507677428

**Comment by webknjaz** [comment]
@gaborbernat it might be a good time to add this check to branch protection ;)

**Comment by gaborbernat** [comment]
Indeed 😁

**Comment by webknjaz** [comment]
FYI chronographer doesn't work because GH changed some API responses and I haven't fixed that yet.

**Comment by webknjaz** [comment]
@gaborbernat @asottile plz accept the updated chronographer permissions request. I'm starting to implement labels management.

**Comment by webknjaz** [comment]
@gaborbernat ^

**Comment by gaborbernat** [comment]
Done 👍

**Comment by hexagonrecursion** [comment]
Is there any specific reason this issue was left open or was it just forgotten?

**Comment by gaborbernat** [comment]
I think just forgotten
