### ISSUE TITLE
Use different working dir for different commands within the same testenv

### ISSUE THREAD

**Issue by SeanXu1984** [tox-dev/tox#1292]
I'm not sure if this should be a bug or not but I want to use different working directories for different commands listed within the same testenv.
Have no idea how to use changedir together with commands to do this.

[testenv:py27]
changedir={toxinidir}/dir1
commands=command1
changedir={toxinidir}/dir2
commands=command2 

There are some dependencies between command1 and command2 but tox does not allow duplicated commands entries.

**Comment by SeanXu1984** [comment]
Some commands don't have any dependencies between them but I don't want to put them into different testenv due to the overhead of testenv setup.

**Comment by gaborbernat** [comment]
This has been brought up a number of times (latest via https://github.com/tox-dev/tox/pull/1193), and ultimately decided won't do as it's not possible to guarantee reproducibility and correctness in general. For example, command2 might break command1s env. It's recommended to use different testenvs, even if these do add some extra setup overhead.
