### ISSUE TITLE
fails check-manifest on appveyor for py2.7

### ISSUE THREAD

**Issue by Borda** [tox-dev/tox#1296]
After upgrading to 3.10.0 `check-manifest` fails for python 2.7 on a simple project
```
py27 run-test: commands[0] | check-manifest --ignore 'tox.ini,tests*'
lists of files in version control and sdist do not match!
missing from VCS:
  .
```
https://ci.appveyor.com/project/Borda/py-sample-project/builds/24544230/job/3977lvvbaxx9a223
I was also testing (rebuild) previously passing commit and it fails also; downgrading to 3.9.0 also solves the issue

**Comment by gaborbernat** [comment]
please install tox with force reinstall flag of pip 😀 Appveyor ships with a horrible old virtualenv by default.

**Comment by Borda** [comment]
@gaborbernat I have upgraded `pip` before installing `tox`, but the result was the same...

**Comment by gaborbernat** [comment]
I'm not talking about upgrading pip, I'm talking about upgrading all tox dependencies (via the force reinstall flag).

**Comment by Borda** [comment]
`pip install -U --force-reinstall tox`
