### ISSUE TITLE
download=false breaks AppVeyor

### ISSUE THREAD

**Issue by akosthekiss** [tox-dev/tox#1302]
The new feature of version v3.10.0, i.e., to disable the automatic upgrade of pip/wheels/setuptools in the created virtual environment (#448), breaks AppVeyor completely. We have experienced this in our project, where everything worked perfectly [7 days ago](https://ci.appveyor.com/project/akosthekiss/fuzzinator/builds/24414281), while triggering a new CI job for the same commit caused AppVeyor go red [today](https://ci.appveyor.com/project/akosthekiss/fuzzinator/builds/24577465). It has turned out that the difference between the two runs was that the earlier job used tox 3.9 while the job of today used 3.11 (and so it called virtualenv with `--no-download`). The only solution I've found was to add `download=true` to tox.ini. 

Some notes:
- No problem on [Travis CI](https://travis-ci.org/akosthekiss/fuzzinator/builds/533069509).
- Running `pip install -U pip` before tox [didn't help](https://ci.appveyor.com/project/akosthekiss/fuzzinator/builds/24577067).
- It seems to me that the new `download` option having False as default is not following semver as it changes existing behavior (which was equivalent to `default=True`).

**Comment by gaborbernat** [comment]
If you want the download option, yes set it to True. Alternatively use force reinstall flag on pip when installing tox  to ensure a newer virtualenv is installed alongside. Appveyor ships an ancient 8.0 version of virtualenv

**Comment by akosthekiss** [comment]
Would you mind giving the command you suggested as the alternative? I'm not sure I know what parametrization of which command you meant.

PS: Ancient virtalenv or not, I didn't expect a minor version bump to change and break things. Tox quite prominently states that it is following Semantic Versioning. Such a change is against those rules IMHO.

**Comment by gaborbernat** [comment]
It's not tox breaking you, but rather the fact you're using features of pip/setuptools that are not present with an older bundled virtualenv. Did you define your pip/setuptools version constraints accurately? 

pip install tox -U --force-reinstall

Changing to download false makes on one end builds repeatable (a sudden new broken release of pip/setuptools no longer breaks you). Plus it forces users to define accurately their pip/setuptools/wheels dependencies.
