### ISSUE TITLE
Documentation for parallel_show_output setting is possibly wrong regarding global vs testenv section 

### ISSUE THREAD

**Issue by john-bodley** [tox-dev/tox#1305]
Per the tox documentation is mentions that the [parallel_show_output](https://tox.readthedocs.io/en/latest/config.html#conf-parallel_show_output) setting is a global `[tox]` setting however this doesn't seem to be the case, i.e., if one's `tox.ini` file is of the form:

```
[tox]
parallel_show_output = true
```

then running `tox --parallel auto` does not show any output. 

According to the [Parallel Mode](https://tox.readthedocs.io/en/latest/example/basic.html#parallel-mode) section in the documentation it states, 

> Parallel mode by default shows output only of failed environments and ones marked as parallel_show_output =True.

which would indicate that the `parallel_show_output` setting should be defined within the environment setting(s) sections, i.e., 

```
[testenv]
parallel_show_output = true
```

which seems to work.

**Comment by gaborbernat** [comment]
This has been fixed at some point, no longer see this with latest documentation.
