### ISSUE TITLE
Question: how to not short circuit a command list on failure? Or "finally"?

### ISSUE THREAD

**Issue by tommyjcarpenter** [tox-dev/tox#1321]
My tox looks like this (it uses a python webtesting framework called tavern)

```
[tox]
envlist = tavern

[testenv:tavern]
whitelist_externals=
    sleep
    docker-compose
deps =
    pytest-xdist
    tavern
changedir=integration_tests
commands=
    docker-compose up --build -d
    sleep 5
    pytest -n 2 .     *****
    docker-compose down
```

If the line marked `*****` fails, the command after it is not executed; this command list "short circuits" and the `docker-compose down` line is never called.

How do I avoid this behavior? Is there a flag that says "keep going, even on a failure"?

**Comment by gaborbernat** [comment]
https://tox.readthedocs.io/en/latest/config.html#conf-commands_post

**Comment by tommyjcarpenter** [comment]
thanks @gaborbernat !!
