### ISSUE TITLE
tox command is failing always

### ISSUE THREAD

**Issue by rojarmj** [tox-dev/tox#1331]
tox command is failing always with below error
# tox -rvv
Traceback (most recent call last):
  File "/usr/bin/tox", line 6, in <module>
    from tox import cmdline
  File "/usr/lib/python2.7/site-packages/tox/__init__.py", line 9, in <module>
    import pluggy
  File "/usr/lib/python2.7/site-packages/pluggy/__init__.py", line 16, in <module>
    from .manager import PluginManager, PluginValidationError
  File "/usr/lib/python2.7/site-packages/pluggy/manager.py", line 6, in <module>
    import importlib_metadata
  File "/usr/lib/python2.7/site-packages/importlib_metadata/__init__.py", line 14, in <module>
    from ._compat import (
  File "/usr/lib/python2.7/site-packages/importlib_metadata/_compat.py", line 21, in <module>
    from contextlib2 import suppress  # noqa
ImportError: cannot import name suppress

**Comment by gaborbernat** [comment]
How did you install tox? what os?

**Comment by rojarmj** [comment]
did "pip install tox", tox installed successfully
cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5"

**Comment by rojarmj** [comment]
our automation test environment is completely locked due to this issue, please suggest any workaround if available

**Comment by gaborbernat** [comment]
please try ``pip install tox --force-reinstall -U`` 👍 if it doesn't fix it please post the output of the command to here 👍

**Comment by rojarmj** [comment]
pip install tox --force-reinstall -U
Collecting tox
  Using cached https://files.pythonhosted.org/packages/d0/50/3daff59797eefc7c2574fbf58c7b82c599c0495e0639f656ba5f1f58cfa2/tox-3.12.1-py2.py3-none-any.whl
Collecting six<2,>=1.0.0 (from tox)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting py<2,>=1.4.17 (from tox)
  Using cached https://files.pythonhosted.org/packages/76/bc/394ad449851729244a97857ee14d7cba61ddb268dce3db538ba2f2ba1f0f/py-1.8.0-py2.py3-none-any.whl
Collecting setuptools>=30.0.0 (from tox)
  Downloading https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl (575kB)
    100% |████████████████████████████████| 583kB 23.4MB/s 
Collecting filelock<4,>=3.0.0 (from tox)
  Using cached https://files.pythonhosted.org/packages/14/ec/6ee2168387ce0154632f856d5cc5592328e9cf93127c5c9aeca92c8c16cb/filelock-3.0.12.tar.gz
Collecting toml>=0.9.4 (from tox)
  Using cached https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl
Collecting pluggy<1,>=0.3.0 (from tox)
  Using cached https://files.pythonhosted.org/packages/06/ee/de89e0582276e3551df3110088bf20844de2b0e7df2748406876cc78e021/pluggy-0.12.0-py2.py3-none-any.whl
Collecting virtualenv>=14.0.0 (from tox)
  Using cached https://files.pythonhosted.org/packages/ca/ee/8375c01412abe6ff462ec80970e6bb1c4308724d4366d7519627c98691ab/virtualenv-16.6.0-py2.py3-none-any.whl
Collecting importlib-metadata>=0.12 (from pluggy<1,>=0.3.0->tox)
  Using cached https://files.pythonhosted.org/packages/7f/72/5e13a37e989bdb54ac3f52808e122cbd9b878ac980f932dc237ff64f8a00/importlib_metadata-0.17-py2.py3-none-any.whl
Collecting configparser; python_version < "3" (from importlib-metadata>=0.12->pluggy<1,>=0.3.0->tox)
  Using cached https://files.pythonhosted.org/packages/ba/05/6c96328e92e625fc31445d24d75a2c92ef9ba34fc5b037fe69693c362a0d/configparser-3.7.4-py2.py3-none-any.whl
Collecting contextlib2; python_version < "3" (from importlib-metadata>=0.12->pluggy<1,>=0.3.0->tox)
  Downloading https://files.pythonhosted.org/packages/a2/71/8273a7eeed0aff6a854237ab5453bc9aa67deb49df4832801c21f0ff3782/contextlib2-0.5.5-py2.py3-none-any.whl
Collecting pathlib2; python_version == "3.4.*" or python_version < "3" (from importlib-metadata>=0.12->pluggy<1,>=0.3.0->tox)
  Using cached https://files.pythonhosted.org/packages/2a/46/c696dcf1c7aad917b39b875acdc5451975e3a9b4890dca8329983201c97a/pathlib2-2.3.3-py2.py3-none-any.whl
Collecting zipp>=0.5 (from importlib-metadata>=0.12->pluggy<1,>=0.3.0->tox)
  Using cached https://files.pythonhosted.org/packages/a0/0f/9bf71d438d2e9d5fd0e4569ea4d1a2b6f5a524c234c6d221b494298bb4d1/zipp-0.5.1-py2.py3-none-any.whl
Collecting scandir; python_version < "3.5" (from pathlib2; python_version == "3.4.*" or python_version < "3"->importlib-metadata>=0.12->pluggy<1,>=0.3.0->tox)
  Using cached https://files.pythonhosted.org/packages/df/f5/9c052db7bd54d0cbf1bc0bb6554362bba1012d03e5888950a4f5c5dadc4e/scandir-1.10.0.tar.gz
flask-restful 0.3.7 requires aniso8601>=0.82, which is not installed.
oslo-db 4.44.0 requires testresources>=2.0.0, which is not installed.
oslo-db 4.44.0 requires testscenarios>=0.4, which is not installed.
keystone 15.0.1.dev11 requires oslo.upgradecheck>=0.1.0, which is not installed.
cinder 14.0.1.dev22 requires google-api-python-client>=1.4.2, which is not installed.
cinder 14.0.1.dev22 requires oauth2client!=4.0.0,>=1.5.0, which is not installed.
cinder 14.0.1.dev22 requires oslo.upgradecheck>=0.1.0, which is not installed.
cinder 14.0.1.dev22 requires rtslib-fb>=2.1.65, which is not installed.
glance 18.0.1.dev8 requires oslo.upgradecheck>=0.1.0, which is not installed.
neutron 14.0.2.dev41 requires oslo.upgradecheck>=0.1.0, which is not installed.
neutron 14.0.2.dev41 requires ovsdbapp>=0.9.1, which is not installed.
cinder 14.0.1.dev22 has requirement ipaddress>=1.0.17, but you'll have ipaddress 1.0.16 which is incompatible.
cinder 14.0.1.dev22 has requirement oslo.policy>=1.44.1, but you'll have oslo-policy 1.43.1 which is incompatible.
cinder 14.0.1.dev22 has requirement python-glanceclient>=2.15.0, but you'll have python-glanceclient 2.9.1 which is incompatible.
cinder 14.0.1.dev22 has requirement taskflow>=3.2.0, but you'll have taskflow 3.1.0 which is incompatible.
keystone 15.0.1.dev11 has requirement PyJWT>=1.6.1, but you'll have pyjwt 1.5.2 which is incompatible.
neutron 14.0.2.dev41 has requirement oslo.versionedobjects>=1.35.1, but you'll have oslo-versionedobjects 1.31.2 which is incompatible.
gnocchi 4.2.3 has requirement WebOb<1.8.0,>=1.4.1, but you'll have webob 1.8.4 which is incompatible.
Installing collected packages: six, py, setuptools, filelock, toml, configparser, contextlib2, scandir, pathlib2, zipp, importlib-metadata, pluggy, virtualenv, tox
  Found existing installation: six 1.11.0
    Uninstalling six-1.11.0:
      Successfully uninstalled six-1.11.0
  Found existing installation: py 1.8.0
    Uninstalling py-1.8.0:
      Successfully uninstalled py-1.8.0
  Found existing installation: setuptools 40.7.0
    Uninstalling setuptools-40.7.0:
      Successfully uninstalled setuptools-40.7.0
  Found existing installation: filelock 3.0.12
    Uninstalling filelock-3.0.12:
      Successfully uninstalled filelock-3.0.12
  Running setup.py install for filelock ... done
  Found existing installation: toml 0.10.0
    Uninstalling toml-0.10.0:
      Successfully uninstalled toml-0.10.0
  Found existing installation: configparser 3.7.4
    Uninstalling configparser-3.7.4:
      Successfully uninstalled configparser-3.7.4
  Found existing installation: contextlib2 0.4.0
Cannot uninstall 'contextlib2'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by gaborbernat** [comment]
Seems like a bad state to me. Who installed contextlib2 via distutils? I would recommend for you to create a dedicated virtualenv where to install tox, or to cleanup contextlib2 distutils installation.
