### ISSUE TITLE
Add support for filtering test environments by "factors"

### ISSUE THREAD

**Issue by TheFriendlyCoder** [tox-dev/tox#1338]
Suppose you have several environments set up in your tox.ini file using a declaration something like this:

```
[tox]
envlist={py2,py3}-{analyse,test,docs}
```

This creates 6 unique test environments (ie: py2-analyse, py2-test, py3-analyse, py3-test, etc.). Further, when invoking tox on the command line using the `-e` parameter, you may refer to one or more of these test environments by name, but it would be nice if there was some shorthand that allowed you to select groups of environments based on "factors" (ie: portions of the environment name).

My use cases would look something like this:

`tox -e py3`   -> run py3-analyse, py3-test, py3-docs
`tox -e analyse`     -> run py2-analyse and py3-analyse
`tox -e py3-analyse,py3-test`   -> run just the analyse and test operations using the Python 3 interpreter

I did notice there is a precedent in the docs for selecting "all" environments using the special `ALL` identifier as in `tox -e ALL`. So maybe building on that pattern and extending it to support "factors" may be preferable, giving us something like `tox -e py3-ALL` or `tox -e analyse-ALL` or similar.

Another alternative would be to add support for the tox "environment generation" syntax when providing environment names on the command line. Then perhaps we could do something like `tox -e {py2,py3}-analyse` or `tox -e py2-{analyse,test,docs}`. This might be more versatile because users could build up more complex patterns based on the environments they have configured.

Personally, I'd be happy with the first suggestion I've made above - allowing individual "factors" to be used as options for environment names. The syntax is quite terse which is nice, and I think the semantics are pretty obvious even to the casual user.

**Comment by rpkilby** [comment]
[tox-factor](https://github.com/rpkilby/tox-factor) should have you covered. e.g., `tox -f py3` would run all `py3-*` builds. The readme has more usage examples.
