### ISSUE TITLE
changedir has a potentially surprising side-effect

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#1342]
If the directory to change into does not exist yet, it is created. I am not sure if this is even a good idea, but this is the behaviour for a long time now.

We should either update the [documentation](https://tox.readthedocs.io/en/latest/config.html?highlight=changedir#conf-changedir) or change the behaviour to crash if the user tries to change into a directory that does not exist.

What do you think?

**Comment by gaborbernat** [comment]
We need to ensure the directory exists as otherwise Windows fails to spin up a subprocess. Failing the command creation altogether. I think we should document it that we'll create it unless exists. Linux allows you to run commands in non-existing directories.

**Comment by obestwalter** [comment]
I do not think that running commands in a non-existent directory is ever an intended behaviour. So we could definitely check before we do anything independent of where we are and crash with a helpful error.
 
I would also tend towards updating the documentation though as nobody ever complained about this behaviour and I guess it is there already for a very long time (didn't check the history though).

**Comment by gaborbernat** [comment]
But what if you want to run a tool whose working directory is the current folder, and potentially would be created on demand. In this case we would fail though it worked until now. Why is bad creating the cwd?

**Comment by obestwalter** [comment]
Didn't say it's bad. It's surprising though. If I say `cd nonexistingdir` or call `os.chdir` I get an error. I also never noticed before that the behaviour is like this. I just checked with tox 2 and there it was already like this, so I guess just documenting it correctly is the way to go.
