### ISSUE TITLE
Improve tox scalability to many repos by reducing its disk footprint

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox#1346]
While tox provide one of the best testing environments for python projects it also creates a huge amount of duplicated files acros .tox folders. 

The use of system site packages as an workaround for reducing tox footprint has a very limited practical use because of many well known issues related to that.

Instead I propose to enable tox to hardlink/symlinks packages so they do no multiple copies are installed in various environments.

To get an idea about the amount of wasted disk space involved and I realised that ~30-35% of my 500GB ssd is taken by .tox folders, with a blazing record on ansible-molecule where .tox folder take **6.3GB** (36 envs). I also counted the number of projects using tox that I have checked out on that machine and is around **~190**.

While pip does a good job caching the packages, the problem is that they still need to be installed in each environment, which takes time and space.

While it may be outside tox power to address that problem alone as it may require modification on virtualenv and/or we should at least identify what prevents us from implementing deduplication support.

**Comment by omry** [comment]
you might be able to solve this at the file system level.
in particular, if you create a zfs mount point with deduplication enabled it would save a ton of space.

**Comment by gaborbernat** [comment]
This type of duplication is due to the installer creating multiples copies. tox 4 now has abstracted out the installer https://github.com/tox-dev/tox/blob/rewrite/src/tox/tox_env/installer.py#L12, so you can implement some smart installer via that which symlinks stuff.
