### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by barneygale** [tox-dev/tox#1347]
Hi, we'd love a new release of tox so we can pick up ef843dcde0882bedc3be32c0b12191054b18fffb. Thanks! :D

**Comment by adithyabsk** [comment]
On that note, it seems that there have been additional releases on pypi which are not reflected in the github tags. Also, is there a changelog that I can be pointed to?

**Comment by gaborbernat** [comment]
all tags available under https://github.com/tox-dev/tox/releases, and changelog under https://tox.readthedocs.io/en/latest/changelog.html

**Comment by gaborbernat** [comment]
tried a release under https://dev.azure.com/toxdev/tox/_build/results?buildId=1919&view=logs&j=380ab8c6-4139-55ff-15c4-fb48260f4dca

**Comment by gaborbernat** [comment]
Resolved via https://pypi.org/project/tox/3.13.0/ #1348
