### ISSUE TITLE
Clarify which part of the indexserver spec is deprecated 

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#1357]
... or even decide to not deprecate it after all.

This came up on the [mailing list](https://mail.python.org/archives/list/tox-dev@python.org/thread/N3URNZALQL7S257Y24QSH72Y7RX2B6OV/). 

It seems that this config option is well established, works as expected and is used in many scenarios (especially corporate when using internal pypi repos with different stages or devpi). So we might want to decide to remove the deprecation notice completely, if there are no objections regarding the maintenance of it.

As @fschulze mentioned, at least the single index variant is highly desirable (and I am pretty sure widely used).

I would opt for removing the deprecation notice and keep the full functionality.

**Comment by gaborbernat** [comment]
I personally would like to remove it completely. I need to think what's a better solution to the problem though.

**Comment by obestwalter** [comment]
Having to pass in something rather than being able to configure it in the `tox.ini` is not a desirable alternative IMO. Behind corporate firewalls this is a very useful feature to set the index to the internal pypi mirror for everyone rather than having to tell everyone they have to call with some special env var set.

**Comment by gaborbernat** [comment]
You can use setenv to set that env var in tox.ini.

**Comment by fschulze** [comment]
I just tested it and I think ``setenv`` with ``PIP_INDEX_URL`` is a good solution. According to the docs it is used for setup and test run. This just needs to be documented prominently so it's easy to find and there should be a deprecation message pointing to the docs when the option is used in the config. Not sure about the command line option though. It doesn't seem to be deprecated, but also only seems to pass on one index straight to pip.

**Comment by fschulze** [comment]
One problem I just thought about is that you can't overwrite ``PIP_INDEX_URL`` from the command line or via CI environment variables, but that may already be the case right now.

**Comment by gaborbernat** [comment]
We can change the default pip command to auto pass through pip index URL from outside env var👌For now we do it explicitly overriding the pip install command inside tox.ini at our company this.

**Comment by gaborbernat** [comment]
Here's what we use:

```
install_command = pip install -i {env:PIP_INDEX_URL:https://magic.index.server.address/simple} {opts} {packages}
```

We should probably just make this as the default and drop the entire indexserver thing. This would keep the installer tool agnostic the index server selection. The main reason for this is that index server is a pip thing, conda/dpkg, for example, doesn't have such. It's a clearer separation of concern if we the tool doesn't know about pips internals; and makes it easier to extend to use other packaging tools.

**Comment by obestwalter** [comment]
This needs a deprecation warning then and a hint how to solve this differently, plus some docs.

**Comment by sinoroc** [comment]
The `indexserver` setting is still the recommended solution in the examples ["_using a different default PyPI url_"](https://tox.readthedocs.io/en/latest/example/basic.html#using-a-different-default-pypi-url) and ["_installing dependencies from multiple PyPI servers_"](https://tox.readthedocs.io/en/latest/example/basic.html#installing-dependencies-from-multiple-pypi-servers).

Is there a newer, up-to-date example?

Is using the `PIP_INDEX_URL` environment variable still the recommended alternative?

**Comment by gaborbernat** [comment]
> Is using the `PIP_INDEX_URL` environment variable still the recommended alternative?

Yes. tox 4 will also recommend this. This ticket is for someone to fix our documentation to reflect this. PRs are welcome.

**Comment by sinoroc** [comment]
Thanks.

I will experiment with that. We will see if I find a technique I feel is good enough to be used as an example.

**Comment by ziima** [comment]
I've replaced the `indexserver` from the docs in basic case. I'm not sure though, what's the purpose of multiple PyPI servers. Is the problem in question to locate packages which are not available at pypi.org?

**Comment by sinoroc** [comment]
> I'm not sure though, what's the purpose of multiple PyPI servers.

@ziima It should cover the [_`--extra-index-url`_](https://pip.pypa.io/en/stable/reference/pip_install/#install-extra-index-url) use cases.

Maybe something like:

```
[tox]
setenv =
    PIP_INDEX_URL = {env:PIP_INDEX_URL:https://pep503.alpha.dev}
    PIP_EXTRA_INDEX_URL = {env:PIP_EXTRA_INDEX_URL:https://pep503.bravo.dev https://pep503.delta.dev}
```

**Comment by fschulze** [comment]
@ziima afaik it was added for devpi etc, so one could test releases before uploading the to PyPI. It might be that multiple indexes were necessary until devpi got inheritance to look at PyPI itself.

**Comment by ziima** [comment]
OK, that seems to be simple. I was somewhat confused by the case where individual packages were installed from different indexes.

**Comment by sinoroc** [comment]
> OK, that seems to be simple. I was somewhat confused by the case where individual packages were installed from different indexes.

I don't think this part can be recreated without the deprecated `indexserver` setting (I have not found how).

**Comment by ziima** [comment]
Me neither, but it seems like a specific behavior of tox only. I haven't found alternatives in other tools, so I believe it's too exotic and can be removed.

**Comment by sinoroc** [comment]
> Me neither, but it seems like a specific behavior of tox only. I haven't found alternatives in other tools, so I believe it's too exotic and can be removed.

@ziima I agree.

On a side note... What might be missing in the Python packaging ecosystem is a requirement notation such as:

```
Library @ https://pep503.tango.dev/simple/
```

I believe this would fit quite well into `requirements.txt` files, or:

```ini
[testenv]
deps =
    Library @ https://pep503.tango.dev/
```

which would translate to:

```
python -m pip install --index-url 'https://pep503.tango.dev/' Library
```

**Comment by sinoroc** [comment]
I opened a discussion on the topic:
* https://discuss.python.org/t/dependency-notation-including-the-index-url/5659

**Comment by sinoroc** [comment]
As far as I understood, the philosophy is that _indexes_ should be indistinguishable, interchangeable. If 2 projects of the same name exist on 2 indexes, it is assumed that they are the exact same project and that 2 distributions of the same name and version number are the exact same distribution and so it does not matter from which one we fetch. In other words:

> Packages are expected to be unique up to name and version, so two wheels with the same package name and version are treated as indistinguishable by pip. This is a deliberate feature of the package metadata, and not likely to change.

-- pfmoore, https://github.com/pypa/pip/issues/5045#issuecomment-369521345

If one needs to circumvent this, they need to put something like _devpi_ in place. Of particular importance is its "_inheritance_" feature, as far as I understood this would be the key feature that would prevent downloading a dependency from the "_wrong_" index when configured right (not sure how, though). I do not know if other servers than _devpi_ would allow this kind of workflow as well.

With that said, and the changes made in #1728, I would say that the topic can be closed.
