### ISSUE TITLE
InterpreterNotFound: jython since 3.10.0

### ISSUE THREAD

**Issue by baztian** [tox-dev/tox#1365]
Just upgraded my tox to the latest version. Found out that I now get a `InterpreterNotFound` exception for jython (2.7.0) envs.
I found out that this error happens starting from 3.10.0. 3.9.0 is good (despite the fact that the virtualenv doesn't work with jython anymore for some other reasen).

For 3.10.0:

    tox -rvv -e jython-driver-hsqldb
    using tox.ini: /home/me/Sources/jaydebeapi/tox.ini (pid 17454)
      removing /home/me/Sources/jaydebeapi/.tox/log
    using tox-3.10.0 from /tmp/toxenv/lib/python3.5/site-packages/tox/__init__.py (pid 17454)
    skipping sdist step
    jython-driver-hsqldb start: getenv /home/me/Sources/jaydebeapi/.tox/jython-driver-hsqldb
    jython-driver-hsqldb cannot reuse: -r flag
    jython-driver-hsqldb create: /home/me/Sources/jaydebeapi/.tox/jython-driver-hsqldb
    ('path found', local('/home/me/bin/jython'))
    jython (/home/me/bin/jython) is {'version': '2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11) \n[OpenJDK 64-Bit Server VM (Oracle Corporation)]', 'name': 'python', 'sysplatform': 'java9-internal', 'executable': '/home/me/Software/jython-2.7.0/bin/jython', 'version_info': [2, 7, 0, 'final', 0], 'is_64': False}
    jython-driver-hsqldb uses None
    ERROR: InterpreterNotFound: jython
    jython-driver-hsqldb finish: getenv /home/me/Sources/jaydebeapi/.tox/jython-driver-hsqldb after 6.79 seconds
    ___________________________________ summary ____________________________________
    ERROR:  jython-driver-hsqldb: InterpreterNotFound: jython

For 3.9.0:

    tox -rvv -e jython-driver-hsqldb
    using tox.ini: /home/me/Sources/jaydebeapi/tox.ini (pid 17952)
      removing /home/me/Sources/jaydebeapi/.tox/log
    using tox-3.9.0 from /tmp/toxenv/lib/python3.5/site-packages/tox/__init__.py (pid 17952)
    skipping sdist step
    jython-driver-hsqldb start: getenv /home/me/Sources/jaydebeapi/.tox/jython-driver-hsqldb
    jython-driver-hsqldb cannot reuse: -r flag
    jython-driver-hsqldb create: /home/me/Sources/jaydebeapi/.tox/jython-driver-hsqldb
      removing /home/me/Sources/jaydebeapi/.tox/jython-driver-hsqldb
    setting PATH=/home/me/Sources/jaydebeapi/.tox/jython-driver-hsqldb/bin:/tmp/toxenv/bin:/home/me/bin:/home/me/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
    [18022] /home/me/Sources/jaydebeapi/.tox$ /tmp/toxenv/bin/python3 -m virtualenv --python /home/me/Software/jython-2.7.0/bin/jython jython-driver-hsqldb
    Running virtualenv with interpreter /home/me/Software/jython-2.7.0/bin/jython
    Already using interpreter /home/me/Software/jython-2.7.0/bin/jython
    New python executable in /home/me/Sources/jaydebeapi/.tox/jython-driver-hsqldb/bin/jython
    Also creating executable in /home/me/Sources/jaydebeapi/.tox/jython-driver-hsqldb/bin/python
    
    /home/me/Sources/jaydebeapi/.tox/jython-driver-hsqldb contains neither jython-dev.jar nor jython.jar.
    Try running this script from the 'bin' directory of an installed Jython or 
    setting $JYTHON_HOME.
    usage: jython [option] ... [-c cmd | -m mod | file | -] [arg] ...
    Try `jython -h' for more information.
    
    ERROR: The executable /home/me/Sources/jaydebeapi/.tox/jython-driver-hsqldb/bin/jython is not functioning
    ERROR: It thinks sys.prefix is '/home/me/Sources/jaydebeapi/.tox' (should be u'/home/me/Sources/jaydebeapi/.tox/jython-driver-hsqldb')
    ERROR: virtualenv is not compatible with this system or executable
    ERROR: invocation failed (exit code 100)
    ERROR: InvocationError for command /tmp/toxenv/bin/python3 -m virtualenv --python /home/me/Software/jython-2.7.0/bin/jython jython-driver-hsqldb (exited with code 100)
    jython-driver-hsqldb finish: getenv /home/me/Sources/jaydebeapi/.tox/jython-driver-hsqldb after 15.90 seconds
    ___________________________________ summary ____________________________________
    ERROR:   jython-driver-hsqldb: InvocationError for command /tmp/toxenv/bin/python3 -m virtualenv --python /home/me/Software/jython-2.7.0/bin/jython jython-driver-hsqldb (exited with code 100)

Setting `JYTHON_HOME` doesn't change the results of the output.

**Comment by gaborbernat** [comment]
This should be fixed now.
