### ISSUE TITLE
What to do about python3.10

### ISSUE THREAD

**Issue by asottile** [tox-dev/tox#1374]
Should we make `tox -e py310` work? Should we introduce a new thing that's `tox -e py2.7`  such that it's unambiguous?

**Comment by obestwalter** [comment]
ooof you really think ahead :)

I guess this is a case then of extending the default parameters. Depending on if the Python release cycle will be shortened or not after 3.8 we have about 12 to 18 months time to get this sorted :)

**Comment by asottile** [comment]
I set up a ppa with the version bumped so we can start trying this out today -- https://launchpad.net/~asottile/+archive/ubuntu/python3.10

there's quite a lot of breakage unfortunately -- for example we can't really start fixing this much here until `virtualenv` is fixed: https://github.com/pypa/virtualenv/pull/1385

**Comment by gaborbernat** [comment]
Virtualenv rewrite in progress will solve this mostly (including tox side)👍would not worry about this for now.

**Comment by asottile** [comment]
I don't think it will, we currently don't detect `py310` as a python factor at all -- and even if we did it seems ambiguous between `3.1.0` `3.10` `31.0` etc.

**Comment by asottile** [comment]
Ideally I'd like to fix this now as it unlocks being able to test the rest of the ecosystem -- no virtualenv / no tox and it's really difficult to validate things

**Comment by gaborbernat** [comment]
Part of the rewrite tox will delegate environment creation related stuff to virtualenv. Wait one more month 👍

**Comment by gaborbernat** [comment]
If you really want go ahead though but fyi 😊

**Comment by asottile** [comment]
hehe I would appreciate a 16.6.3 w/ https://github.com/pypa/virtualenv/pull/1385
