### ISSUE TITLE
Allow optional dependencies

### ISSUE THREAD

**Issue by rxu18** [tox-dev/tox#1376]
Use case: I am working on a project (vertica-python) that introduces a platform-dependent package called `kerberos` for advanced feature. As a result, we will have two possible testing setup.
1. Locally, where we may not have this package but will skip over tests for this advanced feature.
2. Using Travis CI, where we have the environment to install this package and test all features.

Is there a way to make a dependency optional? We can add an env and explicitly state the env every time to test, but this can make the barrier much higher for new contributors. We couldn't find anything specific on documentation and right now we may need to resort to rewriting the tox file in our Travis script.

Thanks!

**Comment by gaborbernat** [comment]
This is a pytest feature you want to skip if that package is not available. Otherwise always run. You can even write a fixture that fails on ci if not present.

**Comment by BenjamenMeyer** [comment]
Tox already supports optional dependencies by setting up separate environments with each dependency. If you want it to be fully optional, then don't include it in the default environment list that tox runs. (Example: https://github.com/TestInABox/stackInABox/blob/master/tox.ini - I have 3 optional dependencies in there; though they all run by default.)

Also, you may want to look at how Travis CI is configured as you can use a matrix there to do the optional dependencies too. (Example: https://github.com/TestInABox/stackInABox/blob/master/.travis.yml).
