### ISSUE TITLE
virtualenv creates incorrect/broken python3 interpreters

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [tox-dev/tox#1381]
as far as i can tell all released versions of virtualenv create a python interpreter with a broken venv module

it would be helpful if python3 interpreters would always use their respective venv module,
making the virtualenv code path something for only the legacy/dead python interpreters

currently i'm working around the issue by using tox-venv

**Comment by gaborbernat** [comment]
virtualenv rewrite will do this which we'll switch to soon after 👍 I don't think your statement holds true generally though.

**Comment by RonnyPfannschmidt** [comment]
most things dont "break", but edge details like the venv module break for example

**Comment by RonnyPfannschmidt** [comment]
btw, whats the timeline for the rewrite? i recall that the rewrite branch of virtualenv is unfinished since ages now

**Comment by gaborbernat** [comment]
I hope by September, the thing is to test the new virtualenv I need a rewrite of tox first 😅 which is wip, but might park and finish first the rewrite 😎 of that

**Comment by asottile** [comment]
@RonnyPfannschmidt if you're looking for a workaround, there's prior art in https://github.com/pre-commit/pre-commit/blob/376d283ba38a24a0df0dff8463f8474d1fd8e3d2/pre_commit/languages/python_venv.py#L21-L47

I think this issue is maybe on the wrong project though and should be on pypa/virtualenv instead?

**Comment by RonnyPfannschmidt** [comment]
Stopping to use virtualenv is hardly a issue that makes sense on virtualenv

**Comment by asottile** [comment]
@RonnyPfannschmidt but the core issue is "venv from virtualenv is broken" is it not -- that's kinda unrelated to tox

**Comment by RonnyPfannschmidt** [comment]
@asottile this is about tox using virtualeenv instead of venv for python3, this is not about virtualenv itself

@gaborbernat as far as i understood this one will auto-close with the next gen virtualenv once it lands?

**Comment by asottile** [comment]
tox will continue to use virtualenv even when that lands, just the internal mechanisms of virtualenv will change approach for py3

**Comment by rpkilby** [comment]
@RonnyPfannschmidt. If you need to use `venv` for Python 3, there is tox-venv, which was born out of #630.

**Comment by RonnyPfannschmidt** [comment]
@rpkilby thanks for the reference, i am currently using tox-venv to avoid tox breaking the world

**Comment by gaborbernat** [comment]
I think this has been fixed.

**Comment by RonnyPfannschmidt** [comment]
yes
