### ISSUE TITLE
bat file-based setup stopped working as of tox 3.10.0

### ISSUE THREAD

**Issue by tkf** [tox-dev/tox#1386]
I'm using `bat` files to run `tox` with 32-bit and 64-bit Python interpreters, as mentioned in [the manual](https://tox.readthedocs.io/en/latest/developers.html#id2).  However, this trick seems to be stopped working as of `tox` 3.10.

* [`tox` 3.9](https://ci.appveyor.com/project/Keno/pyjulia/builds/26389368#L159) finds 32 bit Python 2.7 (via `ci\appveyor\win32\python2.7.bat`): https://ci.appveyor.com/project/Keno/pyjulia/builds/26389368#L326
* [`tox` 3.10](https://ci.appveyor.com/project/Keno/pyjulia/builds/26389589#L160) fails to find 32 bit Python 2.7: https://ci.appveyor.com/project/Keno/pyjulia/builds/26389589#L319
* [`tox` 3.13.2](https://ci.appveyor.com/project/Keno/pyjulia/builds/26389140#L159) fails to find 32 bit Python 2.7: https://ci.appveyor.com/project/Keno/pyjulia/builds/26389140#L319

Are `bat` files still supported?  Is there a way to run `tox` with 32-bit and 64-bit Python interpreters in CI (other than using `tox` <= 3.9)?

ref: https://github.com/JuliaPy/pyjulia/pull/313

**Comment by gaborbernat** [comment]
I'm closing this as I think has been addressed. Please check out tox 4, if it still break we can reopen.
