### ISSUE TITLE
substitution and exit-code ignore conflict

### ISSUE THREAD

**Issue by pwoolvett** [tox-dev/tox#1403]
when a command uses replacements with ignore output, replacements raises `tox.exception.ConfigError`.

No problems:

```ini

[testenv:someenv]
commands = ls {posargs}

[testenv:someenv2]
commands = 
  {[testenv:someenv]commands}
```

Problems:

```ini
[testenv:someenv]
commands = ls {posargs}

[testenv:someenv2]
commands = 
  - {[testenv:someenv]commands}
```

running any tox cmd: `tox --showconfig`

`tox.exception.ConfigError: ConfigError: substitution key 'posargs' not found`

**Comment by gaborbernat** [comment]
```
❯ tox4 c -k commands -- magic
[testenv:someenv]
commands = ls magic

[testenv:someenv2]
commands = ls magic

[testenv:.pkg]

[tox]
```

Seems to have been fixed by the rewrite and new release soon.
