### ISSUE TITLE
Indirect dependency on Python 3 only library

### ISSUE THREAD

**Issue by hackebrot** [tox-dev/tox#1406]
Hi friends! 👋 

Thank you for your work on tox! It's a fantastic project. 🚀 

The cookiecutter builds are currently [failing for Python 2.7](https://ci.appveyor.com/project/cookiecutter/cookiecutter/branch/master/job/ec787v2rawykero1) environments due to an indirect dependency on a Python 3 only library in tox: [more_itertools](https://pypi.org/project/more-itertools)

It looks like this issue has been raised with the dependent package at https://github.com/jaraco/zipp/issues/14. I'm also raising this with the pluggy project, but figured you might want to know.

**Comment by gaborbernat** [comment]
Hmm @jaraco did you made this requirement in the dependency of zipapp?

**Comment by hackebrot** [comment]
Hey @jaraco! 👋 

It looks like the Python 2 test environment uses pip 19.2.3 but the build still [breaks](
https://ci.appveyor.com/project/luzfcb/cookiecutter/builds/26967833/job/mt4qsh5gl990joy6).

**Comment by hackebrot** [comment]
Thank you for your analysis @jaraco! That was helpful and the build is stable again after upgrading virtualenv on our windows CI. 🚀

**Comment by jaraco** [comment]
Perhaps tox should include a minimum dependency on virtualenv to help alleviate this issue (and others).

Sent from my comm

On Aug 27, 2019, at 06:19, Bernát Gábor <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #1406<https://github.com/tox-dev/tox/issues/1406>.

**Comment by bszonye** [comment]
My team was running into this with pip 19.1 and virtualenv 16.5.0 when running `pip install tox`. We were able to work around it with `pip install 'more-itertools<6' tox` but based on the explanation above I didn’t think it would be a problem with those tool versions. We are using `VIRTUALENV_DOWNLOAD=no` if that matters.

**Comment by jaraco** [comment]
@bszonye Glad you found a workaround. Another possible cause is that you're using an index server that's not compliant with the Requires-Python support. You can test with `pip install -i https://your.index.server more_itertools` on Python 2. You should not get `more_itertools` 6. If you do, then your environment is not successfully filtering invalid versions of packages and you'll have issues in the future with more than just `more_itertools` and you'll want to troubleshoot further. Index servers I know to support the Requires-Python are Warehouse (PyPI) and [devpi](https://devpi.net). I highly recommend the latter for company-internal package repositories / mirrors.

**Comment by bszonye** [comment]
Aha! We are already using devpi but not the version with Requires-Python support: https://devpi.net/docs/devpi/devpi/stable/+doc/changelog.html#id69
