### ISSUE TITLE
[BUG]Fail to create rpm using python2

### ISSUE THREAD

**Issue by krmanish** [tox-dev/tox#1407]
I need to have rpm to be required to install in my chroot env where I do not have pip installed. 
When I run `python setup.py bdist_rpm` I get `UnicodeDecodeError`.

**Note that** : `python setup.py build` works just fine.

**Traceback:**
```
Traceback (most recent call last):
  File "setup.py", line 18, in <module>
    package_dir={'': 'src'},
  File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 144, in setup
    _install_setup_requires(attrs)
  File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 137, in _install_setup_requires
    dist.parse_config_files(ignore_option_errors=True)
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 702, in parse_config_files
    self._parse_config_files(filenames=filenames)
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 599, in _parse_config_files
    (parser.read_file if six.PY3 else parser.readfp)(reader)
  File "/usr/lib64/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/usr/lib64/python2.7/ConfigParser.py", line 479, in _read
    line = fp.readline()
  File "/usr/lib64/python2.7/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
```

> python -c "import setuptools;print setuptools.__version__"
> 40.8.0

> 
> Locale
> LANG=en_US.UTF-8
> LC_CTYPE="en_US.UTF-8"
> LC_NUMERIC="en_US.UTF-8"
> LC_TIME="en_US.UTF-8"
> LC_COLLATE="en_US.UTF-8"
> LC_MONETARY="en_US.UTF-8"
> LC_MESSAGES="en_US.UTF-8"
> LC_PAPER="en_US.UTF-8"
> LC_NAME="en_US.UTF-8"
> LC_ADDRESS="en_US.UTF-8"
> LC_TELEPHONE="en_US.UTF-8"
> LC_MEASUREMENT="en_US.UTF-8"
> LC_IDENTIFICATION="en_US.UTF-8"
> LC_ALL=

OS: Fedora-29

Python3 build is OK.

**Comment by asottile** [comment]
What version of `setuptools` are you using (and have you tried the latest)?

**Comment by asottile** [comment]
I was able to generate an rpm without issue in docker 🤷‍♂ 

```bash
docker run -v $PWD:/code:rw --rm -ti fedora bash
```

```console
(venv) [root@08d6cef84ae8 code]# history
    1  dnf install python2
    2  dnf install curl
    3  ls
    4  curl https://asottile.github.io/get-virtualenv.py | python2 - venv
    5  . venv/bin/activate
    6  pip install setuptools --upgrade  # already up to date @41.2.0
    7  ls
    8  echo $LANG  # C.UTF-8
    9  cd /code/
   10  python setup.py  bdist_rpm
   11  dnf install rpmspec    # ignore this, it isn't a thing
   12  dnf install fedora-packager  # used this to find `rpm-build` but said no
   13  dnf install rpm-build
   14  python setup.py  bdist_rpm  # successfully built, you'll need to preinstall setuptools-scm to get the versioning correct
```

**Comment by krmanish** [comment]
> What version of `setuptools` are you using (and have you tried the latest)?
It's **40.8.0**. Description has this detail already.
![image](https://user-images.githubusercontent.com/4631983/64255863-d9793780-cf3f-11e9-8b7d-4fecef609d7c.png)

**Comment by gaborbernat** [comment]
I think this is no longer the case. If it is please check back and we can reopen.
