### ISSUE TITLE
UNC path in additional argument causes tox failure

### ISSUE THREAD

**Issue by cyrilschmidt** [tox-dev/tox#1410]
**Problem description:** when tox is passed a UNC path as additional argument, it fails with the error message like

> ValueError: path is on mount '\\\\172.18.180.162\\Share1', start on mount 'C:'

The tox.ini is attached (note: tox.ini is renamed to tox.ini.txt) [tox.ini.txt](https://github.com/pytest-dev/pytest/files/3546839/tox.ini.txt)

The full stack trace is

> Traceback (most recent call last):
>  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
>    "__main__", mod_spec)
>  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
>    exec(code, run_globals)
>  File "C:\Program Files\Python37\Scripts\tox.exe\__main__.py", line 9, in <module>
>  File "c:\program files\python37\lib\site-packages\tox\session\__init__.py", line 42, in cmdline
>    main(args)
>  File "c:\program files\python37\lib\site-packages\tox\session\__init__.py", line 58, in main
>    config = load_config(args)
>  File "c:\program files\python37\lib\site-packages\tox\session\__init__.py", line 75, in load_config
>    config = parseconfig(args)
>  File "c:\program files\python37\lib\site-packages\tox\config\__init__.py", line 249, in parseconfig
>    ParseIni(config, config_file, content)
>  File "c:\program files\python37\lib\site-packages\tox\config\__init__.py", line 1077, in __init__
>    config.envconfigs[name] = self.make_envconfig(name, section, reader._subs, config)
>  File "c:\program files\python37\lib\site-packages\tox\config\__init__.py", line 1181, in make_envconfig
>    res = env_attr.postprocess(testenv_config=tc, value=res)
>  File "c:\program files\python37\lib\site-packages\tox\config\__init__.py", line 207, in postprocess
>    arg = os.path.relpath(origpath, testenv_config.changedir.strpath)
>  File "c:\program files\python37\lib\ntpath.py", line 562, in relpath
>    path_drive, start_drive))
>ValueError: path is on mount '\\\\172.18.180.162\\Share1', start on mount 'C:'

**How to reproduce:**
`tox -e test-posargs -- \\172.18.180.162\Share1`

**Additional observations:**
1. Tox works if the additional argument is not a UNC path, e.g. `tox -e test-posargs -- C:\`
2. Tox works if the UNC path points to a nonexistent share, e.g. `tox -e test-posargs -- \\172.18.180.162\NoShare`
3. If I move the commands in the default section `[testenv]`, it works.
4. Positional arguments are not even referred to in tox.ini.
5. The `args_are_paths` option should prevent tox from meddling with the arguments, but it does not.

**Environment:**
OS; Windows Server 2012 R2 Datacenter

> C:\>pip list
> Package         Version
> --------------- -------
> filelock        3.0.10
> numpy           1.16.2
> pandas          0.24.2
> pip             19.0.3
> pluggy          0.9.0
> py              1.8.0
> python-dateutil 2.8.0
> pytz            2019.1
> scipy           1.2.1
> setuptools      40.8.0
> six             1.12.0
> toml            0.10.0
> tox             3.8.1
> virtualenv      16.4.3
> xmljson         0.2.0

**Comment by gaborbernat** [comment]
Can you try with tox 4? And ifit still happens post it again?
