### ISSUE TITLE
tox -p without number should enable auto mode

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox#1418]
It would a good improvement in user experience if when adding just `-p`, tox would run in parallel mode, like it does not with `tox -p auto`. This would save 5 keystrokes when calling tox.

I think that `auto` is likely what most people want when they want to run in parallel, so why to ask the to type more for getting it.

**Comment by awecx** [comment]
This would be consistent with makefile `-j` where, if no argument is given, would select a number of parallel recipes to build itself.

**Comment by JulienPalard** [comment]
> This would be consistent with makefile `-j` where, if no argument is given, would select a number of parallel recipes to build itself.

I'm not sure for every make implemn, but quoting the GNU make manpage:

> If the -j  option  is  given  without an argument, make will not limit the number of jobs that can run simultaneously.

Which looks more like `all` than `auto`.

(This typically make `make -j` a bit violent when compiling cpython.)

I'd say `all` is not a sane default, and defaulting to `auto` looks a better choice.

While thinking about it, I **bet** (it's only a bet, so don't mind me) `auto` can be faster than `all` as both run the same quantity of instructions, but in the `all` case there may be more context switches (or worse, swapping).

**Comment by gaborbernat** [comment]
Feel free to open a PR against master and fix it. My available efforts at the moment are aimed at fixing this as part of https://github.com/tox-dev/tox/issues/1394, but that probably will take a while (ETA September).

**Comment by gaborbernat** [comment]
Hello, this now has been released via https://pypi.org/project/tox/3.15.0/ 

![heads up](https://media.tenor.co/images/0118006f847acfcfd22e8bf0fd405e42/tenor.gif)
