### ISSUE TITLE
Prevent environment recreation

### ISSUE THREAD

**Issue by goerz** [tox-dev/tox#1420]
Is there any way to prevent `tox` from re-creating environments if they already exist, no matter what? The `--recreate` option does the opposite: recreate environments no matter what. So, I'd be looking for an explicit `--no-recreate` option (or, change `--recreate` to `--recreate=[auto]/true/false`, although this would deviate from what was discussed in #1372).

I have a couple of use-cases: I have a `tox.ini` for Unix systems and `tox-conda.ini` for Windows which uses `tox-conda`. I'd like to launch a specific tox command e.g. `tox -e linting`  from a script which reuses an existing environment `.tox/py37` that is guaranteed to have been created from a previous tox call, but I don't know whether that previous call was `tox -c tox.ini ...` or `tox -c tox-conda.ini ...`. The problem is that tox will recreate `.tox/py37` if there is any mismatch between the ini files.

Second, for the `tox-conda`-created environments, I was trying to debug some problems with binary incompatibilities of conda packages installed from different channels. To investigate this, I manually ran `conda` commands to un/re-install packages in the `.tox/py37` conda environment. Unfortunately, it seems `tox` or `tox-conda` detects this and recreates the environment, wiping out my changes.

In either case, I just want tox to re-used the existing environment, no questions asked. While I could probably work around the first use case without too much trouble, the second one seems more difficult: I'd like to manually tweak tox environment for debugging and not have to worry whether this might trigger re-creation.

**Comment by goerz** [comment]
For the record, my workaround for the first use-case would be something like this: https://github.com/qucontrol/krotov/blob/e17a5c08719f5f35be3da9fbcea4961a8c361cd2/scripts/pre-commit.py#L51

**Comment by gaborbernat** [comment]
I think this kinda goes against tox philosophy of you define your dependencies, we ensure those dependencies are met when calling the command.
