### ISSUE TITLE
EnvLog does not respect passenv/setenv

### ISSUE THREAD

**Issue by connyay** [tox-dev/tox#1422]
Hello!

This will likely be a crappy bug report because I don't have an isolated repro. Sorry 😞 

Working with tox in a pretty strange environment that basically uses relocatable python installations in specific directories. Noticed on centos boxes an environment could not be created due to the .so not being loaded properly.

Tracked it down to venc.setupenv on [this line](https://github.com/tox-dev/tox/blob/7106a16/src/tox/venv.py#L619). Noticed that `EnvLog. set_python_info` has no concept of the configuration's `passenv` or `setenv` so the `LD_LIBRARY_PATH` does not get set.

Couldn't quickly grok a fix for this. `action.popen` looks promising? but not sure the implications.

Let me know if I can provide any further info.

**Comment by gaborbernat** [comment]
Feel free to open a PR against master and fix it. My available efforts at the moment are aimed at fixing this as part of https://github.com/tox-dev/tox/issues/1394, but that probably will take a while (ETA September).

**Comment by gaborbernat** [comment]
This issue has now been avoided in the rewrite branch.
