### ISSUE TITLE
whitelist_externals for something in $HOME.

### ISSUE THREAD

**Issue by kierun** [tox-dev/tox#1424]
I have a dependency that will always be installed in `$HOME`. I tried to specify it using 

```
whitelist_externals=$HOME/bib/my_crazy_script
```

But that does not work -- I still got the warning. I tried to pass `HOME` to `passenv` but again, that did not sop the warning.

How can I specify this?

**Comment by gaborbernat** [comment]
https://tox.readthedocs.io/en/latest/config.html#environment-variable-substitutions

<blockquote><div><strong><a href="https://tox.readthedocs.io/en/latest/config.html#environment-variable-substitutions">tox configuration specification — tox 3.14.1.dev2 documentation</a></strong></div></blockquote>
