### ISSUE TITLE
tox must upgrade Pip in `.tox` env before installing any other dists

### ISSUE THREAD

**Issue by webknjaz** [tox-dev/tox#1425]
I'm hitting the same problem that pytest hit a while back:
https://ci.appveyor.com/project/CherryPy/cheroot/builds/27622282/job/6etbt4hn5hv08x3y#L132

So basically tox does `pip install 'pip >= 9' 'tox-run-command >= 0.4' 'tox >= 3.13.2'` in `.tox` venv but Pip that is invoked is Pip 8.
So this pulls in more-itertools via as a dependency choosing v7.0.0 which is incompatible with Python 2.

I think, it's reasonable to upgrade Pip as a pre-requisite step.

**Comment by webknjaz** [comment]
Do you mean pinning the dependency of tox itself?

**Comment by gaborbernat** [comment]
![thanks](https://media.tenor.co/images/c5e869302d6ad46d0ab893115d66ea27/tenor.gif)

**Comment by webknjaz** [comment]
:laughing: you need this one last bot here: https://twitter.com/gabro27/status/1173547934132178944

**Comment by gaborbernat** [comment]
hope neither your or me are qualified as a both yet 😆

**Comment by atugushev** [comment]
Thanks for bumping up `virtualenv`! This problem with an old virtualenv always happens in AppVeyor, so I almost in every project in appveyor.yml install the latest virtualenv before tox to fix weird bugs mostly related to pip==8.1.1 (which is currently used in AppVeyor!).
