### ISSUE TITLE
problem running tox with site module

### ISSUE THREAD

**Issue by vahtras** [tox-dev/tox#1432]
The Python version that tox executes has a fundamentally different `site` module than the standard distrubution. Why is that? The resulting error I have had boils down to the following line

    $ ./.tox/py36/bin/python3.6 -c 'import site; print(site.getuserbase())'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    AttributeError: module 'site' has no attribute 'getuserbase'

    $ ./.tox/py36/bin/python3.6 --version
    Python 3.6.8

to be compared with

    $ /usr/bin/python3.6 -c 'import site; print(site.getuserbase())'
    /home/olav/.local
    $ /usr/bin/python3.6 --version
    Python 3.6.8

**Comment by gaborbernat** [comment]
This is a side-effect of how virtualenv works. See https://www.youtube.com/watch?v=o1Vue9CWRxU for an in-depth detail. The next iteration of virtualenv will solve this (https://github.com/pypa/virtualenv/pull/1377); in the meantime you can switch tox to use venv instead by using https://pypi.org/project/tox-venv/
