### ISSUE TITLE
Should `tox -e unknown` output to stderr?

### ISSUE THREAD

**Issue by dmtucker** [tox-dev/tox#1434]
```
$ tox -e foo
ERROR: unknown environment 'foo'
```
These seem inconsistent:
```
$ tox -e foo >/dev/null
```
```
$ tox -c foo >/dev/null
ERROR: foo is neither file or directory
ERROR: tox config file (either pyproject.toml, tox.ini, setup.cfg) not found
```
Is this intentional?

**Comment by gaborbernat** [comment]
I agree with your proposal, could be part of #1394 as it would be breaking.

**Comment by gaborbernat** [comment]
Feel free to open a PR against master and fix it. My available efforts at the moment are aimed at fixing this as part of https://github.com/tox-dev/tox/issues/1394, but that probably will take a while (ETA September).

**Comment by gaborbernat** [comment]
Actually, in tox 4 we allowed users to create new environments on the fly, so in the above case the error message is no longer displayed and instead we run the foo environment as it would be defined under envlist
