### ISSUE TITLE
Extend default passenv to include SSL proxy vars

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox#1437]
There is a list of 3 environment variables that are also needed for SSL proxies. Tox is currently passing proxy vars but missing to pass the SSL vars and the side effect is clear: called code will choke trying to verify the SSL certificates.

```
CURL_CA_BUNDLE
REQUESTS_CA_BUNDLE
SSL_CERT_FILE
```

I am fully aware that use can manually add them to their tox.ini file but this does not scale well at all when you have hundreds of repositories (like openstack for example).

**Comment by gaborbernat** [comment]
This now has been released under https://tox.readthedocs.io/en/latest/changelog.html#v3-14-1-2019-11-13
