### ISSUE TITLE
consider using release-drafter for release notes

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox#1440]
I thin that contributions to tox could be make much easier if we start using https://github.com/apps/release-drafter or something similar. I personally started to use it on few packages I maintain and I am really happy as it automatically updates a github draft release note and when you are ready to make a release you already have all the data completed. See https://github.com/pycontribs/selinux/releases

**Comment by gaborbernat** [comment]
We already generate release notes automatically on PR; I don't think we need this https://tox.readthedocs.io/en/latest/changelog.html#vdraft-2019-10-16. The release process is also automatic at the call of a tox target env. I don't think we want that.

**Comment by gaborbernat** [comment]
We don't use github tags as release documentation, rather the readthedocs changelog is the definitive guide.
