### ISSUE TITLE
document portable way to clean folders

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox#1442]
While using tox it is quite common to want to remove some files, directories or even globing before running some commands. This is needed because previous executions may leave leftovers which can affect the final outcome.

Using shell commands like `rm` for `find` is not really cross platform portable, thus I think that tox should document/recommend better ways to perform these.

**Comment by gaborbernat** [comment]
``python -c 'import shutil; shutil.rmtree()'`` I don't think it's our responsibility to document it though 🤔

**Comment by ssbarnea** [comment]
@gaborbernat It depends on how we look at it. If we consider part of making the product easier to be used by everyone, yes we should. If not, we can skip it.

I am inclined to propose a new feature for doing the cleaning.

You may be surprised to discover that your example does not really work in all cases. Sadly doing a reliable and portable clean-up is not as really as it appears. If you agree at thing being a desirable feature, I will probably try to make PR to implement it, maybe with something like:
```
rmdir=
    **/*.tmp
    ~/.cache/foo/
    {toxinidir}/bar.txt
```

**Comment by gaborbernat** [comment]
I think this is a textbook definition of what should go into a plugin, don't consider this core feature 🤔
