### ISSUE TITLE
installed list is missing system packages like setuptools

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox#1443]
I guess that the currently code uses the result of `pip freeze` instead of `pip freeze --all` which also includes versions of critical libraries like setuptools.

I ended up creating this bug because I got failures to install dependencies that were caused by differences between these libraries that are hidden by default.

**Comment by gaborbernat** [comment]
I'm actually not that sold on the usefulness of that freeze output, so I'm planning to remove it in tox 4. 🤔 What do people use it for? I find it hard to read once you have 8+ dependencies... which is quite easy to get too.

**Comment by asottile** [comment]
I've definitely used the `freeze` output to debug why one CI passed and another failed

Note that `pip freeze --all` requires a new-enough pip (though I think 9.x has it so not really _that_ new)

**Comment by gaborbernat** [comment]
@asottile I'm tempted to move pip freeze in verbose mode only; I don't think it's needed all the time, only at first env setup (such as in CI, where the setup should be verbose either way).

**Comment by asottile** [comment]
if `tox` (default invocation) doesn't include this on first env setup I think that's not great
