### ISSUE TITLE
Add --durations flag

### ISSUE THREAD

**Issue by blueyed** [tox-dev/tox#1450]
Durations are reported with `-vv`, but it might be useful to have it just by itself via `--durations`, since `-vv` is very verbose indeed (including pip progress etc).

Related issue: https://github.com/tox-dev/tox/issues/470

**Comment by blueyed** [comment]
Any input here?
I would really like to use this to trim build logs down (my current workaround it split install and tests).
Happy to give a new `--durations` flag a shot myself.

**Comment by gaborbernat** [comment]
This has been brought up earlier and agreed that this should be a plugin not part of core.

**Comment by blueyed** [comment]
IIRC it was you creating the plugin (https://github.com/tox-dev/tox-durations), but then it moved into the core.  It is just that it is hidden/used with verbosity 2 now.

**Comment by gaborbernat** [comment]
I'm not settled on having a dedicated core option for this, maybe other maintainers can chime in 🤔

**Comment by blueyed** [comment]
What about displaying it with verbosity 1 already?

**Comment by gaborbernat** [comment]
Maybe 🤔
