### ISSUE TITLE
Wrong succeeded message after KeyboardInterrupt

### ISSUE THREAD

**Issue by schlamar** [tox-dev/tox#1453]
When hitting Ctrl+C while tox installs the package, this KeyboardInterrupt results in a wrong succeeded message.

There is a related fix by @asottile in #1257.

    >tox
    GLOB sdist-make: D:\mypackage\setup.py
    py37 inst-nodeps: D:\mypackage\.tox\.tmp\package\1\mypackage-1.0.0.zip
    ERROR: got KeyboardInterrupt signal
    _____________________________________________________________________ summary
      py37: commands succeeded
    ERROR:   flake8: undefined

**Comment by asottile** [comment]
looks like the `except KeyboardInterrupt` I added there needs to be applied more broadly, there's more setup steps that this can trigger on (confirming this bug, I hit this on stream yesterday as well)

**Comment by gaborbernat** [comment]
🤔 feel free to fill a PR 👍

**Comment by asottile** [comment]
ah mine was slightly different and I haven't had time to dig into it, same class of problem though [vid](https://www.youtube.com/watch?v=v84pwcI0RMc&t=1h20m55s)

**Comment by gaborbernat** [comment]
Feel free to open a PR against master and fix it. My available efforts at the moment are aimed at fixing this as part of https://github.com/tox-dev/tox/issues/1394, but that probably will take a while (ETA September).

**Comment by gnikonorov** [comment]
It looks like this still happens off of head. @gaborbernat do you mind if I make a PR?

```
gnikonorov:~/tox$ tox -e py37
.package create: /home/gnikonorov/tox/.tox/.package
.package installdeps: setuptools >= 40.0.4, setuptools_scm >= 2.0.0, <4, wheel >= 0.29.0
py37 create: /home/gnikonorov/tox/.tox/py37
py37 installdeps: pip >= 19.3.1
^CERROR: got KeyboardInterrupt signal
_________________________________________________________________________________________________________________ summary __________________________________________________________________________________________________________________
  py37: commands succeeded
  congratulations :)
gnikonorov:~/tox$ tox -e py37
py37 create: /home/gnikonorov/tox/.tox/py37
py37 installdeps: pip >= 19.3.1
py37 inst: /home/gnikonorov/tox/.tox/.tmp/package/1/tox-3.20.2.dev11+g649c6c0.tar.gz
^CERROR: got KeyboardInterrupt signal
_________________________________________________________________________________________________________________ summary __________________________________________________________________________________________________________________
  py37: commands succeeded
  congratulations :)
gnikonorov:~/tox$ tox -e py37
py37 inst-nodeps: /home/gnikonorov/tox/.tox/.tmp/package/1/tox-3.20.2.dev11+g649c6c0.tar.gz
^CERROR: got KeyboardInterrupt signal
_________________________________________________________________________________________________________________ summary __________________________________________________________________________________________________________________
  py37: commands succeeded
  congratulations :)
gnikonorov:~/tox$
```

**Comment by gaborbernat** [comment]
Go ahead.

**Comment by gnikonorov** [comment]
Thank you @gaborbernat ! I should have a PR up soon
