### ISSUE TITLE
tox breaks `getpass.getuser` on Windows

### ISSUE THREAD

**Issue by schlamar** [tox-dev/tox#1455]
The function `getpass.getuser` should be an platform agnostic way of getting the current user. This works fine on Windows as long as the `USERNAME` environment variable is set. However, as tox doesn't pass environment variables this is broken in tox environments.

This leads to really confusing bugs, for example https://github.com/gitpython-developers/GitPython/issues/356 where the root cause was even not detected.

I suggest you pass `USERNAME` per default to tox environments.

**Comment by gaborbernat** [comment]
The idea here that people pass in such projects explicitly this env-var; not all projects need it all the time.
