### ISSUE TITLE
tox not working for py36 and py37 : InterpreterNotFound

### ISSUE THREAD

**Issue by zainab-amir** [tox-dev/tox#1477]
```
using tox.ini: /project/tox.ini (pid 348)
  removing /project/.tox/log
using tox-3.14.1 from /project/local/lib/python2.7/site-packages/tox/__init__.pyc (pid 348)
skipping sdist step
py36-django111 start: getenv /project/.tox/py36-django111
py36-django111 cannot reuse: -r flag
py36-django111 create: /project/.tox/py36-django111
python (/project/bin/python) is {u'executable': u'/project/bin/python', u'name': u'python', u'version_info': [2, 7, 12, u'final', 0], u'sysplatform': u'linux2', u'version': u'2.7.12 (default, Oct  8 2019, 14:14:10) \n[GCC 5.4.0 20160609]', u'is_64': True}
py36-django111 uses None
ERROR: InterpreterNotFound: python3.6
py36-django111 finish: getenv /project/.tox/py36-django111 after 0.02 seconds
```
#### Notes
- It works fine when I run `tox -e py27-django111` and `tox -e py35-django111`
- I am running it inside a docker container

**Comment by gaborbernat** [comment]
Do you have python3.6 and python3.7 installed and available on the PATH?

**Comment by zainab-amir** [comment]
```
which python3
/usr/bin/python3
```

**Comment by gaborbernat** [comment]
That's python 3, what about which python3.7?

**Comment by zainab-amir** [comment]
Yeah it gives nothing

**Comment by gaborbernat** [comment]
Your machine does not have python 3.6 and 3
7 installed, only 3.5 so hence why we can't run it 🤔

**Comment by vkijasev** [comment]
I have installed python3.7 however tox (direct invocation or via CI):

[py37] $ python /tmp/jenkins1345650166964425693.py
GLOB sdist-make: /var/lib/jenkins/workspace/test_pytest1/TOXENV/py37/setup.py
py37 create: /var/lib/jenkins/workspace/test_pytest1/TOXENV/py37/.tox/py37
ERROR: InterpreterNotFound: python3
___________________________________ summary ____________________________________
ERROR:  py37: InterpreterNotFound: python3
Build step 'Execute Python script' marked build as failure

# which python
/usr/bin/python
# which python3.7
/usr/local/bin/python3.7

no python3 -> but I am not calling that one

NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"

**Comment by gaborbernat** [comment]
Can you display the log message of ``tox -rvve py37``?

**Comment by vkijasev** [comment]
Sure

> tox -rvve py37
using tox.ini: /var/lib/jenkins/workspace/test_pytest1/TOXENV/py37/tox.ini (pid 3641)
  removing /var/lib/jenkins/workspace/test_pytest1/TOXENV/py37/.tox/log
python (/usr/bin/python) is {u'sysplatform': u'linux2', u'executable': u'/usr/bin/python', u'version': u'2.7.18 (default, May  7 2020, 09:20:17) \n[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]', u'name': u'python', u'version_info': [2, 7, 18, u'final', 0], u'is_64': True}
py37 uses None
using tox-3.15.1 from /usr/local/lib/python2.7/site-packages/tox/__init__.pyc (pid 3641)
GLOB start: packaging
GLOB sdist-make: /var/lib/jenkins/workspace/test_pytest1/TOXENV/py37/setup.py
  removing /var/lib/jenkins/workspace/test_pytest1/TOXENV/py37/.tox/dist
[3646] /var/lib/jenkins/workspace/test_pytest1/TOXENV/py37$ /usr/bin/python2.7 setup.py sdist --formats=zip --dist-dir .tox/dist >.tox/log/GLOB-0.log
running sdist
running egg_info
writing TestPytest.egg-info/PKG-INFO
writing top-level names to TestPytest.egg-info/top_level.txt
writing dependency_links to TestPytest.egg-info/dependency_links.txt
reading manifest file 'TestPytest.egg-info/SOURCES.txt'
writing manifest file 'TestPytest.egg-info/SOURCES.txt'
warning: sdist: standard file not found: should have one of README, README.rst, README.txt

running check
warning: check: missing required meta-data: url

warning: check: missing meta-data: either (author and author_email) or (maintainer and maintainer_email) must be supplied

creating TestPytest-0.1
creating TestPytest-0.1/TestPytest.egg-info
copying files to TestPytest-0.1...
copying setup.py -> TestPytest-0.1
copying TestPytest.egg-info/PKG-INFO -> TestPytest-0.1/TestPytest.egg-info
copying TestPytest.egg-info/SOURCES.txt -> TestPytest-0.1/TestPytest.egg-info
copying TestPytest.egg-info/dependency_links.txt -> TestPytest-0.1/TestPytest.egg-info
copying TestPytest.egg-info/top_level.txt -> TestPytest-0.1/TestPytest.egg-info
Writing TestPytest-0.1/setup.cfg
creating '.tox/dist/TestPytest-0.1.zip' and adding 'TestPytest-0.1' to it
adding 'TestPytest-0.1'
adding 'TestPytest-0.1/TestPytest.egg-info'
adding 'TestPytest-0.1/PKG-INFO'
adding 'TestPytest-0.1/setup.cfg'
adding 'TestPytest-0.1/setup.py'
adding 'TestPytest-0.1/TestPytest.egg-info/top_level.txt'
adding 'TestPytest-0.1/TestPytest.egg-info/PKG-INFO'
adding 'TestPytest-0.1/TestPytest.egg-info/dependency_links.txt'
adding 'TestPytest-0.1/TestPytest.egg-info/SOURCES.txt'
removing 'TestPytest-0.1' (and everything under it)

GLOB finish: packaging  after 0.34 seconds
copying new sdistfile to '/root/.tox/distshare/TestPytest-0.1.zip'
package .tmp/package/1/TestPytest-0.1.zip links to dist/TestPytest-0.1.zip (/var/lib/jenkins/workspace/test_pytest1/TOXENV/py37/.tox)
py37 start: getenv /var/lib/jenkins/workspace/test_pytest1/TOXENV/py37/.tox/py37
py37 cannot reuse: -r flag
py37 create: /var/lib/jenkins/workspace/test_pytest1/TOXENV/py37/.tox/py37
ERROR: InterpreterNotFound: python3
py37 finish: getenv /var/lib/jenkins/workspace/test_pytest1/TOXENV/py37/.tox/py37 after 0.00 seconds
__________________________________________ summary __________________________________________
ERROR:  py37: InterpreterNotFound: python3
cleanup /var/lib/jenkins/workspace/test_pytest1/TOXENV/py37/.tox/.tmp/package/1/TestPytest-0.1.zip

**Comment by vkijasev** [comment]
Note: this works on Windows10 where I have just python3.7 installed

**Comment by vkijasev** [comment]
(thanks to your command) I see that Jenkins is using tox in python2.7
using tox-3.15.1 from /usr/local/lib/python2.7/site-packages/tox/__init__.pyc 

So I have uninstalled that one and installed another one with python3.7 in venv .toxbase (as presented in youtube by jetbrains)

Now I can run manually tox and pytest runs (py37)

  py37: commands succeeded
  congratulations :)


Just there is a problem with Jenkins which could not see tox.
