### ISSUE TITLE
Editorial: consider offering alternative to whitelist_externals

### ISSUE THREAD

**Issue by annevk** [tox-dev/tox#1491]
Using whitelist (and its counterpart) isn't exactly welcoming. While migrating away from it entirely might be hard due to compatibility considerations, it'd be nice if configuration files from projects that build on this technology could avoid it.

See https://tools.ietf.org/html/draft-knodel-terminology for additional context.

**Comment by gaborbernat** [comment]
We cannot do this without breaking backwards compatibility. We might be able to add other aliases for this setting as part of #1394, ETA at least September.

**Comment by gaborbernat** [comment]
> Can an alias be provided in the meantime?

PRs are welcome.

**Comment by annevk** [comment]
@dajose thank you!

**Comment by gaborbernat** [comment]
![thanks](https://media.tenor.co/images/1114067881329bb4218880eeb7ec34fd/tenor.gif)

**Comment by gaborbernat** [comment]
This is now released with 3.18.0
