### ISSUE TITLE
"extras" not used with "usedevelop = True"

### ISSUE THREAD

**Issue by blueyed** [tox-dev/tox#1496]
`extras` is ignored with `usedevelop = True`.
I think `pip install ".[extra]"` could be simulated?

I've seen https://github.com/tox-dev/tox/issues/1105, which is about "skip_install = True" though.

**Comment by webknjaz** [comment]
I'm pretty sure that extras work with `usedevelop`. https://github.com/cherrypy/cheroot/blob/e125ed3/tox.ini#L15-L16 + https://travis-ci.com/cherrypy/cheroot/jobs/277038841#L214 proves it.

So maybe it's some combo of `usedevelop` and some other setting that causes the behavior that you described.

**Comment by webknjaz** [comment]
Also, are you sure you use modern version of `tox`?

**Comment by asottile** [comment]
seems to work for me, please reopen a new issue with a full reproduction, version information, etc.

```console
$ tox -e foo
foo create: /tmp/x/.tox/foo
foo develop-inst: /tmp/x
foo installed: astpretty==1.7.0,# Editable install with no version control (foo==0.0.0),-e /tmp/x
foo run-test-pre: PYTHONHASHSEED='1558296208'
___________________________________ summary ____________________________________
  foo: commands succeeded
  congratulations :)
$ cat tox.ini 
[tox]

[testenv:foo]
usedevelop = true
extras = wat
$ cat setup.py 
from setuptools import setup

setup(
    name='foo',
    extras_require={'wat': ['astpretty']},
)
```

**Comment by blueyed** [comment]
With pytest's tox config:

```diff
diff --git i/tox.ini w/tox.ini
index cf50945fb..d8f9c8b51 100644
--- i/tox.ini
+++ w/tox.ini
@@ -56,6 +56,7 @@ deps = pre-commit>=1.11.0
 commands = pre-commit run --all-files --show-diff-on-failure {posargs:}

 [testenv:mypy]
+usedevelop = true
 extras = checkqa-mypy, testing
 commands = mypy {posargs:src testing}
```

```console
% tox -e mypy -r
mypy recreate: /tmp/tox…/Vcs/pytest/mypy
mypy develop-inst: …/Vcs/pytest
mypy installed: attrs==19.3.0,more-itertools==8.1.0,packaging==20.0,pluggy==0.13.1,py==1.8.1,pyparsing==2.4.6,pytest==5.3.4,six==1.14.0,wcwidth==0.1.8
mypy run-test-pre: PYTHONHASHSEED='2450275420'
mypy run-test: commands[0] | mypy src testing
WARNING: test command found but not installed in testenv
  cmd: …/Vcs/pytest/.venv/bin/mypy
  env: /tmp/tox…/Vcs/pytest/mypy
Maybe you forgot to specify a dependency? See also the whitelist_externals envconfig setting.
```

Also happens with a minimal `tox.ini` there:
```ini
[tox]

[testenv:mypy]
usedevelop = true
extras = mypy
commands = mypy {posargs:src testing}
```

The problem seems to be that it picks up another egg-info?!
```console
% …/.tox/mypy/bin/python -m pip install --exists-action w -e '…/Vcs/pytest[checkqa-mypy]'
Looking in indexes: http://localhost:3141/root/pypi/+simple/
Obtaining file://…/Vcs/pytest
  Installing build dependencies ... done
  pytest-warn-sample 0.1 does not provide the extra 'checkqa-mypy'
…
Installing collected packages: pytest-warn-sample
  Running setup.py develop for pytest-warn-sample
Successfully installed pytest-warn-sample
You are using pip version 18.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

I have:
```
./pytestwarning/pytest_warn_sample.egg-info
./src/pytest.egg-info
```

The former likely as a leftover due to some testing.

But it shows that what `tox` runs is different with regard to the outcome from
`pip install -e '.[…]'`, where it does not pick up the "wrong egg-info".

In any case `tox` should maybe fail with the
"pytest-warn-sample 0.1 does not provide the extra 'checkqa-mypy'" error, i.e.
with any non-existing extra that is specified - which would have shown that there is something wrong without looking at the (very) verbose output, and it seems to make sense to fail with non-existing extras.

Not creating a new issue for now to avoid spam, and since it can be worked around by removing the confusing egg-info.

**Comment by asottile** [comment]
I still can't reproduce, you haven't provided enough information (in particular versions, and I can see you have some environment variables affecting your output as well) -- but from your output it looks like it's a bug in pip and you're using an old version of pip so maybe it's that?

**Comment by blueyed** [comment]
> I still can't reproduce

Have you created another `egg-info`?

The `pytestwarning` dir I have in `pytest`'s root is https://github.com/ykvch/pytestwarning.
So clone it there, and then `pip install -e .` it into pytest's virtualenv (created via `python -m venv` with Python 3.8.1) to create the egg-info therein.

> in particular versions

tox 3.14.3
System pip (tox via system also): 19.3

Using `download = true` additionally fixes it though, so it appears to be indeed a problem with pip/virtualenv/setuptools (shipped with tox?).  How can I compare the bundled versions with the ones being used?

**Comment by asottile** [comment]
the bundled versions come from the version of `virtualenv` you have adjacent to `tox`

**Comment by asottile** [comment]
usually when sharing bug info, use `pip freeze` to show versions

**Comment by blueyed** [comment]
That's virtualenv 16.1.0-3 (Arch Linux) - quite outdated apparently.
All good then I assume from your side.

**Comment by blueyed** [comment]
Well, for the system Python it is quite a lot though (287 lines).

**Comment by asottile** [comment]
still would have been useful -- the original report was pretty useless: no reproduction, no version information

with the output of pip freeze and a reproduction it would have been easy to pinpoint the issue (outdated virtualenv) without me having to guess at it
