### ISSUE TITLE
include the HTTP proxy environment variables in PASSENV by default

### ISSUE THREAD

**Issue by pfmoore** [tox-dev/tox#1498]
Tox doesn't include HTTP proxy variables (`HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY`) in `PASSENV` by default. As those variables basically say "you need to use this proxy or network access won't work" they seem like something that would be required for any network-related test.

I suggest that the variables are added to the list of ones included in `PASSENV` by default.

#258 was raised about this issue, before `PASSENV` existed as far as I can see, and appears to have been accepted with the resolution being that tox passed all environment variables. Presumably at some point, that was restricted again and `PASSENV` introduced, but the proxy variables weren't considered at that time?

**Comment by gaborbernat** [comment]
the main reason we haven't don't so yet is that you only need this if you've tests that access the network, this shouldn't be that many, not?

**Comment by pfmoore** [comment]
In general, I guess so. I hit this on pip, where the `lint` environment uses `pre-commit` and `pre-commit` runs git to install checks. So not a common case, certainly ;-) Conversely, though, *not* passing the proxy vars just leaves the test environment with broken networking, which seems pointless at best. I'm happy to say it's not a high priority, but I do think it's worth doing at some point.

**Comment by gaborbernat** [comment]
I've been setting this in all my projects, so could be the default 🤷‍♂ if you have time for a PR send it on 👍
