### ISSUE TITLE
Can't run different commands per platform

### ISSUE THREAD

**Issue by quakehead** [tox-dev/tox#1499]
I want to run a different command depending on the platform (e.g. windows, linux, macos).
In the I saw the deps section being specified for different envs ([conditional settings](https://tox.readthedocs.io/en/latest/config.html#factors)).

However, conditional commands aren't running for me. I have

```
[testenv:sanity]
whitelist_externals =
    touch
commands =
    touch /tmp/works-generic
    linux: touch /tmp/works-linux
    darwin: touch /tmp/works-macos
```

Only the first command runs.

I've tried tox 3.0.0 and tox 3.14.3 with no difference

**Comment by BenjamenMeyer** [comment]
AFAIK, the conditional command is environment specific. That is, you have an environment named `touch`, `linux`, `darwin` and they get run when that environment is run. It's not an OS relationship.

If you're looking to differentiate on OS platform, I'd probably suggest having environments named with the platform in them:

```
envlist = sanity-{linux,darwin,generic,windows}

[testenv:sanity-{linux,darwin,generic,windows}]
whitelist_externals =
    touch
commands =
    sanity-touch: touch /tmp/works-generic
    sanity-linux: touch /tmp/works-linux
    sanity-darwin: touch /tmp/works-macos
    sanity-windows: touch %TEMP%/works-windows
```

You might be able to also define a variable to hold the file location too (for your example).

**Comment by quakehead** [comment]
Thanks. I have an envlist, and conditional commands run in the `[testenv]`, but not `[testenv:deploy]` section for example.

**Comment by BenjamenMeyer** [comment]
@quakehead  correct, because `[testenv:deploy]` is only for the `deploy` environment where `[testenv]` refers to all environments.

**Comment by quakehead** [comment]
I opted instead to write a small python script that is cross-platform
