### ISSUE TITLE
Curly braces cannot be escaped in env substitution

### ISSUE THREAD

**Issue by blueyed** [tox-dev/tox#1502]
`commands = echo {env:DOESNOTEXIST:@\{u\}}` results in: `{env:DOESNOTEXIST:@{u}}`.

Without escaping them (`commands = echo {env:DOESNOTEXIST:@{u}}`):
```
  File "/usr/lib/python3.8/site-packages/tox/config/__init__.py", line 1638, in _substitute_from_other_section
    raise tox.exception.ConfigError("substitution key {!r} not found".format(key))
tox.exception.ConfigError: ConfigError: substitution key 'u' not found
```

tox 3.14.3

**Comment by gaborbernat** [comment]
Feel free to open a PR against master and fix it. My available efforts at the moment are aimed at fixing this as part of https://github.com/tox-dev/tox/issues/1394, but that probably will take a while (ETA September).

**Comment by jayvdb** [comment]
I've checked most versions back to 2.0 and this never worked.
