### ISSUE TITLE
The job exceeded the maximum log length, and has been terminated.

### ISSUE THREAD

**Issue by adamhaber** [tox-dev/tox#1505]
My package depends on nightly releases of both tensorflow and tensorflow-probability. Tests were [successful](https://travis-ci.org/adamhaber/stan2tfp/builds/634428345) last time I updated the package; then, probably due to a dependency change in tf-nightly or tfp-nightly, the build fails. I've tried to update the dependencies in setup.py to `tf-nightly` but for some reason this installs tf 1.15 instead of tf 2.1, on which tfp-nightly depends. I _think_ I was able to fix this by updating pip itself:
```
commands = 
    python -m pip install --upgrade pip
    pip install tf-nightly --upgrade
    python setup.py test
```
But now I get the error message mentioned above, and I'm not sure how to debug this since I can't see where the build actually fails.

[This](https://travis-ci.org/adamhaber/stan2tfp/builds/639097312) is the latest build attempt, and [this](https://github.com/adamhaber/stan2tfp) is the actual repo with tox.ini and setup.py. Thanks in advance!

**Comment by asottile** [comment]
this has nothing to do with tox, sorry -- that error message is coming from travis-ci itself
