### ISSUE TITLE
conda package

### ISSUE THREAD

**Issue by TejasAvinashShetty** [tox-dev/tox#1508]
It would be nice to have a conda package. This would prevent version clash, easy updates.

**Comment by asottile** [comment]
I believe it already exists: https://anaconda.org/conda-forge/tox

**Comment by TejasAvinashShetty** [comment]
Does it work as expected? I had some problems recently in my setup while trying out a  cookie-cutter.

**Comment by asottile** [comment]
no idea, we don't maintain it

**Comment by rpkilby** [comment]
Out of curiosity, do you know how does? 🤔

**Comment by asottile** [comment]
https://github.com/conda-forge/tox-feedstock/blob/f0464c084cbc651d14a607b21032e2bbb65e98f4/recipe/meta.yaml#L57-L61

**Comment by rpkilby** [comment]
Neat. Thanks.

**Comment by TejasAvinashShetty** [comment]
Thanks
Regards,

Tejas Shetty
B Tech.Pharma
Department of Pharmaceutical Science and Technology
Institute of Chemical Technology, Matunga,
Maharashtra, India.
Contact No.: +91 9987015305,9004350057,8450978380,022 25582905
Email ID: tejasshetty.1808@gmail.com

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
02/29/20,
11:22:19 PM
