### ISSUE TITLE
conditional configuration depending on if environment variable is set

### ISSUE THREAD

**Issue by svenevs** [tox-dev/tox#1515]
## Goal

- If `SPHINX_VERSION` environment variable set, install dep `sphinx=={env:SPHINX_VERSION}`
- Otherwise, install dep `sphinx` (without the `==`).

The motivation is to test against latest `sphinx` when running `tox`, but on CI we would like to test against a matrix as well as locally be able to `SPHINX_VERSION=1.8.5 tox` for example.

## Goofy Workaround

```ini
[tox]
envlist = py

[testenv]
deps =
    sphinx{env:SPHINX_VERSION:}
```

and require that people include the `==` in the environment variable, e.g., `SPHINX_VERSION===1.8.5 tox`.  It works, but it just feels so wrong.

## Ugly hack on tox

Working within the current replacement "language"

https://github.com/tox-dev/tox/blob/b7a1559bd8c61917eec1c590ead9b8fbbe19d444/src/tox/config/__init__.py#L1583-L1593

I came up with a not so intuitive "`env_set`" substitution pattern: `{env_set:KEY:value}` will expand to `value` if and only if `KEY` is set in the environment.  If `KEY` is not set, then it expands to the empty string.  This lets me do this:

```ini
deps =
    sphinx{env_set:SPHINX_VERSION:==}{env:SPHINX_VERSION:}
```

Which I totally concede is rather obtuse.  Like yeah...it technically works, but honestly how useful is it outside of my specific case?  (Patch omitted, it's nearly the same as `def _replace_env` in that file).

--------------------

Is there a better way to approach this?  I tried to find a way to define the [`extra` env marker](https://www.python.org/dev/peps/pep-0508/#id24) but I don't think I can or even should.  I can also define a `[sphinx]` section and set a `version` field and do `sphinx=={env:SPHINX_VERSION:{[sphinx]version}}`, but then I have to remember to update `[sphinx]version` when new releases roll out.

I'd be interested in implementing any version of a feature that lets me do this.  For example, what if we added support for like `{if:<condition>:<value>}`?  Trying to propose ideas that don't change the formatting of the regex, but what about something like allowing us to run raw python code?  `python -c 'import os; v = os.getenv("SPHINX_VERSION", None); d = "sphinx==" + v if v else "sphinx"; print(d)'`

I feel like raw python code might be nice to have, but it also feels like a security problem.

I understand if this is closed as #wontfix since I can just put the `==` in my env vars.  But I'd love to be able to solve this in a more intuitive way.  Thank you for any input / suggestions / tips! :slightly_smiling_face:

**Comment by svenevs** [comment]
Closing due to lack of interest / clearly no widely impacted audience.  Please let me know if there is a time or way that implementing any version of this feature could be done by me, and how it should be done.  Thanks again for `tox` :heart:

**Comment by gaborbernat** [comment]
I'd be happy to support this at some level in tox 4, see rewrite branch, but that's probably a few months away 🤷‍♂️
