### ISSUE TITLE
Black config in pyproject.toml file breaks tox

### ISSUE THREAD

**Issue by meshy** [tox-dev/tox#1523]
**Tox version:** `3.14.4`

`pyproject.toml`:

```toml
[tool.black]

skip-string-normalization = true
skip-numeric-underscore-normalization = true
```

Unexpected error:

```
ERROR: pyproject.toml file found.
To use a PEP 517 build-backend you are required to configure tox to use an isolated_build:
https://tox.readthedocs.io/en/latest/example/package.html
```

As you can see, I'm not using a PEP517 build backend, so this was a little unexpected!

**Comment by gaborbernat** [comment]
This is expected though. There have been long topics on pip tracker about this, but in essence once you create pyproject.toml you opt in to the new style build system, see https://www.python.org/dev/peps/pep-0518/ and https://www.python.org/dev/peps/pep-0517/. And by opting-in, you are required to specify the required arguments for the system. Black decided to use ``pyproject.toml`` as a configuration file, which is allowed but all users using it are also enforced to switch to the new style build system. Which is a best practice by now so there's no harm in doing so.

**Comment by meshy** [comment]
Gotcha -- OK thanks.
