### ISSUE TITLE
[3.14.6] Build tests fails, because of pathlib2

### ISSUE THREAD

**Issue by tuxmaster5000** [tox-dev/tox#1549]
pathlib2 is deprecated for python 3.
See:
https://github.com/mcmtroffaes/pathlib2

**Comment by gaborbernat** [comment]
Why would the test fail?

**Comment by tuxmaster5000** [comment]
I simple replace all calls from pathlib2 to pathlib and the tests passed gain.
Because since python 3.4 pathlib is integrated into it:
https://docs.python.org/3/library/pathlib.html

**Comment by gaborbernat** [comment]
tox 3.4.16 still supports python 2, so we cannot do that. Again why would tests fail with pathlib2?

**Comment by tuxmaster5000** [comment]
Because the package for pathlib2 are not delivered anymore on CentOS7

**Comment by gaborbernat** [comment]
Use pip install to acquire it directly from PyPi then?

**Comment by tuxmaster5000** [comment]
This is not an real option, because CentOS7 and newer only support Python 3.6.
As an workaround I have patched out the dependency. But nicer will be an switch, that this dependency are only used on old python versions.

**Comment by gaborbernat** [comment]
@tuxmaster5000 because tox 3 still plans to support python 2 it's unlikely will do this; so best chance is with the rewrite and tox 4 a WIP at https://github.com/tox-dev/tox/tree/rewrite
