### ISSUE TITLE
tox forces version of setuptools when creating new environment

### ISSUE THREAD

**Issue by keymone** [tox-dev/tox#1554]
python version `3.6`
tox version `3.14.6`
system setuptools `41.4.0` - the version i need to be used everywhere
tox.ini has `requires = setuptools==41.4.0`
requirements.txt has `setuptools==41.4.0`

running `tox -e foo` results in `setuptools>=46` installed and used inside foo's environment

running `tox --force-dep setuptools==41.4.0 -e foo` - same issue

what am i doing wrong?

**Comment by gaborbernat** [comment]
Did you enable isolated builds?

**Comment by keymone** [comment]
I would just comment that this solution is not very discoverable and presence of `requires` and `--force-dep` options are confusing when it seems like they should address this exact issue.

**Comment by gaborbernat** [comment]
First and foremost force dep is ment to override deps within tox.ini post environment creation. Second you should enable isolated builds that avoids needing to use the host environment to build. Finally use pyproject.toml to specify your build dependencies per pep 518.
