### ISSUE TITLE
requirements change not picked up by tox

### ISSUE THREAD

**Issue by jheld** [tox-dev/tox#1555]
When I make changes to my project's `requirements.txt` and run tests, `tox` no longer picks up the change and so I must run it with `tox -r` first.

This is for a django project (and we have no `setup.py`), but this has worked in the past, just now figured I should open an issue.

Version:
3.14.2
Interpreter: CPython 3.7

**Comment by gaborbernat** [comment]
Feel free to open a PR against master and fix it. My available efforts at the moment are aimed at fixing this as part of https://github.com/tox-dev/tox/issues/1394, but that probably will take a while (ETA September).
