### ISSUE TITLE
Output of windows cmd line redirecting to jenkins

### ISSUE THREAD

**Issue by tarraanand** [tox-dev/tox#1557]
Stage("execution")
{
Steps{
bat 'start cmd.exe /c c://users//doc//sample.bat'
}}

The above script is just opening the cmd prompt and executing it . it's not taking the output of the execution . Even if the execution is failed the stage is showing as successful and passing to next stage deploying ....so I want yo develop it so that the output in the cmd prompt should take as input by jenkins and stage should go on ...if it fails in cmd prompt the stage in jenkins should also fail ...if the execution is successful in cmd prompt the stage should be successful in Jenkins....can anyone help ?

**Comment by gaborbernat** [comment]
I don't think this is a tox related question. Please try on StackOverflow.
