### ISSUE TITLE
Pass PIP_EXTRA_INDEX_URL by default 

### ISSUE THREAD

**Issue by georgealton** [tox-dev/tox#1561]
tox currently passes `PIP_INDEX_URL` as a default environment config. This parameter allows the user to specify a package index.

pip supports another configuration parameter for additional indexes; `PIP_EXTRA_INDEX_URL`.

I think it would be beneficial to pass `PIP_EXTRA_INDEX_URL` by default in addition to `PIP_INDEX_URL` to support index configuration parameters transparently

**Comment by gaborbernat** [comment]
Feel free to open a PR against master and fix it. My available efforts at the moment are aimed at fixing this as part of https://github.com/tox-dev/tox/issues/1394, but that probably will take a while (ETA September).

**Comment by gaborbernat** [comment]
Hello, this now has been released via https://pypi.org/project/tox/3.15.0/ 

![heads up](https://media.tenor.co/images/0118006f847acfcfd22e8bf0fd405e42/tenor.gif)
