### ISSUE TITLE
tox ignores directories without an `__init__.py` in python 3

### ISSUE THREAD

**Issue by gothill** [tox-dev/tox#1564]
Apologies if I am missing something here, but this issue seems worth flagging, as the use case is quite banal. Python 3.3 introduced [Implicit Namespace Packages](https://www.python.org/dev/peps/pep-0420/) :

> Allowing implicit namespace packages means that the requirement to provide an __init__.py file can be dropped completely

However, tox 3.14 will _ignore_ any directories which don't contain a `__init__.py` when it builds and installs a version of the package from source into `.tox/{py3env}/lib`.

This leads to a situation where expected directories are not installed, and tests fail due to broken import paths, because an `__init__.py` was missing which Python 3.3+ doesn't actually require.

Given that Python 3 is the standard these days, it seems that tox should either know to disregard missing `__init__.py` files for Python 3.3+ or at least warn the user that directories have been ignored for that reason.

Environment

- tox 3.14.6
- python 3.7.6
- pip 20.0.2

`tox.ini`:

```
[tox]
envlist =
    # Commands to run against multiple Python versions
    {py37}-test

[testenv]
basepython = python3.7
setenv =
    PYTHONPATH={toxinidir}/tests
    PYTHONUNBUFFERED=yes
usedevelop = false
deps =
    pytest
    pytest-cov
    .[test]
install_command = pip install {opts} {packages} .[test]
commands =
    {posargs:py.test}

[testenv:py37-test]
passenv =
    TEST_*
```

**Comment by gaborbernat** [comment]
tox does not build your package. It delegates it to your builder. By default as is your case this is setuptools. Setuptools is ignoring those because you need to change your setup.py to use namespace packages. You can see the output by running ``tox -vvv -e your-env``

**Comment by gothill** [comment]
Ah sorry. Thanks 👍
