### ISSUE TITLE
tox need an option to override basepython for specific environment

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox#1565]
I do have a valid use-case where I want the CI/CD system to assure that when `tox -e devel` runs, it will use a specific python version.

For practical reasons the `devel` environment does not mention any specific python, as the code is supposed to run well with any python. Still, when doing CI/CD testing. we want to be sure that we test with specific versions.

At this moment the only tuning option is `--discover` but that one is only overriding the lookup directories for finding python executables. If this specific python interpreter is located in the same folder as the other ones, you would be able to use this option to enforce use of a specific one.

The reality is the on most Linux distributions all python executables will be installed in the same folder.

There are two workarounds that I theoretically possible but both of them look over-complicated:
* create a virtualenv using `--python python3.8` and give that virtualenv bin directory to tox 
discovery.
* create a new folder and create a symlink for the interpreter, give this folder to `tox --discovery`.
* create an additional `py38-devel` environment, which uses `basepython`, and inherits all the other options from the `devel` one.

If possible, I would prefer a ``--python`` option added to tox which is behaving similar to the one in virtualenv.

**Comment by gaborbernat** [comment]
``--discovery`` is the actual python executable, not a directory. Now injecting the python itself on its own will not be enough to force to use that, as that would not specify the python spec specified in basepython. You would also need a match-all spec. That being said you can already achieve what you want via:

``tox -e py38 --discover $(which python3.8)``

This will force creation to the Python under the return of which.

**Comment by ssbarnea** [comment]
Maybe I did something wrong because that is exactly what I run locally, and when I went inside the virtualenv, I found python3.7 instead of python3.8 (py37 being my default intepreter, the one that was tox installed with). I will try on other platforms too, maybe tox-pyenv confused it.

**Comment by gaborbernat** [comment]
It should work, see the logic at https://github.com/tox-dev/tox/blob/master/src/tox/interpreters/common.py#L12-L19 added via https://github.com/tox-dev/tox/pull/1526

**Comment by ssbarnea** [comment]
This method is not working for several reasons:
- if executable is missing, tox will continue to run and pick another python version
- it requires `which` and that is not installed on all platforms
- `type` are more portable that `which` but its output is not directly usable
- `command -v` is also an alternative, but I am not sure if it would work on all platforms, like Windows?

I think that these could be addressed by making two changes to tox:
- assure tox fails when discover is mentioned and it does not resolve to something
- enable --discover to perform which internally when called without full paths, so we avoid the cross-platform challenges. I think that `shutil.which` with fallback to https://pypi.org/project/whichcraft/ could be a good compromise.

It is essential to assure that tox fails when is asked to use a specific interpreter as otherwise we risk running CI/CD pipelines that are using wrong versions of python. It already happened to me twice to run wrong versions without knowing, in one case it took two months to *discover* it.

**Comment by ssbarnea** [comment]
@gaborbernat This ticket is no longer a feature request, it did grow into a full bug. 

I created a simple example to reproduce it at https://github.com/ssbarnea/foo/ -- the output can be seen below. 

Mainly it seems that the discovery options does not work at all and causes false positives: mainly tox endup running other versions of python instead of the ones we try to enforce.

```
$ ./reproduce.sh                                                                                                                                                          [13:14:02]
++ which python3.8 python3.7 python3.6
+ for PYTHON in '$(which python3.8 python3.7 python3.6)'
++ /Users/ssbarnea/.pyenv/shims/python3.8 --version
Testing pinning /Users/ssbarnea/.pyenv/shims/python3.8 with tox:
+ export 'PINNED_PYTHON=Python 3.8.2'
+ PINNED_PYTHON='Python 3.8.2'
+ echo 'Testing pinning /Users/ssbarnea/.pyenv/shims/python3.8 with tox:'
+ tox --discover /Users/ssbarnea/.pyenv/shims/python3.8 -re devel
devel recreate: /Users/ssbarnea/c/t/foo/.tox/devel
devel run-test-pre: PYTHONHASHSEED='2342527513'
devel run-test: commands[0] | bash -xc 'A=$(python --version); [ "$A" = "$PINNED_PYTHON" ]'
++ python --version
+ A='Python 3.8.2'
+ '[' 'Python 3.8.2' = 'Python 3.8.2' ']'
______________________________________________________________________________________ summary ______________________________________________________________________________________
  devel: commands succeeded
  congratulations :)
+ for PYTHON in '$(which python3.8 python3.7 python3.6)'
++ /Users/ssbarnea/.pyenv/shims/python3.7 --version
Testing pinning /Users/ssbarnea/.pyenv/shims/python3.7 with tox:
+ export 'PINNED_PYTHON=Python 3.7.7'
+ PINNED_PYTHON='Python 3.7.7'
+ echo 'Testing pinning /Users/ssbarnea/.pyenv/shims/python3.7 with tox:'
+ tox --discover /Users/ssbarnea/.pyenv/shims/python3.7 -re devel
devel recreate: /Users/ssbarnea/c/t/foo/.tox/devel
devel run-test-pre: PYTHONHASHSEED='2822116741'
devel run-test: commands[0] | bash -xc 'A=$(python --version); [ "$A" = "$PINNED_PYTHON" ]'
++ python --version
+ A='Python 3.8.2'
+ '[' 'Python 3.8.2' = 'Python 3.7.7' ']'
ERROR: InvocationError for command /usr/local/bin/bash -xc 'A=$(python --version); [ "$A" = "$PINNED_PYTHON" ]' (exited with code 1)
______________________________________________________________________________________ summary ______________________________________________________________________________________
ERROR:   devel: commands failed
+ for PYTHON in '$(which python3.8 python3.7 python3.6)'
++ /Users/ssbarnea/.pyenv/shims/python3.6 --version
Testing pinning /Users/ssbarnea/.pyenv/shims/python3.6 with tox:
+ export 'PINNED_PYTHON=Python 3.6.10'
+ PINNED_PYTHON='Python 3.6.10'
+ echo 'Testing pinning /Users/ssbarnea/.pyenv/shims/python3.6 with tox:'
+ tox --discover /Users/ssbarnea/.pyenv/shims/python3.6 -re devel
devel recreate: /Users/ssbarnea/c/t/foo/.tox/devel
devel run-test-pre: PYTHONHASHSEED='1719654386'
devel run-test: commands[0] | bash -xc 'A=$(python --version); [ "$A" = "$PINNED_PYTHON" ]'
++ python --version
+ A='Python 3.8.2'
+ '[' 'Python 3.8.2' = 'Python 3.6.10' ']'
ERROR: InvocationError for command /usr/local/bin/bash -xc 'A=$(python --version); [ "$A" = "$PINNED_PYTHON" ]' (exited with code 1)
______________________________________________________________________________________ summary ______________________________________________________________________________________
ERROR:   devel: commands failed
./reproduce.sh  5.09s user 1.19s system 98% cpu 6.380 total
```

**Comment by gaborbernat** [comment]
``--discover`` is not an enforce-ing tool; it's a hint to the discovery system to prefer the provided one if possible. There is no way to enforce an absolute path python; if you'd like that new feature I'd recommend for now define a plugin and we can talk about providing it out of box for tox 4...

**Comment by ssbarnea** [comment]
This started by wanting to enforce a specific python to be used for an environment, one environment that did not had any version mentioned in its name. 

If I did not miss anything, it seems that it would be impossible to enforce tox to use a specific version of python on an environment without touching the tox.in file, which would be against CI/CD testing principles where you should never touch(change) the tested code. Using a sed to hack tox.ini file seems like a really bad practice.

**Comment by gaborbernat** [comment]
@ssbarnea for that use case today probably the cleanest is to create a tox plugin that overrides discovery via some cli flag 🤷

**Comment by gaborbernat** [comment]
After discussing this on Gitter, we concluded that this use case is better served by https://github.com/tox-dev/tox/issues/1330.
