### ISSUE TITLE
Ability to replace packaging step with acquiring it from local/remote sdist/wheelhouse

### ISSUE THREAD

**Issue by altendky** [tox-dev/tox#1566]
In CI I like to have build jobs first that create and archive all artifacts that will go to PyPI (wheels and sdist).  I then run a job for each of them to verify that those actual to-be-uploaded files work rather than just that my cloned repo will pass tests.  At present to do this I have a build step that looks at the existing `dist/` and somehow picks out a file (I've done both a `pip download` and a Python script to glob for `*.whl` etc) and stores the path in an environment variable to be passed to `tox --installpkg` in the actual test step.  This is annoying to have to do.  I've looked over existing options and haven't come up with anything that seems to work how I want it to.  Implementing this may involve some combination of existing features or perhaps two new command line arguments.  One to specify the wheelhouse path and another to pick between sdist and bdist.  Oh, and in the case of Linux you get regular vs. the multiple manylinux options I suppose.  Ugh and text width at least for 2.7, maybe 3.5/3.6, I haven't dug hard on this.

**Comment by webknjaz** [comment]
I have exactly the same use-case as I'm now building a GitHub Actions workflow that builds the wheels as a first stage and then transfers them into the test jobs and finally publishes those same artifacts. I was planning to come up with a similar solution by overriding `install_command` or `commands_pre` in a child testenv.

**Comment by gaborbernat** [comment]
The way I see it there are two separate topics conflated here. Both try to achieve roughly the following:

- build a package,
- install that package into a target environment,
- run some tests on the test suite,
- if all tests passed run some follow-up job.

The difference between the two separate topics is that one of these packages is a source distribution, while the other is a wheel. Currently, tox only supports source distributions. We don't support wheels yet, mainly because of handling non-universal wheels introduces a lot more complication that the current code base is prepared for. I do plan to address this within the rewrite, tox 4. 

I see you try to cramp all the work in the same tox job, via some kind of altering of ``--installpkg``, ``instal_command``, ``skipsdist`` and ``commands_pre``/``comands_post``. While you might get this working feels very hacky and would not generally make it accessible to everyone. tox 4 will allow specifying the package (and type) to install per tox environment so things here will be a lot simpler. Furthermore, you'll probably want in this to set up a publish tox environment that depends on all the test environments, and if all runs finished perform it.

``skipsdist`` does not support env bound factor variables because that option is not handled per environment but rather per tox run in tox 3. This flag does not make sense per env. If you want per env set ``skip_install`` - https://tox.readthedocs.io/en/latest/config.html#conf-skip_install, tox will not build a package if all envs to be run have this flag set to ``True``.

**Comment by altendky** [comment]
Thanks, I'll take a look at `skip_install` again and see what I can do with that for now.  The sequencing etc of the build/test/publish don't have anything particularly to do with tox in my head.  At present I'm not even using a tox env for building.  I probably should and probably will but the build-then-test-then-publish level is still a CI config responsibility in my mind.  Even if tox gets to supporting this it won't achieve the parallelism in CI that you can get via the CI config.

Come to think of it, are you expecting that tox does the building aside from me writing a build-my-wheels env?  The only thing I was trying to do before this ticket as related to tox was specifying a file to `--installpkg` to be installed and tested _instead_ of tox handling the building.  I already have `dist/mything.whl` and dist/mything.tar.gz`.  I thought it would be nice to be able to `--wheelhouse dist/ --dist-type bdist` to ask tox to use `dist/mything.whl` (as mentioned there are actually more things to specify) as this would avoid me having to store `ls dist/*.whl` and pass that into `--installpkg`.

Also, to be sure, are you saying that `--installpkg` doesn't work properly if I pass it something like `dist/this.whl`?  Or was your comment about only supporting source distributions referring only to what tox itself will build for you.

**Comment by gaborbernat** [comment]
We already support parallel runs so don't see why the CI would be any more powerful 🤷‍♂️

**Comment by altendky** [comment]
By giving you 20x VMs to run rather than 1x VMs with 20x jobs sharing it.

**Comment by gaborbernat** [comment]
So in the case, you can run builds across VMs I don't think the situation changes by much. There are two cases we can cover here:

1. The wheel is a universal wheel.
2. The wheel is not a universal wheel.

In case the wheel is universal things still stand, you can build the wheel up front, and then deploy them to other VMs. Then you can invoke tox in each of these VMs, where tox will set up a virtual environment and install the package into. This is the case when ``--instalpkg`` may be used to override the build statement. Publish can be a follow-up tox environment, in another VM, assuming the earlier passed.

In case you don't have a universal wheel you need to build the wheel for every VM, so in this case, every VM will run its own full shebang of build a package, install that package into a target environment, run some tests on the test suite.


tox 3 at the moment can only build source distributions (as they're not platform dependent). tox 4 will support wheel build. ``-instalpkg`` could be used to side-step the install and use a pre-built file instead.

**Comment by altendky** [comment]
I think my attempt to provide context on this issue confused rather than clarified.  This request was not meant to involve any aspect of tox building wheels or implementing any relationship between environments or parallelism.  It is about building on the functionality provided by `--installpkg` by adding the ability to select and install a dist file from a complete cross-platform cross-version etc wheelhouse.  Let me retry.

In one case presently I have a pre-tox step where I do something like `pip download --find-links dist/ --dest selected_dist/ --no-deps --only-binary :all: mypackage` to select a single dist file and then `tox -e py37 --installpkg selected_dist/*` to have tox test that single pre-built dist file.  Since the `pip` execution ought to be run from in the env that tox will be running tests in it's actually a three step process (create env, identify dist file, run tox).  Integrating this dist-selection-from-wheelhouse functionality into the tox cli would cut that down to one step.  For the sake of example, not prescribing what the option names ought to be nor showing the complicated scenarios, this might look like `tox --wheelhouse dist/ --dist-type wheel`.  The change from `--installpkg` is that tox would help select the dist file to install based on the limitations applied by the Python in the env (platform, Python version, etc) and then further restricted by new cli options when needed (multiple manylinux, text width, maybe more).

I would think the actual selection code either already exists elsewhere in a reusable form, or it should.  Not should like 'you owe it to me' but rather should like 'if it does not exist then i would expect tox to not implement the feature until another library does provide this functionality'.

I understand that this may be a corner case usage.  Then again, I think lots of Python CI doesn't actually test the files they are going to distribute which seems bad and this feature could play a role in improving that.

My CI is laid out in three steps.  Build artifacts that might later get published.  Test those artifacts.  If tests pass and it is a tagged commit to be released, publish the artifacts.

If this second attempt doesn't clearly explain my needs I'm willing to move on and close the issue.  There doesn't seem to be significant interest in which case it is unlikely this this feature would be implemented anyways.

(Note that the pip download approach suffers from https://github.com/pypa/pip/issues/7995)

**Comment by gaborbernat** [comment]
I see. I don't think what your proposing belongs to core tox straight up. I'm of the opinion to implement this part as tox plugin first, which effectively replaces the build package step with this acquire from remote/folder. If the plugin becomes popular we can discuss merging it inside core. Sadly there's no easy way to do this in tox 3. In tox 4 it could be a registered option that can be selected under https://github.com/tox-dev/tox/blob/rewrite/src/tox/tox_env/python/virtual_env/package/util.py#L7

**Comment by altendky** [comment]
Thanks for the pointers there.  I've got a few things on my plate right now but I at least would like to try to implement this at some point.  To have it on the record, it was suggested to me that https://pypi.org/project/resolvelib/ may be relevant to this task, though I haven't gotten to confirming either way yet.

Do you generally leave tickets for potential new plugins open here?  If not then we can close this out.  If I start anything I'll follow up here for anyone that finds this in the future.

@webknjaz, if you are interested enough to start into this, don't hesitate.  If I get to it, it won't be right away.

**Comment by gaborbernat** [comment]
I leave the ticket open for now; tox 4 is not going to be a thing before September... but thanks for bringing this to my attention will make sure to cater for this use case when finalizing the design for tox 4.

**Comment by gaborbernat** [comment]
tox 4 now supports sdist/wheel via --installpkg, so I'm closing this now.
