### ISSUE TITLE
On py38 envs, need: setenv = PYTHONPATH={envdir}/lib/python3.8

### ISSUE THREAD

**Issue by auria** [tox-dev/tox#1572]
I use an environment called "unit" to run unit tests (`tox -e unit`). The environment needs a python module on `.tox/unit/lib/<pythonversion>` to make the unit tests work (FYI, that module is deployed by a different component, but it is a dependency for one of the programs tested here).

In previous Ubuntu distros, where py35 and py36 are the default interpreters, `sys.path` already included said folder (ie. `.tox/unit/lib/python3.5/module.py` or `.tox/unit/lib/python3.6/module.py`).

However, in py38, the default `sys.path` includes `.tox/unit/lib/python3.8/site-packages` but not the previous folder. Hence, the extra `PYTHONPATH` config mentioned in the subject.

I'm not sure if this is a bug or something expected. I tried with tox `3.13.2` and the current latest version (`3.14.6`) with same results.

FWIW, the mentioned workaround works even when the interpreter changes to the previous versions (so, backward compatible).

Thank you,
-Alvaro.

**Comment by gaborbernat** [comment]
The fact that you need the standard library path on ``sys.path`` is highly specific to use case. In such cases you can try setting PYTHONPATH to that location via your ``tox.ini``. This setting is not needed for **most** applications so we'll not add it at core level. You can though do it via your tox configuration. Probably better to add it though as in ``{envsitepackagesdir}/..``.
