### ISSUE TITLE
--installpkg does not work with extras

### ISSUE THREAD

**Issue by Spenser309** [tox-dev/tox#1576]
I have the following tox config which works great for sdist.

```
[tox]
isolated_build = True
envlist = premerge

[testenv:premerge]
extras = tests
deps = pytest-xdist
commands = pytest -s -v --junitxml=junit-{envname}.xml
```

When I execute tox with `tox --installpkg dist/*.whl`.  The extras parameter is being ignored (and thus my test deps are not installed)

It looks like in `--installpkg`, the pip installation command is `pip install --no-deps <name>.whl[tests]`; but the `--no-deps` option to pip is causing my deps to not be installed as defined in setup.cfg. 

I've worked around the issue by making the install command the following.
```
[tox]
isolated_build = True
envlist = premerge

[testenv:premerge]
extras = tests
deps = pytest-xdist
install_command = pip install {pacakges}
commands = pytest -s -v --junitxml=junit-{envname}.xml
```

**Comment by webknjaz** [comment]
Oh, I was about to file the same issue. My workflow is that I build the dists in a separate job, then I use `--installpkg --notest` followed by an invocation with `--skip-pkg-install` (a separate step is nicer when looking at what CI does). Also, it always sets `recreate = True` in this case.
I guess, this is one of the reasons for me to prefer `pip-tools`, especially as it also manages the pins better. Plus having a `testing` extra with unpinned deps in user-facing metadata is not particularly useful.

**Comment by gaborbernat** [comment]
I think this works with tox 4. Can anyone validate that? Unlikely will ever be fixed for v3.

**Comment by gaborbernat** [comment]
Closing per above.
