### ISSUE TITLE
Also passes lower case proxy environment variables by default

### ISSUE THREAD

**Issue by EFanZh** [tox-dev/tox#1583]
It seems that currently, only upper case proxy environment variables (`HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY`) are passed by default. I think maybe it’s a good idea to pass lower case ones (`http_proxy`, `https_proxy`, `no_proxy`) too.

Related: #1498, #1500.

**Comment by gaborbernat** [comment]
tox 4 only passes lower case, I believe this should work for all platforms.
