### ISSUE TITLE
Support selecting Python patch versions

### ISSUE THREAD

**Issue by laike9m** [tox-dev/tox#1591]
It would be nice if we can specify tox to use different patch versions, like `3.8.1`, `3.8.2`, as there may exist subtle differences that can affect our tests. Several relevant questions can be found on SO:

- [run tox on different python patch versions](https://stackoverflow.com/q/36887076/2142577)
- [How to test a library against different Python *patch* versions?](https://stackoverflow.com/q/57245532/2142577)

**Comment by gaborbernat** [comment]
This is already possible. You can define a new tox environment and set basepython as ``python3.8.1``; or pass a python 3.8.1 path via ``--discover`` to a `py38`` environment.

**Comment by laike9m** [comment]
Thanks Bernát, may I ask for an example of this?

**Comment by gaborbernat** [comment]
For a one of check against 3.8.1 (assuming your python3.8 points to 3.8.2) you can use the [discover flag][1]

```bash
tox --discover /path/to/python3.8.1 -e py38
```

If you want to define an environment that always uses 3.8.1 you can do that by defining a new tox environment and setting [basepython][2] as ``python3.8.1``.

```ini
[testenv:py381]
basepython = python3.8.1

[testenv:py382]
basepython = python3.8.2
```

  [1]: https://tox.readthedocs.io/en/latest/config.html#cmdoption-tox-discover
  [2]: https://tox.readthedocs.io/en/latest/config.html#conf-basepython

**Comment by laike9m** [comment]
Thanks. It worked, though I have to use `testenv:python383` instead of `testenv:py383`, otherwise tox will complain about `InterpreterNotFound`. The solution comes from https://github.com/tox-dev/tox/issues/378#issuecomment-413937359, so I'm guessing the root cause is the same, but I didn't investigate.
