### ISSUE TITLE
Facing an issue using Tox on Windows 10

### ISSUE THREAD

**Issue by NevilleMthw** [tox-dev/tox#1596]
Hi, I'm fairly new to this Tox testing feature, for some reason, I try to use: ```tox -e``` it doesn't work, neither does the ```tox``` command. The project I'm working on is not mine, it's an open-source project.
This is the tox.ini file:
```[tox]
envlist=clean,py{36,37,38},report

[testenv]
commands=
  coverage run --append -m pytest
  coverage report
deps=-r requirements/test.txt

[testenv:report]
basepython=python3.8
skip_install=true
deps=-r requirements/test.txt
commands=
  coverage report
  coverage xml 

[testenv:clean]
basepython=python3.8
skip_install=True
deps=-r requirements/test.txt
commands=coverage erase

[testenv:run]
basepython=python3.8
commands=python {posargs}
passenv=SMALLD_TOKEN

[testenv:fmt]
basepython=python3.8
skip_install=True
commands=
  autoflake -ri --remove-all-unused-imports --ignore-init-module-imports {env:PY_FILES}
  isort -rc {env:PY_FILES}
  black -t py36 {env:PY_FILES}
  sort -o .gitignore .gitignore
deps=-r requirements/fmt.txt
whitelist_externals=sort
setenv=
  PY_FILES=setup.py smalld/ test/ examples/

[testenv:pip-compile]
basepython=python3.6
skip_install=True
commands=
  pip-compile --output-file=requirements/fmt.txt requirements/fmt.in
  pip-compile --output-file=requirements/test.txt requirements/test.in
deps=pip-tools==5.1.2
setenv=
  LC_ALL=C.UTF-8
  LANG=C.UTF-8
  ```
Also, did ```pip install tox``` but the requirements are satisfied. Any help would be appreciated.

**Comment by gaborbernat** [comment]
Can you detail what you type and what you see, when you say it's not working?

**Comment by NevilleMthw** [comment]
> Can you detail what you type and what you see, when you say it's not working?

Okay so I tried the following commands:
Tox:
```
'tox' is not recognized as an internal or external command,
operable program or batch file.
```
Tox -e:
```
'tox' is not recognized as an internal or external command,
operable program or batch file.
```
The command itself is not recognized.

**Comment by gaborbernat** [comment]
Before you can use it you need to install tox, see https://tox.readthedocs.io/en/latest/install.html

**Comment by gaborbernat** [comment]
Can you try to install it via:

``python -m pip install tox`` and then do ``python -m tox`` instead of just ``tox``? Most likely your script path is not on your PATH on Windows.

**Comment by NevilleMthw** [comment]
I just checked and it does show my scripts path is there on my PATH. It directly links to the python scripts folder, ```C:\Program Files (x86)\Python 3.8.1\Scripts```. I also tried the other way of running it and it still doesn't show anything.

**Comment by gaborbernat** [comment]
Can you attach the output of both the install and when you're invoking it?

**Comment by NevilleMthw** [comment]
> Can you attach the output of both the install and when you're invoking it?

When I tried pip install tox:
![image](https://user-images.githubusercontent.com/18580821/83850591-36e62300-a722-11ea-94d8-cb75abb366be.png)

When I tried python -m pip install tox:
![image](https://user-images.githubusercontent.com/18580821/83850718-5ed58680-a722-11ea-89fb-2378aa7b1c5f.png)

**Comment by gaborbernat** [comment]
Use ``python -m pip install tox`` please to install.

**Comment by gaborbernat** [comment]
Sigh, windows now ships ``python`` that opens up windows store app to install the store python. Your tox is installed either in the paths from image one, check it form there, ensure it's on path. Or invoke it directly.

**Comment by NevilleMthw** [comment]
> Sigh, windows now ships ``python`` that opens up windows store app to install the store python. Your tox is installed either in the paths from image one, check it form there, ensure it's on path. Or invoke it directly.

Yes it works.Thank you for your help!
