### ISSUE TITLE
Data Files missing in package installation by tox

### ISSUE THREAD

**Issue by HeloiseS** [tox-dev/tox#1599]
Hello!

I have a data directory within my package that contains data subdirectories. Maintaining these subdirectories is paramount to my unit tests since it mimics the architecture that my package has ti deal with. 

The problem is that, although the files in the data folder get installed properly in all the environments I've set up in tox, the subfolders are not there. This means that tests that should work fine end up failing. 

Is there a reason why I have missing directories?
My tox file looks like this: 
```
[tox]
envlist =
     py{36,37}-test-numpy{116,117,118}
     py{36,37}-test-pandas{025,1}
     py37-cov
[testenv]
setenv = PYSYN_CDBS = {toxinidir}/hoki/data/cdbs/
deps =
    numpy116: numpy==1.16.*
    numpy117: numpy==1.17.*
    numpy118: numpy==1.18.*
    pandas025: pandas==0.25.*
    pandas1: pandas==1.0.*
    pytest
    codecov
commands =
    pytest
    cov: codecov --token=724a343a-36d5-4289-9516-598c12d42409
```

thank you!

**Comment by gaborbernat** [comment]
tox does not handle packaging of the files themeselves. It's your build backend that handles that part (setuptools/flit/poetry/etc). So the issue lies within the configuration for those projects.
