### ISSUE TITLE
Globally change distshare and maybe more

### ISSUE THREAD

**Issue by dabljues** [tox-dev/tox#1602]
By default, the tox environments are stored in `~/.tox/distshare` (I mean those zipped ones). This can be change with `distshare=` variable in `tox.ini` or other project configuration files. But when you have many tox projects, maybe you can't enforce changing `distshare` in all of them.

It would be nice to set variables like this (because i.e. distshares are not stored in project) globally for a machine/user, having a global tox configuration file in like `~/.config` or something. Of course not all things should be possible to be configured globally I guess, but those like `distshare` make sense to be.

**Comment by gaborbernat** [comment]
This will be possible with tox v4, coming Q4 (WIP at https://github.com/tox-dev/tox/tree/rewrite/src/tox).

**Comment by dabljues** [comment]
Okay, thanks for the info

**Comment by gaborbernat** [comment]
We decided to drop distshare functionality in tox 4. That being said all flags defaults may be changed globally in tox 4.
