### ISSUE TITLE
Option to bypass package installation on demand

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/tox#1605]
Currently if you want to separate tox setup and run via:

```
tox -e py --notest
tox -e py
```

The second invocation still builds the package and installs it. I suggest adding ``--skip-package-install`` that would skip this step and go ahead straight with running the test suite? (especially useful in CIs to avoid the redundant rebuild and install) @asottile what you think?

**Comment by asottile** [comment]
option seems fine, it'd be safer if it validated that the package was already installed

**Comment by gaborbernat** [comment]
Any cheap validation methods here though? 🤔 I'm not sure I can think of something that does not involve calling out to pip via subprocess which is not always cheap 🤔 and finding out the package name similarly can be expensive unless we start caching the built package names... which then involves more complication (though would be easier in tox 4, where we have better-caching system in-place). So, for now, I'm tempted to go ahead with no validation and make it use with caution flag.
