### ISSUE TITLE
RFE: Use a HOSTNAME environment variable instead of socket.getfqdn() in ResultLog

### ISSUE THREAD

**Issue by hroncok** [tox-dev/tox#1615]
Hello. When I build Fedora RPM Python packages locally, I have a setup with disabled network -- to make sure the package will build fine in the official Fedora build system, which is "offline".

My setup (common to other Fedora packagers) times out when the code within runs DNS queries. tox, even when invoked very simply (e.g. via `tox -l`), calls `socket.getfqdn()`:

https://github.com/tox-dev/tox/blob/9e61b2d5ed78385c52d584adbe67fbeb44a11f34/src/tox/logs/result.py#L24

As a result, the invocation hangs for ~1 minute, then proceeds. This is a tad inconvenient, especially since `tox` might be invoked multiple times in some of our packages.

I respect that this network setup is not the most common one. However, would you accept a pull request that prefers the value of the `HOSTNAME` environment variable if set, over a call to `socket.getfqdn()`?

**Comment by gaborbernat** [comment]
> I respect that this network setup is not the most common one. However, would you accept a pull request that prefers the value of the `HOSTNAME` environment variable if set, over a call to `socket.getfqdn()`?

Sounds good.

**Comment by hroncok** [comment]
Ready for inspection in https://github.com/tox-dev/tox/pull/1616

**Comment by hroncok** [comment]
Thank you for accepting my change.

**Comment by gaborbernat** [comment]
Thanks for the PR.
