### ISSUE TITLE
tox should map all TOX_ prefixed variables to options

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox#1627]
Like other command line tools, tox should generically map any `TOX_FOO=bar` to environment variable too an lowercase option like `--foo=bar`.

This approach would make it easier to control and configure on both development stations and CI pipelines.

Also, implementing this would simplify the code as we would no longer need specific code that does this type of mappings for each option.

I sure that pip and ansible do this kind of mapping, better described as **configurable defaults fallback**, and likely pytest too.

**Comment by gaborbernat** [comment]
This is already done in the rewrite branch. No plan to implement this for version 3, unless someone is volunteering.

**Comment by ssbarnea** [comment]
In that case why not making a `4.0a0` or `4.0dev0` release and branching current master as `stable/3.x`? Not having a pre-release does not encourage early adopters to test it and provide feedback.

**Comment by gaborbernat** [comment]
It's because while this feature is implemented, there are countless others that are not. Unlikely to get a first beta release I'm comfortable sharing with the wider audiance before December.
