### ISSUE TITLE
Failure to run tox on Travis CI on Python 3.6, working elsewhere

### ISSUE THREAD

**Issue by dvarrazzo** [tox-dev/tox#1635]
Hello,

I am working with the development of psycopg3, and I'm trying to create two distributions: "psycopg3" would be pure python, "psycopg3-c" would be an add-on to improve performance but requiring more dependencies on at install time (compiler, dev headers...). What I'm trying to do is to keep both the distributions into the same git repository. So, in the [multiple-distributions branch](https://github.com/psycopg/psycopg3/tree/multiple-distributions) I'm currently testing this layout:

```
psycopg3/
+-- tox.ini
+-- psycopg3/
|     +-- setup.py
|     +-- psycopg3/
|           +-- __init__.py
|           +-- [more python code]
+-- psycopg3_c/
      +-- setup.py
      +-- [cython, c code]
```

tox seems to work well locally: from blank you can pretty much:

- clone the repos
- create a python 3.6 virtualenv and source
- pip install tox
- run `tox` in the project directory and everything gets tested ok:

```
  py36: commands succeeded
ERROR:  py37: InterpreterNotFound: python3.7
ERROR:  py38: InterpreterNotFound: python3.8
  black: commands succeeded
  flake8: commands succeeded
  mypy: commands succeeded
```

However, testing on gitlab ci fails with a problem that seems originating from the temporary package that tox creates: see [this build failure](https://travis-ci.org/github/psycopg/psycopg3/builds/712753699). Previously all the jobs were failing, now only the ones using python 3.6 it seems. Message error is 

    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-wsekflql/setup.py'

I could "fix" py 3.7 and 3.8 by [pinning setuptools and wheel versions](https://github.com/psycopg/psycopg3/compare/c2e01db0c0cf...a5c6bc1dc1a1) but that doesn't seem to affect python 3.6 tasks.

I understand that you are not responsible of what happens on Travis CI of course: I would appreciate your insight to understand why this command might fail there. Have you got idea what else could be different? Versions are:

- python 3.6.7 on Travis, 3.6.9 locally
- pip 20.1.1
- tox 3.18.1

Thank you very much!

**Comment by gaborbernat** [comment]
1. For black you can skip install via https://tox.readthedocs.io/en/latest/config.html#conf-skip_install?
2. https://github.com/psycopg/psycopg3/blob/multiple-distributions/tox.ini#L23 use src layout as does tox/virtualenv?
3. https://travis-ci.org/github/psycopg/psycopg3/jobs/712753703#L313-L342 issue will be with setuptools/packaging, note how setup.py is never added or pyproject.toml hence the failure you see, most likely due to the later missing. You could confuse tox in believing you have pyprojec.toml but the sub-projects yo upackage don't have it. The UNKNOWN names and 0.0.0 version would also concern me.

**Comment by dvarrazzo** [comment]
1) thank you for skip_install
2) I should think about it. I wonder how should I put two setup.py.
3) does tox assumes a setup.py in the same directory of tox.ini? Or is it possible to decouple the two?

**Comment by gaborbernat** [comment]
tox makes no assumption, all assumptions are made by python packaging standards, read pep 517 and pep 518 for details

**Comment by dvarrazzo** [comment]
Hi @gaborbernat 

the bit that I am missing is how to configure the sdist creation. The fact that tox.ini is not in the same directory of setup.py leads to the creation of that `UNKNOWN` broken package, and I haven't seen in the documentation how to do differently.

FYI, [as of now](https://github.com/psycopg/psycopg3/tree/2f82d0284c896c10a34b4887e87910814478d71d), I have stabilised on this project layout:

```
psycopg3/
+-- tox.ini  # for only linting, with skip_install = true
+-- psycopg3/
|     +-- setup.py
|     +-- tox.ini  # to test this package
|     +-- pyproject.toml
|     +-- psycopg3/
|           +-- __init__.py
|           +-- [more python code]
+-- psycopg3_c/
      +-- setup.py
      +-- tox.ini  # to test this package
      +-- pyproject.toml
      +-- psycopg3_c/
            +-- [cython, c code]
```

As you can see the project requires three `tox.ini` and tests can only run using e.g. `tox -c psycopg3_c -e py36`. Trying to add the tests to the root `tox.ini`, e.g.

```diff
(.venv) piro@akela:~/dev/psycopg3$ git diff tox.ini
diff --git a/tox.ini b/tox.ini
index db270ab..82553aa 100644
--- a/tox.ini
+++ b/tox.ini
@@ -1,7 +1,16 @@
 [tox]
-envlist = black, flake8, mypy
+envlist = py{36,37,38}, black, flake8, mypy
 isolated_build = True
 
+[testenv:py{36,37,38}]
+changedir = psycopg3
+commands =
+    pytest ../tests {posargs}
+passenv = PG* PSYCOPG3_TEST_DSN PYTEST_ADDOPTS PSYCOPG3_IMPL
+deps =
+    pytest >= 6, < 6.1
+    pytest-asyncio >= 0.14.0, < 0.15
+
 [testenv:black]
 commands = black --check --diff .
 deps = black
```

causes the `UNDEFINED` problem described. Even specifying `changedir`, that seems to have effect only after sdist.

I think it would be great if a project with this layout could do with a single `tox.ini` in the root directory. Do you think there is a way to achieve it (anything I'm missing from the docs)? If not, does it seem a scenario interesting to support for tox? Happy to collaborate if I can.

Thank you very much!

**Comment by gaborbernat** [comment]
> The fact that tox.ini is not in the same directory of setup.py

I don't think we support this scenario. You could get it working but you'd be relying on implementation details. IMHO the safest solution here is for each project to have its own ``tox.ini``...
