### ISSUE TITLE
_rewrite_args changes absolute path locations

### ISSUE THREAD

**Issue by lockshaw** [tox-dev/tox#1638]
When `args_are_paths` is set to False, elements of `posargs` are still modified as if they are paths. 

For example, in the attached example project (only the `tox.ini` is relevant--the rest is just a stub to make tox run), we have the following `tox.ini`:
```
[testenv]
commands= echo {posargs}
args_are_paths = false
```
When we run 
```
$ tox "$PWD/somepackage"
```
from within the root of the project directory then, I would expect the result to be that the full path is printed, since `args_are_paths` is set to false. However, `_rewrite_args` ([here](https://github.com/tox-dev/tox/blob/9d011829cf3d7d73d82e1700fe864fdaa7ca71f8/src/tox/action.py#L249)) overwrites the path and changes `posargs` to `somepackage`. Since the `cwd` when running the tests is different (no longer the original "$PWD"), this no longer refers to the same location. 

Is this intended, or is this a bug?

If there is any other information I can provide that would be helpful, please let me know! Thanks!

[somepackage.tar.gz](https://github.com/tox-dev/tox/files/5005077/somepackage.tar.gz)

Operating system: Ubuntu 18.04
Tox version: 3.15.2
Python version: 3.7.5

**Comment by gaborbernat** [comment]
> Is this intended, or is this a bug?

It is intended.
