### ISSUE TITLE
docs refactoring: towncrier draft + sphinx as an ext

### ISSUE THREAD

**Issue by webknjaz** [tox-dev/tox#1639]
So I happened to borrow the idea of embedding the draft Towncrier output into Sphinx docs and turned it into a native Sphinx extension: [ansible/pylibssh@f5f9ef1](https://github.com/ansible/pylibssh/pull/118/commits/f5f9ef17e51b0c80db6e48388ebb4d48ee021e91).

The basic use is:
```rst
.. towncrier-draft-entries:: |release| [UNRELEASED DRAFT]
```
(for example, there's also configuration options and defaults)

@gaborbernat would you want it here? It basically could replace the hack this generating a gitignored file. I'm considering releasing it as a standalone dist but right now it's only available as vendored copy-paste.

**Comment by gaborbernat** [comment]
Sure 😃

**Comment by gaborbernat** [comment]
After consideration, we'll keep this internal for now. We can discuss in a years time or so, considering how the plugin project evolves.
