### ISSUE TITLE
ERROR: missing D:\Testing Framework\pyproject.toml

### ISSUE THREAD

**Issue by ShehzadaAlam** [tox-dev/tox#1641]
Tox version: 3.18.1

OS type: Windows 10 Home Edition.

Virtual env Type: conda virtual env.

Issue Description: This is the first time I'm using tox, and it clearly stated that either I need to create **pyproject.toml, tox.ini or setup.cfg** to invoke tox, so I've generated tox.ini by using tox-quickstart in the same directory where all my files reside but when I try to Run **'tox'** command it prompts me stating **ERROR: missing pyproject.toml**.

Please check the screenshot attached.

![tox issue](https://user-images.githubusercontent.com/50400399/89408730-72ab6200-d73e-11ea-8c9f-48c4ce91aadf.jpg)

**Comment by gaborbernat** [comment]
As the error says you need to create a pyproject.toml per https://www.bernat.tech/pep-517-and-python-packaging/ e.g. https://github.com/tox-dev/tox/blob/master/pyproject.toml#L1-L7

**Comment by stuart23** [comment]
> As the error says you need to create a pyproject.toml per https://www.bernat.tech/pep-517-and-python-packaging/ e.g. https://github.com/tox-dev/tox/blob/master/pyproject.toml#L1-L7

Link is broken
