### ISSUE TITLE
Allow to run tox --devenv without config file

### ISSUE THREAD

**Issue by hroncok** [tox-dev/tox#1643]
See https://github.com/tox-dev/tox/pull/1642#issuecomment-669609613

> heheh I actually noticed this behaviour recently and considered it a feature (at least for `tox --devenv` which *just works* even without tox configuration)

> Well, if it is useful to allow devenv without configuration, let's do that explicitly and not just with setup.cfg?

**Comment by hroncok** [comment]
I've looked into it and many "set defaults" things are tightly coupled with "parse an ini config" I will prep a PR for this but it might be worth considering to uncouple those two things (I won't have time to do that).

**Comment by gaborbernat** [comment]
For tox 3 I don't think we'll do any major refactors/decoupling that's reserved for tox 4 on the rewrite branch.

**Comment by hroncok** [comment]
Ack. Here is my PR: https://github.com/tox-dev/tox/pull/1644

**Comment by gaborbernat** [comment]
Released via https://pypi.org/project/tox/3.19.0/
