### ISSUE TITLE
Test tox plugins with different basepython

### ISSUE THREAD

**Issue by pmeier** [tox-dev/tox#1649]
# Motivation

I'm currently in the process of writing a `tox` plugin that internally utilizes the Python version of the environment. I'm accessing that via 
 
```python
subprocess.check_output([venv.envconfig.basepython, "--version")
```

This works as intended, but I'm having trouble to test this in CI.

# Problem

I invoke my tests via `tox`, which means that in the virtual environment only one interpreter is present. In my test I use the [`init_proj` fixture](https://github.com/tox-dev/tox/blob/23dd96f5a6891fb13e298ea941bd457931421ffd/src/tox/_pytestplugin.py#L344) to write the following `tox.ini`:

```ini
[tox]

requires = tox-ltt;  my plugin
envlist = py

[testenv]

basepython = py38;  just has to be different from the invoking python
```

Running this with the [`cmd` fixture](https://github.com/tox-dev/tox/blob/23dd96f5a6891fb13e298ea941bd457931421ffd/src/tox/_pytestplugin.py#L120), it fails expectably with

```python
tox.exception.InterpreterNotFound: InterpreterNotFound: py38
```

# Question / Feature request

Is it possible to test a scenario like this? If not or only hacky, are you interested in adding this? With guidance, I could help out. 

While searching for a solution for my problem I found the [`mock_venv` fixture](https://github.com/tox-dev/tox/blob/23dd96f5a6891fb13e298ea941bd457931421ffd/src/tox/_pytestplugin.py#L490) which might be used for this. 

But then the docstring states:

https://github.com/tox-dev/tox/blob/23dd96f5a6891fb13e298ea941bd457931421ffd/src/tox/_pytestplugin.py#L489-L491

**Comment by gaborbernat** [comment]
I think it's possible to do this, but we haven't got anyone requesting this before. Can you shed some light on why you must need a different python version?

**Comment by pmeier** [comment]
I'm sorry, but the project I needed this for is currently inactive. I forgot about this issue. I'll try to reconstruct my use-case.

The plugin I wrote behaves differently for different python versions. I need to parse a list and select an item that fits my current python version. Thus, to test this it would be beneficial to be able to test this for different python versions.

I'm fully aware that this is an edge-case and I don't expect anyone else besides me working on it. Given that, I'm closing this for now and only reopen it if the project becomes active again.
