### ISSUE TITLE
Preserve line breaks in the output of list_dependencies_command

### ISSUE THREAD

**Issue by Choc13** [tox-dev/tox#1651]
Currently (I believe) the output from the `list_dependencies_command` is split on new lines and joined with a comma. This can make the dependency list quite hard to read when trying to debug dependency issues in a build. For example the current output looks something like:

```
docs-test installed: alabaster==0.7.12,argh==0.26.2,astroid==2.4.2,attrs==19.3.0,avro-python3==1.9.2.1,Babel==2.8.0,...
```

We are also using `tox-conda` and would like to set `list_dependencies_command` to `conda list`. However, this outputs a tabular format, which then becomes illegible when the newlines are removed and joined with a comma.

Is there any reason this output needs to be formatted to remove the line breaks? Would it be possible print the output of the `list_dependencies_command` more verbatim to make it more legible?

I'm happy to do the PR for this, but I first wanted to check if there were any underlying reasons for the way it currently is.

**Comment by gaborbernat** [comment]
In general we don't want to add flags for these but I'm open for an environment variable for this.

**Comment by Choc13** [comment]
OK cool. Just so I understand, what's the rationale for stripping the line breaks and joining with a comma currently? Could we change the default behaviour to just output exactly as the command outputs, line breaks and all?

**Comment by gaborbernat** [comment]
We can't change the output by default that would be a breaking change and we don't do those.

**Comment by Choc13** [comment]
Ok fair enough. I perhaps naively assumed this was just a message that's output to the console for diagnostic purposes and therefore wouldn't be depended on by anyone.

**Comment by gaborbernat** [comment]
@Choc13 still planning to address this?

**Comment by Choc13** [comment]
@gaborbernat I don't think I'm going to have time to do this in the foreseeable future. Sorry.

**Comment by gaborbernat** [comment]
I'll close this then. If anyone wants to pick it up we can reopen.
