### ISSUE TITLE
Make tox fail on unspecified pyXX environments

### ISSUE THREAD

**Issue by chrisjsewell** [tox-dev/tox#1657]
When submitting a bug make sure you can reproduce it via ``tox -rvv`` and attach the output of that to the bug. Ideally, you should also submit a project that allows easily reproducing the bug. Thanks!

tox will fail on a "completely" unknown environment (as fixed in #1160).
However, if I have an environment list like:

```
$ tox -a
py36-sphinx2
py36-sphinx3
```

running `tox -e py36` will still run and create an environment.

Is there a way to stop this?

**Comment by gaborbernat** [comment]
There's no way to stop it and that's on purpose. It offers the flexibility to test pythons that are not defined within your tox.ini.
