### ISSUE TITLE
Provide a way to select features/settings based on Python version

### ISSUE THREAD

**Issue by jaraco** [tox-dev/tox#1658]
Currently, tox has environments, and if one selects environments by Python version (i.e. `py36`), that environment can also be used to select features. e.g.:

```tox.ini

[testenv]
commands =
    py36: python -V
```

However, this approach doesn't match the Python version - it only matches the environment name. If the same environment is invoked with `py` or `python`, the `py36`-tagged command will not run.

Similarly, if an environment is tagged for a specific Python version, that environment isn't selected when the matching python version is used:

```tox.ini

[testenv:py38]
commands = python -V
```

That command environment won't be selected on Python 3.8 if the TOX_ENV is `py` or `python`.

It would be nice if there were some way to provide specific behavior based on the python version of the environment or perhaps other factors.

Perhaps one way this could be done is to re-use the behavior of packaging's environment markers. tox could allow the user to create environment factors based on environment markers. For example:

```tox.ini
[tox]
add_factors =
    py36plus = python_version >= "3.6"
    windows = platform_system == "Windows"
```

Then, on Python 3.6 or later, the test is invoked as if `tox -e -py36plus` was invoked when on Linux and Python 3.6 or later and as if `tox -e -windows` was invoked when on Windows, and `-windows-py36plus` when both.

**Comment by gaborbernat** [comment]
I'm going to close this now and put it under the won't do part of core. If anyone creates the plugin feel free to link it here.
