### ISSUE TITLE
Make Change Log discoverable to bots

### ISSUE THREAD

**Issue by cooperlees** [tox-dev/tox#1670]
Hi,

Super low priority, can we try workout why some bots can't find your change log? Maybe it's because you don't add changes to the GitHub release? e.g. when I cut a release for bandersnatch I add them on the release:
- https://github.com/pypa/bandersnatch/releases/tag/4.3.0

## Example
On bandersnatch I'd love to see what the charges are between my version of tox and what I'm moving to on PRs like this:
https://github.com/pypa/bandersnatch/pull/684

**Comment by gaborbernat** [comment]
This sounds to me like a bug ticket to the bot, not to us. If raising the issue to the bot can identify the issue we can reopen with something actionable.

**Comment by cooperlees** [comment]
I gave a suggestion for the release process that would potentially allow pyup.io to show users a changelog. So that meets your request of "something actionable".

pyup.io works for all dependencies but tox, so your uncommon `changes.rst` in docs directory is obviously not common.

**Comment by cooperlees** [comment]
Maybe also adding a change log link in `setup.*` might help?

Example:
https://github.com/pypa/bandersnatch/blob/master/setup.cfg#L17
```
Change Log = https://github.com/pypa/bandersnatch/blob/master/CHANGES.md
```

Then it will also show on https://pypi.org/project/tox/

**Comment by gaborbernat** [comment]
I don't want to include the change log on GitHub, so if possible first I'd like to exhaust other options of pypi up.

**Comment by gaborbernat** [comment]
Also let's not go on potentially, but on definite solutions.
