### ISSUE TITLE
add an "disthash=sha256" option to support installing the `get_package` dist with pinned constraints

### ISSUE THREAD

**Issue by graingert** [tox-dev/tox#1672]
being able to use tox with securely pinned deps is tantalizingly close

when the:

```ini
[toxenv]
disthash=$HASHER
```

if present, tox should generate the hash of the `get_package()` file, using the passed $HASHER, it should then pass a TemporaryFile `-r` requirement containing the dist and the `--hash=sha256:`

https://github.com/tox-dev/tox/issues/1167#issuecomment-688426203

**Comment by graingert** [comment]
so it turns out pip doesn't process "--hash" calls unless they're in a requirements file: https://github.com/PyCQA/modernize/pull/228/files#diff-256be86b218458267e29f38e19906417R72

**Comment by gaborbernat** [comment]
@graingert so what options do we have here then?

**Comment by graingert** [comment]
@gaborbernat I've opened a discussion here for more options https://discuss.python.org/t/some-way-to-pass-hash-on-the-cli-or-to-ignore-file-uris-when-using-require-hashes/5256

the options today as I see them:
* tox could integrate my [tox installcommand](https://github.com/PyCQA/modernize/pull/228/files#diff-380c6a8ebbbce17d55d50ef17d3cf906R90) and pass a temp requirements.txt with hashes in

* tox could pass a PEP 440 direct reference, with "Locally stored URL-based requirements" `foo[extra,test] @ file:///path/to/foo.tar.gz#sha256=8badfood`

**Comment by graingert** [comment]
I'm looking to implement a "hypermodern workflow", like @cjolowicz https://github.com/cjolowicz/cookiecutter-hypermodern-python/ but with tox/flit rather than nox/poetry.

what hypermodern does that I'm interested in, is create a constraints.txt (with hashes in). That constraints file is passed to nox which is passed to pip, so that every nox environment uses securely pinned dependencies

I want tox to use that constraints.txt such that tox can use in tox bootstrap, and in installing any other toxenv

**Comment by gaborbernat** [comment]
> I want tox to use that constraints.txt such that tox can use in tox bootstrap, and in installing any other toxenv

Can you clarify a bit what does bootstrap means and installing any other toxenv? (or whats's the difference between them).

**Comment by graingert** [comment]
> > I want tox to use that constraints.txt such that tox can use in tox bootstrap, and in installing any other toxenv
> 
> Can you clarify a bit what does bootstrap means and installing any other toxenv? (or whats's the difference between them).

Sorry I mean provision, not bootstrap: https://tox.readthedocs.io/en/latest/config.html#conf-provision_tox_env

**Comment by graingert** [comment]
pip issue here https://github.com/pypa/pip/issues/10362

**Comment by gaborbernat** [comment]
This seems to have not gained much traction or feedback so I'll close it as lack of demand. If either the pip issue makes progress or we get more people interested we can reopen.
