### ISSUE TITLE
tox-quickstart offers outdated Python environments 

### ISSUE THREAD

**Issue by hroncok** [tox-dev/tox#1674]
When I run `tox-quickstart`, it offers me some old Python versions:

```
What Python versions do you want to test against?
            [1] py37
            [2] py27, py37
            [3] (All versions) py27, py35, py36, py37, pypy, jython
            [4] Choose each one-by-one

```

This also happens on systems where I only have PyPy 3.6 and Python 3.9.

I've looked into the code and I've found:

https://github.com/tox-dev/tox/blob/800b4cc1261b490a8afa34b44dc804a82ecf0b81/src/tox/constants.py#L14-L16

I wonder whether this could be updated:

 - to have `CURRENT_RELEASE_ENV = "py38"` (the latest released stable Python version) and to include `"pypy3", "py39"` in the list

Or even:

- List the current interpreter as the `CURRENT_RELEASE_ENV` value (i.e. when my tox runs on Python 3.9, have `"py39"`)
- Lists available interpreters in quickstart instead of a random selection?

**Comment by gaborbernat** [comment]
> Or even:
> 
> * List the current interpreter as the `CURRENT_RELEASE_ENV` value (i.e. when my tox runs on Python 3.9, have `"py39"`)

Definitely yes.

> * Lists available interpreters in quickstart instead of a random selection?


This is a bit harder because you'd need to trial and error, but I'd be ok with it. I generally tend to copy from other projects the ``tox.ini``, hence did not discover this. Happy to accept PRs though.

**Comment by finn0** [comment]
@hroncok may I work on this issue? I guess, this issue won't be too hard for people who recently start learning Python.

**Comment by gaborbernat** [comment]
It's yours 👍

**Comment by hroncok** [comment]
Feel free to take it. Let me know if you need some help.

**Comment by jayvdb** [comment]
ping @finn0 how are you going?  Need any help?

**Comment by finn0** [comment]
@jayvdb first of all sorry for the delay reply.  Sorry, I was busy in some other work and I couldn't find any time to work on the issue. I will be busy till next week, meanwhile if anybody wants to take over this issue, please go ahead.

**Comment by gaborbernat** [comment]
Closing as has been fixed on the rewrite branch.
