### ISSUE TITLE
tox cannot find system package in /usr/lib/python3/dist-packages/

### ISSUE THREAD

**Issue by nschloe** [tox-dev/tox#1679]
I would like to use [gmsh](https://gmsh.info/) in a tox test. Its Python interface is installed (as a single file) at
```
python3 -c "import gmsh; print(gmsh.__file__)"
```
```
/usr/lib/python3/dist-packages/gmsh.py
```
Running `pytest` in my package folder yields no problem, but `tox` reports
```
    import gmsh
E   ModuleNotFoundError: No module named 'gmsh'
```
The issue can be resolved by copying `gmsh.py` from `/usr/lib/python3/dist-packages/` into `/usr/lib/python3.8/`

My tox config is rather simple:
```
[tox]
envlist = py3
isolated_build = True

[testenv]
deps =
    exdown
    matplotlib
    pytest
    pytest-cov
commands =
    pytest --cov {envsitepackagesdir}/pygmsh --cov-report xml --cov-report term
```
The build has to be isolated as otherwise
```
ERROR: pyproject.toml file found.
To use a PEP 517 build-backend you are required to configure tox to use an isolated_build:
https://tox.readthedocs.io/en/latest/example/package.html
```
Any idea what could be the issue here?

**Comment by asottile** [comment]
is there a reason you can't [install it from pypi](https://pypi.org/project/gmsh/) ?  alternatively you can enable system-site-packages for your virtualenv (though this will have unintended side-effects because it puts system packages onto your test path) -- iirc you can do that with a `setenv = VIRTUALENV_SYSTEM_SITE_PACKAGES=1`

**Comment by nschloe** [comment]
The gmsh Python policy is a bit unclear. For example, the pypi package and the official releases aren't always in sync. (The pypi package requires the system lib to build.) Anyway, with your comments I'll be able to work my way through it. Thanks!
