### ISSUE TITLE
Requesting a 3.21.0 release

### ISSUE THREAD

**Issue by etr2460** [tox-dev/tox#1686]
#1682 in master solves some dependency issues for us, but it's not yet released on pypi. Is a release of 3.21.0 planned soon? Thanks!

**Comment by gaborbernat** [comment]
Triggered via https://github.com/tox-dev/tox/pull/1687

**Comment by gaborbernat** [comment]
https://pypi.org/project/tox/3.20.1/

**Comment by etr2460** [comment]
Thanks!
