### ISSUE TITLE
Intermittent macOS Python 3 CI failure in test_parallel_interrupt

### ISSUE THREAD

**Issue by jayvdb** [tox-dev/tox#1699]
Intermittent macOS failures in `test_parallel_interrupt` experienced in last few days, unrelated to the several different PRs they occurred on:

https://dev.azure.com/toxdev/tox/_build/results?buildId=2674&view=logs&jobId=ea003c71-61e4-522a-c34f-fab7d14eeff7

https://dev.azure.com/toxdev/tox/_build/results?buildId=2694&view=logs&j=ea003c71-61e4-522a-c34f-fab7d14eeff7&t=ffbfb534-ce0f-54dd-55a1-c597bc6d7924

https://dev.azure.com/toxdev/tox/_build/results?buildId=2699&view=logs&j=6f785b48-ed19-5349-e6cb-bb6d29a19c8b&t=4621fbdb-f74d-5491-ece0-e6cd5b96369c

https://dev.azure.com/toxdev/tox/_build/results?buildId=2703&view=logs&j=6f785b48-ed19-5349-e6cb-bb6d29a19c8b&t=4621fbdb-f74d-5491-ece0-e6cd5b96369c

https://dev.azure.com/toxdev/tox/_build/results?buildId=2730&view=logs&j=6f785b48-ed19-5349-e6cb-bb6d29a19c8b&t=4621fbdb-f74d-5491-ece0-e6cd5b96369c

**Comment by jayvdb** [comment]
Appears to have been reported in https://github.com/tox-dev/tox/issues/1470 (closed by opener @kloczek without explanation) and https://github.com/tox-dev/tox/issues/1520 (only pypy was fixed).

**Comment by jayvdb** [comment]
Hmm. An intermittent failure on Windows in `test_parallel_result_json`, apparently caused by `py.error.EBUSY`

https://dev.azure.com/toxdev/tox/_build/results?buildId=2697&view=logs&j=18fdbe60-1f00-5bb0-ebb2-c0f5cf5b2053&t=c43adaf4-2fef-5364-6a38-be409f92e121

**Comment by jayvdb** [comment]
Another Windows py27 https://dev.azure.com/toxdev/tox/_build/results?buildId=2706&view=logs&jobId=18fdbe60-1f00-5bb0-ebb2-c0f5cf5b2053&j=18fdbe60-1f00-5bb0-ebb2-c0f5cf5b2053&t=c43adaf4-2fef-5364-6a38-be409f92e121 , in `test_parallel_recreate`, which fails at
```py
>       assert not ({f.basename for f in after} - {f.basename for f in end})
E       AssertionError: assert not (set(['.lock', 'e1-0.log', 'e1-1.log']) - set(['e1-0.log', 'e1-1.log',
```

but as an aside it also has the following in the log

```py
  File "<string>", line 1
    [print("hello world") for _ in range(1)]
         ^
SyntaxError: invalid syntax
```

Seems strange to have py3 specific syntax in a test, the following would fix that aspect, and that might even mask the underlying problem.
`python2 -c 'from __future__ import print_function; [print("hello world") for _ in range(1)]'`

**Comment by jayvdb** [comment]
Very different failure on py36 macOS

https://dev.azure.com/toxdev/tox/_build/results?buildId=2711&view=logs&jobId=ab8589c0-300c-5834-3150-76b8e970208b&j=ab8589c0-300c-5834-3150-76b8e970208b&t=b2790b9c-7911-59ff-2f30-f8dd15d02c39

```py
tests/unit/config/test_config.py::TestSetenv::test_getdict_lazy_update PASSED [100%]
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/runner/work/1/s/.tox/py36/lib/python3.6/site-packages/_pytest/main.py", line 257, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>     return Analysis(data, it, self._file_mapper)
INTERNALERROR>   File "/Users/runner/work/1/s/.tox/py36/lib/python3.6/site-packages/coverage/results.py", line 20, in __init__
INTERNALERROR>     self.statements = self.file_reporter.lines()
INTERNALERROR>   File "/Users/runner/work/1/s/.tox/py36/lib/python3.6/site-packages/coverage/python.py", line 191, in lines
INTERNALERROR>     return self.parser.statements
INTERNALERROR>   File "/Users/runner/work/1/s/.tox/py36/lib/python3.6/site-packages/coverage/python.py", line 186, in parser
INTERNALERROR>     self._parser.parse_source()
INTERNALERROR>   File "/Users/runner/work/1/s/.tox/py36/lib/python3.6/site-packages/coverage/parser.py", line 241, in parse_source
INTERNALERROR>     self._raw_parse()
INTERNALERROR>   File "/Users/runner/work/1/s/.tox/py36/lib/python3.6/site-packages/coverage/parser.py", line 206, in _raw_parse
INTERNALERROR>     self.raw_statements.update(self.byte_parser._find_statements())
INTERNALERROR>   File "/Users/runner/work/1/s/.tox/py36/lib/python3.6/site-packages/coverage/parser.py", line 96, in byte_parser
INTERNALERROR>     self._byte_parser = ByteParser(self.text, filename=self.filename)
INTERNALERROR>   File "/Users/runner/work/1/s/.tox/py36/lib/python3.6/site-packages/coverage/parser.py", line 367, in __init__
INTERNALERROR>     self.code = compile_unicode(text, filename, "exec")
INTERNALERROR>   File "/Users/runner/work/1/s/.tox/py36/lib/python3.6/site-packages/coverage/phystokens.py", line 285, in compile_unicode
INTERNALERROR>     code = compile(source, filename, mode)
INTERNALERROR> ValueError: source code string cannot contain null bytes

============ 588 passed, 5 skipped, 1 warning in 451.12s (0:07:31) =============
ERROR: InvocationError for command /Users/runner/work/1/s/.tox/py36/bin/pytest --cov .tox/py36/lib/python3.6/site-packages/tox --cov-config tox.ini --junitxml /Users/runner/work/1/s/.tox/junit.py36.xml -n=0 . (exited with code 3)
_```

**Comment by gaborbernat** [comment]
Seems to have stablilized.
