### ISSUE TITLE
Isolated builds call optional PEP 517 hook.

### ISSUE THREAD

**Issue by domdfcoding** [tox-dev/tox#1705]
[tox.helper.build_requires.py](https://github.com/tox-dev/tox/blob/e4d0d60070a4a88b3ca051634c7a01df333af238/src/tox/helper/build_requires.py#L15) calls the optional PEP 517 hook ``get_requires_for_build_sdist`` without first checking if the backend implements it. This results in a crash when building a project:

```python traceback
Traceback (most recent call last):
  File "/home/domdf/.local/lib/python3.8/site-packages/tox/helper/build_requires.py", line 11, in <module>
    for_build_requires = backend.get_requires_for_build_sdist(None)
AttributeError: module 'repo_helper.build' has no attribute 'get_requires_for_build_sdist'
```

PEP 517 says that the requirements should default to ``[]`` if the hook isn't implemented.

Something like

```python
if hasattr(backend, "get_requires_for_build_sdist"):
    for_build_requires = backend.get_requires_for_build_sdist(None)
else:
    for_build_requires = []
```

should fix this.

 

Relevant part of PEP 517: https://www.python.org/dev/peps/pep-0517/#get-requires-for-build-sdist

**Comment by jayvdb** [comment]
That looks like the right fix.
There are not (yet) any direct tests for the build_requires.py helper ; see `tests/unit/test_z_cmdline.py` for some simple ways to create tests.

`tests/unit/package/builder/test_package_builder_isolated.py` has some relevant bigger tests which could be easily adapted to build a package with a backend doesnt have this attribute.

**Comment by gaborbernat** [comment]
This is now fixed on the rewrite branch.
