### ISSUE TITLE
Support for Python 3.9

### ISSUE THREAD

**Issue by pelliu** [tox-dev/tox#1714]
I am working on oci-python-sdk, we use tox to run tests. Now python 3.9.0 is released, I just wanna ask when tox can support python 3.9, so that we can also support python 3.9 in our project, thanks!

**Comment by gaborbernat** [comment]
Hey, it should be working. Did you run into any issues?

**Comment by pelliu** [comment]
I haven't tried it yet, from the release note I didn't see it supports 3.9, so just asked here, if it supports python3.9, could you please update the notes officially? Thanks!

**Comment by gaborbernat** [comment]
Going ahead please always assume we are compatible with new python versions (unless stated otherwise). We always add our CI to new python release candidates, so by the time the interpreters come out we're good to go.
