### ISSUE TITLE
Make it easier to use custom discovery classes with virtualenv v20+

### ISSUE THREAD

**Issue by AWhetter** [tox-dev/tox#1721]
## Current behaviour

tox always passes the `--python` flag to virtualenv (https://github.com/tox-dev/tox/blob/a7903508fa07068b327e15cfdbf8ea330ab78765/src/tox/venv.py#L699). Since virtualenv v20, this flag has been interpreted as part of the "builtin" discovery class (https://github.com/pypa/virtualenv/blob/de69dfadf6d8f622a82f269b7d43832997c86cb1/src/virtualenv/discovery/builtin.py#L23-L30). However it is possible to use custom discovery classes via the command line (though not when using tox), configuration file, or environment variables. When a custom discovery class is used, the class must implement a `--python` flag even if it does not use it because tox always passes the flag.

## Desired Behaviour

Ideally a custom discovery class would not need to implement the parsing of a `--python` flag when it does not use it.

## Possible Implementation

According to the comment in the tox code (https://github.com/tox-dev/tox/blob/a7903508fa07068b327e15cfdbf8ea330ab78765/src/tox/venv.py#L698), the `--python` flag is passed to prevent a virtualenv config file from overriding the basepython that tox wants virtualenv to use. However environment variables take precedence over both command line flags and the config file. Therefore instead of passing `--python`, tox could instead set `VIRTUALENV_PYTHON` if it does not already exist.

**Comment by gaborbernat** [comment]
> When a custom discovery class is used, the class must implement a `--python` flag even if it does not use it because tox always passes the flag.

As both tox and virtualenv maintainer, I'm slightly puzzled how you would know with a custom discovery logic what python to provision. Can you expand a bit on how this custom discovery mechanism would work without the ``--python`` flag (and why it cannot use the python flag)?

**Comment by AWhetter** [comment]
Hello again @gaborbernat! It's the same situation I was in on https://github.com/pypa/virtualenv/issues/1954

We have an in-house environment management tool that deals with entering an exiting those environments. We only ever have a single version of Python installed in those environments. So for us we are configuring which environment to enter rather than which Python executable to use.
Although I suppose it's probably not great for us to assume that there's only ever one Python installation in an environment, I think the point still stands that a custom discovery class could be configured in some other way than only a path to a Python executable?

**Comment by gaborbernat** [comment]
I guess, but then what would you expect to happen when someone runs with:

```
envlist=py38,py37
```

If you only have one version I'd expect to check for whatever ``--python`` is and if it's not what we expect raise. In all other cases return that one python environment possible.

**Comment by AWhetter** [comment]
We have tox plugins that expect specific configuration variables from the tox.ini and pass it through to the virtualenv plugin.

**Comment by gaborbernat** [comment]
Fair enough, but I'd argue for the correctness of tox you still want to handle the ``--python`` flag per above. And just accept the ``--python`` flag in your discovery. Alternatively, you can write a tox plugin that replaces the default virtualenv call and customize it with your own that does not pass on the ``--python`` 🤔 not sure what else we can do on our side. There's no way tox to enquire what discovery mechanism is used and what arguments it needs.

**Comment by AWhetter** [comment]
I've always avoided implementing `tox_testenv_create` without calling the default implementation because it calls `venv._pcall()`, which is difficult to emulate manually, and because there's so much encoded into it like calling `cleanup_for_venv()` and passing on `--always-copy` and `--no-download`. If a new option like that were ever added, then the tox plugin would have to implement it and potentially also worry about whether the version of tox the plugin is being used with supports that new option.

Having to always accept `--python` is fair enough though I suppose. You're right that it would be more correct for us to accept it and use it. We do go through the bother of implementing `tox_get_python_executable()` and making sure that it's correct after all.

**Comment by gaborbernat** [comment]
For what's worth I'm just working on a rewrite of tox that's going to make things easier, and avoid the pcall issue, but don't expect it to happen (for wide release) before end of this year.

**Comment by gaborbernat** [comment]
You can have a snapshot of it from alpha branch.

**Comment by AWhetter** [comment]
Sounds promising. I'll check it out. Thanks again for your help

**Comment by gaborbernat** [comment]
Ah, the wrong name, https://github.com/tox-dev/tox/tree/rewrite#rewrite-branch here it is.
