### ISSUE TITLE
Tox fails when using 'envdir' in [testenv] and 'requires' in [tox]

### ISSUE THREAD

**Issue by isaac-ped** [tox-dev/tox#1722]
When the `[tox]` section requires a new installation, it seems to use the environment specified by the top-level `[testenv]` envdir, if provided.

Upon creation of the test environment, it then appears recreate the environment from which python is currently executing, resulting in an error.

A minimal tox.ini file that reproduces the issue:
```ini
[tox]
skipsdist=true
# Any package that doesn't exist in the base python
requires = setuptools==50.3.1

[testenv]
envdir=test-env
```

`tox -r` results in:
```
.tox create: /tox-test/test-env
.tox installdeps: setuptools==50.3.1, tox >= 3.20.1
python recreate: /tox-test/test-env
ERROR: invocation failed (exit code 2), logfile: /tox-test/test-env/log/python-0.log
================================== log start ===================================

=================================== log end ====================================
ERROR: InvocationError for command /tox-test/test-env/bin/python -m virtualenv --no-download --python /tox-test/test-env/bin/python test-env (exited with code 2)
___________________________________ summary ____________________________________
ERROR:   python: InvocationError for command /tox-test/test-env/bin/python -m virtualenv --no-download --python /tox-test/test-env/bin/python test-env (exited with code 2)
```

The error does not occur if the root-level `[tox]` requirements are already satisfied by the system python, or if envdir is specified for a specific tox environment and not the top-level one.

The full output of tox -rvv is attached here:
[tox-rvv.log](https://github.com/tox-dev/tox/files/5447541/tox-rvv.log)

Reproduced inside of a clean `python:3.8` docker image with tox installed via pip.
```shell
root@python3.8:~$ python --version
Python 3.8.6
root@python3.8:~$ tox --version
3.20.1 imported from /usr/local/lib/python3.8/site-packages/tox/__init__.py
root@python3.8:~$ uname --all
Linux python3.8 5.4.0-45-generic #49~18.04.2-Ubuntu SMP Wed Aug 26 16:29:02 UTC 2020 x86_64 GNU/Linux
```

**Comment by gaborbernat** [comment]
Well, that's unfortunate. The problem with `testenv` is that it sets that value for all tox environments. And we do use tox environments for provisioning the requires (and also the package build). To fix this you need to (re)set [this value to the default](https://tox.readthedocs.io/en/latest/config.html#conf-envdir) for the provisioning package ([defined by this config]( https://tox.readthedocs.io/en/latest/config.html#conf-provision_tox_env)):

```ini
[testenv:.tox]
envdir = {toxworkdir}/{envname}
```
