### ISSUE TITLE
tox4: proposal for a style guide

### ISSUE THREAD

**Issue by gnikonorov** [tox-dev/tox#1734]
Hello!

I think it may be beneficial to add a style guide for the rewrite branch. I believe it would really help onboard new developers, and save maintainers time since they wouldn't have to worry so much about stylistic errors ( e.g.: snake case v camel case ).

Would it be possible to write one up? Apologies if I missed it. I looked through the rewrite branch didn't see one.

**Comment by gaborbernat** [comment]
We're mostly talking about following pep-8 and python 3.6+ idioms.

**Comment by jayvdb** [comment]
@gaborbernat , what about line length?  pep-8 's line length of 80 would be the most common problem in the tox codebase, and 'fixing' it to 80 would IMO be a step backwards.

black uses the much saner 120.  Would using black on tox , at least rewrite branch, be acceptable?

**Comment by gaborbernat** [comment]
It's already that https://github.com/tox-dev/tox/blob/rewrite/pyproject.toml#L6-L9

**Comment by jayvdb** [comment]
Great. I see the master README also mentions "Code style: .. black".

maybe a note in the CONTRIBUTING also..?

Otherwise this seems to be already solved.

**Comment by gaborbernat** [comment]
The case here was more alongside black + PEP-8 + a few others (e.g. start exception messages with lowercase), etc.
