### ISSUE TITLE
Tox takes over 30s to run any kind of command

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox#1735]
``tox --version`` is the only command that is not affected by this weird delay I receintly observed, one that looks like waiting for a missing DNS entry to resolve or something else involving network timeouts.

This happens when there are no plugins installed or configured inside tox.ini file, on any project, at least on MacOS.

```
$ tox -vvva
using tox.ini: /Users/ssbarnea/c/a/molecule/tox.ini (pid 53831)
  removing /Users/ssbarnea/c/a/molecule/.tox/log
##### this is where the 30s delay happens..... ###
using tox-3.20.1 from /Users/ssbarnea/.pyenv/versions/3.9.0/lib/python3.9/site-packages/tox/__init__.py (pid 53831)
default environments:
...

additional environments:
...
Time: 0h:00m:31s
```

It happens with any project using tox and I am unable to stop it even by pressing Ctrl-C
```
$ tox -a
^C^C%
Time: 0h:00m:31s
FAIL: 2
```

**Comment by gaborbernat** [comment]
Can you run strace on it?

**Comment by ssbarnea** [comment]
There is no strace for macos and I am unwilling to [disable SIP to run alternative](https://stackoverflow.com/questions/31045575/how-to-trace-system-calls-of-a-program-in-mac-os-x) as root. I am still looking for a way to identify what happens, I am really curious.

**Comment by ssbarnea** [comment]
After testing with another account and being able to reproduce it I decided is time to reboot the machine. I guess I would have taken [IT Crowd](https://www.youtube.com/watch?v=nn2FB1P_Mn8) guidelines ad literam.

I am afraid I will never know what caused it. It has being like this for a number of days and only tox cli was affected, out of tons of cli utilities I use.
