### ISSUE TITLE
Allowing to package with formats different than zip

### ISSUE THREAD

**Issue by wherka** [tox-dev/tox#1741]
Hello,
as it stands tox exposes the concept of **distshare** area which allows to get the packages as a side effect of the tests. Which in my opinion is quite nice as one may capture the packages which were actually used during the tests and do something with them - releasing or perhaps just publishing them as a mean of the pre-release validation.

However, there one aspect which bothers me a bit. The --formats is hardcoded to **zip**. Wouldn't it be nice to make it more flexible and pass the suitable value as per [official doc](https://docs.python.org/3/distutils/sourcedist.html)?

I appreciate tox was not meant for packaging,  but since it's there already, can we not make it a little bit more convenient to the users please?

Thanks in advance for consideration!

Cheers,
Waldek

**Comment by gaborbernat** [comment]
As the name of the file indicates that part of the system is considered legacy, and no longer planned to be extended any further. Such functionality should be set via your build backends configuration files, per PEP-517.
