### ISSUE TITLE
[idea] Command to run after parallel run

### ISSUE THREAD

**Issue by JulienPalard** [tox-dev/tox#1744]
The initial idea is to be able to run a coverage combine after a parallel run.

Say I have two branches with a condition like: `if sys.version_info >= (3, 8)`, and I run `coverage` for all envs (say py37, py38, py39), say:

```ini
[testenv]
deps = -r requirements-dev.txt
commands =
    coverage run -m pytest

setenv =
  COVERAGE_FILE=.coverage.{envname}
```

so at the end I have one file per tox env: `.coverage.py37`, `.coverage.py38`, and `.coverage.py39`.

I would like to have tox automatically run a `coverage combine .coverage.*` on them, followed by a `coverage report ... --fail-under=...`.

This can actually be done quite easily:

    tox -p all; coverage combine .coverage.*; coverage report --include '*my_proj*' --fail-under=100

but it would probably be nicer if integrated in tox.

I'm not sure about the best way to describe it in the `tox.ini`, maybe via a `finalize` option to the `[tox]` section, like:

```ini
[tox]
isolated_build = True
envlist = py37,py38,py39
finalize =
    coverage combine .coverage.*
    coverage report --include '*myproj*' --fail-under=100

[testenv]
deps = -r requirements-dev.txt
commands =
    coverage run -m pytest
```

**Comment by gaborbernat** [comment]
This why depends was introduced.

https://tox.readthedocs.io/en/latest/config.html#conf-depends
https://github.com/tox-dev/tox/blob/master/tox.ini#L2-L9
https://github.com/tox-dev/tox/blob/master/tox.ini#L81-L97

**Comment by JulienPalard** [comment]
Wah. Thanks @gaborbernat :) I completly missed it.
