### ISSUE TITLE
Allow environment variables to be passed at runtime

### ISSUE THREAD

**Issue by isaiah1112** [tox-dev/tox#1745]
Per the documentation, environment variables can be configured in the `tox.ini` file: https://tox.readthedocs.io/en/latest/example/basic.html#setting-environment-variables

However, it would be nice to be able to pass these to `tox` at runtime similar to something like this:
```
tox -E VAR1 VAL -E VAR2 VAL
```

This way you could override specific environment variables at runtime if desired.

**Comment by gaborbernat** [comment]
Isn't it easier to set it yourself on the call side?

```
env VAR1=VAL tox  
```

**Comment by isaiah1112** [comment]
That didn't appear to work in my testing unfortunately since `tox` is creating a `virtualenv` and the environment variables aren't passed into those virtual environments.

**Comment by gaborbernat** [comment]
That's on purpose if you want to pass on something you must add it to the passenv list.
