### ISSUE TITLE
Wrong encoding in tox env with Py <= 3.6 (NixOS)

### ISSUE THREAD

**Issue by znewman01** [tox-dev/tox#1746]
My Pythons all have the right encoding:

```bash
$ echo $LANG
en_US.UTF-8
$ for python in python2.7 python3.6 python3.7 python3.8; do
>        $python -c 'import locale; import sys; print((sys.version, locale.getpreferredencoding()))'
>  done
('2.7.18 (default, Apr 19 2020, 21:45:35) \n[GCC 9.3.0]', 'UTF-8')
('3.6.12 (default, Aug 15 2020, 06:59:32) \n[GCC 9.3.0]', 'UTF-8')
('3.7.9 (default, Aug 15 2020, 06:36:35) \n[GCC 9.3.0]', 'UTF-8')
('3.8.5 (default, Jul 20 2020, 13:26:22) \n[GCC 9.3.0]', 'UTF-8')
```

But in the Tox environment, they don't ([output with `-rvv`](https://github.com/tox-dev/tox/files/5576245/tox.txt)):

```ini
# tox.ini
[tox]
envlist = py27,py36,py37,py38

[testenv]
commands = python -c "import locale; print(locale.getpreferredencoding())"
```

```bash
$ tox --skip-pkg-install -qq 
('2.7.18 (default, Apr 19 2020, 21:45:35) \n[GCC 9.3.0]', 'ANSI_X3.4-1968')
('3.6.12 (default, Aug 15 2020, 06:59:32) \n[GCC 9.3.0]', 'ANSI_X3.4-1968')
('3.7.9 (default, Aug 15 2020, 06:36:35) \n[GCC 9.3.0]', 'UTF-8')
('3.8.5 (default, Jul 20 2020, 13:26:22) \n[GCC 9.3.0]', 'UTF-8')
```

It turns out that I need the `LOCALE_ARCHIVE` environment variable to fix this:

```bash
$ TOX_TESTENV_PASSENV=LOCALE_ARCHIVE tox --skip-pkg-install -qq
('2.7.18 (default, Apr 19 2020, 21:45:35) \n[GCC 9.3.0]', 'UTF-8')
('3.6.12 (default, Aug 15 2020, 06:59:32) \n[GCC 9.3.0]', 'UTF-8')
('3.7.9 (default, Aug 15 2020, 06:36:35) \n[GCC 9.3.0]', 'UTF-8')
('3.8.5 (default, Jul 20 2020, 13:26:22) \n[GCC 9.3.0]', 'UTF-8')
```

I'm not entirely sure what changed between 3.6 and 3.7, but it seems to have something to do with `nl_langinfo` in the `_locale` module (a wrapper for glibc's `nl_langinfo`).

`LOCALE_ARCHIVE` is [specific to NixOS](https://github.com/NixOS/nixpkgs/blob/273e58ebd9f8ef04948a89d496c7cb23dab8cbe8/pkgs/development/libraries/glibc/nix-locale-archive.patch). However, we do have *other* `passenv` defaults related to locale, and some OS-specific `passenv` defaults.

Would you consider accepting a PR to put `LOCALE_ARCHIVE` in the default `passenv` setting? If so, I can attempt to do this (I think I'd do it for *all* non-Windows OSes, but advice appreciated here). If not, feel free to close but I wanted to file a bug because a Google hit like this would have saved me an hour or two.

**Comment by asottile** [comment]
given that `LOCALE_ARCHIVE` is nonstandard, I don't think this should be passenv'd by default
