### ISSUE TITLE
LD_PRELOAD should be included in the default passenv list

### ISSUE THREAD

**Issue by AllSeeingEyeTolledEweSew** [tox-dev/tox#1747]
Hi,

I think `LD_PRELOAD` should be included in the default `passenv` list. I have a specific use case:

I use an environment which restricts all traffic to run over a socks proxy. Since not all tools support socks, one solution to this problem is tools like [proxychains](https://github.com/haad/proxychains), which uses `LD_PRELOAD` to trap tcp connections and route them over a proxy.

(in particular, I use [tails](https://tails.boum.org) which routes all traffic over a tor socks proxy, and provides [torsocks](https://github.com/dgoulet/torsocks), which works equivalently to proxychains)

In my usage so far, `proxychains tox` works fine, but only if I include `LD_PRELOAD` in passenv by one means or other.

Given `LD_LIBRARY_PATH` was included in the default list as an outcome of #265, this seems like enough motivation that `LD_PRELOAD` also ought to be.

**Comment by asottile** [comment]
>  should be included in the default passenv list. I have a specific use case:

these are conflicting statements -- if you have a special case you should use `passenv` or `TOX_PASSENV`
