### ISSUE TITLE
Non-pip dependency?

### ISSUE THREAD

**Issue by thorlucas** [tox-dev/tox#1759]
I have a dependency (RDKit), that has a more involved installation process and can't just be installed using pip. It requires compilation of a massive C library with specific flags, etc.

Is there a way to just tell tox to ignore that dependency and instead use the currently installed systemwide dependency?

Thanks,

**Comment by gaborbernat** [comment]
> Is there a way to just tell tox to ignore that dependency and instead use the currently installed systemwide dependency?

https://tox.readthedocs.io/en/latest/config.html#conf-sitepackages

**Comment by thorlucas** [comment]
Awesome, thank you!
