### ISSUE TITLE
commands split to multiple lines with error

### ISSUE THREAD

**Issue by heyxingtang** [tox-dev/tox#1765]
Referring to [tox doc](https://tox.readthedocs.io/en/latest/config.html#tox-environment-settings)，command can be split into multi-lines
> Each line is interpreted as one command; however a command can be split over multiple lines by ending the line with the \ character.

my command line are very long and not readable(about 2000 colums), so i try to split it by ending the line with the \ ,  and when command execute, there will add on more space after each line feed, and tox version is 2.7.0

Hope to give me guidance

**Comment by gaborbernat** [comment]
Can you please detail why the extra space is an issue? And please do post an example of this.

**Comment by heyxingtang** [comment]
It seems that I should ask questions in another place.

**Comment by heyxingtang** [comment]
@gaborbernat

**Comment by heyxingtang** [comment]
Sorry, sir, I found why extra space occur, 
in 2.7.0 tox.config._ArgvlistReader.getargvlist
```python
        for line in value.splitlines():
            line = line.rstrip()
            if not line:
                continue
            if line.endswith("\\"):
                current_command += " " + line[:-1]
                continue
            current_command += line
            if is_section_substitution(current_command):
                replaced = reader._replace(current_command, crossonly=True)
                commands.extend(cls.getargvlist(reader, replaced))
            else:
                commands.append(cls.processcommand(reader, current_command))
            current_command = ""
```
when deal with a line end with \, it will add a space. and it still exist on [master branch](https://github.com/tox-dev/tox/blob/69af6cdf168df4e82d6ce0f3d05571bd100418f9/src/tox/config/__init__.py#L1939).
Cloud you post an example to show how to divide a commands line into multiple lines?

**Comment by gaborbernat** [comment]
I think now should be ok with tox 4.
