### ISSUE TITLE
Enable github discussions feature

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox#1786]
Please enable the github discussions feature so we can avoid cluttering the issue tracker with usage questions.

A big number of tickets we receive fell under user/support questions and to add noise to the issue tracker. I personally had a very good experience using it on several popular repositories(2-3k stars). The amount of false reports went down considerably.

Another neat feature is that repository owners can convert existing issues into discussions, mainly is moving them. As you can guess, that is a very nice way to cleanup.

There is no need to send a broad announce, just enable it and see how people are using it or not. An announce can be made after it is confirmed to work fine.

For example a thread for tox4 feedback would be a very good starting point for experimenting it.

**Comment by gaborbernat** [comment]
Resolved via https://github.com/tox-dev/tox/discussions/1787
