### ISSUE TITLE
tox4: dependency constraints treated as normal dependencies

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox#1789]
When submitting a bug make sure you can reproduce it via ``tox -rvv`` and attach the output of that to the bug. Ideally, you should also submit a project that allows easily reproducing the bug. Thanks!
```
deps =
  -r {toxinidir}/docs/requirements.in
  -c {toxinidir}/docs/requirements.txt
```

Using this approach for installing dependencies produces a failure now like below:
```
ERROR: Double requirement given: ansible-base==2.10.4 (from -c /Users/ssbarnea/c/a/ansible-lint/docs/requirements.txt (line 8)) (already in ansible-base (from -r /Users/ssbarnea/c/a/ansible-lint/docs/requirements.in (line 1)), name='ansible-base')
```

Constraints should not be counted as dependencies, so it should not cause conflicts.

That is a real issue because projects made have a centralized pinned list of all dependencies (requirements.txt) while installing subsets of them on various environments.

The example below is not very practical as you could easily just install the requiresments.txt, but my previous paragraph should explain the real-world use-case.

How are we supposed to deal with constraints in tox4?

**Comment by gaborbernat** [comment]
We forward deps as is to pip under a temporary ``requirements.txt``. So the question is why is pip choking on it?

**Comment by gaborbernat** [comment]
I can no longer replicate this with the latest version from the rewrite branch.
