### ISSUE TITLE
tox4: run arbitrary command in a tox environment

### ISSUE THREAD

**Issue by uranusjr** [tox-dev/tox#1790]
Moving the discussion from Discourse: https://discuss.python.org/t/tool-tox-4-on-the-horizon/6537/11?u=uranusjr

Currently tox offers ways to populate an environment without executing `command`. But to make the environment actually useful, the user needs to manually dig into the `.tox` directory themselves. It would be useful to have a tox command like

```
tox exec <env-name> -- command [args ...]
```

to populate an environment and run an arbitrary command on it. It’d be best if there’s a flag to skip the `install_reqs` step as well (i.e. just run the command I provide, don’t do anything else).

**Comment by gaborbernat** [comment]
Seems tox 3 has this as a plugin https://github.com/dstanek/tox-run-command
