### ISSUE TITLE
tox 4: store deps requirement files outside of root

### ISSUE THREAD

**Issue by The-Compiler** [tox-dev/tox#1813]
When running tox 4, it seems to generate requirement files like `requirements-_o484rwn.txt` right in the project directory. While those are cleaned up afterwards, they can still be disruptive as they show up in file trees, as untracked git files, etc.

Wouldn't it make more sense to store them inside `.tox/` or perhaps a system-wide temporary directory instead?

**Comment by gaborbernat** [comment]
> Wouldn't it make more sense to store them inside `.tox/` or perhaps a system-wide temporary directory instead?

Sadly not because paths within a requirements file are relative to the folder in which they reside. So to do this we first have to implement a feature request of rewriting paths within that file to absolute (which is hard to detect), and then validate it does not break transitive requirements files.

**Comment by The-Compiler** [comment]
Sorry for the late answer, this got lost in my inbox for a bit.

That makes sense, but then I think they should be 1) hidden, and 2) clearly identifiable in case e.g. something crashes and the files don't get cleaned up.

In other words, I'd prefer something like `.tox-requirements-_o484rwn.txt`

**Comment by gaborbernat** [comment]
Yeah, I do plan to fix this before public release. At the moment I'm tempted to unroll the first level to CLI arguments... as it was working with tox 3...

**Comment by gaborbernat** [comment]
Resolved by https://github.com/tox-dev/tox/pull/1906
