### ISSUE TITLE
tox 4: Missing console entry point

### ISSUE THREAD

**Issue by The-Compiler** [tox-dev/tox#1814]
After a `pip install --pre tox`, it seems like there's no `tox` console entry point. Is that intended?

**Comment by gaborbernat** [comment]
> However, for now, it’s more important to find things that broke so let’s focus on that. Until it becomes stable the name is tox4 (and similarly works in .tox4 work directory), so you can try it/use it in parallel with tox 3.
Yes, from https://discuss.python.org/t/tool-tox-4a-on-the-horizon/6537.
