### ISSUE TITLE
tox4: colors not showing up in the output for pytest

### ISSUE THREAD

**Issue by nicoddemus** [tox-dev/tox#1818]
Howdy,

When running `tox4 -e py38-xdist` (4.0.0a3) on pytest's repo (https://github.com/pytest-dev/pytest/commit/f6529fd3a14dc99939a372352652b443eaf38962), I don't see the usual colored output:

![image](https://user-images.githubusercontent.com/1085180/104448659-3ba66b80-557c-11eb-91f9-d77bf5e2890e.png)

Compared with tox `3.21.1`:

![image](https://user-images.githubusercontent.com/1085180/104449238-0d755b80-557d-11eb-92ea-10dc8913f3fa.png)

If I set `FORCE_COLOR=1` with `setenv` on my `tox.ini`, then I see colors normally.

**Comment by gaborbernat** [comment]
I'm surprised it works with tox 3, but the underlying issue is a hard one https://github.com/tox-dev/tox/issues/1773, my solution within tox itself for now is https://github.com/tox-dev/tox/blob/rewrite/tox.ini#L29.

**Comment by gaborbernat** [comment]
If you have any experience with tty/openpty/termios help/suggestion would be much appreciated.

**Comment by nicoddemus** [comment]
> I'm surprised it works with tox 3

That makes two of us. It was a bit surprising that it just works like that, but thought I would mention in case this was an unknown issue, but glad it has been mapped out already. 👍 

> If you have any experience with tty/openpty/termios help/suggestion would be much appreciated.

Not much I'm afraid. 😕

**Comment by gaborbernat** [comment]
By the way what shell and terminal you're using there?

**Comment by nicoddemus** [comment]
I'm using [cmder](https://cmder.net).

**Comment by gaborbernat** [comment]
Does that use ps or cmd.bat as the shell?

**Comment by nicoddemus** [comment]
It's configurable, but I'm using `cmd`. 👍
