### ISSUE TITLE
tox4: not all extras are evaluated

### ISSUE THREAD

**Issue by jugmac00** [tox-dev/tox#1868]
I have a tox ini with a `testenv` incl `extras = test` and a `testenv:coverage` incl. `extras=test, coverage`.

The coverage env fails with `pytest-cov` missing - only in `tox4`.

# reproduce

```
git clone git@github.com:morepath/more.cerberus.git

cd more.cerburus

tox4 -r
```

This only happens when running all envs - the error does not show when running `coverage` in isolation.

Tested both with current tox pre and tox head.

```
coverage: remove tox env folder /home/jugmac00/Projects/more.cerberus/.tox/4/coverage
coverage: install_package_deps> .tox/4/coverage/bin/python -I -m pip install 'setuptools>=40.8.0' wheel 'cerberus<2.0.0,>=1.3.2' 'morepath>=0.19' 'pytest>=2.9.1' pytest-remove-stale-bytecode webtest
coverage: install_package> .tox/4/coverage/bin/python -I -m pip install --no-deps --force-reinstall --no-build-isolation -e /home/jugmac00/Projects/more.cerberus
coverage: commands[0]> pytest --cov --cov-fail-under=100
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --cov --cov-fail-under=100
  inifile: /home/jugmac00/Projects/more.cerberus/setup.cfg
  rootdir: /home/jugmac00/Projects/more.cerberus

coverage: exit 4 (0.20 seconds) /home/jugmac00/Projects/more.cerberus> pytest --cov --cov-fail-under=100
.pkg: _exit> python /home/jugmac00/opt/tox4/lib/python3.8/site-packages/tox/util/pep517/backend.py True setuptools.build_meta __legacy__
coverage: FAIL ✖ in 4.42 seconds
```

**Comment by gaborbernat** [comment]
Can you please always publish the output with ``tox -v -v`` when reporting bugs? Thanks!

**Comment by gaborbernat** [comment]
This has been released part of https://tox.readthedocs.io/en/rewrite/changelog.html#v4-0-0a5-2021-01-23, please check it and report back if the issue still persists. Thanks for your feedback, it really helps!

![thanks](https://media.tenor.co/images/50a3949444d36feb211094d789694885/tenor.gif)

**Comment by jugmac00** [comment]
Works like a charm!

Thanks for all your work.

P.S.: I am running out of problems :-)
