### ISSUE TITLE
tox fails to correctly detect plugins versions: MissingDependency with editable installs

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox#1871]
```
$ tox --version                                                                                                                 [13:23:00]
3.21.1 imported from /Users/ssbarnea/.pyenv/versions/3.9.0/lib/python3.9/site-packages/tox/__init__.py
registered plugins:
    tox-ansible-1.0.3.dev1 at /Users/ssbarnea/c/a/tox-ansible/src/tox_ansible/hooks.py
```
When running you can see something like:
```
$ tox -va
using tox.ini: /Users/ssbarnea/c/a/ansible-role-collect-logs/tox.ini (pid 19564)
could not satisfy requires MissingDependency(<Requirement('tox-ansible>=1.0.3')>)
```
The side effect of this is that tox will install and use its own copy of tox-ansible instead of using the already available version that is newer than the requirement.

As I am plugin developer I often install plugins from source as editable. 

Initially I believed that there was something wrong on how this plugin was packaged or a bug in setuptools-scm but I based on few tests I am starting to believe that may not be the case:

```
$ python
Python 3.9.0 (default, Oct 10 2020, 09:43:04)
>>> from importlib.metadata import version
>>> version("tox_ansible")
'1.0.3.dev1'
>>> from importlib.metadata import version
>>> version("tox_ansible") > "1.0.3"
True
>>> version("tox_ansible") > "1.0.4"
False
```

That proves that the reported version is correct and that is newer than 1.0.3, which is listed inside requires. 

On the other hand, I also observed another weird thing: reinstalling tox-ansible as editable with `pip install -e .` does uninstall '1.0.3.dev1' and replaces it with '1.0.4.dev1' -- and after this happens, tox no longer complains about outdated version.

Clearly [setuptools-scm fails to updated the version after a tag was created](https://github.com/pypa/setuptools_scm/issues/518), but at the same time importlib is very clear that `1.0.3.dev1` is considered newer than `1.0.3`, something tox does not seem to agree about.

**Comment by asottile** [comment]
> but at the same time importlib is very clear that 1.0.3.dev1 is considered newer than 1.0.3, something tox does not seem to agree about.

nah your comparisons are invalid, you're comparing strings when you should be comparing versions:

```python
>>> from packaging.version import Version
>>> Version('1.3.0dev1') >= Version('1.3.0')
False
```
