### ISSUE TITLE
Build C Extensions during installation.

### ISSUE THREAD

**Issue by kumaraditya303** [tox-dev/tox#1896]
Currently `tox` install the project as per https://tox.readthedocs.io/en/latest/config.html?highlight=install#conf-install_command 
`python -m pip install {opts} {packages}` which does not copies the extensions to their place like with `pip install -e.`.
Because of this it is manually required to do something like `pip install -e.`.

### Proposed Solution
`tox` should install by project with editable mode by default or run `build_ext --inplace` command.

**Comment by gaborbernat** [comment]
You can use https://tox.readthedocs.io/en/latest/config.html#conf-usedevelop to make this the default.

Note your users will not be installing the package via -e, so you're likely don't want to do this though.
