### ISSUE TITLE
tox requires not exposed in the config object

### ISSUE THREAD

**Issue by hroncok** [tox-dev/tox#1918]
I cannot find tox [requires](https://tox.readthedocs.io/en/latest/config.html#conf-requires) on the config object. The minversion is there, but the requires are not. They appear to be parsed, used and forgotten.

https://github.com/tox-dev/tox/blob/555f3f13b18da1470b6518be654e3e4e2fdec654/src/tox/config/__init__.py#L1297-L1302

I'd like to be able to [read them from a plugin](https://github.com/fedora-python/tox-current-env/issues/39).

I can send a PR, if this would be accepted.

**Comment by gaborbernat** [comment]
Sure 👍🏻

**Comment by hroncok** [comment]
Side note: It seems that this expects the value to be there:
https://github.com/tox-dev/tox/blob/555f3f13b18da1470b6518be654e3e4e2fdec654/src/tox/exception.py#L98-L99
