### ISSUE TITLE
Passing PKG_CONFIG_PATH env var by default

### ISSUE THREAD

**Issue by naveen521kk** [tox-dev/tox#1931]
I was trying to set up tox for a C extension and noticed that the `PKG_CONFIG_PATH` variable isn't passed by default. [`pkg-config`](https://www.freedesktop.org/wiki/Software/pkg-config/) is a tool used by many C extensions to find dependencies that are not located in the default install locations(especially in windows), and `PKG_CONFIG_PATH` env var will specify that.

**Comment by gaborbernat** [comment]
Considering that c-extensions are the minority I'd say you should explicitly pass this via ``passenv``.
