### ISSUE TITLE
[FR] `--result-json` does not work with `-av`

### ISSUE THREAD

**Issue by webknjaz** [tox-dev/tox#1966]
So I wanted to programmatically extract the list of envs and since `--result-json` works for the test results I sorta expected this to work for other flags too.

I'm not sure whether to file this as a bug or a feature request but it's probably worth having some discussion/official response on this.

**Comment by gaborbernat** [comment]
The official way of getting this feeding ``tox --showconfig`` to a config parser.

**Comment by webknjaz** [comment]
Ah, I didn't know about that option! Thanks! For my case, though, it was enough to just do `tox -a` and `str.splitlines()` it...

**Comment by gaborbernat** [comment]
Sometimes you want the basepython/other keys for each tox environment 👍🏻 In those cases you need the ``--showconfig``.
