### ISSUE TITLE
Run commands before extras/package installation

### ISSUE THREAD

**Issue by yannikschaelte** [tox-dev/tox#1969]
Is there a way of executing commands prior to package/extras installation?

Reason: Some dependencies may require the installation of further dependencies before pip installing them. For this, being able to define commands to run before that would be good. "commands_pre" does not seem to do that, as far as I see.

**Comment by yannikschaelte** [comment]
Thanks @gaborbernat , totally makes sense. I missed the "prior to" in the deps documentation. install_requires would indeed be preferable, here just not directly applicable as it concerns an optional dependency which must be set up more properly.

**Comment by ssbarnea** [comment]
@gaborbernat I am inclined to say that the issue is still valid. For example I want to run a command before installing dependencies, to check if system packages were installed, system packages that in case of missing would prevent installation of the dependencies.

**Comment by thenewguy** [comment]
@gaborbernat I've just encountered this in a project upgrading tox from an older version.  The project is spread over many apps and uses a templated constraint file from a remote source to sync installed versions. There doesn't seem to be any way to generate the templated constraint file in the newer versions of Tox. In the older versions of tox it was possible to do it within `install_command` but now tox fails while inspecting the deps. Do you have any suggestions for where to insert the command that fetches the constraint file? Thanks!

**Comment by gaborbernat** [comment]
Keep using old version or write a plugin to achieve that. Core no longer supports that use case.
