### ISSUE TITLE
tox4: suggested towncrier file "something.trivial" is not permitted by `pre-commit` check

### ISSUE THREAD

**Issue by jugmac00** [tox-dev/tox#2007]
I tried to use  a towncrier file as suggested in the docs a la "something.trivial" but this was not permitted by `pre-commit` :-D

```
changelog filenames......................................................Failed
- hook id: changelogs-rst
- exit code: 1

changelog files must be named ####.(feature|bugfix|doc|removal|misc).rst

docs/changelog/minor.doc.improvements.trival
```

_Originally posted by @jugmac00 in https://github.com/tox-dev/tox/issues/2006#issuecomment-815922714_

**Comment by gaborbernat** [comment]
We need to update the documentation to follow that pre-commit rule.

**Comment by jugmac00** [comment]
So, do we want a failing CI when somebody creates a typofix PR? Or rather update the pre-commit rule to allow `something.trivial` files again?

**Comment by gaborbernat** [comment]
typofix PRs are misc if outside of documentation 👍🏻 and within just doc

**Comment by jugmac00** [comment]
Hm, I wonder why this was not autoclosed by #2010... any way, it's done.
