### ISSUE TITLE
tox does not rebuild when changes are made to [options.extras_require]

### ISSUE THREAD

**Issue by tdamsma** [tox-dev/tox#2008]
After trying out tox following recommended best practices from pyscaffold, this issue bit me: https://github.com/pyscaffold/pyscaffold/issues/438
I added a package to the `[options.extras_require]` section in my `setup.cfg`, and only after running tox with the -r option it was actiually installed. 

This cost me way too long to figure that out, so if this is expected behaviour perhaps it can be documented more explicitly? From the logs it seemed like tox had actually rebuilt and installed my app, but apparently is was using a cached version. 

Would be even better if the cache is busted based on changes in the `setup.cfg`, would that be a possibility?

**Comment by gaborbernat** [comment]
This has been fixed on the rewrite branch, to be released as tox 4. There are no plans to backport the fix as of today.

**Comment by tdamsma** [comment]
Great that this is already on the radar, woll wait for tox 4. Thanks!

**Comment by jugmac00** [comment]
@tdamsma You can and probably should at least try tox4 already today, especially as it solves your problem right now.

I run both the [pre-release](https://pypi.org/project/tox/4.0.0a6/) and current head from master at work and for my personal projects successfully already for some time.

Certainly there are still [open issues](https://github.com/tox-dev/tox/milestone/7) but maybe you are not affected by them, or maybe you can report another problem so it will be fixed once tox4 will be finally released.

I bet you know, but just in case you don't, you can install a pre-release via `pip install --pre tox`.

I recently did a [lightning talk](https://youtu.be/d3rDDDjKu1M?t=1830) about how I tested the tox4 pre-release against the almost 300 Zope projects.

**Comment by gaborbernat** [comment]
With https://github.com/tox-dev/tox/pull/2009, we're now taking the next step and things will also be picked up if you change the contents of your requirements/constraint files. Generally, the expectation is that 99% of the time tox should be able to figure out when you've changed your dependencies and make sure they are used.
