### ISSUE TITLE
tox4: Mark files that have to be compatible with Python 2

### ISSUE THREAD

**Issue by eumiro** [tox-dev/tox#2013]
Some files have to be kept compatible with Python 2.

To prevent premature modernization of code to Python 3.6+, mark these files as Python 2 compatible. Non-marked files are supposed to follow the current compatibility listed in `setup.cfg` (currently Python 3.6–3.9).

**Comment by gaborbernat** [comment]
The files in question are already marked in our pre-commit config https://github.com/tox-dev/tox/blob/rewrite/.pre-commit-config.yaml#L20-L21

**Comment by eumiro** [comment]
Fixed by #2015
