### ISSUE TITLE
tox4: Bugs in the validation of --hash argument

### ISSUE THREAD

**Issue by eumiro** [tox-dev/tox#2018]
The regular expression that checks the content of the `--hash` command line argument:

https://github.com/tox-dev/tox/blob/rewrite/src/tox/tox_env/python/pip/req/args.py#L52

```
_HASH = re.compile(r"sha(256:[a-z0-9]{64}|384:[a-z0-9]{96}|521:[a-z0-9]{128})")
```

does not accept `sha512:` as prefix but accepts non-hexadecimal characters beyond `a-f`. This should be fixed with a help of appropriate tests.

**Comment by jugmac00** [comment]
I just got pinged that the second problem reported in this issue hasn't been fixed yet.

todos:
- [ ] do not allow letters beyond a-f
- [ ] add test(s)

**Comment by eumiro** [comment]
Done.
