### ISSUE TITLE
threading.Thread.setDaemon has been deprecated in favor of setting daemon attribute directly in Python 3.10

### ISSUE THREAD

**Issue by tirkarthi** [tox-dev/tox#2032]
Ref : python/cpython#25174

https://github.com/tox-dev/tox/blob/7aa130318d168ccc476d856ff7b1531bdaf263cc/src/tox/util/spinner.py#L87

**Comment by jugmac00** [comment]
Thank you for the notice.

@tirkarthi, do you want to create a pull request?

**Comment by tirkarthi** [comment]
Sure, created https://github.com/tox-dev/tox/pull/2033 . Since this was a simple change I was not sure if this needs a news entry. Please let me know if one is needed.

**Comment by jugmac00** [comment]
Thank you! As this is no user-facing change, a changelog entry is not necessary.

If you want, you can add yourself to the list of contributors:
https://github.com/tox-dev/tox/blob/master/CONTRIBUTORS

**Comment by tirkarthi** [comment]
Thanks, added myself.

**Comment by jugmac00** [comment]
fixed by #2033
