### ISSUE TITLE
setupdir should be checked for bad directories

### ISSUE THREAD

**Issue by stefansjs** [tox-dev/tox#2048]
Describe what improvement you want and how would this be used. Thanks!
I just made the mistake of using 

```ini
setupdir = {toxinidir}/..
```

which deleted not only my entire source tree, but my .git directory as well. It seems like this value is typically inside the tox directory. It should at the very least be made clear in the documentation that changing setupdir will delete some other directory. IMHO it would be ideal to generate at least a warning that the directory is outside the .tox directory, and at most actually generate an error if it contains sources and/or the toxinidir

**Comment by stefansjs** [comment]
distdir is similarly dangerous. With bugs in my tox.ini I keep managing to delete whole source directories. Is there a workaround for deleting code outside the .tox directory?

**Comment by gaborbernat** [comment]
I'd be interested to know why do you feel you need to change any of these? Any reason the defaults are not good enough?

**Comment by stefansjs** [comment]
We're using tox as part of a larger build process that builds several things (in several environments). The idea is to build wheels with tox and take the output and put it into a single shared directory where those wheels can be consumed from.

If there's a better alternative for copying output files I'd love to hear it. So far the limitations that I've hit include (1) tox doesn't allow glob patterns in commands (hence cp *.whl wheelhouse/ isn't possible), (2) I don't find a way to ask tox for its output filename (hence cp {toxartifactname} wheelshouse/ isn't possible either), (3) this distdir gets deleted every invocation, (4) distshare is deprecated (? the documentation provides no explanation or alternative). I've been at it for a couple days and still have no clear idea of how to consume the wheel files produced by tox (which gets more difficult every time tox deletes my tox.ini file and I have to start from scratch again).

It seems like tox _expects_ distdir to be inside .tox, but doesn't fail/warn when it isn't

**Comment by gaborbernat** [comment]
I don't think it expects to be there, but it does clean it out before building; and yes it is deprecated. tox currently doesn't build wheels, not natively at least. Can you post some example configurations you find it's not working? Would give a better idea what you're trying to do. You shouldn't use cp to copy things, that would not be cross-platform compatible.

**Comment by stefansjs** [comment]
Yes, I'm using tox-wheel to build wheels.

```ini
[tox]
minversion = 2.32.0
requires =
    tox-wheel
    tox-pyenv
envlist = py36,py37,py38,py39
# distdir = {env:WHEELS_DIR}  <-- This feels dangerous. I'm probably misunderstanding

[testenv]
wheel = true
wheel_build_env = {envname}-build_env
deps =
    -r {toxinidir}/python/requirements.txt
    -r {toxinidir}/python/tests/requirements.txt
changedir = python
commands = python unit_tests.py
# cp {distdir}/*.whl {env:WHEELS_DIR}/  <-- This also doesn't work because tox doesn't run a shell on the glob pattern


# Create an isolated build env to build wheels for each test environment
[testenv:{py36,py37,py38,py39}-build_env]
deps = -r {toxinidir}/python/build-requirements.txt
```

The idea is that I build a set of wheels for different environments (and eventually run this tox in different containers) to produce multiple wheels, and test those wheels in a set of test environments. Building wheels does differ in that I can produce built packages for different interpreter versions.

I guess the assumed tox workflow is to just rerun setup.py after running tox to get the dist artifacts? But it would still be nice to either (1) get the built package file path (so that I can consume it how I want) or (2) provide a destination where built artifacts should be placed.

Tox does such a great job of automating environments creation and installing what I need to build/test. I'm just looking for the easiest way to consume the built package afterwards.

**Comment by gaborbernat** [comment]
In this case, I'd keep the wheels as they are by default inside `.tox/dist`. Then you can do a copy after your test suite runs to where you want. You should do this via a small python script. Python has glob support and is cross-platform (see https://docs.python.org/3/library/shutil.html#shutil.copytree, etc).

**Comment by stefansjs** [comment]
Ok, so here's my workaround
```ini
whitelist_externals = sh
commands =
    python unit_tests.py
    sh -c 'cp {distdir}/*.whl {posargs}/'
```
I know it's not as portable as `python -c 'import shutil, glob;list(map(lambda f: shutil.copy(f, "{posargs}/"), glob.glob("{distdir}/*.whl")))'`, but it's way more concise, and I don't need to support windows (more likely to work as I expect)

I do still think that if you're going to delete an entire directory, you should at least warn users that it's about to happen. Your comment makes me think these are internal details that I don't really need to control. So why do I have the ability to change it? It really does seem like if you don't expect me to change it, and I'm left with "do this at your own risk" I should get a lot more information about how risky it is, both in the documentation and from the tool itself

**Comment by gaborbernat** [comment]
> I do still think that if you're going to delete an entire directory, you should at least warn users that it's about to happen. Your

I mean the tool is just doing what you explicitly asking what to do. If you misconfigure the tool you'll shoot yourself in the foot.

> So why do I have the ability to change it?

Some users who are more careful with their changes and understand better what they are doing can take advantage of it to configure more advanced workflows.
