### ISSUE TITLE
Setting prompt for virtual environments

### ISSUE THREAD

**Issue by qudade** [tox-dev/tox#2055]
When creating virtual environments with `venv` you can set the prompt to something else.

E.g.

```
python3 -m venv --prompt foo .venv
```

will create the virtual environment in directory `.venv` and the prompt will show someting like `(foo) >` instead of `(.venv) >`.

Is it possible to achieve the same when creating a virtual environment with `tox`?

If not, would you consider this as a feature for the future? (support for virtual environments with newer Python (3.6+) versions would be sufficient I think)

**Comment by gaborbernat** [comment]
You can set the `VIRTUALENV_PROMPT` env-var within a tox environment with the value you'd like. Perhaps this should default to the current tox environment.
