### ISSUE TITLE
Commits from 4 March onwards missing from master branch

### ISSUE THREAD

**Issue by domdfcoding** [tox-dev/tox#2058]
Looking at the master branch the latest commit is now 32e74a804635ba790deef706b57c10f8219de1db from 3rd March, which can't be right as there's been activity since then.

I can see the commits I'm expecting in a fork (https://github.com/ssbarnea/tox/commits/master), and the commits still seem to exist here, just not linked to the branch (e.g. https://github.com/tox-dev/tox/commit/6eacc86ddd13c63b48efdd03c3ca1e5c2d7bb8b1)

At the bottom of https://github.com/tox-dev/tox/pull/2031 it says:

```
gaborbernat force-pushed the tox-dev:master branch from 6eacc86 to 32e74a8 12 hours ago
```

so I'm guessing that's the cause. @gaborbernat I assume you didn't mean to do that?

**Comment by gaborbernat** [comment]
Fixed 👍
