### ISSUE TITLE
Allow to specify site packages

### ISSUE THREAD

**Issue by ynikitenko** [tox-dev/tox#2059]
### What
In the configuration there is an option

>  sitepackages=false(true|false)
> 
>    Set to true if you want to create virtual environments that also have access to globally installed packages.

I'd like to allow some packages to be searched globally, but not all of them.

### Why
Not all packages can be installed with `pip`. I have a package `ROOT`, which I build myself from source code, and which has Python bindings (`import ROOT` works fine). However, I'd like all other packages to be installed by `tox` (because they are available in `PyPI`).

**Comment by gaborbernat** [comment]
You can use/set PYTHONPATH via setenv to achieve this.

**Comment by ynikitenko** [comment]
You are right, thanks. I did that, and I also commented the string `sitepackages = true` in `tox.ini`, because otherwise it took `pytest` from system, not from `deps`.
You can add this to the documentation about `sitepackages`.

**Comment by ynikitenko** [comment]
Thanks for the suggestion.
No, I don't want to due to two reasons: 1) I'm not an expert in tox and not sure what wording its developers would prefer 2) I didn't download its whole code, so it would be easier for a person who already cloned the repo.
