### ISSUE TITLE
Missing changelogs and GitHub releases

### ISSUE THREAD

**Issue by The-Compiler** [tox-dev/tox#2060]
The newest release [on PyPI](https://pypi.org/project/tox/#history) is 3.23.1. However, the [changelog](https://github.com/tox-dev/tox/blob/master/docs/changelog.rst) stops at 3.22.0, and the latest ["proper" release according to GitHub](https://github.com/tox-dev/tox/releases?after=3.14.3) is 3.13.2:

![image](https://user-images.githubusercontent.com/625793/117649277-a153de80-b18f-11eb-9dd7-214a73ca3ab1.png)

**Comment by gaborbernat** [comment]
We don't do github releases. Fixed the changelog.

**Comment by The-Compiler** [comment]
> We don't do github releases.

You did for 3.13.2, and apparently did for 3.23.1 again :wink: If you don't intend to do them for future releases, maybe remove all GitHub releases, so that the GitHub repo page doesn't show a wrong latest release?

> Fixed the changelog.

Thanks. It looks like there's a missing heading:

```
v3.23.1 (2021-05-05)
Bugfixes
^^^^^^^^
```

[resulting in](https://github.com/tox-dev/tox/blob/master/docs/changelog.rst):

> v3.23.1 (2021-05-05) Bugfixes ^^^^^^^^

I'd be happy to submit a PR to fix it, but I assume there's some automation involved which didn't do the right thing?

**Comment by jugmac00** [comment]
We are using https://pypi.org/project/towncrier/ - but as the changelog entries are already merged, I think there is no other way than to manually fix the changelog. I'd say - PR welcome :-)
