### ISSUE TITLE
allow plugin to influence "special" environments like .package

### ISSUE THREAD

**Issue by freddrake** [tox-dev/tox#2064]
I'm attempting to write a plugin that can help manage the "basepython" settings used in my organization, since these are consistent and never what's found on $PATH.

Unfortunately, I'm finding that I can't affect the Python used for .package without including something like this in ``[testenv]``:

~~~~~~ ini
basepython =
    .package: /opt/cleanpython39/bin/python3
~~~~~~

This doesn't have to refer to .package; it can even name an environment that doesn't exist:

~~~~~~ ini
basepython =
    dontuse: /opt/cleanpython39/bin/python3
~~~~~~

Not including at least a basepython like this causes the Python interpreter running tox to be used, and that appears to be filled in by default.  (I'm trying to honor configured basepython values to avoid surprises.)

I've been trying to accomplish this using the ``tox_configure`` and ``tox_get_python_executable`` hooks.  I'm using tox 3.14.3 for now.

Is there a supported way to configure the basepython for special environments?

**Comment by freddrake** [comment]
Further experimentation suggests that even

~~~~~~ ini
basepython =
~~~~~~

is sufficient to avoid getting the Python running tox being populated as the basepython attribute of the TestenvConfig objects.

It's a little surprising the `tox_get_python_executable` hook can be called before the `tox_configure` hook.

**Comment by gaborbernat** [comment]
I can't understand your description. You're saying you're trying to do this via a plugin but then you show examples of the tox.ini :thinking: Are you trying to do this via the ``tox.ini`` file or via plugin then?

**Comment by freddrake** [comment]
Fair enough.  I'm wanting to convert a mass of basepython settings from configuration to something computed by a plugin.

The original configuration includes this:

~~~~~~ ini
[tox-keepertech]
basepython = /opt/kt-python38/bin/python3

[testenv]
basepython =
    .package: {[tox-keepertech]basepython}
    coverage: {[tox-keepertech]basepython}
    dists: {[tox-keepertech]basepython}
    docs: {[tox-keepertech]basepython}
    isort: {[tox-keepertech]basepython}
    py37: /opt/kt-python37/bin/python3
    py38: /opt/kt-python38/bin/python3
    py39: /opt/kt-python39/bin/python3
    py310: /opt/kt-python310/bin/python3
~~~~~~

This works just fine without any plugin.  But with several packages carrying similar piles of basepython settings, this is a pain,
and makes things hard to read (though it is explicit).

I would like to remove all of these basepython settings except the [tox-keepertech] section, which is specific to my organization.

Using the attached tox_keepertech.py I get very different behaviors depending on whether my tox.ini includes any basepython setting for any factor.

With no basepython setting at all, running **tox -eisort-check** generates:

~~~~~~ text
- tox_configure
  .package: '/home/fdrake/tools/tox-new/bin/python3' {'.package'}
  py38: 'python3.8' {'py38'}
  py39: 'python3.9' {'py39'}
  coverage-report: '/home/fdrake/tools/tox-new/bin/python3' {'report', 'coverage'}
  isort-check: '/home/fdrake/tools/tox-new/bin/python3' {'isort', 'check'}

  isolated build: .package
  [testenv:.package] basepython already configured.
.package create: /home/fdrake/p/fa/kt.insight.service/.tox/.package
- tox_get_python_executable .package
  [testenv:.package] basepython from tox.ini: /home/fdrake/tools/tox-new/bin/python3
.package installdeps: setuptools, wheel
isort-check create: /home/fdrake/p/fa/kt.insight.service/.tox/isort
- tox_get_python_executable isort-check
  [testenv:isort-check] basepython from tox.ini: /home/fdrake/tools/tox-new/bin/python3
isort-check installdeps: isort
isort-check inst: /home/fdrake/p/fa/kt.insight.service/.tox/.tmp/package/1/kt.insight.service-1.4.65.tar.gz
isort-check installed: ...removed...
isort-check run-test-pre: PYTHONHASHSEED='1966115401'
isort-check run-test: commands[0] | python -m isort --check-only kt tests
_______________________________________________________ summary _______________________________________________________
  isort-check: commands succeeded
  congratulations :)
~~~~~~

Notably, when `tox_configure` is invoked, the basepython settings have already been computed.

When setting basepython to an empty string or using a factor name that's not referenced, like the "dontuse" example from my initial report, I see very different behavior for the same **tox -qisort-check** command:

~~~~~~ text
- tox_get_python_executable py38
- tox_get_python_executable py39
  [testenv:py39] basepython = '/opt/kt-python39/bin/python3'
  # based on factor py39
  [testenv:py38] basepython = '/opt/kt-python38/bin/python3'
  # based on factor py38
- tox_configure
  .package: '' {'.package'}
  py38: '' {'py38'}
  py39: '' {'py39'}
  coverage-report: '' {'report', 'coverage'}
  isort-check: '' {'check', 'isort'}

  isolated build: .package
  [testenv:.package] basepython = '/opt/kt-python38/bin/python3'
  # configured default
- tox_get_python_executable .package
  [testenv:{envname}] basepython configured by us.
- tox_get_python_executable isort-check
  [testenv:isort-check] basepython = '/opt/kt-python38/bin/python3'
  # configured default
isort-check inst-nodeps: /home/fdrake/p/fa/kt.insight.service/.tox/.tmp/package/1/kt.insight.service-1.4.65.tar.gz
isort-check installed: ...removed...
isort-check run-test-pre: PYTHONHASHSEED='716385095'
isort-check run-test: commands[0] | python -m isort --check-only kt tests
_______________________________________________________ summary _______________________________________________________
  isort-check: commands succeeded
  congratulations :)
~~~~~~

The plugin is getting invoked for the .package environment, but I essentially have to configure *something* for basepython to avoid the defaults for that; even the `tox_configure` hook isn't called early enough to populate the settings based on there being no configuration, because something in tox is providing values.

This archive contains a sample tox.ini and the tox_keepertech.py plugin:
[sample.zip](https://github.com/tox-dev/tox/files/6510289/sample.zip)

**Comment by freddrake** [comment]
Should I take the silence to mean my explanation remains confusing, or just that you're busy?

**Comment by gaborbernat** [comment]
Always the later 😊 that being said looking through the code I don't think this is possible, because https://github.com/tox-dev/tox/blob/master/src/tox/config/__init__.py#L633 is a method scope within a function, and as such inaccessible/not override-able. I'd recommend for you to wait for tox 4, which would offer you a better solution for achieving this... (see rewrite branch).

**Comment by freddrake** [comment]
Thanks, Bernát!  That pointer helped.

I'll definitely look for a better way to do this in tox 4, but my naturally devious side pushed through to make it work under tox 3.

This updated archive includes the tox_keepertech.py I came up with, if you're curious about how it worked out:
[sample.zip](https://github.com/tox-dev/tox/files/6547826/sample.zip)
