### ISSUE TITLE
--devenv fails because root .tox environment is provisioned in identical envdir

### ISSUE THREAD

**Issue by isaac-ped** [tox-dev/tox#2065]
Attempting to create a development environment with `--devenv` causes  fatal errors if the root tox environment needs to be provisioned

This minimal setup reproduces the issue (as long as that version of setuptools is not already installed on the host)
```ini
[tox]
requires =
    setuptools==56.2.0
```
with a very minimal setup.py:
```python
from setuptools import setup   
                               
setup(                         
    name="noop",               
    packages=[]                
)
```

Running:
`tox -rvv --devenv venv`

Tox provisions its root environemnt in `venv`:
```
.tox start: getenv /sandbox/tox-debug/venv
.tox cannot reuse: -r flag
.tox create: /sandbox/tox-debug/venv
```
and then later tries to remove it to create the devenv:
```
py recreate: /sandbox/tox-debug/venv
  removing /sandbox/tox-debug/venv
```

Seems related to https://github.com/tox-dev/tox/issues/1501, though that issue seems to be less general 

```shell
$ tox --version
3.23.1 imported from /u1/ipedisich/.local/lib/python3.6/site-packages/tox/__init__.py
```
(also reproduced with python3.7)
[Full output of `tox -rvvv`](https://github.com/tox-dev/tox/files/6517600/tox-error.txt)

**Comment by gaborbernat** [comment]
Released via https://pypi.org/project/tox/3.24.0/
