### ISSUE TITLE
tox -p suppresses color output

### ISSUE THREAD

**Issue by pbelskiy** [tox-dev/tox#2070]
Hello! 

Is it possible to print colorful error output when running tox in parallel? Same tox behavior on my previous and current version (3.23.1)

**Comment by jugmac00** [comment]
Hi @pbelskiy, I do not understand - I am on `tox` 3.23.1 and I see the failed runs in red color.

![Screenshot from 2021-05-26 14-02-41](https://user-images.githubusercontent.com/9895620/119656581-247d6180-be2b-11eb-80be-50b023ec2e9d.png)

Could you please tell us in which version of `tox` you have problems and in which you had no problems?

Could you also please provide screenshots?

Thank you!

**Comment by jugmac00** [comment]
Thanks for clarifying!

## single env
![Screenshot from 2021-05-27 11-44-01](https://user-images.githubusercontent.com/9895620/119804909-138f2780-bee1-11eb-9a94-129d1235b24a.png)

# parallel mode
![Screenshot from 2021-05-27 11-45-10](https://user-images.githubusercontent.com/9895620/119804917-1558eb00-bee1-11eb-980e-3381b64a9b15.png)

Interestingly, on the `tox-rewrite` branch for the upcoming `tox4`, there is no color by default for single envs...
![Screenshot from 2021-05-27 11-53-26](https://user-images.githubusercontent.com/9895620/119806186-40900a00-bee2-11eb-8d24-898a8a349d58.png)

And in parallel there are no tracebacks shown at all!

![Screenshot from 2021-05-27 11-54-54](https://user-images.githubusercontent.com/9895620/119806355-6ae1c780-bee2-11eb-819b-168b5b797f9f.png)
