### ISSUE TITLE
IRC channel in docs

### ISSUE THREAD

**Issue by The-Compiler** [tox-dev/tox#2079]
The docs for tox [currently state](https://tox.readthedocs.io/en/latest/support.html) this as a possible contact channel:

> - hang out on the irc.freenode.net #pylib channel

I suppose this is because when Holger Krekel started tox, he was already using the channel for pylib/pytest, so it made it easier for him to have everything in one place.

However, it looks like nobody from the current tox maintainers is actually there. There are tox questions popping up from time to time (though mostly it's about pytest).

Given what [happened to Freenode](https://lwn.net/SubscriberLink/857140/dc452f02b823fd14/), pytest is now moving over to a new #pytest channel on irc.libera.chat: https://github.com/pytest-dev/pytest/pull/8722

@flub and I are the group contacts for both #pylib and #pytest on Libera, so the remaining question is what should happen to the #pylib channel on Libera (the one on Freenode was never registered, so it's anarchy there :laughing:). Personally I'd like for it to redirect to #pytest (since pylib usage outside of pytest is pretty much non-existent nowadays), but that would then mean that tox would probably need to find a new home.

What do you think?

**Comment by gaborbernat** [comment]
Fixed via https://github.com/tox-dev/tox/blob/master/docs/support.rst
