### ISSUE TITLE
Misaligned pypy3.* binaries on MacOS

### ISSUE THREAD

**Issue by Themanwithoutaplan** [tox-dev/tox#2080]
While I have pypy3 in my standard tox.ini, I don't run it a lot and didn't notice it was no longer working. I use MacPorts to manage my local Pythons and Pypy3 has been deprecated in favour of pypy36 and pypy37. The binaries for these are both without decimal points which means that tox doesn't find them. I'm looking for the best way to fix this. My hotfix was to redefine the basepython in the testenv but that could cause problems on other systems. Alternatively, I could add symlinks with decimals, but that won't help anyone else on MacOS.

Suggestions? Should I take this up with the MacPorts maintainers?

**Comment by asottile** [comment]
yeah I believe this is a macports problem, pypy themselves name the binaries as `pypy3.7`:

```
$ ls ~/opt/pypy3.7-v7.3.3-linux64/bin/
libpypy3-c.so  libpypy3-c.so.debug  pypy  pypy3  pypy3.7  pypy3.debug
```

**Comment by gaborbernat** [comment]
Closing per above.
