### ISSUE TITLE
Include `HOME` in the default passenv on POSIX systems

### ISSUE THREAD

**Issue by JustAnotherArchivist** [tox-dev/tox#2083]
The `HOME` environment variable should always be present per the POSIX specification, but tox doesn't include it in the default passenv. This means that e.g. code using `os.environ['HOME']`, which would always work fine otherwise on a POSIX-compliant operating system, crashes with a `KeyError` when run inside tox. For a real-world example, see [this Travis CI build](https://travis-ci.com/github/jjjake/internetarchive/builds/224924797) from <https://github.com/jjjake/internetarchive/pull/405>.

I suppose there's an argument to not pass the real `HOME` as that may cause all sorts of trouble with reproducibility via config files etc. Perhaps a blank temporary directory would be an option? Regardless of the solution, I'd consider the absence of `HOME` in a process's environment on POSIX a bug.

**Comment by jugmac00** [comment]
You can always set `passenv` to allow additional environment variables, see https://tox.readthedocs.io/en/latest/config.html#conf-passenv

I cannot comment on which variables should be passed in by default.

**Comment by gaborbernat** [comment]
We don't plan to pass a real or fake HOME; users who do need this are encouraged to use either setenv or passenv.
