### ISSUE TITLE
terminating during inst step results in inst-nodep next time

### ISSUE THREAD

**Issue by stefansjs** [tox-dev/tox#2084]
If I terminate tox during the `inst` step, the next time I run tox it will run `inst-nodep` and then inevitably fail on tests because I don't have any of the dependencies.

I've been running tox on a package that can't be installed on my machine. This is hard to debug, so often it hangs for a long time during the `inst` step. Then hang is not tox's fault, but a side effect of pip's new resolver which doesn't fail quickly on invalid package dependencies. Once the hang happens I typically end up terminating it rather than waiting 4 hours for the installation to fail.

This seems like an edge case. I don't know what tox's logic is for deciding to do `inst-nodep`, but it seems like it's not handling the case when `inst` was terminated (but maybe is handling failure correctly?).

Here's some example output (truncated to highlight the important parts)
```bash
(.venv) % tox
py36 create: ~/code/<project_dir>/.tox/py36
py36 wheel-make: cleaning up build directory ...
py36 wheel-make: commands[0] | python ~/code/<project_dir>/setup.py bdist_wheel --dist-dir ~/code/<project_dir>/.tox/dist
running bdist_wheel
running build
running build_py
creating build/lib
...
removing build/bdist.macosx-10.15-x86_64/wheel
py36 create: ~/code/<project_dir>/.tox/py36
py36 inst: ~/code/<project_dir>/.tox/.tmp/package/1/<project>-0.1-py3-none-any.whl
^CERROR: got KeyboardInterrupt signal
_________________________________________________________________ summary _________________________________________________________________
ERROR:   py36: keyboardinterrupt
(.venv) % tox
py36 wheel-make: cleaning up build directory ...
py36 wheel-make: commands[0] | python ~/code/<project_dir>/setup.py bdist_wheel --dist-dir ~/code/<project_dir>/.tox/dist
running bdist_wheel
running build
running build_py
...
removing build/bdist.macosx-10.15-x86_64/wheel
py36 inst-nodeps: ~/code/<project_dir>/.tox/.tmp/package/1/backfill_stems-0.1-py3-none-any.whl
py36 installed: backfill-stems @ file://~/code/<project_dir>/.tox/.tmp/package/1/<project>-0.1-py3-none-any.whl
py36 run-test-pre: PYTHONHASHSEED='1736987215'
py36 run-test: commands[0] | python -m unittest discover -s src/ -p '*.py'
EEEE

And then a bunch of import errors.
```

In my case I'm trying to install tensorflow-gpu which is not available for mac. Again, my fault, but this may help reproduce long-running installation.

**Comment by gaborbernat** [comment]
I believe this now has been fixed with version 4 (rewrite branch). Please try with that and if the problem still exist we can reopen the issue.
