### ISSUE TITLE
Generated shell scripts don't quote special characters

### ISSUE THREAD

**Issue by ppoilbarbe** [tox-dev/tox#2088]
Hello,
Here is a part of my tox.ini file:

    [tox]
    requires =
        tox-conda
    envlist=py{37,38,39}-{check,test,coverage,build,doc}

    # Using mamba and boa to speed up build.
    # For example: conda package with conda-build:       >24h
    #                            with conda mambabuild:  10min

    .
    .
    .

    [testenv:py{37,38,39}-check]
    description = Check code formatting and common errors

    commands =
        mamba install --yes {env:CHANNEL_OPTIONS} \
            "black>=21.0,<22.0a0" \
            "flake8" \
            "isort"
        {toxinidir}/common_files/check-syntax

When I run this environment I obtain an error (extracted from output log):

    py37-check run-test: commands[0] | mamba install --yes --override-channels --channel octantdev --channel conda-forge 'black>=21.0,<22.0a0' flake8 isort
    setting PATH=/builds/tox_workdir/py37-check/bin:/opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    [5492] /builds/project-0$ /builds/tox_workdir/py37-check/bin/mamba install --yes --override-channels --channel octantdev --channel conda-forge 'black>=21.0,<22.0a0' flake8 isort
    /builds/tox_workdir/py37-check/.tmpqc983wrt: line 3: 22.0a0: No such file or directory
    ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['/builds/tox_workdir/py37-check/bin/mamba', 'install', '--yes', '--override-channels', '--channel', 'octantdev', '--channel', 'conda-forge', 'black>=21.0,<22.0a0', 'flake8', 'isort']' command failed.  (See above for error)
      ERROR: InvocationError for command /builds/tox_workdir/py37-check/bin/mamba install --yes --override-channels --channel octantdev --channel conda-forge 'black>=21.0,<22.0a0' flake8 isort (exited with code 1)
    py37-check finish: run-test  after 0.99 seconds

It comes from the shell script generated by conda (in a `.tmp*` file, difficult to trap, an option to keep temporary files would be great for debugging, but this is not the topic):

    eval "$(/homelocal/anaconda/conda/bin/conda shell.posix hook)"
    conda activate  /homelocal/su_php/dev/octantng/tox-core/py37-check
    /homelocal/su_php/dev/octantng/tox-core/py37-check/bin/mamba install --yes --override-channels --channel octantdev --channel conda-forge black>=21.0,<22.0a0 flake8 isort

As you can see, `black>=21.0,<22.0a0` is not quoted so the error "22.0a0: No such file or directory" is shown and the file `=21.0,` is created (and not seen before, when there was no "`<`" character, in a CI environment running in docker)
It is quoted in the command under the `commands`section` but it is lost.
Parameters that do not begin with a special shell character (depending on system :() like ">", "<", "|" (and maybe others) should be quoted in order to being able to specify python versions (at least) in commands.

We use `tox-conda` as a dependency then `mamba` and `boa` to do tests and builds (only conda is way too long)

Compressed log file: [run.log.gz](https://github.com/tox-dev/tox/files/6657546/run.log.gz)

**Comment by gaborbernat** [comment]
Did you try using a single quote?

**Comment by ppoilbarbe** [comment]
With single quotes, it is the same result. The shell script generated is the same.

**Comment by gaborbernat** [comment]
I believe this now has been fixed with version 4 (rewrite branch). Please try with that and if the problem still exist we can reopen the issue.
