### ISSUE TITLE
Add a way to ignore pyproject.toml

### ISSUE THREAD

**Issue by berislavlopac** [tox-dev/tox#2097]
I'm trying to run tox in a project which uses no setup mechanism, as it's not a package but an app/service. The tox configuration is set up in `tox.ini`, but when I execute it I get the following message:

```ERROR: build-system section missing inside [...]/pyproject.toml```

I need to have that file for the configuration of some other tools (e.g. `black`), but its presence should not mean that tox must use it for defining builds.

**Comment by jugmac00** [comment]
As it seems you have found a solution, what about sharing it? Maybe someone else will encounter the same issue.

**Comment by berislavlopac** [comment]
The `skipsdist` [global setting](https://tox.readthedocs.io/en/latest/config.html#tox-global-settings) resolves this issue:

```
[tox]
skipsdist = true
```
