### ISSUE TITLE
tox4: specify behavior for `tox -e ALL`

### ISSUE THREAD

**Issue by jugmac00** [tox-dev/tox#2112]
In tox3 this runs really all environments, in tox4 this runs all envs in the envlist.

@asottile @gaborbernat @obestwalter What's your take on this?

I am +1 on running really all environments with `tox -e ALL`.

Related to #2045

Interestingly, `tox -e ALL` also behaves differently between tox3 and tox4.

```
❯ tox -e ALL
hello run-test-pre: PYTHONHASHSEED='1741336755'
hello run-test: commands[0] | python3 -c 'print("Hello")'
Hello
goodbye run-test-pre: PYTHONHASHSEED='1741336755'
goodbye run-test: commands[0] | python3 -c 'print("Goodbye")'
Goodbye
_______________________________________________________ summary ________________________________________________________
  hello: commands succeeded
  goodbye: commands succeeded
  congratulations :)


❯ tox4dev -e ALL
hello: commands[0]> python3 -c 'print("Hello")'
Hello
  hello: OK (0.13=setup[0.10]+cmd[0.03] seconds)
  congratulations :) (0.16 seconds)
```

I suppose `ALL` should really run all envs, not only those in `envlist`? @gaborbernat

_Originally posted by @jugmac00 in https://github.com/tox-dev/tox/issues/2045#issuecomment-826657324_

**Comment by gaborbernat** [comment]
We should make tox 3 and 4 behave the same way. Anything else is a bug on this.
