### ISSUE TITLE
Isolated build with 'enscons' as backend build system fails

### ISSUE THREAD

**Issue by oczkoisse** [tox-dev/tox#2130]
I'm trying to use `tox` with `isolated_build` set to `true` and [`enscons`](https://github.com/dholth/enscons) as the backend build system. When `isolated_build` is not set (default is `false` I think), `tox` works fine. However, when `isolated_build` is set to `true`, the build fails with the following error:

```
action: .package, msg: get-build-requires
cwd: C:\Users\banga\Projects\Personal\labeling-tool
cmd: 'C:\Users\banga\Projects\Personal\labeling-tool\.tox\.package\Scripts\python' '.venv\Lib\site-packages\tox\helper\build_requires.py' enscons.api '' ''
Traceback (most recent call last):
  File ".venv\Lib\site-packages\tox\helper\build_requires.py", line 15, in <module>
    for_build_requires = backend.get_requires_for_build_sdist(None)
AttributeError: module 'enscons.api' has no attribute 'get_requires_for_build_sdist'
```

I might be wrong but I thought `get_requires_for_build_sdist` and `get_requires_for_build_wheel` were optional hooks in PEP 517 and should be assumed to return empty list if absent.

The tox configuration in `pyproject.toml` is:

```toml
[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py37, py38, py39
isolated_build = true

[testenv]
deps = pytest
commands = pytest
"""
```

**Comment by oczkoisse** [comment]
I've set up an example repository [here](https://github.com/oczkoisse/test-enscons). To reproduce the error:

1. Clone the repo
2. Set up a virtual environment
3. `pip install tox enscons`
4. Run `tox`. You should get an error similar to the following
   ```
   ========================================================================== log start ==========================================================================
   Traceback (most recent call last):
     File ".venv\Lib\site-packages\tox\helper\build_requires.py", line 15, in <module>
       for_build_requires = backend.get_requires_for_build_sdist(None)
   AttributeError: module 'enscons.api' has no attribute 'get_requires_for_build_sdist'
   
   =========================================================================== log end ===========================================================================
   ERROR: FAIL could not package project - v = InvocationError("'C:\\Users\\banga\\Projects\\Personal\\test-enscons\\.tox\\.package\\Scripts\\python' '.venv\\Lib\\site-packages\\tox\\helper\\build_requires.py' enscons.api '' ''", 1)
   ```
5. Setting `isolated_build = false` in `pyproject.toml` doesn't cause the above error

**Comment by gaborbernat** [comment]
This is a bug in our system, namely here https://github.com/tox-dev/tox/blob/master/src/tox/helper/build_requires.py#L15. This has been fixed in tox v4, but not on the v3 branch. PRs weclome.
