### ISSUE TITLE
configured with "isolated_build", but tox saying that I did not

### ISSUE THREAD

**Issue by jric** [tox-dev/tox#2148]
tox used to work on my repo, but recently I tried to run tests after many upgrades, and got this error:

```
ERROR: pyproject.toml file found.
To use a PEP 517 build-backend you are required to configure tox to use an isolated_build:
https://tox.readthedocs.io/en/latest/example/package.html

```

I followed the instructions there and had this `pyproject.toml` file:

```
[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tox]
isolated_build = True
```

That produced this error: 

`toml.decoder.TomlDecodeError: Only all lowercase booleans allowed (line 9 column 1 char 111)`

I changed `True` to `true`, and I'm back to the original error: `you are required to configure tox to use an isolated_build`

System info:

```
jric@Alexs-MacBook-Pro-3 apperror % tox --version
3.24.1 imported from /usr/local/lib/python3.9/site-packages/tox/__init__.py
macOS Big Sur - Version 11.5.1
```

**Comment by gaborbernat** [comment]
tox doesn't support native pyproject.toml config yet, so either you use tox.ini or you do https://tox.readthedocs.io/en/latest/example/basic.html#pyproject-toml-tox-legacy-ini
