### ISSUE TITLE
Allow execution of an env under a different Python

### ISSUE THREAD

**Issue by jaraco** [tox-dev/tox#2187]
In jaraco/skeleton/tox.ini, I define a ["docs" environment](https://github.com/jaraco/skeleton/blob/719a7ced8a1713b7fe94d842a8f6fec7425b8a0a/tox.ini#L16-L22) that normally builds under "python" (whatever that version defaults to). Thus `tox -e docs` automatically upgrades to latest Python as I migrate the system default to the latest Python.

However, sometimes, there are bugs on the latest Python (e.g. sphinx-doc/sphinx#9562), so I'd like the ability through the command-line to specify to use a different interpreter.

I tried `tox -e py39-docs`, but that returns `unknown environment 'py39-docs'`. Similar for `tox -e docs-py39`.

For the default environment (`testenv`), I _can_ specify `tox -e py39` and it will run that environment with the desired interpreter.

I'm using tox==3.24.3.

Is there any way without mutating the tox.ini or changing the default python to override the interpreter for a non-default env?

**Comment by gaborbernat** [comment]
This is not possible under tox 3. However, if you upgrade to tox 4 you can do:

```
tox4 -x testenv:docs.base_python=python3.8
```

You can install it under https://pypi.org/project/tox/4.0.0a8 . We're just cleaning things up, but is stable enough that I've been using as a daily driver for the last three months :+1:
