### ISSUE TITLE
Everything else not related to the tile is just noise because of the lack of rebase. Needs tests though, hence why this is waiting here patiently. The free time I've had in the last month has been focused on rewriting virtualenv which in turn would essentially make so that we can delete the entire interpreters package. WIP

### ISSUE THREAD

**Issue by mora441** [tox-dev/tox#2188]
Everything else not related to the tile is just noise because of the lack of rebase. Needs tests though, hence why this is waiting here patiently. The free time I've had in the last month has been focused on rewriting virtualenv which in turn would essentially make so that we can delete the entire interpreters package. WIP

_Originally posted by @gaborbernat in https://github.com/tox-dev/tox/issues/1272#issuecomment-506952239_

**Comment by mora441** [comment]
Chek me to this profile becase is very bad for me

**Comment by gaborbernat** [comment]
This has been now done in tox v4, and we have no plans to do this in tox 3.
