### ISSUE TITLE
Adopt plugin tox-external-wheels 

### ISSUE THREAD

**Issue by keller00** [tox-dev/tox#2189]
Describe what improvement you want and how would this be used. Thanks!

`tox-external-wheels` simply adds the ability to use externally created wheel files with globing patterns for environments and the ability to execute a script to generate the external wheels.

**Comment by gaborbernat** [comment]
With tox 4 supporting building wheels out of the box, is there still a need for this?

**Comment by sfc-gh-mkeller** [comment]
I think so. I wrote this plugin for a project that has C-extensions, in which case the build takes place in a manylinux Docker container, but tests run under a modern OS.
In this case you would want to point the testing system's `tox` to some externally built wheel file to test what will be released.

**Comment by keller00** [comment]
I think so. I wrote this plugin for a project that has C-extensions, in which case the build takes place in a `manylinux` Docker container, but tests run under a modern OS.
In this case you would want to point the testing system’s `tox` to some externally built wheel file to test what will be released.

**Comment by gaborbernat** [comment]
Any reason why not just add a build backend that uses docker instead of virtual environments?

**Comment by keller00** [comment]
Do you have an example of this? Maybe I'm just not aware of such solutions 😅

**Comment by gaborbernat** [comment]
No, because it's not written yet, but that would be a better solution here :blush: We need a docker version of the execution engine - https://github.com/tox-dev/tox/tree/rewrite/src/tox/execute/local_sub_process, and a packaging API that uses docker instead of virtualenv here https://github.com/tox-dev/tox/blob/rewrite/src/tox/tox_env/python/virtual_env/package/api.py

**Comment by keller00** [comment]
Ahh maybe this would be a good opportunity for me to contribute back to `tox`.

> Do you have a pipeline using this plugin that demonstrates building the wheel in Docker and then running that on the modern OS?

Yes https://github.com/snowflakedb/snowflake-connector-python/blob/9d7559bdab6ea972d69788d9197ae88dadb1f068/.github/workflows/build_test.yml#L93 is one of the build jobs https://github.com/snowflakedb/snowflake-connector-python/blob/9d7559bdab6ea972d69788d9197ae88dadb1f068/.github/workflows/build_test.yml#L214 is one of the test jobs (notice the -ci in the environments that we run and then that uses tox-external-wheels defined here https://github.com/snowflakedb/snowflake-connector-python/blob/9d7559bdab6ea972d69788d9197ae88dadb1f068/tox.ini#L36

**Comment by gaborbernat** [comment]
Just to clarify, this is not trivial and definitely will be more complicated than what this plugin does today. However, I feel this would be the right solution. 

First, we'd need to finish the docker env here https://github.com/tox-dev/tox-via-docker, and then build on top of that a manylinux wheel builder.

**Comment by gaborbernat** [comment]
@keller00 want to do the transfer then?

**Comment by keller00** [comment]
Yes, sorry I have been thinking about this for the past couple of days.
Let's do the transfer until the other projects you mentioned are finished, after that we can reconsider deprecating my plugin.

**Comment by gaborbernat** [comment]
This has been done now.
