### ISSUE TITLE
usedevelop without setup.py failure

### ISSUE THREAD

**Issue by AntoineD** [tox-dev/tox#2197]
When `usedevelop` is enabled with a project that only has a `setup.cfg` but no `setup.py`, on the second tox execution with no changes at all, tox crashes because `VirtualEnv._needs_reinstall` relies on `setup.py` to get the name of the project's package.

A PR is coming next.

**Comment by gaborbernat** [comment]
I don't think it's possible to use `usedevelop` without a `setup.py`. How does this even passes at first run?

**Comment by AntoineD** [comment]
> I don't think it's possible to use `usedevelop` without a `setup.py`. How does this even passes at first run?

This happens with an env that does not run the tests, I'll see what happens otherwise.

**Comment by AntoineD** [comment]
This works fine when running pytest in the commands of the such an env.

@gaborbernat What do you mean by not possible?

**Comment by gaborbernat** [comment]
`usedevelop` implies the installation of the package via `setup.py`. The installation will fail without `setup.py.

**Comment by AntoineD** [comment]
From what I can see, the installation works fine with only `setup.cfg` and no `setup.py` when `usedevelop = True`.

Have you tried?

**Comment by gaborbernat** [comment]
Hmm, did setuptools and pip change this? Can you dig up from pip+setuptools changelog when this was added? I know a while back you could not install in develop mode a package, because the interface was the `setup.py` file itself. It might work now but we need to figure out what versions of pip+setuptools require that 🤔

**Comment by AntoineD** [comment]
The failures of the PR's CI's jobs seems to be related to what you are saying. Things behave differently on my PC, I'll dig up.

**Comment by AntoineD** [comment]
This has been [fixed](https://github.com/pypa/pip/pull/9547) in [pip 21.1](https://pip.pypa.io/en/stable/news/#v21-1).

**Comment by posita** [comment]
Just curious, but what's the fix here? Tox should require `pip>=21/1`?

**Comment by AntoineD** [comment]
@posita Yes (not considering tox).

**Comment by posita** [comment]
> A PR is coming next.

Is this still true, or should this be closed without a fix?

**Comment by AntoineD** [comment]
The [PR](https://github.com/tox-dev/tox/pull/2198) has been closed without merge.

**Comment by posita** [comment]
I don't think `pip` fixes this. I still see this with `pip==21.2.4`.

**Comment by posita** [comment]
Digging into this a bit, this **_works_** (including on the second and subsequent runs):

``` yaml
[tox]
# …
skipsdist = true

[testenv]
# …
deps =
    --editable .  # <-- this works
```

This fails on the second run (per the OP):

``` yaml
[tox]
# …
skipsdist = true

[testenv]
# …
usedevelop = True  # <-- this works once, then fails on subsequent runs
```

**Comment by posita** [comment]
Here's a test case: [posita/test-case-for-tox-2197](https://github.com/posita/test-case-for-tox-2197).

``` sh
$ tox -e py39,py39-workaround
# …
  py39: commands succeeded
  py39-workaround: commands succeeded
  congratulations :)
$ tox -e py39,py39-workaround
# …
ERROR:   py39: InvocationError for command /private/tmp/foo/.tox/py39/bin/python /private/tmp/foo/setup.py --name (exited with code 2)
  py39-workaround: commands succeeded
```

**Comment by ssbarnea** [comment]
I am quite interested about fixing this because I already started to remove the historical `setup.py` from most projects since pip started to allow editable installs without it.

**Comment by webknjaz** [comment]
> I don't think `pip` fixes this. I still see this with `pip==21.2.4`.

Pip does fix `pip install -e .` but it's not what tox uses IIRC. I think tox attempts invoking the deprecated[^1] `setup.py develop`

[^1]: See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for the details.

**Comment by ssbarnea** [comment]
I spent the last couple of hours trying to **keep coverage working** while dropping the broken `usedevelop` and switching to `--editable .` but without any luck so far.

Apparently almost all repo setups I found implement coverage using tox editable installs. Shortly I cannot drop setup.py without breaking coverage. Did anyone managed to find a configuration where this still works?

**Comment by gaborbernat** [comment]
https://github.com/tox-dev/tox/blob/rewrite/tox.ini#L29 should work

**Comment by ssbarnea** [comment]
In the end I was able to make it work with https://github.com/ansible-community/ansible-compat/pull/96  I no longer use pytest-cov as running `coverage ...` is more reliable. 

I am really glad we have a workaround.
