### ISSUE TITLE
tox 4: enable plugins to discover config sections & testenvs

### ISSUE THREAD

**Issue by dcrosta** [tox-dev/tox#2200]
My plugin [tox-docker](https://github.com/tox-dev/tox-docker) could benefit from being able to discover all configuration sections and/or to get a list of all testenvs from the `Config`.

tox-docker starts docker containers as configured by each testenv; the testenv references another section (eg `[docker:nginx]` by way of saying `docker=nginx` in the testenv). In order to discover all configuration, I need to enumerate all testenvs or all sections (and filter the list to `docker:*` sections).

I'm currently doing the former with:

```python
class EnvDockerConfigSet(ConfigSet):
    def __init__(self, conf: Config) -> None:
        super().__init__(conf)

        self.add_config(
            keys=["docker"],
            of_type=EnvList,
            default=EnvList([]),
            desc="docker image configs to load",
            post_process=list,
        )

def discover_container_configs(config: Config) -> Sequence[str]:
    docker_configs = set()
    for env_name in config:
        env_config = config.get_section_config(f"testenv:{env_name}", EnvDockerConfigSet)
        docker_configs.update(env_config.load("docker"))
    return list(docker_configs)
```

It would be more explicit to have eg. `config.get_test_envs()` that returns either all testenvs, or better yet, the specific testenvs that will be run (eg due to setting `-e` on the commandline, or the `envlist`, etc).

**Comment by gaborbernat** [comment]
1. For getting a list of all tox environments you can use https://github.com/tox-dev/tox/blob/rewrite/src/tox/session/cmd/show_config.py#L61. We need to expose this somehow though on the `config` argument or something like that.

2. For the new configuration section: So there's some complexity we need to tackle here: different configu2ration sources. Today this is mostly INI file only. However, going ahead we'll have other files, such as the `pyproject.toml`. For that file, it's not allowed to reuse the `docker` namespace directly, but instead, https://www.python.org/dev/peps/pep-0518/#tool-table governs that. To follow that ad litera you'll likely want to add the docker sections under `tool.tox-docker.docker-nginx`, and `tool.tox-docker.docker-db`. The system should hideaway this from you somehow.
