### ISSUE TITLE
tox 4: enable plugins to run before/after each testenv

### ISSUE THREAD

**Issue by dcrosta** [tox-dev/tox#2201]
My plugin [tox-docker](https://github.com/tox-dev/tox-docker) needs a way to run code before and after the testing part of each testenv.

Before each testenv runs, tox-docker will start appropriate docker containers based on configuration (see #2200 for more), and sets environment variables for the testenv to inform tests of the containers' IP and ports. After the test run, the containers are stopped and removed.

This could either mean bringing back `tox_runtest_pre` and `tox_runtest_post`, or adding `tox_wrap_test` which could act like a generator-context manager. For example:

```python
@impl
@contextmanager
def tox_wrap_test(env: TestEnv):
    # ... start docker containers ...

    try:
        yield  # tests run here
    finally:
        # ... clean up started containers ...
```

**Comment by ymyzk** [comment]
tox-gh-actions also has a similar request. It has been using `tox_runtest_pre` and `tox_runtest_post` hooks to use [log line grouping on GitHub Actions](https://github.com/actions/toolkit/blob/dd046652c32b45c0207b37ee0bc0ebf43a28b257/docs/commands.md#group-and-ungroup-log-lines) and we'd like to implement something similar for tox v4 as well. https://github.com/ymyzk/tox-gh-actions/issues/39 https://github.com/ymyzk/tox-gh-actions/issues/80

Here's what we want to do:

```shell
$ tox4
.pkg: get_requires_for_build_sdist> python ... True setuptools.build_meta __legacy__
.pkg: prepare_metadata_for_build_wheel> python ... True setuptools.build_meta __legacy__
.pkg: build_sdist> python ... True setuptools.build_meta __legacy__

(tox-gh-actions wants to write the start of the log line grouping here)

flake8: install_package> python -I -m pip install --force-reinstall --no-deps ...
flake8: commands[0]> flake8 setup.py

(tox-gh-actions wants to write the end of the log line grouping here)

.pkg: _exit> python ... True setuptools.build_meta __legacy__
  flake8: OK (1.53=setup[1.34]+cmd[0.18] seconds)
  congratulations :) (1.57 seconds)
```
