### ISSUE TITLE
tox4: allow tox plugins to read and update a configuration

### ISSUE THREAD

**Issue by ymyzk** [tox-dev/tox#2210]
## Summary
In a tox plugin, I'd like to read a configuration then update it. It seems we cannot do this because the configuration will be cached when a plugin read it once.

This may be simply because I don't know how to override configurations with tox v4. If tox v4 already provides an API to enable this, please let me know. Thanks.

## Use case
I'd like to read and update the envlist in tox-gh-actions. Other existing tox v3 plugins have similar use case.

## Example
This example uses `envlist` but this should be the same for other configs as well.

```ini
[tox]
envlist = existing
```

```python
from tox.config.loader.memory import MemoryLoader
from tox.config.main import Config

@impl
def tox_configure(config: Config) -> None:
    # Read config once, the value will be cached into config.core._defined["envlist"]._cache
    envlist = config.core["envlist"]
    print(envlist)  # Get ["existing"]

    # Override the config
    config.core.loaders.insert(0, MemoryLoader(env_list=EnvList(["override"])))

    # I expect ["override"] to be returned but ["existing"] is returned because of the cache
    print(config.core["envlist"])
```

## Mitigation
We can still clear the cache by using internal APIs but it's not ideal.
```python
config.core._defined["envlist"]._cache = _PLACE_HOLDER
```

**Comment by gaborbernat** [comment]
Why do you want to read a configuration and then update it?

**Comment by ymyzk** [comment]
It's the design of the plugin and explained in https://github.com/ymyzk/tox-gh-actions/blob/master/ARCHITECTURE.md. Please read it through if you have time. Examples in https://github.com/ymyzk/tox-gh-actions/blob/master/README.md may also help.

I assume this is something we need for other plugins.
* tox-travis: https://github.com/tox-dev/tox-travis/blob/0.12/src/tox_travis/envlist.py#L14-L27
* tox-factor: https://github.com/rpkilby/tox-factor/blob/bb36b281c8719af23c21ce78528f864bcdbd2e3e/src/tox_factor/hooks.py#L65

**Comment by gaborbernat** [comment]
That document doesn't tell me **exactly** the reason. Can you highlight it for me, please?

**Comment by ymyzk** [comment]
The reason is that the plugin should not generate and run new environments which are not explicitly defined defined by users. This is the design choice. The purpose of plugin is running a subset of the default envlist based on different factors such as Python version and environment variables.

**Comment by gaborbernat** [comment]
I'm less interested in the design part and more interested in why exactly you're reading the envlist and then setting it. Note the `envlist` is **NOT** the user-defined tox environments. It's the environment to run if the user did not specify anything on the CLI. If you're reading `envlist` to determine what environments are defined, you're doing it wrong. Is it for some other case?

**Comment by ymyzk** [comment]
> Note the envlist is NOT the user-defined tox environments. It's the environment to run if the user did not specify anything on the CLI. 

Okay, I understand. As tox-gh-actions overrides environments only when environments are not explicitly given by users ([README](https://github.com/ymyzk/tox-gh-actions#overriding-environments-to-run)), "the environment to run if the user did not specify anything on the CLI" is exactly what tox-gh-actions wants to get. Could you kindly tell me a better way to get this other than reading from `envlist`?

Again, we need this because the plugin wants to run subset of the environment to run if the user did not specify anything on the CLI".

**Comment by gaborbernat** [comment]
> "the environment to run if the user did not specify anything on the CLI" is exactly what tox-gh-actions wants to get.

Wouldn't be better to allow the user to specify any tox environment defined, not just: ``the environment to run if the user did not specify anything on the CLI``? E.g. a release package environment is something the user might choose to run in the CI only, but not put it in the default list.

**Comment by ymyzk** [comment]
Your approach can be one design choice for this type of plugin but I don't want to discuss how this plugin should decide environments to run further in the tox-dev/tox project. I would like to focus on migrating users from tox v3 to tox v4 with minimum breaking changes. That's why I'm filing a ticket here.

**Comment by gaborbernat** [comment]
Thanks for explaining. I see your point of view now. That being said I'd like to avoid adding knobs to the core unless there's a strong need for it. I don't agree that this design choice is desirable for a tox plugin you're trying to do. I'd consider it a bug, rather than a feature that kind of functionality. Therefore, I don't think there's a strong need for this, so I'll close the ticket for now.

**Comment by ymyzk** [comment]
Okay, thank you very much for your hard work. I'll do my best for users. I hope tox v4 works well with other plugins as well.
