### ISSUE TITLE
tox4: plugins need a way to modify a testenv's environment variables

### ISSUE THREAD

**Issue by dcrosta** [tox-dev/tox#2215]
tox-docker needs to set environment variables that will be present for running tests. I've tried this from `tox_run_before_commands`:

```python
tox_env.conf["set_env"].update_if_not_present(...)
```

but it looks like the caching in `ToxEnv` at https://github.com/tox-dev/tox/blob/rewrite/src/tox/tox_env/api.py#L287-L288 is preventing this from having any effect

**Comment by dcrosta** [comment]
At a glance, it looks like that caching may be a premature optimization and could just be removed? Doing so fixes my use case, in any event; however, I feel like it might be nice to have a more direct way for plugins to modify the environment rather than mutating set_env...

**Comment by gaborbernat** [comment]
You're not supposed to change configuration by mutating it. You're supposed to do that by registering a custom runner to extend it and by using a memory loader to override it 👍

**Comment by dcrosta** [comment]
Any pointers how to do that?

Does it compose? If multiple plugins want to set environment, how does each of their runners work together?

**Comment by gaborbernat** [comment]
It doesn't compose. Do we have some use cases where plugins need to compose, I haven't seen until now.

**Comment by dcrosta** [comment]
I don't know of any off hand, but if any other plugin also wanted to do something that required a runner, it would then be incompatible with tox-docker, if I'm understanding correctly?

**Comment by gaborbernat** [comment]
Depends: in theory the users can use the inline plugin systems to combine runners (by inheriting from both runners and defining a new runner). Though admittedly this isn't the cleanest solution. What runners you're looking to combine with tox-docker?

**Comment by dcrosta** [comment]
I'm not sure we're talking about quite the same thing. Here's my scenario: imagine that tox-docker (which modifies the test process environment) and another plugin (let's say it controls test randomness by setting `PYTHONHASHSEED` or whatever) both exist. If a tox end-user wants to use both of these, ordinarily they'd do it just by installing them alongside tox, and it would all "just work". (This would be the case in tox3)

If plugins have to implement a subclass of `RunToxEnv` (I guess that's what you mean by "register a custom runner") to change the environment in tox4, then it won't be possible for the end-user to use both these plugins in the normal way.

This is the scenario I'm talking about when I say "compose" -- I don't mean, "can I write Python code in a plugin which combines things," which I can; I mean, "can end users use tox in the normal way and get the expected behavior".

Does this request make sense?

**Comment by gaborbernat** [comment]
Yeah, I was talking about the same thing. However, I'm yet to see a case where this was actually needed, hence wanting some actual case, not hypotheticals.

**Comment by dcrosta** [comment]
I think there's an added complication here. The only concrete type I can find to inherit from for a custom runner is the `VirtualEnvRunner`, but since this is a _specific_ thing, that doesn't seem like the right place to inherit from. Again this begs the question of composability. I have seen some other plugins that eg. run the tox commands outside of a virtual env, just directly in the environment that `tox` is invoked in. In these cases, presumably these plugins would also have a runner, and we'd have the issue again.

I really think that "setting environment for the test commands" is a generic and useful capability that tox should expose for plugins.

**Comment by gaborbernat** [comment]
> Er, didn't see #2218 when I wrote this, whoops

Yeah, hope that resolves all concerns you've had 😊
