### ISSUE TITLE
A virtualenv created by tox downloads seed packages when download is False

### ISSUE THREAD

**Issue by Exagone313** [tox-dev/tox#2222]
Hi,

When setting `download = False` option in an environment definition, which is [documented here](https://tox.readthedocs.io/en/latest/config.html#conf-download), the created virtualenv will still download pinned pip, setuptools and wheel versions as declared by the virtualenv package: https://github.com/pypa/virtualenv/blob/1cc503bfadc2c0e8c3ecac6c0a3f430ee601d9a0/src/virtualenv/seed/wheels/embed/__init__.py

By adding the `--no-seed` argument when executing the virtualenv package module (which is done in `src/tox/venv.py`), this feature can be disabled.

I'm willing to create a PR for this bug. I need to look for the compatibility with earlier virtualenv package versions.

**Additional context**

virtualenv 20.8.0 upgraded setuptools to 58, which removed support for 2to3. It broke our CI that used the `download = False` option in `tox.ini`.

I created a documentation issue on the virtualenv repository for improving the documentation for `--no-seed`: https://github.com/pypa/virtualenv/issues/2188

**Comment by Exagone313** [comment]
Adding the flag may break the compatibility for current deployments, I need extra input from maintainers on that topic.

**Comment by gaborbernat** [comment]
I'm not sure this is a bug. tox passes on the no-download flag as expected. virtualenv respects it as far as eager upload goes. However, the virtualenv periodic update feature is what's triggering. Perhaps download should imply no periodic update too though :thinking:

**Comment by Exagone313** [comment]
It seems odd to me that pinning these three dependencies (pip, setuptools, wheels) requires patching virtualenv (`virtualenv.seed.wheels.embed`). Is that really the "supported" way?

I thought it was actually downloading these versions from Pypi (I have not checked what it is doing exactly, I only increased verbosity while trying to reproduce the behavior out of tox).

What's the reasoning behind that situation?

I would assume that the currently installed versions of these three packages would be copied into the created virtualenv, but I understand that installing a package doesn't keep a copy of the wheel (so it can't actually "copy" an installed package - also you can specify a different Python version that would mess things up).

Couldn't there be a way to fix these dependencies in `tox.ini` like you can fix your (other) dependencies in a `requirements.txt`? Which means versions, downloaded from Pypi by default, if you didn't provide links to wheels (or configured a mirror in pip.conf).

I couldn't find a way to run a `pip install` before installing my own dependencies, so I could install these three dependencies (if I assume these pinned versions can still be installed with more recent versions installed...). And the whole thing is about setuptools that broke retrocompatibility...

Packaging is surely a mess.

**Comment by gaborbernat** [comment]
> It seems odd to me that pinning these three dependencies (pip, setuptools, wheels)

You'll need to define what do you exactly mean by pinning to answer that.


> requires patching virtualenv (`virtualenv.seed.wheels.embed`)

It doesn't, but it does require you to specify what type of pinning you want in your configuration.

> What's the reasoning behind that situation?

There's a long topic on peoples expectations of the pip/setuptools/wheel on virtualenv, see here https://discuss.python.org/t/how-should-virtualenv-behave-respective-of-seed-packages-e-g-pip-by-default/4146. As you will see from there everyone is looking for something different, so the current behaviour is the middle ground.

**Comment by gaborbernat** [comment]
> Couldn't there be a way to fix these dependencies in `tox.ini` like you can fix your (other) dependencies in a `requirements.txt`? Which means versions, downloaded from Pypi by default, if you didn't provide links to wheels (or configured a mirror in pip.conf).

It is, you should set the `VIRTUALENV_PIP`, `VIRTUALENV_WHEEL` and `VIRTUALENV_SETUPTOOLS` to the version you require (within the setenv), as the virtualenv documentation shows.

> Packaging is surely a mess.

It's a community effort, you're invited to improve it.

**Comment by Exagone313** [comment]
I can confirm that this work.

I'm thinking of sending a PR to edit the `docs/config.rst` file that mentions `VIRTUALENV_PIP` to explicitly mention the two other variables.

**Comment by xmo-odoo** [comment]
@gaborbernat stumbled upon this issue while trying to understand why tox+3.4 didn't work, is there a way to use the `VIRTUALENV_` envkeys to tell virtualenv to use whatever the latest *compatible* version of those packages is? As-is, for versions of python not supported anymore by virtualenv[^fair] tox... pretty much stops working until you find out about the magic invocation, then hunt down what the latest version of the seeds should be for that outdated version of python.

Assuming you follow the same timeline for the now-EOL 3.5 as you did for 3.4[^repeat] that means tox/3.5 will start breaking around the end of next year, possibly earlier if you accelerate the schedule on way-outdated-and-EOL versions.

[^fair]: which is completely fair, don't get me wrong
[^repeat]: which, again, perfectly fair

**Comment by gaborbernat** [comment]
I believe this has been fixed in tox version 4, so please test it there and we can reopen if still persists.
