### ISSUE TITLE
toxworkdir must not be related to the source directory when using meson.build.

### ISSUE THREAD

**Issue by daknuett** [tox-dev/tox#2231]
This is less of a bug and more of a report of something that should be documented. All steps are working fine by themselves but joined together they exhibit unwanted behaviour.

**Steps to reproduce**

- Use `meson` and `mesonpep517` to build python packages that depend on numpy. The canonical way to do so is:

```
    pymod = import('python')
    python = pymod.find_installation('python3')
    pydep = python.dependency()

    numpy_cmd = run_command(python, ['-c', 'import numpy; print(numpy.get_include())'], check : true )
    message(numpy_cmd.stdout().strip())
    message('include_directories(numpy_cmd.stdout().strip())')
    numpy_incdir = include_directories(numpy_cmd.stdout().strip())
    numpy_dep = declare_dependency(include_directories: numpy_incdir)
```

- Use `tox` for testing and do not specify `toxworkdir` in `tox.ini` or specify a `toxworkdir` that is related to `meson`'s source directory.

**Behaviour**

- When invoking `python3 -m build .` to build the package no errors occur. 
- When running `tox` the build process fill fail with the following message from `meson`:

```
    meson.build:10:0: ERROR: Tried to form an absolute path to a source dir.
    You should not do that but use relative paths instead.
```
To get include path to any directory relative to the current dir do
```
    incdir = include_directories(dirname)
```
After this incdir will contain both the current source dir as well as the
corresponding build dir. It can then be used in any subdirectory and
Meson will take care of all the busywork to make paths work.

Dirname can even be '.' to mark the current directory. Though you should
remember that the current source and build directories are always
put in the include directories by default so you only need to do
include_directories('.') if you intend to use the result in a
different subdirectory.

- I made a [repository showcasing](https://gitlab.com/daknuett/test_numpy_meson_tox) the problem.

**Known Fix**

Specify the `toxworkdir` in `tox.ini`, e.g.:

```
    toxworkdir=/tmp/.tox
```
I think this behaviour should be documented somewhere because it is very counterintuitive to fix and might appear quite often in the future if more projects adapt `meson` for their python3 build process.

**Comment by daknuett** [comment]
@rgommers you might run across this problem in your rgommers/scipy. I was unable to get it to compile so far, therefore I don't know if you have the same issue.

**Comment by daknuett** [comment]
Assuming you have a setup like `project/{meson.build,tox.ini,...}` `tox` will build the virtualenv somewhere in `project/.tox/`. This is part of `meson`'s source directory. 

`include_directories` forbids using absolute paths when they could be relative to the source directory (in this case it would be `.tox/some/path`) but `numpy.get_include` returns an absolute path.

**Comment by rgommers** [comment]
> `include_directories` forbids using absolute paths when they could be relative to the source directory (in this case it would be `.tox/some/path`) but `numpy.get_include` returns an absolute path.

Ah thanks, that makes sense now. Yes, that is a problem. Having dev environments in-tree is something I avoid and I'm not a tox user, so I didn't see this before. In scipy we have a `tox.ini`, but it's not really used for anything except `flake8` config.

**Comment by gaborbernat** [comment]
> suming you have a setup like `project/{meson.build,tox.ini,...}` `tox` will build the virtualenv somewhere in `project/.tox/`. This is part of `meson`'s source directory.

Why is this a problem? I'm not at all familiar with meson so sadly I don't follow.

**Comment by daknuett** [comment]
@gaborbernat PEP517 defines a standardized way of building python packages and aims to replace `setuptools` and `distutils`. There are several backends that can be used to build packages, including `tomli` and `mesonpep517`. The great advantage of `mesonpep517` (which uses the meson build system) is that it is extremely easy to link against other libraries and compile C/C++/Fortran code.

This is a reason why the scipy build process has been ported to meson (by @rgommers)  and why I use it in some of my packages.

However, `tox` uses a default `toxworkdir` that is considered in-tree by `meson`. Meson (for good reasons) refuses to compile the project in this case.

The fix is easy: Specify a `toxworkdir` that is not in meson's source directory. But the error message produced by meson is not helping to find this fix. I think this fix should be documented.

**Comment by gaborbernat** [comment]
> Meson (for good reasons) refuses to compile the project in this case.

Can you elaborate on this? How does it fail, what it prints?

> : Specify a `toxworkdir` that is not in meson's source directory.

Where do you point this folder if not within the project?

**Comment by daknuett** [comment]
> Can you elaborate on this? How does it fail, what it prints? 

I just realized my original comment is very poorly formatted. I made an appropriate edit. Here is the output from meson:

```
meson.build:10:0: ERROR: Tried to form an absolute path to a source dir.
You should not do that but use relative paths instead.

To get include path to any directory relative to the current dir do

incdir = include_directories(dirname)

After this incdir will contain both the current source dir as well as the
corresponding build dir. It can then be used in any subdirectory and
Meson will take care of all the busywork to make paths work.

Dirname can even be '.' to mark the current directory. Though you should
remember that the current source and build directories are always
put in the include directories by default so you only need to do
include_directories('.') if you intend to use the result in a
different subdirectory.
```

You can reproduce this behaviour using https://gitlab.com/daknuett/test_numpy_meson_tox. I do not remember the full reasoning behind this behaviour but it can be solved by specifying an out-of-tree `toxworkdir`.

> Where do you point this folder if not within the project?

`toxworkdir=/tmp/.tox` works. Something like `~/.toxworkdirs/projectname/` should work also.

**Comment by gaborbernat** [comment]
> I do not remember the full reasoning behind this behaviour but it can be solved by specifying an out-of-tree `toxworkdir`.

This is a bit against the design policy of tox, and unusual for tox so would be nice to know why.

> `toxworkdir=/tmp/.tox` works. Something like `~/.toxworkdirs/projectname/` should work also.

This might work but neither of those two is guaranteed to be present or writeable.  So all meson projects would set this explicitly and say they only support that.

**Comment by daknuett** [comment]
Perhaps @eli-schwartz has some thoughts on that.

**Comment by gaborbernat** [comment]
> One solution would be to add a built-in dependency type for numpy, which we want to do anyway, which can guarantee that the string is correct even if it is an absolute path.
> 
> Another solution would be to implement [mesonbuild/meson#7908](https://github.com/mesonbuild/meson/pull/7908) and then use it to relocate the returned string from the numpy include as a relative path, if it is in the source tree.

Sounds to me neither is really anything to do for tox, but perhaps something to document in the mesonbuild project.

**Comment by eli-schwartz** [comment]
Option two could be implemented in a backwards compatible way for current versions of meson, by using a slightly more elaborate `python -c '...'` probe (since you're already working with a python subprocess, it costs little to do so, once you know you need to).

**Comment by eli-schwartz** [comment]
Yes, I would classify this as a meson UX issue which should be solved either by meson or by mesonpep517 projects, and which tools like tox should not be concerned with.

Patches to add a FAQ entry to the meson docs would be welcome, although I could look into this when I get the chance I suppose.

**Comment by gaborbernat** [comment]
Cool, I'll close this then.
