### ISSUE TITLE
Do not add coverage to PyPy CI runs

### ISSUE THREAD

**Issue by mattip** [tox-dev/tox#2252]
Describe what improvement you want and how would this be used. Thanks!
PyPy CI runs seem to be about 3x slower than CPython ones. For a [single sample](https://dev.azure.com/toxdev/tox/_build/results?buildId=3412&view=logs&j=9ae52fd2-8967-5276-eca4-50facaa10db8):

name | time
---|---
py27 linux | 6m 39s
py36 linux | 7m 22s
py37 linux | 6m 11s
py38 linux | 7m 12s
py39 linux | 6m 49s
py310 linux | 7m 9s
pypy linux | 18m 30s
pypy3 linux | 19m 22s

The command used in the `run tox test environment` step is https://github.com/tox-dev/tox/blob/4cf816c97de18dca9d99dc86fec341c1d2c4a20a/tox.ini#L37-L42

It uses `--cov` for PyPy. Coverage is very slow on PyPy, would you consider running the PyPy tests without it?

Also, using azure pipelines means you currently [cannot move past pypy3.6](https://github.com/microsoft/azure-pipelines-tasks/issues/15232). Would you consider moving some/all of the CI to github actions (moving some would allow more CI to run in parallel but would make collating the results harder)?

If either of these are acceptable, I can work on PRs to implement them.

**Comment by gaborbernat** [comment]
Closing as per above. We moved to Github actions now.

**Comment by mattip** [comment]
> Why is coverage so slow 

On CPython it leverages the C-API to work in C. On PyPy, the use of `sys.settrace()` breaks the JITted code, since we don't really know what is going on in the tracing function. We should revisit this in PyPy, we last looked at it [in 2013](https://www.pypy.org/posts/2013/10/making-coveragepy-faster-under-pypy-935409618297062344.html) but maybe there are more improvements we could make.
