### ISSUE TITLE
tox fails on JSON decoding when latest setuptools emits a deprecation warning for setup_requires

### ISSUE THREAD

**Issue by alex** [tox-dev/tox#2261]
https://github.com/pyca/cryptography/runs/3985968157?check_suite_focus=true contains an example of what this failure looks like, and https://github.com/pyca/cryptography/pull/6465 demonstrates fixing it by removing setup_requires.

What happens here is that setuptools emits a `SetuptoolsDeprecationWarning` (due to the presence of `setup_requires`), this obviously ends up in the stdout/stderr that tox is trying to `json.loads` which leads to this error.

IMO there's really two issues here:
1. `tox` should log the output in cases like this to make them easier to debug
2. `tox` should handle this somehow, perhaps by splitting stdout from stderr

**Comment by gaborbernat** [comment]
This is not an issue in tox v4 and I have no plans to fix it for v3, so I'm closing this now.
