### ISSUE TITLE
requires option creates virtual environment before displaying help

### ISSUE THREAD

**Issue by maltevesper** [tox-dev/tox#2265]
I added a requires statement as follows to my tox.ini, afterwards running `tox --help` would create the provisioning virtual environment before displaying the help. Clearly, I would expect `tox --help` to display the help without modifying the file system...

```
[tox]
requires = 
    virtualenv >= 20.10.0
```

Output:
```MalteV /d/Testing/git/test (feature/packaging)
$ tox --help
.tox create: D:\Testing\git\test\.tox\.tox
.tox installdeps: virtualenv >= 20.10.0, tox >= 3.24.3
usage: tox [--version] [-h] [--help-ini] [-v] [-q] [--showconfig] [-l] [-a] [-c CONFIGFILE] [-e envlist] [--devenv ENVDIR] [--notest] [--sdistonly] [--skip-pkg-install] [-p [VAL]] [-o]
           [--parallel--safe-build] [--installpkg PATH] [--develop] [-i URL] [--pre] [-r] [--result-json PATH] [--discover PATH [PATH ...]] [--hashseed SEED] [--force-dep REQ]
           [--sitepackages] [--alwayscopy] [--no-provision [REQUIRES_JSON]] [-s [val]] [--workdir PATH]
           [args ...]

tox options
...
```

Details:
OS Win 10
tox 3.24.3

**Comment by maltevesper** [comment]
If this issue is not in tox 4 (not tested) I for one do not care for a fix for tox 3

**Comment by gaborbernat** [comment]
> Clearly, I would expect `tox --help` to display the help without modifying the file system...

That would be unwise. If that would happen plugins could not extend the help message.
