### ISSUE TITLE
Question: Allow local executable

### ISSUE THREAD

**Issue by yannikschaelte** [tox-dev/tox#2266]
I want to use an executable in a local folder, `bin/tool`, by adding the local folder to PATH. However,

```yml
[testenv:test]
setenv =
    # add tool to path
    PATH = {env:PWD}/bin:{env:PATH}
allowlist_externals = *
commands =
    # doesn't work
    tool --version
    # works
    {env:PWD}/bin/tool --version
```

does not work, only with absolute path. Adding the folder to PATH outside tox works, however it would be preferable if those adjustments could be done within this config file. What am I doing wrong?

**Comment by gaborbernat** [comment]
PWD is not defined. You'd likely want to use `{toxinidir}` instead that points to the root of the project, where the `tox.ini` file lives.
