### ISSUE TITLE
pip fails if the source tree contains a module imported by pip

### ISSUE THREAD

**Issue by rainwoodman** [tox-dev/tox#2281]
Tox runs dependency installation from toxinidir via `python -m pip`. toxinidir usually points to the root directory of the checked out source code. If the source checkout has a directory name that conflicts with a package imported by `pip`, then `python -m pip` fails. 

Here is a sample error:
```

cat ~/package/.tox/py38/log/py38-1.log
action: py38, msg: getenv
cwd: /home/user/package
cmd: /home/user/package/.tox/py38/bin/python -m pip install pytest
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/user/package/.tox/py38/lib/python3.8/site-packages/pip/__init__.py", line 1, in <module>
    from typing import List, Optional
ImportError: cannot import name 'List' from 'typing' (/home/user/package/typing/__init__.py)

```

The error occurs as long as there is a file named `/home/user/package/typing/__init__.py`.

Note that running `pip` (not through python -m) works from the directory.

**Comment by gaborbernat** [comment]
This is more of a python issue rather than a tox issue. I'm personally fine with the current status quo and not convinced to change to not invoke stuff via the -m, :thinking: yet.

**Comment by rainwoodman** [comment]
Indeed. We were able to work around this by moving the sub-packages to a 'src'-like directory for the PIP distribution.
The package was original written for bazel, where an extra directory level would 'contaminate' the bazel label.

**Comment by gaborbernat** [comment]
Closing per above.
