### ISSUE TITLE
Docs: misleading description of `usedevelop`

### ISSUE THREAD

**Issue by babolivier** [tox-dev/tox#2282]
The current documentation [says](https://tox.wiki/en/latest/config.html#conf-usedevelop):

> Install the current package in development mode with “setup.py develop” instead of installing from the `sdist` package. (This uses pip’s `-e` option, so should be avoided if you’ve specified a custom **`install_command`** that does not support `-e`).

This to me reads that `tox` will try to run `setup.py develop` to install the current package (and `pip -e` might be involved at some point but that's not very clear). However, looking at the [code](https://github.com/tox-dev/tox/blob/51cc218e71949e90ab7982bbb12a475fcbb90613/src/tox/venv.py#L391-L392) it looks like all it does is add `-e` to the install command, which is a completely different thing.

**Comment by gaborbernat** [comment]
pip under the hood will call `python setup.py develop` when called via `-e`, at least prior to the latest pip that adds support for PEP-660. So IMHO the documentation is accurate in this sense, but please feel free to add a PR that addresses this.

**Comment by gaborbernat** [comment]
the rewrite branch has this correctly https://tox.wiki/en/rewrite/config.html#usedevelop, no plans to address it in v3
