### ISSUE TITLE
[tox4] Document loaders on config set

### ISSUE THREAD

**Issue by frenzymadness** [tox-dev/tox#2287]
I'm trying to port our tox extension to the new tox 4 and I have one problem described in this thread: https://github.com/fedora-python/tox-current-env/pull/42#pullrequestreview-799430800

The problem basically is that it's not possible to call `get_env` in `tox_add_env_config` because it causes an endless recursion. I need to do it so I can overwrite some settings loaded from config with values from the extension.

**Comment by gaborbernat** [comment]
> The problem basically is that it's not possible to call `get_env` in `tox_add_env_config` because it causes an endless recursion.

Can you post an example code doing this?

**Comment by frenzymadness** [comment]
It has been a few weeks since I touched it last time but this should be it:
```python
@impl
def tox_add_env_config(env_conf, config):
    loader = MemoryLoader(allowlist_externals=["*"])
    env_name = next(config.env_list())
    config.get_env(env_name, loaders=[loader])
```

To accomplish the same, I have my own executor where I can simply rewrite the option in the request:
```python
class CurrentEnvRunExecutor(Execute):
    def build_instance(
        self,
        request,
        options,
        out,
        err,
    ):
        # Disable check for the external commands,
        # all of them are external for us.
        request.allow = None
        return LocalSubProcessExecuteInstance(request, options, out, err)
```

**Comment by gaborbernat** [comment]
At that point, the config is already constructed. You're trying to construct it again that's causing the infinite recursion. If you want to extend the loaders can't you directly insert the memory loader into env_conf?

**Comment by gaborbernat** [comment]
https://github.com/tox-dev/tox/blob/rewrite/src/tox/config/sets.py#L27. e.g. https://github.com/tox-dev/tox-gh/blob/main/src/tox_gh/plugin.py#L63

**Comment by frenzymadness** [comment]
Thanks for your help, this little piece of code solved my problem:
```python
@impl
def tox_add_env_config(env_conf, config):
    # This allows all external commands.
    # All of them are extenal for us.
    loader = MemoryLoader(allowlist_externals=["*"])
    config.core.loaders.insert(0, loader)
```
I see that you want to use this issue for better documentation of loaders so I'm gonna keep it open.
