### ISSUE TITLE
tox4: --colored is yes by default

### ISSUE THREAD

**Issue by AntoineD** [tox-dev/tox#2288]
With tox4a9, contrary to the [docs](https://tox.wiki/en/rewrite/cli_interface.html#tox---colored) `--colored` is yes by default.
What is the expected default?

**Comment by gaborbernat** [comment]
Yes, colored is on but default is the expected behaviour.

**Comment by AntoineD** [comment]
Would you like a PR to fix the docs?

**Comment by gaborbernat** [comment]
Yes, please 👍

**Comment by gaborbernat** [comment]
We likely want to set `FORCE_COLOR` for the doc build 😊 in readthedocs. I like the current runtime logic and don't want to touch it.
