### ISSUE TITLE
4.0.0a10 missing from github

### ISSUE THREAD

**Issue by adamchainz** [tox-dev/tox#2312]
I noticed that there's 4.0.0a10 on PyPI but no corresponding tag on GitHub. Was it accidentally missed during release?

**Comment by gaborbernat** [comment]
It was there as tag.  We don't use the Github release feature necessarily, so the releases tab might be outdated, but it's the tag that really counts. Mirrored to release now - https://github.com/tox-dev/tox/releases/tag/4.0.0a10

Any reason you work of releases and not tags?

**Comment by adamchainz** [comment]
I don't work off them, in fact I don't care for them :P . I just loaded the repo and saw GitHub shows the latest release on the repo page, assumed it was a missing tag. You can disable display of the release on the repo front page with the cog top right of the settings page.
