### ISSUE TITLE
The `-c` flag in `deps` doesn't affect the `extras`

### ISSUE THREAD

**Issue by dvarrazzo** [tox-dev/tox#2319]
Hello,

We have a constraint file, containing:
```
pytest-asyncio == 0.16.0
```

and the dependency in `setup.py`:
```
    "test": [
        "pytest-asyncio >= 0.16",
    ],
```

We have made a change that breaks pytest-asyncio 0.16, so we expect tests to fail.

This didn't happen on the entire grid  [in this test run](https://github.com/psycopg/psycopg/runs/4807916830?check_suite_focus=true): The `python` tests passed because pytest-asyncio 0.17.0 was installed anyway. The `c` tests failed as expected.

The difference between the two is that the `python` configuration looks like:

```
[testenv]
commands =
    python -bb -m pytest {posargs}
extras = test
deps =
    -c {toxinidir}/../tests/constraints.txt
```

whereas the `c` configuration looks like:

```
[testenv]
commands =
    python -bb -m pytest {posargs}
deps =
    -e {toxinidir}/../psycopg[test]
    -c {toxinidir}/../tests/constraints.txt
```

My expectation is that `-c` would apply to the packages installed by `extras` config entry too, not only to what installed by `deps`.

Is my expectation wrong or is this a bug? Is there a way to apply the `-c` to the extras too, or is it right to use  `-e {toxinidir}/../psycopg[test]` to test the `psycopg` package too?

Thank you very much!

**Comment by jugmac00** [comment]
This is working as expected, or at least as agreed upon :-)

This situation has been discussed before in
https://github.com/tox-dev/tox/issues/1939

There is also a faq entry (admittedly only in the documentation for the upcoming version 4):
https://tox.wiki/en/rewrite/faq.html#using-constraint-files

In the above bug discussion there is also an example shown for the solution via the `install_command` - maybe that should be added to the faq? @gaborbernat 

https://github.com/tox-dev/tox/issues/1939#issuecomment-814851730

**Comment by gaborbernat** [comment]
> In the above bug discussion there is also an example shown for the solution via the `install_command` - maybe that should be added to the faq? @gaborbernat

IMHO tox 4 is enough here, hopefully in 2-3 months is out and then is no longer a problem. In the meantime, if someone can put in a PR for the old doc sure, we can merge it; but I'd not keep an issue open for it for now, considering it's fixed in v4.

**Comment by jugmac00** [comment]
I was thinking of adding the example from https://github.com/tox-dev/tox/issues/1939#issuecomment-814851730 to the tox 4 faq.

see #2320

**Comment by dvarrazzo** [comment]
Thank you very much. Using `PIP_CONSTRAINT` seems the best option, because it can be set with the least repetitions and also added to `pasenv` and set from the outside.

One note: [the docs](https://tox.wiki/en/rewrite/faq.html#using-constraint-files) have a typo: the var name is `PIP_CONSTRAINT`, not the plural.

Cheers!
