### ISSUE TITLE
Linking extension in venv created by via MSVC's link fails using GitHub's `windows-2022` image

### ISSUE THREAD

**Issue by adamreichold** [tox-dev/tox#2354]
GitHub Actions recently [switched](https://github.com/actions/virtual-environments/issues/4856) their `windows-latest` alias from `windows-2019` to `windows-2022` which lead to tox-based tests of an extension using `rust-numpy` to start failing as inside of the venv created by tox, `link.exe` was resolved to the GNU `link` utility installed with Git for Windows instead of MSVC's linker.

[Here](https://github.com/PyO3/rust-numpy/runs/5153579543?check_suite_focus=true) is the first job that failed. And [here](https://github.com/PyO3/rust-numpy/runs/5153946654?check_suite_focus=true) is the same job working with the only difference being that `windows-latest` was replaced by `windows-2019.

**Comment by gaborbernat** [comment]
I don't see how this is an issue in the control of tox. IMHO this is most likely up to Github, but at best you could say it's pip.
