### ISSUE TITLE
Colors suggestion

### ISSUE THREAD

**Issue by henryiii** [tox-dev/tox#2356]
I'm liking the tox4 colors, but I think the bold should continue all the way to the `>`.  For something like `py39-test: commands[0]> pytest`, there are three things to visually parse split by `:` and `>`. Having the color change after the `:` and the bold change after the >`` might be a good way to help it be visually parsable into three segments without introducing another color (another color is just fine by me, too).

<img width="1074" alt="Screen Shot 2022-02-15 at 3 18 02 PM" src="https://user-images.githubusercontent.com/4616906/154142303-c0b17164-9440-48bc-9158-0f564938facb.png">

**Comment by mxd4** [comment]
Hi, you're right there is a need to make the actual commands stand out.
I think the second text block (between `:` and `>`) should be a different color from the actual commands, **and** bold as well.
