### ISSUE TITLE
Make tox available as pre-commit hook

### ISSUE THREAD

**Issue by lcnittl** [tox-dev/tox#2361]
I believe it could be very useful to have a hook for `tox` usable in pre-commit.

Of course it would be somewhat ridiculous to run them at `pre-commit` stage, but I can imagine that this could be quite handy at a [`pre-push`](https://pre-commit.com/#pre-commit-during-push) stage, to be "reminded" (😄) to run testing locally, before breaking a CI/CD pipeline.

Thanks for your consideration!
Cheers, lcnittl

**Comment by gaborbernat** [comment]
`tox` is a bit too heavy to be invoked automatically, so I'd say -1 to this, but I'll let @asottile weigh in 👍

**Comment by asottile** [comment]
agreed, tox doesn't really fit the model (slow, not self contained)

you can always set up a local hook if you need it but it doesn't really make sense

**Comment by gaborbernat** [comment]
For reference, @asottile is the primary maintainer of pre-commit so he knows the best.
