### ISSUE TITLE
Delete `tox` mailing list

### ISSUE THREAD

**Issue by jugmac00** [tox-dev/tox#2364]
After careful consideration, we, the `tox` maintainers, have come to the conclusion that it is not worth any more to continue the `tox` mailing list.

In the last year, and especially in the last couple of months there have been almost only spam emails, which are both distracting and bind maintainer time (block spammers etc).

As alternative channels to contact us and to get help, we have
- https://github.com/tox-dev/tox/discussions
- https://discord.gg/tox
- https://stackoverflow.com/questions/tagged/tox
and all maintainers are active on Twitter, too.

A PR will follow to remove the link to the `tox` mailing list from our documentation.

**Comment by gaborbernat** [comment]
Resolved by https://github.com/tox-dev/tox/pull/2365
