### ISSUE TITLE
Tox passenv by default only passes HTTP_PROXY but not http_proxy

### ISSUE THREAD

**Issue by poggenhans** [tox-dev/tox#2372]
According to the docs, tox passenv is [case insensitive](https://tox.wiki/en/latest/config.html#conf-passenv). Apparently this is not the case for variables passed through by default. This means that e.g. `HTTP_PROXY` will be forwarded by default, but not `http_proxy`. This is a problem because some linux programs look for the upper-case version (e.g. `pip`) and some for the lower-case version (e.g. `apt` and `git`).

This problem can be worked around by explicitly setting `passenv = HTTP_PROXY HTTPS_PROXY`, because then tox will also include the lower-case pendants, but this feels a bit counter-intuitive.

I'd propose to either include the lower-cased proxy variables into the list of default variables (and clarify in the docs that case-insensitivity doesn't apply for default variables) or treat all default variables as case insensitive. I can also prepare a PR for any of the two solutions if desired.

**Comment by jugmac00** [comment]
As @poggenhans volunteered to create a PR, @gaborbernat, which of the two suggested solutions do you prefer?
