### ISSUE TITLE
tox4: (regression) unable to run interactive commands

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox#2374]
While with tox 3 it was possible to start interactive commands as shells, with tox4 this is no longer possible because apparently there is some buffering implied which has two side effects:

* Output not displayed until a new line is send, so `login:` prompt would not be seen
* What you type is not displayed

I tried setting `PYTHONUNBUFFERED=1` but it has no effect.

If you happened to had a tox env that runs `docker run -it container-name /bin/bash`, debugging would become close to impossible with tox4.

**Comment by gaborbernat** [comment]
PRs to address this are welcome, note though this likely is a **very** hard PR. I'll mark it not important enough though to block release. Furthermore, your report is missing many required information: OS and console manager you're using, for example, project. This should work (mostly) on Linux, I've tried with PDB/breakpoint, not sure how much docker differs. Might be related to https://github.com/tox-dev/tox/issues/1773

**Comment by ssbarnea** [comment]
I will try to narrow it down tomorrow. I wondered myself because I do remember being able to use pdb too, so it might not really be a general problem that breaks all interactive consoles.

tx

**Comment by masenf** [comment]
> this likely is a very hard PR

still a work in progress, but I think [this PR](https://github.com/tox-dev/tox/pull/2711) will address this issue.

**Comment by masenf** [comment]
@ssbarnea this should be fixed on posix platforms as of [tox 4.0.12](https://tox.wiki/en/latest/changelog.html#v4-0-12-2022-12-16) please try again and reopen if you still face issues running interactive commands.

For Windows specifically, we are tracking pty support with #2337, but likely not happening any time soon.
