### ISSUE TITLE
tox3 30s delay caused by DNSServiceCreateConnection on macos

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox#2375]
More than an year after https://github.com/tox-dev/tox/issues/1735 was closed and locked, I was able to find what was causing it.

It happens on MacOS only when tox.ini file was modified, so if you run it again, it will not be affected by that undesired 30s delay, which is extremely annoying as it applies even for `tox -l` commands.

Here is the culprit from MacOS Console:
```
default	08:08:07.717039+0000	mDNSResponder	[R1351382] DNSServiceCreateConnection START PID[53961](python3.10)
default	08:08:07.717132+0000	mDNSResponder	[R1351383] DNSServiceQueryRecord(1D000, 0, <mask.hash: 'W4U2JyNMP4qPLaREUfA9Aw=='>, Addr) START PID[53961](python3.10)
default	08:08:07.717885+0000	mDNSResponder	[R1351384] DNSServiceQueryRecord(1D000, 0, <mask.hash: 'W4U2JyNMP4qPLaREUfA9Aw=='>, AAAA) START PID[53961](python3.10)
default	08:08:07.718398+0000	mDNSResponder	[R1351383] DNSServiceQueryRecord(1D000, 0, <mask.hash: 'AxiCO2kN2tb6f+xUNi2KVQ=='>, Addr) STOP PID[53961](python3.10)
default	08:08:07.718460+0000	mDNSResponder	[R1351384] DNSServiceQueryRecord(1D000, 0, <mask.hash: 'AxiCO2kN2tb6f+xUNi2KVQ=='>, AAAA) STOP PID[53961](python3.10)
default	08:08:07.719293+0000	mDNSResponder	[R1351385] DNSServiceQueryRecord(15000, 0, <mask.hash: 'BbGOo0pN8UoXPv6jtlO7tg=='>, PTR) START PID[53961](python3.10)
default	08:08:37.720264+0000	mDNSResponder	[R1351385] DNSServiceQueryRecord(15000, 0, <mask.hash: 'lubOf0RtXl5C9ERWs7ZGfQ=='>, PTR) STOP PID[53961](python3.10)
default	08:08:37.745626+0000	mDNSResponder	[R1351382] DNSServiceCreateConnection STOP PID[53961](python3.10)
```

I am not sure what is causing it. I should mention that I do have a full dual IPv4 and IPv6 connectivity on that machine, something that is still not very common. You current stack status can easily be verified with a site like https://ipv6-test.com/

Reference: https://bugs.python.org/issue35164

**Comment by ssbarnea** [comment]
After bit more debugging, I was able to find a way to enable the logging of the effective [dns queries](https://apple.stackexchange.com/questions/438146/how-to-decode-dnsservicequeryrecord-requests-for-debugging-purposes) and I found the culprit, the attempt to do the reverse hostname check.

It is even visible on my example, the DNS query that takes 30s is the PTR one. The other 2 queries are resolving current hostname to IPv4 and IPv6, which works instantly.

Why tox really needs to do this and why it seems to be doing it when `tox.ini` is touched are two other interesting questions.

**Comment by ssbarnea** [comment]
@gaborbernat Considering that the Python bugs was not fixed in 4 years and I doubt it will, how are you feeling about replacing the `socket.getfqdn()` with `socket.gethostname()` which is not affected by that problem?

As the bug is specific to macos, we could add wrapper function and make it use full one for non macos and return short/fast one on macos.

**Comment by gaborbernat** [comment]
> @gaborbernat Considering that the Python bugs was not fixed in 4 years and I doubt it will, how are you feeling about replacing the `socket.getfqdn()` with `socket.gethostname()` which is not affected by that problem?

Sounds good 👍

**Comment by frankgu968** [comment]
Just discovered this thread while googling for a separate issue. Perhaps this is also related: https://apple.stackexchange.com/questions/175320/why-is-my-hostname-resolution-taking-so-long
