### ISSUE TITLE
support a tox-ini-dir environment variable

### ISSUE THREAD

**Issue by jdknight** [tox-dev/tox#2381]
I would like to suggest the introduction of a `TOX_INI_DIR` environment variable which holds the same value as `{toxinidir}` does. The goal is to provide an environment variable which a project's testing logic can refer to when trying to use artifacts stored in a project's repository. While tests could refer to `__file__` to help find artifacts based off the path of a test's source file, the `__file__` environment may not always be set to an absolute path (based on which interpreter is being tested). In a situation where a test environment changes the tox's working directory (`--workdir`), it may not be possible to find desired artifacts for a test.

An existing workaround for such a case is to manually prepare a `TOX_INI_DIR` environment variable based off of `{toxinidir}` inside a `tox.ini` file:
```
setenv =
    TOX_INI_DIR={toxinidir}
```

**Comment by gaborbernat** [comment]
Hello,

> An existing workaround for such a case is to manually prepare a `TOX_INI_DIR` environment variable based off of `{toxinidir}` inside a `tox.ini` file:
> 
> ```
> setenv =
>     TOX_INI_DIR={toxinidir}
> ```

Yeah, you should use this solution. This is not a widely requested feature to make this the default, so you're encouraged to enable it via config in the meantime.
