### ISSUE TITLE
ModuleNotFoundError exception when trying to use tox with a Python version installed using pyenv

### ISSUE THREAD

**Issue by lgp171188** [tox-dev/tox#2384]
On the Kubuntu 21.10 installation in my laptop, I have installed `tox`(version `3.24.1`) from the official Ubuntu repositories. Python 3.9 is the default installed version of Python 3. Since the project that I work on, `lpcraft`, requires Python 3.8, I installed Python `3.8.13` using `pyenv` (the git checkout method). I have set Python `3.8.13` as a global version in `pyenv`.

When I try to run any environment that uses Python 3.8, it errors out with an exception.
```
$ tox -rvv -e lint
using tox.ini: /home/guruprasad/d/c/lpcraft/tox.ini (pid 116411)
  removing /home/guruprasad/d/c/lpcraft/.tox/log
using tox-3.21.4 from /usr/lib/python3/dist-packages/tox/__init__.py (pid 116411)
python3.8 (/home/guruprasad/.pyenv/shims/python3.8) is {'executable': '/home/guruprasad/.pyenv/versions/3.8.13/bin/python3.8', 'implementation': 'CPython', 'version_info': [3, 8, 13, 'final', 0], 'version': '3.8.13 (default, Mar 22 2022, 11:22:05) \n[GCC 11.2.0]', 'is_64': True, 'sysplatform': 'linux', 'extra_version_info': None}
lint uses /home/guruprasad/.pyenv/versions/3.8.13/bin/python3.8
lint start: getenv /home/guruprasad/d/c/lpcraft/.tox/lint
lint cannot reuse: -r flag
lint create: /home/guruprasad/d/c/lpcraft/.tox/lint
  removing /home/guruprasad/d/c/lpcraft/.tox/lint
setting PATH=/home/guruprasad/d/c/lpcraft/.tox/lint/bin:/home/guruprasad/.pyenv/versions/:/home/guruprasad/.pyenv/shims:/home/guruprasad/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/guruprasad/local/bin
[116437] /home/guruprasad/d/c/lpcraft/.tox$ /usr/bin/python3 -m virtualenv --no-download --python /home/guruprasad/.pyenv/versions/3.8.13/bin/python3.8 lint
created virtual environment CPython3.8.13.final.0-64 in 71ms
  creator CPython3Posix(dest=/home/guruprasad/d/c/lpcraft/.tox/lint, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/guruprasad/.local/share/virtualenv)
    added seed packages: pip==20.3.4, pkg_resources==0.0.0, setuptools==44.1.1, wheel==0.34.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
lint installdeps: pre-commit
setting PATH=/home/guruprasad/d/c/lpcraft/.tox/lint/bin:/home/guruprasad/.pyenv/versions/:/home/guruprasad/.pyenv/shims:/home/guruprasad/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/guruprasad/local/bin
[116445] /home/guruprasad/d/c/lpcraft$ /home/guruprasad/d/c/lpcraft/.tox/lint/bin/python -m pip install pre-commit
Traceback (most recent call last):
  File "/home/guruprasad/.pyenv/versions/3.8.13/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/guruprasad/.pyenv/versions/3.8.13/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/guruprasad/d/c/lpcraft/.tox/lint/lib/python3.8/site-packages/pip/__main__.py", line 23, in <module>
    from pip._internal.cli.main import main as _main  # isort:skip # noqa
  File "/home/guruprasad/d/c/lpcraft/.tox/lint/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/guruprasad/d/c/lpcraft/.tox/lint/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/guruprasad/d/c/lpcraft/.tox/lint/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/guruprasad/d/c/lpcraft/.tox/lint/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._vendor.packaging.utils import cize_name
ModuleNotFoundError: No module named 'pip._vendor.packaging'
ERROR: invocation failed (exit code 1)
ERROR: could not install deps [pre-commit]; v = InvocationError('/home/guruprasad/d/c/lpcraft/.tox/lint/bin/python -m pip install pre-commit', 1)
lint finish: getenv /home/guruprasad/d/c/lpcraft/.tox/lint after 0.30 seconds
__________________________________________________________________________________________ summary __________________________________________________________________________________________
ERROR:   lint: could not install deps [pre-commit]; v = InvocationError('/home/guruprasad/d/c/lpcraft/.tox/lint/bin/python -m pip install pre-commit', 1)
```
Running the same `pip` installation command using the pyenv-installed `python` script/binary works okay without any errors. 

**Steps to reproduce**
* Install `tox` version 3.24.1, preferably from the Ubuntu 21.10 repositories if possible.
* Install `pyenv` using the Git checkout method.
* Install Python 3.8.13 using `pyenv`.
* Make the `3.8.13` version global.
* Clone the `lpcraft` repository locally

       git clone https://git.launchpad.net/lpcraft 
* Navigate inside the `lpcraft` directory.
* Run `tox -e lint` or `tox -e py38`
* The command will fail with an exception similar to the one that I have pasted above.

**Comment by lgp171188** [comment]
This issue doesn't happen if I install the `tox-pyenv` plugin. So could the necessity of this plugin be documented somewhere, if relevant?

**Comment by gaborbernat** [comment]
> * Install `tox` version 3.24.1, preferably from the Ubuntu 21.10 repositories if possible.

We don't support the Ubuntu repositories so not much to do with us.

> ```
> [116445] /home/guruprasad/d/c/lpcraft$ /home/guruprasad/d/c/lpcraft/.tox/lint/bin/python -m pip install pre-commit
> Traceback (most recent call last):
>   File "/home/guruprasad/.pyenv/versions/3.8.13/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/home/guruprasad/.pyenv/versions/3.8.13/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/home/guruprasad/d/c/lpcraft/.tox/lint/lib/python3.8/site-packages/pip/__main__.py", line 23, in <module>
>     from pip._internal.cli.main import main as _main  # isort:skip # noqa
>   File "/home/guruprasad/d/c/lpcraft/.tox/lint/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 10, in <module>
>     from pip._internal.cli.autocompletion import autocomplete
>   File "/home/guruprasad/d/c/lpcraft/.tox/lint/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
>     from pip._internal.cli.main_parser import create_main_parser
>   File "/home/guruprasad/d/c/lpcraft/.tox/lint/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
>     from pip._internal.cli import cmdoptions
>   File "/home/guruprasad/d/c/lpcraft/.tox/lint/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
>     from pip._vendor.packaging.utils import cize_name
> ModuleNotFoundError: No module named 'pip._vendor.packaging'
> ```

As this part shows the error happens within pre-commit, so nothing to do with tox. Likely the issue will be something `virtualenv` related, as see here:


```
[116437] /home/guruprasad/d/c/lpcraft/.tox$ /usr/bin/python3 -m virtualenv --no-download --python /home/guruprasad/.pyenv/versions/3.8.13/bin/python3.8 lint
created virtual environment CPython3.8.13.final.0-64 in 71ms
  creator CPython3Posix(dest=/home/guruprasad/d/c/lpcraft/.tox/lint, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/guruprasad/.local/share/virtualenv)
    added seed packages: pip==20.3.4, pkg_resources==0.0.0, setuptools==44.1.1, wheel==0.34.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
```

`pkg_resources==0.0.0` is not too promising. Again the `virtualenv` project itself is not maintaining/responsible for what you get from Debian. Based on what I see this is a bug in the virtualenv repackaging for Debian and you should report it there.

**Comment by lgp171188** [comment]
> As this part shows the error happens within pre-commit, so nothing to do with tox. Likely the issue will be something virtualenv related, as see here:

@gaborbernat, this error also happens with other environments that do not use `pre-commit` at all. Since the issue got resolved by installing `tox-pyenv` and this is likely a distribution packaging issue, I will try recreating the issue with tox installed directly from PyPI and report here if I see the same issue. Thank you!

**Comment by gaborbernat** [comment]
As said above the problem is the usage of the Debian virtualenv/tox package.
