### ISSUE TITLE
[Windows] User site-packages is not added to python path when running test with sitepackages = true

### ISSUE THREAD

**Issue by niander** [tox-dev/tox#2402]
In Windows, the default user site-packages location is `%APPDATA%\Python\PythonXY\site-package`. If `%APPDATA%` doesn't exist, python won't find the user site-packages folder and won't add it to the python path.

When using tox with the `sitepackages = true` option, even though a normal virtual environment would have the user site-packages in the python path, it seems that because tox doesn't add `%APPDATA%` to the subprocess environment, python can't find whatever packages are expected to exist in the user site-packages folder when it is being executed in a toxenv.

This is about the **user** site-packages folder, not the system one.

**Comment by jugmac00** [comment]
Hey @niander,

Thanks for the bug report.

Could you please add the output of `tox -rvv` as requested in the issue template?

Could you please also test whether this bug still exists in tox 4 beta? https://pypi.org/project/tox/4.0.0b2/

FWIW there is no issue on Linux - `sitepackages = true` works as expected - I tried this with `pygments` which is available in my `site-packages` but not in the project.

```
from setuptools import setup, find_packages

setup(
    name='MyPackageName',
    version='1.0.0',
    author='Author Name',
    author_email='author@example.net',
    description='Description of my package',
    packages=find_packages(),
)
```

```
[tox]

[testenv]
commands = python -c "import pygments; print(dir(pygments))"
;sitepackages = true
```

That said I have no access to a Windows box, so let's wait for the output of `tox -rvv` and the results when you use tox 4.

**Comment by niander** [comment]
I updated the issue.

Using your setup.py and the following tox.ini:

```
[tox]

[testenv]
sitepackages = true
commands = python -c "import attr; print(attr)"
```

Notice that the package `attr` is installed in the **user** site-packages (not system site-packages):

`python -c "import att; print(attr)"`:
```
<module 'attr' from 'C:\\Users\\niassis\\AppData\\Roaming\\Python\\Python37\\site-packages\\attr\\__init__.py'>
```
* Python 3.7.9 and tox==3.25.0

`tox -rvv`: [output-tox3.txt](https://github.com/tox-dev/tox/files/8506966/output-tox3.txt)

* Python 3.7.9 and tox==4.0.0b2

`tox -rvv`: [output-tox4.txt](https://github.com/tox-dev/tox/files/8507001/output-tox4.txt)

**Comment by niander** [comment]
I don't think this issue exists outside Windows specifically because of the special treatment that Windows receives when looking for user site-packages. Check this code in [`site.py`](https://github.com/python/cpython/blob/dbd9d75fedfebb215fe3e2b60249ac642cc8abf2/Lib/site.py#L277)
That being said, this issue makes using the plugin `tox-conda` impossible since conda environments include user site-packages by default and because during the `install-deps` step `%APPDATA%` seems to still exists in the environment of the subprocess, which is not true for when it is just running commands. I think this is something that the `tox-conda` plugin modify.

**Comment by niander** [comment]
I found where the passenv are defined. I will make a PR with the proposed change.

**Comment by jugmac00** [comment]
Thanks for your contribution. While I had a hunch it is about env variables, as I have no access to a Windows box, I asked a colleague to take a look at this issue/PR.
