### ISSUE TITLE
tox doesn't work as expected in CI

### ISSUE THREAD

**Issue by demberto** [tox-dev/tox#2403]
My library [tkinter-msgcat](https://github.com/demberto/tkinter-msgcat) runs `coverage` commands from `tox`. This does create coverage data files locally on Windows in `{toxinidir}` as expected. However this doesn't happen in Github CI.

I don't exactly know which one is the issue, Github CI, `tox` or `coverage.py`, but one thing to be noted is that, when I run `coverage.py` directly in the CI (in my library [PyFLP](https://github.com/demberto/PyFLP)), it does create the coverage data files, which makes me suspect tox itself is the issue.

**Comment by gaborbernat** [comment]
Please post the output from tox -rvv

**Comment by demberto** [comment]
> Please post the output from tox -rvv

From local PC or from CI?

**Comment by gaborbernat** [comment]
Well from the env where you observe the problem 🤷

**Comment by demberto** [comment]
I am using tox-gh-actions so this is all the output I get:

```
using tox.ini: /home/runner/work/tkinter-msgcat/tkinter-msgcat/tox.ini (pid 1690)
running tox-gh-actions
original envconfigs: ['.package', 'py37', 'py3[8](https://github.com/demberto/tkinter-msgcat/runs/6074419602?check_suite_focus=true#step:5:8)', 'py3[9](https://github.com/demberto/tkinter-msgcat/runs/6074419602?check_suite_focus=true#step:5:9)', 'py3[10](https://github.com/demberto/tkinter-msgcat/runs/6074419602?check_suite_focus=true#step:5:10)', 'docs', 'linters', 'coverage', 'flake8', 'pylint', 'bandit']
original envlist_default: ['py37', 'py38', 'py39', 'py310', 'docs', 'linters']
original envlist: ['py37', 'py38', 'py39', 'py310', 'docs', 'linters']
Python versions: ['3.10', '3']
tox-gh-actions config: {'python': {}, 'env': {}}
using the following factors to decide envlist: []
overriding envlist with: []
enabling problem matcher
using tox-3.25.0 from /opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/tox/__init__.py (pid [16](https://github.com/demberto/tkinter-msgcat/runs/6074419602?check_suite_focus=true#step:5:16)90)
___________________________________ summary ____________________________________
  congratulations :)
disabling problem matcher
```

**Comment by gaborbernat** [comment]
Without providing what I asked for there's not much I can do here.

**Comment by demberto** [comment]
> Without providing what I asked for there's not much I can do here.

Ok I will try it on an Ubuntu VM to confirm if its really tox that causes this
