### ISSUE TITLE
Generalizing testenv

### ISSUE THREAD

**Issue by brandon-leapyear** [tox-dev/tox#2412]
It seems to me that `[testenv]` does at least two things:
1. Specify the base environment that all other testenvs inherit from
2. Provide the fallback case for any env not matched by any other `[testenv:...]` definition

It seems like these two features should be explicit:
1. Add a `parent` option for a `testenv` to specify another `testenv` to inherit from
    * ~[This comment](https://github.com/tox-dev/tox/issues/1433#issuecomment-540961053) seems to imply this will be handled by tox 4, but I can't see any mention in #1394 about this~ I do see the docs for this now! Seems to be implemented in https://github.com/gaborbernat/tox/commit/575f648bec4720b4d5e47fd8a1e73fbe22e9f6da
2. Allow patterns in a testenv name; e.g. `[testenv:*-dist]`
    * Related: https://github.com/tox-dev/tox/issues/189
    * Use cases:
        * Set `usedevelop` by default, but adding `-dist` to the end of any environment uses a wheel build
        * If someone had two test frameworks (e.g. a pytest suite and a unittest suite), you could have both `[testenv:pytest-*]` and `[testenv:unittest-*]`
            * I guess the current approach for this is to have two different `tox.ini` files
            * Generative sections don't completely help here, as I'd like to keep the current `[testenv]` functionality of being to specify both `py37-django15` and `py37-pandas13`; a generative section like `py{37,38,39,310}-django{15,16}-pandas{11,12,13}` will require both django + pandas to be specified. Adding a trailing comma like `py{37,38}-django{15,16,}-pandas{11,12,13,}` doesn't work; it will require matching `py37--pandas11`.

With these two features, a tox 3 config
```ini
[testenv]
...

[testenv:docs]
...
```
would be equivalent to
```ini
[testenv:*]
...

[testenv:docs]
parent = [testenv:*]
...
```

**Comment by gaborbernat** [comment]
tox 4 uses the key base instead of parent, but the feature is there, check the documentation 👌

**Comment by gaborbernat** [comment]
tox 4 uses the key base instead of parent, but the feature is there, check the documentation 👌

**Comment by brandon-leapyear** [comment]
@gaborbernat what about the second feature mentioned?

**Comment by gaborbernat** [comment]
> @gaborbernat what about the second feature mentioned?

no plans, we will add python config support that will allow this advanced use case
