### ISSUE TITLE
`install_command` only accepts a single command, but the documentation says that I can “provide arbitrary commands” to it

### ISSUE THREAD

**Issue by oakkitten** [tox-dev/tox#2433]
The documentation for `install_command` says,

> Note: You can also provide arbitrary commands to the `install_command`. (...)

I don't think this is correct. Given this config,

```ini
[tox]
skip_install = true
skipsdist = true
envlist = foo

[testenv]
install_command =
    echo '!!!!!!!!!!!!!!!!!!!!!!! install 1' {packages}
    echo '!!!!!!!!!!!!!!!!!!!!!!! install 2' {packages}
commands =
    echo '!!!!!!!!!!!!!!!!!!!!!!! test' {envname}
allowlist_externals =
    echo
deps =
    zoo
```

tox 3 will only execute the first command:

```
$ python -m tox -rvv
...
[1190] /mnt/c/Users/s/tox_install_command_test$ /usr/bin/echo '!!!!!!!!!!!!!!!!!!!!!!! install 1' zoo
!!!!!!!!!!!!!!!!!!!!!!! install 1 zoo
foo finish: getenv /mnt/c/Users/s/tox_install_command_test/.tox/foo after 17.95 seconds
...
```

and tox 4 will execute what appears to be the two commands glued together as one, but only replacing the first `{packages}`

```
$ python -m tox -rvv
...
foo: 20300 W install_deps> echo '!!!!!!!!!!!!!!!!!!!!!!! install 1' zoo echo '!!!!!!!!!!!!!!!!!!!!!!! install 2' '{packages}' [tox/tox_env/api.py:398]
!!!!!!!!!!!!!!!!!!!!!!! install 1 zoo echo !!!!!!!!!!!!!!!!!!!!!!! install 2 {packages}
foo: 20324 I exit 0 (0.01 seconds) /mnt/c/Users/s/tox_install_command_test> echo '!!!!!!!!!!!!!!!!!!!!!!! install 1' zoo echo '!!!!!!!!!!!!!!!!!!!!!!! install 2' '{packages}' pid=1269 [tox/execute/api.py:275]
...
```

I suppose that tox should:
  * Change the documentation so that it doesn't say that I can use command“s” in `install_command`;
  * Produce an error if I try, instead of ignoring lines or gluing them together.

Also, tox might:
  * Support multiple installation commands via `install_commands` (note the ”s”), and only require `{packages}` to be passed to one of them;
  * Deprecate `install_command` in favor of the above.

See logs: [tox3.txt](https://github.com/tox-dev/tox/files/8827179/tox3.txt), [tox4.txt](https://github.com/tox-dev/tox/files/8827180/tox4.txt).

**Comment by gaborbernat** [comment]
I think here the documentation is where the issue is. The `install_command` was designed and always only allowed one command to be specified. And I'd keep that behaviour. If you want to call multiple ones you should create a shim python script that forwards our one call to multiple ones.

**Comment by oakkitten** [comment]
May I ask why not allow multiple commands? Besides, wouldn't reusing the logic from `commands` simplify things? Anyway, in the case of a single command, it would be nice to have an error of sorts if the user does try to put multiple.

**Comment by gaborbernat** [comment]
> May I ask why not allow multiple commands?

To limit complexity in tox. 1 command is enough 99% of time and when it's not can be worked around the users.

> Anyway, in the case of a single command, it would be nice to have an error of sorts if the user does try to put multiple.

I believe this should happen in tox 4 🤔

**Comment by oakkitten** [comment]
> To limit complexity in tox. 

But if you reused the logic from `commands`, wouldn't it _reduce_ complexity?

> I believe this should happen in tox 4 🤔

While I didn't test with main, the snippets above use 4.0.0b1.

**Comment by gaborbernat** [comment]
> But if you reused the logic from `commands`, wouldn't it _reduce_ complexity?

Those two are handled conceptually differently and I'd not overload them. You introduce a lot of complexity there, what if the first command fails and the second succeeds. Again, if you must you can achieve this by writing a custom plugin. The core tox will not support this thought.

**Comment by oakkitten** [comment]
With `commands`, if the first command fails, the second isn't run. I would expect exactly the same behavior from `install_command`. I am not sure how these are conceptually different.

But I guess since `install_command` is deprecated it's not worth discussing it. (When will it be removed? I don't think that documentation mentions that it's deprecated.)
