### ISSUE TITLE
tox4: fails when invoked inside Git bash (MINGW64)

### ISSUE THREAD

**Issue by johannesloibl** [tox-dev/tox#2437]
When execution any tox command inside a Git bash shell following error occurs:

![image](https://user-images.githubusercontent.com/48917891/171736856-e839bbd5-b7df-4413-90b5-51c7ecdbeb5a.png)

Tox version 4.0.0b4 (tox 3.25 works fine)

**Comment by jugmac00** [comment]
I have no access to a Windows box - yet... I pinged a friend at Microsoft.

**Comment by ssbarnea** [comment]
One first question here is if we should support MINGW under Windows as we already have: navite and WSL paths. I did not imagine that MinGW is still a thing in 2022.

**Comment by ssbarnea** [comment]
Closing as unable to reproduce. I installed mingw and tried running tox 4 with tox repository itself, so far it worked fine.
