### ISSUE TITLE
Introducing PyQt5 to project causes SIGABRT

### ISSUE THREAD

**Issue by Zlopez** [tox-dev/tox#2440]
## Description
After adding PyQt5 library to project `pytest` started to fail with `SIGABRT`. Initially I thought this is a `pytest` issue, but running the command manually inside the virtual environment works without issue.

### What fails
`tox -e py310` fails as well for other python version `py39` `py38`

### What works
`source .tox/py310/bin/activate.fish`
`py.test -vv --cov-config .coveragerc --cov=qadventure --cov-report term --cov-report xml --cov-report html`

### PR with the change
https://github.com/Zlopez/QAdventure/pull/5
Branch `main` is passing all the tox tests.

### Output of `tox -rvve py310`
[tox.log](https://github.com/tox-dev/tox/files/8889285/tox.log)

**Comment by jugmac00** [comment]
The issue might be that PyQt5 expects some environment variables to be set, and tox isolates the build.

As a first check, I would suggest to configure tox to pass all environment variables into the build:
```
[testenv]
passenv = *
```

If that works, I suggest to lookup the PyQt5 documentation to only pass in the required environment variables, ie
```
passenv = FOO BAR
```

**Comment by Zlopez** [comment]
Thanks to the help, this was it.

I fixed this by adding
```
[testenv]
passenv = DISPLAY
```
