### ISSUE TITLE
tox.wiki documentation site offline

### ISSUE THREAD

**Issue by niccokunzmann** [tox-dev/tox#2452]
When I go to https://pypi.org/project/tox/
I can see that https://tox.wiki/ should have the documentation
When I open https://tox.wiki/
This website does not work.

    Unable to connect

**Comment by jugmac00** [comment]
Works for me. Do you still experience issues? Maybe it was a temporary glitch?

If you have still issues, you could run traceroute to pinpoint the problem.

**Comment by niccokunzmann** [comment]
@jugmac00 It works now. Thanks!
