### ISSUE TITLE
Where to document installation of different Python versions

### ISSUE THREAD

**Issue by niccokunzmann** [tox-dev/tox#2453]
Many projects use tox for their tests.
Usually, they test with several Python versions.

As a newcomer to these projects, to testing, to tox, I have a hard time figuring out how to install different Python versions next to each other and how to use them with tox. As a result, I will probably only test the code with one Python version - the one installed.

As such, I would like to document how to actually add the Python versions which are required by the project and written down in the `tox.ini` file.
I wonder about the place where to document it:
- It does not feel right to do it in each project using tox because many of them lack documentation either way.
- Since I use [pyenv](https://github.com/pyenv/pyenv), I could document how to use it with tox but then, I would not find it when I follow the tox installation.
- I would personally expect a section [in the install instructions](https://tox.wiki/en/latest/install.html) on how to satisfy the requirements - namely the different Python versions and some operating system specifics.

Is there any resistance to a small section? Is there more to consider?

**Comment by jugmac00** [comment]
Thanks for creating this issue.

While I certainly understand your motivation, this would be completely out of scope for this project's documentation.

There are just too many possible ways to install Python and also we'd need to take care of the different operating systems.

So we have (at least)...
- Windows
- Linux
-- deb based systems e.g. Ubuntu
-- rpm based systems e.g. Fedora
-- Arch and similar systems
- Mac

And...
- compile from source
- x different package managers
- Windows store
- installers from python.org
- homebrew
- deadsnakes
....

I only have access to Ubuntu.

So I neither could create those guides, review them or fix them when they are broken.

I still like your idea.

I am +1 to accept a PR which creates a how-to which explains which different possibilities there are out there, but with no explanation, but only links to official guides which are maintained and have possibly stable links.

I am currently not at home. If you agree with my idea I will have a look where to put the new document later on.

**Comment by niccokunzmann** [comment]
I think that is great. I would expect that section at the end of the install document.
I can create a PR with a first draft.

**Comment by jugmac00** [comment]
@niccokunzmann Go for it! Whenever you have some spare time.

**Comment by niccokunzmann** [comment]
@jugmac00 Thanks, I gave it a go, see #2476.
I just came across this because the `icalendar` package needs tox and a good testing with all versions and I struggled my way though installing these.
