### ISSUE TITLE
Multiple Path of test files can to set in env variable but "\" for new line not working

### ISSUE THREAD

**Issue by rahulmukherjee68** [tox-dev/tox#2455]
When submitting a bug make sure you can reproduce it via ``tox -rvv`` and attach the output of that to the bug. Ideally, you should also submit a project that allows easily reproducing the bug. Thanks!

So here i am using my pytest files as a env variable for different tox enviroment like if `test-functional_api` is a part of my tox enviroment as factor then `TEST_PATH` variable path will be set where its value  contains different pytest folder/dir  which are needed to get tested .

The issue is that there are many files and folder structure is different i need to set different python folder/files in on `TEST_PATH` . I want place different folder in new line but it is giving error so thats the issue
```
setenv =
test-functional_api: TEST_PATH= {toxinidir}/pytests/functional/core \
                                                          {toxinidir}/pytests/unit/api
```

Here the backslash is not working throwing related to ini file nor can i write different path in different line its also throwing related to python split
```
    name, rest = line.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

Can anyone see to this issue i have a long list of files and i dont want to write it in 1 line new line in env variable is not working

**Comment by jugmac00** [comment]
Hey Rahul,

I have a bit of a hard time to understand what the problem is.

Could please you edit your question and use triple quotes around your code examples?
see https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

Please make sure to correctly indent your code examples, as the used ini format is sensitive to whitespace - at very least for indentation.

Also, please add the requested output of `tox -rvv`.

Thank you!

**Comment by rahulmukherjee68** [comment]
> Hey Rahul,
> 
> I have a bit of a hard time to understand what the problem is.
> 
> Could please you edit your question and use triple quotes around your code examples? see https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code
> 
> Please make sure to correctly indent your code examples, as the used ini format is sensitive to whitespace - at very least for indentation.
> 
> Also, please add the requested output of `tox -rvv`.
> 
> Thank you!

Hey thank you for quick feedback can you look now i would be attaching the tox -rvv ASAP

**Comment by jugmac00** [comment]
your configuration snippet is broken

you need to indent the value, see https://tox.wiki/en/latest/config.html?highlight=setenv#conf-setenv
