### ISSUE TITLE
Use tomllib from the standard library on Python 3.11+

### ISSUE THREAD

**Issue by hroncok** [tox-dev/tox#2462]
Hey,
would you accept a pull request that uses tomllib rom the standard library on Python 3.11+ and fallbacks to tomli, instead of toml?

**Comment by hroncok** [comment]
I was testing the changes, so I opened a draft PR without a changelog entry to present what change I meant. If acceptable, I'll add the entry. https://github.com/tox-dev/tox/pull/2463

**Comment by jugmac00** [comment]
Looks like tomli never had support for Python 2.7. I am not sure what are the plans about that in the future. `tox4` will require Python 3.7 as a minimum, but I don't think it makes a lot of sense to drop support for Python 2.7 for tox 3 anymore.

**Comment by hroncok** [comment]
I have not thought about that. Will fallback to toml. Not today though.

**Comment by hroncok** [comment]
Done.
