### ISSUE TITLE
tox support for package using build backend hatchling

### ISSUE THREAD

**Issue by bjlittle** [tox-dev/tox#2470]
First of all, thanks for `tox`, it's truly fabulous :+1: 

### Scenario

I'm in the process of migrating a package that I maintain from using `setuptools` to `hatchling` (see [hatch](https://github.com/pypa/hatch)) as a build backend, and as a result have no `setup.py` nor `setup.cfg`.

### Issue

When using `tox` with `usedevelop = true`, `tox` v3.25.1 it fails to perform a `pip install --editable` and reports that it is performing a `develop-inst-noop`.

After a little digging, it *appears* that [tox.venv.VirtualEnv._needs_reinstall](https://github.com/tox-dev/tox/blob/e826f4adec18005f7fa60623ffd178eb0d23d79b/src/tox/venv.py#L334) is returning ``False`` to [tox.venv.VirtualEnv.install_pkg](https://github.com/tox-dev/tox/blob/e826f4adec18005f7fa60623ffd178eb0d23d79b/src/tox/venv.py#L392), hence the `develop-inst-noop`.

### Context

I'm seeing this issue within a GHA CI run, where the `tox` environment is pre-seeded with known cached packages (for performance), so opted not to use the `isolated_build` option. However, when this option is used this issue does not occur (which I understand).

Failed CI job: see [here](https://github.com/bjlittle/geovista/runs/7556015823?check_suite_focus=true)
Package feature branch: see [here](https://github.com/bjlittle/geovista/tree/hatch)

### Question

I noticed that you have a `tox` [rewrite](https://github.com/tox-dev/tox/tree/rewrite) feature branch... will this future feature branch correctly handle `hatchling` based packages that want to use `tox`?

Many thanks! :+1:

**Comment by jugmac00** [comment]
Hey @bjlittle!

Thanks for reaching out! While @gaborbernat is way more familiar with build backends, let's see whether I can help answering your questions.

As you already noticed the rewrite branch... indeed, it will support `hatchling` based packages, as tox itself will use hatchling with the upcoming next version 4, see https://github.com/tox-dev/tox/blob/86e9c8da10e6e7cbcbd02cb6d326597048515b6d/pyproject.toml#L1-L3

I would suggest that you try your MP with the prerelease of tox (pip install --pre tox). I saw that your package uses two tox plugins. The plugin system between tox 3 and tox 4 is not 100% compatible. So it is a good idea to double check the compatibility before tox 4 gets finally released.

**Comment by bjlittle** [comment]
Awesome, thanks @jugmac00 for getting back so quickly :beers: 

Okay, I'll give that a try and let you know how I get on.

Just curious... when are you guys roughly expecting to make the next major release of `tox` 4.x?

Sounds like the `tox` plugin ecosystem will need to respond to that as well to ensure 100% compatibility, right?

**Comment by jugmac00** [comment]
> Just curious... when are you guys roughly expecting to make the next major release of tox 4.x?

We are pretty far with tox 4 - there is even a beta out there already, but basically we all do this in our spare time, and there is only so and so much free time. Currently, there is not much free time :-)
 
There are a couple of release blockers... https://github.com/tox-dev/tox/milestone/7 While we still would like to see some more contributions, before releasing tox 4 we need to make sure that those things are handled.

So, we cannot give you a date - though - I have been using tox 4 basically since a year, also in production, as I am not affected by the listed issues.

About plugin compatibility... there is this mega thread .. https://github.com/tox-dev/tox/issues/1974 Bernát reached out to quite some of the more popular plugins. If yours are not yet included, it makes sense to get back to us and discuss whether a port to tox 4 makes sense, or maybe the plugin functionality is already included in tox 4.

**Comment by bjlittle** [comment]
@jugmac00 Update...

Okay so I've given it a whirl using `pip install --pre tox`, as you recommended, and I also pre-installed the `tox` 4.x compliant `tox-conda` plugin from the [tox-4](https://github.com/tox-dev/tox-conda/tree/tox-4) feature branch.

However, I hit a problem from a missing piece of functionality in `tox-conda`, namely in [tox_conda.api](https://github.com/tox-dev/tox-conda/blob/tox-4/src/tox_conda/api.py#L61), which looks like a dev WIP stub function at the moment :+1: 

This isn't a problem or a blocker for me, as I'm only tentatively dipping my toe into the new `tox` v4.x world. I'm totally happy just to wait for time to pass and all the connective pieces to eventually come together.

That said, the mother-of-all issue [#1974](https://github.com/tox-dev/tox/issues/1974) appears to be missing [tox-run-command](https://github.com/dstanek/tox-run-command), which would be nice to have. So I don't know if that can be added to the list? Or will `tox` 4.x now offer that functionality?

Anyways, thanks again for your help and advice. Much appreciated.

Totally happy for you to close this issue, unless it helps server as a reminder for future dev work.

Also, I'm assuming that a noob (like myself) who wants to start making dev contributions to `tox` should target `level:easy` issues, right?

**Comment by jugmac00** [comment]
@bjlittle I completely missed your reply!

> That said, the mother-of-all issue https://github.com/tox-dev/tox/issues/1974 appears to be missing [tox-run-command](https://github.com/dstanek/tox-run-command), which would be nice to have. So I don't know if that can be added to the list? Or will tox 4.x now offer that functionality?

Indeed, tox in version 4 or higher comes with the `exec` subcommand, see file:///home/jugmac00/Projects/tox/.tox/docs_out/cli_interface.html#tox-exec-(e)

> Also, I'm assuming that a noob (like myself) who wants to start making dev contributions to tox should initially target level:easy issues, right?

Indeed :-)

> However, I hit a problem from a missing piece of functionality in tox-conda, namely in [tox_conda.api](https://github.com/tox-dev/tox-conda/blob/tox-4/src/tox_conda/api.py#L61), which looks like a dev WIP stub function at the moment +1

When you hit issues with a plugin, please create an issue on the respective issue tracke, e.g. https://github.com/tox-dev/tox-conda
