### ISSUE TITLE
Support arbitrary arguments in the environment

### ISSUE THREAD

**Issue by jaraco** [tox-dev/tox#2473]
Similar to how pip and pytest allows arbitrary arguments to be inferred from the environment, I'd like for tox to do the same. 

Today, I'd like to be able in one CI environment to declare `--site-packages`, but to do so, I have to update all CI environments to take a `{matrix.toxargs}` and then set `toxargs` only in the relevant environment to `--site-packages`. Better would be to allow for `TOX_ARGS=--site-packages` or `TOX_SITE_PACKAGES=true` to indicate in that environment to act is if `--site-packages` had been passed. I prefer the latter option (variable per option, the pip approach) because it generalizes better, although I recognize that would take more work than `TOX_ARGS` (the pytest approach).

**Comment by gaborbernat** [comment]
This already is implemented in tox v4.

**Comment by gaborbernat** [comment]
> Just checking in on this request. Is this feature blocked on all of [the 4.0 milestone](https://github.com/tox-dev/tox/issues?q=is%3Aopen+is%3Aissue+milestone%3A4.0+sort%3Aupdated-desc)? Any estimate on when that might land?

Yes, and no idea. 



> I see the code _sets_ TOX_WORK_DIR to toxworkdir, but I'd also like it to honor the env var if set. Let me know if it would be necessary/helpful to file a separate request for that feature (#20 is already closed without a fix).

https://tox.wiki/en/rewrite/cli_interface.html#tox--x and https://tox.wiki/en/rewrite/config.html#configuration
