### ISSUE TITLE
tox.wiki documentation site offline

### ISSUE THREAD

**Issue by Rahul-RB** [tox-dev/tox#2486]
tox.wiki doesn't seem to be loading for anyone.
Is there an ongoing upgrade?

![image](https://user-images.githubusercontent.com/19649954/188544630-8bfd9372-1d4d-4ea9-99cd-cbf70a5838c2.png)
![image](https://user-images.githubusercontent.com/19649954/188544655-f2caf2bc-8cdc-459c-83f8-0c005368e2b1.png)

**Comment by gaborbernat** [comment]
Seems the DNS went down, not sure why, investigating.

**Comment by dcambie** [comment]
For the other people arriving here, a recent (Release 3.25.1.dev31) PDF of the docs is available at https://buildmedia.readthedocs.org/media/pdf/tox-gaborbernat/latest/tox-gaborbernat.pdf

**Comment by Rahul-RB** [comment]
Loading now, closing this issue.

**Comment by gaborbernat** [comment]
From our domain name provider:

> We experienced an attack on our DNS servers yesterday and our servers didn’t scale up to handle the attack. We believe the issue has since been resolved.

> We are in the process of migrating all domains to our new DNS servers, powered by Cloudflare. This attack only affected domains that are using our old DNS servers. If you would like to move your domains to our new DNS servers please follow this guide, [How to switch to Porkbun's Nameservers](https://kb.porkbun.com/article/63-how-to-switch-to-porkbuns-nameservers).

> All domains will automatically be moved to our new DNS servers within the next couple of weeks.

**Comment by Rahul-RB** [comment]
@gaborbernat  ah I see, thank you for the update!

**Comment by gaborbernat** [comment]
We have moved to the new nameservers by the way, so this should not happen again!
