### ISSUE TITLE
Can I build a standalone executable using `tox`?

### ISSUE THREAD

**Issue by pvinis** [tox-dev/tox#2527]
Seems like `tox` can do a bunch of stuff. I know there is `cx_Freeze` and `pyinstaller` that can build a standalone executable. Can I use `tox` for the same thing? Can `tox` somehow build an executable that is self-contained, all the deps are inside, and I can just move the one file to another computer and it could run (assuming same arch)?

**Comment by gaborbernat** [comment]
tox is just an orchestrator, it only provisions environments and invokes tools. If a python tool can do that, than you can tox to set it up and run it. tox itself does not do such though.

**Comment by pvinis** [comment]
gotcha. ill look into that. thanks.
