### ISSUE TITLE
Drop py as direct dependency

### ISSUE THREAD

**Issue by asturza2** [tox-dev/tox#2544]
https://github.com/tox-dev/tox/blob/0e1054be19c3bfa0ae7cc3f5a05355814dd531e4/setup.cfg#L40

Tox is failing our CI Safety Checks.  

Can `py` simply be droped as a dependency? 

https://pyup.io/v/51457/f17/

https://github.com/pytest-dev/py/issues/287

https://github.com/dnsimple/dnsimple-python/pull/388

**Comment by gaborbernat** [comment]
It cannot be dropped. This is not planned for version 3, version 4 does not use this project anymore. Version 4 might be released sometime early next year. This project is not the true security issue. It's more of a false positive.
