### ISSUE TITLE
tox  failing to ignore return code

### ISSUE THREAD

**Issue by osfrickler** [tox-dev/tox#2561]
## Issue

Sample tox.ini:

```
[testenv]
allowlist_externals = false
commands =
  -false
```

Expected result from tox (works with tox3): pass

Result with 4.0.0rc1:

```
$ ~/vv/bin/tox 
py: commands[0]> -false
py: exit 2 (0.00 seconds) /home/jharbott/tmp> -false
  py: FAIL code 2 (0.06=setup[0.06]+cmd[0.00] seconds)
  evaluation failed :( (0.15 seconds)
```

## Environment

Provide at least:

- OS: Ubuntu 22.04

**Comment by osfrickler** [comment]
Cool, I didn't even know there is a `- ` variant. (TBH I only learned about this whole feature when I tested tox4 on some OpenStack projects.)

Thinking about it, I wouldn't mind if you'd deprecate the `-cmd` variant, it is pretty confusing anyway in the end, I was first looking for a command named `-cmd` until I found the docs for this.

**Comment by gaborbernat** [comment]
Yeah, the thing is I don't want this to be a breaking change, hence why in the end decided to accept `-cmd` too...
