### ISSUE TITLE
Remove gitter integration

### ISSUE THREAD

**Issue by jugmac00** [tox-dev/tox#2583]
It looks like the tox gitter community was created in 2018. While it had its use in the past, it is no longer used.

Also, meanwhile we have a discord instance as a direct replacement. Additionally, we have discussions on the git repo and we (or at least I) monitor also StackExchange.

Let's make support a bit more focused and close gitter.

There is no way to do it via the gui - having a look at https://gitlab.com/gitterHQ/webapp/blob/develop/docs/communities.md#delete-a-community I think @gaborbernat has to send an email to support@gitter.im

I will create a pull request to remove the link to gitter at https://github.com/tox-dev/tox/issues/new/choose

- [x] remove link from the list when creating a new issue
- [ ] delete the gitter instance -> @gaborbernat needs to send an email to support@gitter.im

**Comment by gaborbernat** [comment]
I did email them 👍

**Comment by jugmac00** [comment]
The link to check whether it is still up or not:
https://gitter.im/tox-dev/Lobby

**Comment by gaborbernat** [comment]
Done.
