### ISSUE TITLE
tox4: conflicting factors

### ISSUE THREAD

**Issue by jugmac00** [tox-dev/tox#2602]
Running tox4 rc3 against [zopefoundation/AccessControl](https://github.com/zopefoundation/AccessControl) I get the following error:

```
    raise ValueError(f"conflicting factors {', '.join(candidates)} in {env_name}")
ValueError: conflicting factors pypy, pypy3 in pure-pypy-pypy3

```

It works for tox v3.

Either this is a bug or we need to document the changed behavior.

Relevant tox configuration:
https://github.com/zopefoundation/AccessControl/blob/54befd0eece545ab90f811bc8c24e493e0c60066/tox.ini

**Comment by gaborbernat** [comment]
This is valid: pypy means pypy2 and pypy3 is conflicting. This was a warning before, but now is failing as the warn said.

**Comment by jugmac00** [comment]
I just ran tox v3 against above mentioned repository, and I saw no warning. Where was this deprecated? Or where did you see a warning? Or where was the warning set?

What is the action item for this issue? Does the above mentioned project need to update its tox.ini? If you have a minute, could you have a look how that needs to be changed? And do we want to have our users see an exception, or should we catch it and present a nice error message and explain what to do?
