### ISSUE TITLE
BUG: (xref) tox 4.0 breaks tox-pyenv

### ISSUE THREAD

**Issue by neutrinoceros** [tox-dev/tox#2611]
## Issue
xref https://github.com/tox-dev/tox-pyenv/issues/21
I was hoping to get this adressed in tox-pyenv before the final release, now I don't know how to deal with that other than dropping tox-pyenv altogether. Is this package unmaintained ?

**Comment by gaborbernat** [comment]
This is a question for maintainers of that plugin, so please follow that issue.
