### ISSUE TITLE
Tox 4.0 - py2.7 env - 'cannot determine number of cpus'   (os.environ['NUMBER_OF_PROCESSORS'] missing)

### ISSUE THREAD

**Issue by matthuisman** [tox-dev/tox#2629]
Python 3.7.9 on Windows x64
Running unittests in py3.5, 3.7 and 2.7

2.7 fails when using multiprocessing.cpu_count()
Due to os.environ['NUMBER_OF_PROCESSORS'] missing from environment

If I run directly in the python2.7 in Windows, above works fine so seems related to new tox 4.0 as was working on 3.X

**Comment by gaborbernat** [comment]
Please put in a PR with a passing CI where we pass through this env-var here https://github.com/tox-dev/tox/blob/main/src/tox/tox_env/python/api.py#L99 note you'll need to amend the test here https://github.com/tox-dev/tox/blob/main/tests/session/cmd/test_show_config.py#L101

**Comment by gaborbernat** [comment]
Resolved by https://github.com/tox-dev/tox/pull/2647

**Comment by matthuisman** [comment]
Thanks for the quick fix and release!
Much appreciated :)
