### ISSUE TITLE
Undocumented user level config file [tox4]

### ISSUE THREAD

**Issue by ziima** [tox-dev/tox#2633]
In FAQ for tox 4 I discovered a note about "user level config-file", but I can't find any details, such as default file location, structure of the config and its behavior.

**Comment by jugmac00** [comment]
Thanks for your report. I agree this is under-documented.

As a starter, if you finish the above quoted sentence, it is mentioned that you should run `tox --help` for the file location.

When I do that, I see
```
config file '/home/jugmac00/.config/tox/config.ini' missing (change via env var TOX_CONFIG_FILE)
```
at the very end of the output.

**Comment by jugmac00** [comment]
@gaborbernat I played a bit with `user level config-file`.

Could you give an example how one would look like and what use cases are there?

Then I could create some documentation.

**Comment by gaborbernat** [comment]
It's mostly to alter CLI defaults, e.g. you can set:

```
[tox]
work_dir = .tox-magic
```

To change the working directory, I think 🤔

**Comment by kpfleming** [comment]
I just tried to use this for the first time. I have `/tox/config.ini` with only the example above (setting the `workdir` (not `work_dir`)), and `TOX_CONFIG_FILE` pointed to it.

Unfortunately tox doesn't even look at `tox.ini` in the local directory with the environment variable set this way. In a directory containing a `tox.ini` which defines 7 environments:

* With `TOX_CONFIG_FILE` set to point to the user-level config file, `tox list` lists only the default `py` environment.

* With `TOX_CONFIG_FILE` not set, `tox list` lists the seven defined environments.

At least with tox 4.3.5, this is not working the way it is documented, the specified configuration file *replaces* the automatically-found one, it doesn't augment it. If you'd prefer that I open a new issue, I'm happy to do that.

**Comment by masenf** [comment]
Link issue #2890
