### ISSUE TITLE
{[testenv:<env>]deps} not working when having both [testenv:<env>] and [<env>] section

### ISSUE THREAD

**Issue by JeremyVriens** [tox-dev/tox#2636]
## Issue

Since Tox 4.x, the `{[testenv:<env>]deps}` is not working anymore when having both `[testenv:<env>]` and `[<env>]` sections in the `tox.ini`. In my example I've used `isort`, but it works for any package, ex. `bandit`, `black` or `mypy`.

## Environment

Provide at least:

- OS: Any
- `pip list` of the host Python where `tox` is installed:

```
tox 4.0.2
```

## Output of running tox

Provide the output of `tox -rvv`:

```
```

## Minimal example

If possible, provide a minimal reproducer for the issue:

```
[tox]
envlist = linters

[isort]
# Some isort config

[testenv:isort]
deps = isort

[testenv:bandit]
deps = bandit

[testenv:linters]
deps =
    {[testenv:isort]deps}
    {[testenv:bandit]deps}
```
Running `tox --show-config -e linters` will only show `bandit` under deps:
```
deps =

  bandit
```

**Comment by JeremyVriens** [comment]
To unblock this issue, I've moved my isort config to my pyproject.toml file. However, that doesn't solve this bug yet.

**Comment by gaborbernat** [comment]
```ini
[a]
[testenv:a]
deps = c
[testenv:b]
deps = {[testenv:a]deps}
```

Minimal repro with:
```ini
❯ tox c -k deps -e a
[testenv:a]
deps =
```
