### ISSUE TITLE
pytest-xdist reports non-matching test discovery with tox 4.0

### ISSUE THREAD

**Issue by maxnoe** [tox-dev/tox#2645]
## Issue

In our builds, the remaining issue now is that the parallel build using `pytest-xdist` complains about non matching tests
with the different workers, this doesn't happen with 3.x:

https://github.com/astropy/astropy/actions/runs/3649817291/jobs/6164998098

## Environment

Provide at least:

- OS: ubuntu 32 bits on github actions
- `pip list` of the host Python where `tox` is installed: see log output above

**Comment by gaborbernat** [comment]
A PR fixing this would be much appreciated! My hunch is that is related to some env-var not passing through or some python seeding but need someone to confirm.

**Comment by maxnoe** [comment]
This was caused by tox 4 not setting `PYTHONHASHSEED` anymore

**Comment by jremmet** [comment]
Also  --hashseed cmdline option doesn't help here
