### ISSUE TITLE
Numeric factor in environment name wrongly causes "conflicting factors" error

### ISSUE THREAD

**Issue by nsoranzo** [tox-dev/tox#2657]
https://github.com/tox-dev/tox/pull/2597 had the unintended effect of interpreting a numeric factor (e.g. `2105`) as a candidate base python, breaking previously valid environment names (e.g. `py37-foo-2105`) by raising `ValueError: conflicting factors py37, 2105 in py37-foo-2105`.
Example GitHub workflow build: https://github.com/galaxyproject/planemo/actions/runs/3654111042/jobs/6174245903 for `tox.ini` https://github.com/galaxyproject/planemo/blob/nsoranzo-patch-1/tox.ini

_Originally posted by @nsoranzo in https://github.com/tox-dev/tox/pull/2597#discussion_r1044065606_

**Comment by gaborbernat** [comment]
> For an environment named `py310-foo-py`, I'm getting:

This is not the same case, and in your case the failure is expected as explained in other issue.
