### ISSUE TITLE
passenv should fail on environment variables containing spaces

### ISSUE THREAD

**Issue by ericzolf** [tox-dev/tox#2658]
## Issue

Since tox 4.0, passenv is a comma separated list of environment variables, where it used to be a space separated list:
https://tox.wiki/en/4.0.3/faq.html#tox-4-changed-ini-rules

I'm fine with this, BUT tox silently accepts a space separated list of environment variables, even though the environment variables are silently not passed, making root cause analysis more difficult than necessary for people (like me) migrating from tox 3 to 4. Since no shell (AFAIK) accepts environment variables with spaces in it, once the list has been split, none of its elements should contain spaces, or a meaningful error should be output.

## Environment

Provide at least:

- OS: Fedora 37 or Ubuntu 20.02
- `pip list` of the host Python where `tox` is installed:

```console
$ pip list
Package       Version
------------- -------
cachetools    5.2.0
chardet       5.1.0
colorama      0.4.6
distlib       0.3.6
filelock      3.8.2
packaging     22.0
pip           22.3.1
platformdirs  2.6.0
pluggy        1.0.0
py            1.11.0
pyproject_api 1.2.1
setuptools    62.6.0
six           1.16.0
tox           4.0.3
virtualenv    20.17.1
wheel         0.38.4
```

## Output of running tox

```console
MYENV None
```

I'd expect an error message of some kind that the passenv format isn't correct.

## Minimal example

```ini
[testenv]
passenv = MYENV YOURENV
commands =
    python -c 'import os; print("MYENV", os.getenv("MYENV"))'
```

**Comment by gaborbernat** [comment]
PR welcome 😁

**Comment by ericzolf** [comment]
Taking the challenge but I might need a bit of help:

* `pass_env_post_process` in `src/tox/tox_env/api.py` seems to be a good place to detect the error
* I guess `logging.error` is to be used to report errors
* but how to properly handle the error, exit the program? Raise a Fail exception?

**Comment by gaborbernat** [comment]
I think raising the failure error.

**Comment by ericzolf** [comment]
Raising a HandledError made tox fail with a useless message (not mine at least!), so I raised "Fail", which looks fine to me. I'll complete the draft PR #2671 once I've got a sign that my changes look OK.
