### ISSUE TITLE
ValueError: conflicting factors

### ISSUE THREAD

**Issue by tushar-deepsource** [tox-dev/tox#2664]
For an environment named `py310-foo-py`, I'm getting:

```
ValueError: conflicting factors py310, py in py310-foo-py
```

This shows up in tox v4.0.3

_Originally posted by @tushar-deepsource in https://github.com/tox-dev/tox/issues/2657#issuecomment-1344517965_

**Comment by gaborbernat** [comment]
This is expected. This kind of naming is confusing because py means tox python version while py310 means python 3.10.
