### ISSUE TITLE
color highlighting for commands within tox (i.e. pytest) no longer works in tox 4 

### ISSUE THREAD

**Issue by zzzeek** [tox-dev/tox#2677]
The new highlighting for tox install commands is nice, but it appears to completely remove highlighting for the test commands themselves, which is usually the output we spend most of our time looking at.

I tried to see if NO_COLOR would resolve but this just removes all highlighting.  

I'm not seeing any option on how to restore this, please advise.

tox < 4:

![Screenshot from 2022-12-11 11-05-19](https://user-images.githubusercontent.com/128223/206914598-f3c4971b-097d-449a-acec-6433e6981416.png)

tox >=4

![Screenshot from 2022-12-11 11-06-06](https://user-images.githubusercontent.com/128223/206914610-3ef6f43e-61e7-49d5-974d-ee7915eabeb2.png)

**Comment by gaborbernat** [comment]
https://tox.wiki/en/latest/faq.html#tox-4-known-regressions

**Comment by gaborbernat** [comment]
Duplicate of https://github.com/tox-dev/tox/issues/1773
