### ISSUE TITLE
The --pre option isn't passed to pip

### ISSUE THREAD

**Issue by fschulze** [tox-dev/tox#2690]
With tox 4.0.8 the ``--pre`` option is not passed to the ``pip install`` command anymore, unlike tox 3. This is easily seen in the output of the ran commands with the ``-v`` option. As I see nothing in the changelog about this and the option isn't throwing an error I think this is a regression.

**Comment by gaborbernat** [comment]
How did you set the pre-option?

**Comment by fschulze** [comment]
I used ``--pre`` on the command line. It seems like the option doesn't exist anymore. It isn't listed in the cli help output of either ``tox`` or ``tox run``. It is still in the documentation though: https://tox.wiki/en/latest/config.html#pip-installer I would expect tox to fail if it encounters an unknown option. Is there a new alternative to that option?

**Comment by fschulze** [comment]
I just saw that there is also a ``tox legacy`` command and the option is still listed there, but doesn't work either.

**Comment by gaborbernat** [comment]
We're deprecating with v4 all flags controlling pip. You should be using the PIP environment variables instead, so here it would be `PIP_PRE=1` I think, we do already recommend it for custom index servers, see https://tox.wiki/en/latest/faq.html#using-a-custom-pypi-server. We should document this though and fix the legacy command --pre not working.

**Comment by fschulze** [comment]
Thanks for pointing out ``PIP_PRE``, I didn't think of that.

**Comment by Czaki** [comment]
@gaborbernat could you point out where PIP_PRE is documented in pip documentation? I cannot find them

**Comment by gaborbernat** [comment]
That's a question for the pip developers.

**Comment by Czaki** [comment]
> That's a question for the pip developers.

It is your decision to switch from pip documented feature (`--pre` flag) to the undocumented one (`PIP_PRE` env var).

**Comment by gaborbernat** [comment]
Did you read the pip documentation before you started accusing for a free service? https://pip.pypa.io/en/stable/topics/configuration/#environment-variables I'll accept 5 dollar donation for doing your work myself.

**Comment by Czaki** [comment]
I try to google it without any results. 
Maybe without hope that such basic things could be easily googlable, I could read the whole documentation. especially in tox documentation the `--pre` flag is still mentioned and no `PIP_PRE`, but `pip_pre` without any information that it is an environment variable that should be capitalized. 


I go back to debugging my tox configuration.
