### ISSUE TITLE
Copy pasta docstring in test_req_file tests

### ISSUE THREAD

**Issue by sparkiegeek** [tox-dev/tox#2693]
https://github.com/tox-dev/tox/blob/2df6015c053670eaf7b2aaa0ef48c96d140a0ba4/tests/tox_env/python/pip/test_req_file.py#L44

https://github.com/tox-dev/tox/blob/2df6015c053670eaf7b2aaa0ef48c96d140a0ba4/tests/tox_env/python/pip/test_req_file.py#L57

https://github.com/tox-dev/tox/blob/2df6015c053670eaf7b2aaa0ef48c96d140a0ba4/tests/tox_env/python/pip/test_req_file.py#L65

All three docstrings are copies of the docstring for https://github.com/tox-dev/tox/blob/2df6015c053670eaf7b2aaa0ef48c96d140a0ba4/tests/tox_env/python/pip/test_req_file.py#L21 which actually tests that `--hash` is incompatible with deps list

**Comment by gaborbernat** [comment]
How did you spot this? 🤔

**Comment by sparkiegeek** [comment]
> How did you spot this? thinking

I stumbled across it whilst looking through recent commits to see if #2697 had been fixed recently :)

**Comment by gaborbernat** [comment]
https://github.com/tox-dev/tox/commit/968ea7d7c3b11e82c3f93e0af78068e8b1376e17
