### ISSUE TITLE
Environment variables containing strings with spaces are not accepted any longer for passenv/pass_env.

### ISSUE THREAD

**Issue by Marc2508** [tox-dev/tox#2696]
Looks like this change:
https://github.com/tox-dev/tox/issues/2658
causes an error for environment variables that are strings:
py3: failed with pass_env values cannot contain whitespace, use comma to have multiple values in a single line, invalid values found '-m "not scale"'

export PYTEST_ARGS = '-m "not scale"'

passenv = 
   {env:PYTEST_ARGS}

Is this intended?

**Comment by mgedmin** [comment]
This seems like weird syntax.  If you want PYTEST_ARGS to be passed to the commands executed by tox, you would put

    pasenv = PYTEST_ARGS

in the tox.ini.  Why are you using `{env:PYTEST_ARGS}`?  {env:...} is for including the value of the environment variable into tox configuration.

**Comment by gaborbernat** [comment]
This seems like a broken configuration where the validation caught it. You're welcome 😊
