### ISSUE TITLE
Can't suppress report via -qq

### ISSUE THREAD

**Issue by sparkiegeek** [tox-dev/tox#2697]
## Issue

With a command that outputs information to stdout, it's hard to use `tox` to execute that and capture the result since `tox` insists on printing a report afterwards.

e.g. 
```console
$ TERM=dumb tox exec -qq -- python -c 'print("foo")' | wc -l
```

expect `1`, get `3`

See `_print` in https://github.com/tox-dev/tox/blob/2df6015c053670eaf7b2aaa0ef48c96d140a0ba4/src/tox/session/cmd/run/common.py#L145-L166

## Environment

Provide at least:

- OS: Ubuntu 22.04 LTS
- `pip list` of the host Python where `tox` is installed: https://paste.ubuntu.com/p/BbbJ7bz8Hd/

## Output of running tox

Provide the output of `tox -rvv`:

https://paste.ubuntu.com/p/X85DB6HDw5/

## Minimal example

If possible, provide a minimal reproducer for the issue:

```console
git clone https://github.com/tox-dev/tox.git
env -C tox python3 -m tox exec -e dev -qq -- python -c 'print("foo")'
```

**Comment by gaborbernat** [comment]
Feel free to put in a PR to address this.

**Comment by webknjaz** [comment]
I also noticed this. Subscribing to updates...

**Comment by gaborbernat** [comment]
I think what you wanted to say: I'll open a PR 😜
