### ISSUE TITLE
tox 4 ignores TOX_SKIP_ENV

### ISSUE THREAD

**Issue by mgedmin** [tox-dev/tox#2698]
## Issue

My `make release` for [gitlab-trace](https://github.com/mgedmin/gitlab-trace) runs `TOX_SKIP_ENV=check-manifest tox -p auto`.  This worked with tox 3.x.  It now fails in tox 4, because it doesn't skip the check-manifest toxenv.

Since the documentation page describing the TOX_SKIP_ENV has 'latest' in the URL (https://tox.wiki/en/latest/config.html#envlist), I think it should still be supported?

## Environment

Provide at least:

- OS: Ubuntu 22.10
- `pip list` of the host Python where `tox` is installed:

```console
$ pipx runpip tox list
Package       Version
------------- -------
cachetools    5.2.0
chardet       5.1.0
colorama      0.4.6
distlib       0.3.6
filelock      3.8.2
packaging     22.0
pip           22.3.1
platformdirs  2.6.0
pluggy        1.0.0
py            1.11.0
pyparsing     3.0.9
pyproject_api 1.2.1
setuptools    65.6.3
six           1.16.0
toml          0.10.2
tomli         2.0.1
tox           4.0.2
virtualenv    20.17.1
wheel         0.38.4
```

**Comment by gaborbernat** [comment]
Please feel free to put in a PR for this 👍

**Comment by mgedmin** [comment]
I'm tempted to accept the challenge.  Would you be able to give some hints about where I should start looking?

**Comment by mgedmin** [comment]
Well, it seems to work: https://github.com/tox-dev/tox/pull/2707
