### ISSUE TITLE
Arrow keys no longer work in PDB with tox 4

### ISSUE THREAD

**Issue by tucked** [tox-dev/tox#2705]
Add `--pdb` to a `pytest` call (with or without `{tty:--color=yes}`), or insert a `pytest.set_trace()` or `breakpoint()` call.
The up arrow cannot be used to access previous commands in `tox>=4`:
``` 
(Pdb) pp value
'{}'
(Pdb) ^[[A
```
In `tox<4` the second prompt would show `(Pdb) pp value`.

**Comment by gaborbernat** [comment]
Please submit a PR to fix it. 👍

**Comment by gaborbernat** [comment]
Perhaps there's some env-var to overwrite this behavior?

**Comment by masenf** [comment]
I believe this was fixed by #2711, at least on posix platforms.

Windows still doesn't support pty, and thus will still have this issue (#2337).

@tucked can we close this?
