### ISSUE TITLE
Trouble replacing {distdir} with $TOX_PACKAGE

### ISSUE THREAD

**Issue by tucked** [tox-dev/tox#2706]
For example: https://github.com/dmtucker/verdoc/blob/fce4eaefcd29cb7e6da5853b95974e54ecff13e7/tox.ini#L28-L36

With tox 4, `{distdir}` is literal:
``` console
$ tox -e publish
...
publish: commands[0]> .tox/publish/bin/python -m build --outdir '{distdir}' .
...
publish: commands[1]> twine check '{distdir}/*'
Checking {distdir}/verdoc-1.0.2-py3-none-any.whl: PASSED
Checking {distdir}/verdoc-1.0.2.tar.gz: PASSED
```
The docs say to replace it with the `TOX_PACKAGE` environment variable, but `{env:TOX_PACKAGE}` is empty:
``` diff
diff --git a/tox.ini b/tox.ini
index 062e7a6..6ddba98 100644
--- a/tox.ini
+++ b/tox.ini
@@ -32,8 +32,8 @@ deps =
     build ~= 0.4.0
     twine ~= 3.4.0
 commands =
-    {envpython} -m build --outdir {distdir} .
-    twine {posargs:check} {distdir}/*
+    {envpython} -m build --outdir {env:TOX_PACKAGE} .
+    twine {posargs:check} {env:TOX_PACKAGE}/*

 [testenv:static]
 basepython = python3.7
```
``` console
$ tox -e publish
...
publish: commands[0]> .tox/publish/bin/python -m build --outdir .    
...
publish: commands[1]> twine check '/*'
```
I tried `"$TOX_PACKAGE"` too, but it is also interpreted literally:
``` diff
diff --git a/tox.ini b/tox.ini
index 062e7a6..07b47fe 100644
--- a/tox.ini
+++ b/tox.ini
@@ -32,8 +32,8 @@ deps =
     build ~= 0.4.0
     twine ~= 3.4.0
 commands =
-    {envpython} -m build --outdir {distdir} .
-    twine {posargs:check} {distdir}/*
+    {envpython} -m build --outdir "$TOX_PACKAGE" .
+    twine {posargs:check} "$TOX_PACKAGE"/*

 [testenv:static]
 basepython = python3.7
```
``` console
$ tox -e publish
...
publish: commands[0]> .tox/publish/bin/python -m build --outdir '$TOX_PACKAGE' .
...
publish: commands[1]> twine check '$TOX_PACKAGE/*'
Checking $TOX_PACKAGE/verdoc-1.0.3.dev0+gfce4eae.d20221214-py3-none-any.whl: PASSED
Checking $TOX_PACKAGE/verdoc-1.0.3.dev0+gfce4eae.d20221214.tar.gz: PASSED
```
Neither `TOX_PACKAGE` diff works with tox 3 either, FWIW.

**Comment by gaborbernat** [comment]
For your use case using {envtmpdir} is a much better choice.

**Comment by ivankravets** [comment]
@gaborbernat, thanks for your work on Tox. FYI, we downgraded tox to the 3.x because it does not work on Windows when using `--basetemp="{envtmpdir}"`.

Could you suggest any workarounds?

Log: https://github.com/platformio/platformio-core/actions/runs/3687893035/jobs/6242035742#step:7:121
Code: https://github.com/platformio/platformio-core/blob/develop/tox.ini#L52

**Comment by tucked** [comment]
> For your use case using {envtmpdir} is a much better choice, and works for both tox 3 and 4.

Great, I'll look into that, thanks :+1:

Should `{env:TOX_PACKAGE}` be empty here, though? For example, if I wanted to use the `package: wheel` directive and remove the `build` call from the `publish` env to just upload the wheel tox built instead of rebuilding it, wouldn't I need `{env:TOX_PACKAGE}`?

**Comment by gaborbernat** [comment]
@ivankravets 

> @gaborbernat, thanks for your work on Tox. FYI, we downgraded tox to the 3.x because it does not work on Windows when using `--basetemp="{envtmpdir}"`.

I believe if you remove the quotes will work. tox will take care of quoting when injecting `{envtmpdir}`, you don't need to do it yourself.

> Should `{env:TOX_PACKAGE}` be empty here, though?

It should, TOX_PACKAGE is the package built for your current env. If package is not wheel or sdist there's no package to inject.

**Comment by tucked** [comment]
It seems to be empty even when `package = wheel`...

**Comment by gaborbernat** [comment]
Ah, yeah {env:TOX_PACKAGE} will be empty because env pulls from the caller envs. But the env-var will be set within that env, so from commands can use it.

**Comment by tucked** [comment]
> But the env-var will be set within that env, so from commands can use it.

How does one access that? `$TOX_PACKAGE` seems to be taken literally 🤔

**Comment by gaborbernat** [comment]
What do you want to achieve?

**Comment by tucked** [comment]
Ultimately, I want to test the sdist+wheel that tox creates, then publish the exact same artifacts without rebuilding.

**Comment by gaborbernat** [comment]
Well, that will be troublesome. For first because tox only builds either sdist or wheel for a single env, not both. So at very least you'd need a sdist env, then a wheel env, and a third that consumes those twos outputs 🤔

**Comment by gaborbernat** [comment]
Something like this could work:

```ini
[testenv:sdist]
package = sdist
commands = python -c 'shutil.copyfile(os.environ["TOX_PACKAGE"], "dist")'
[testenv:wheel]
package = wheel
commands = python -c 'shutil.copyfile(os.environ["TOX_PACKAGE"], "dist")'
[testenv:publish]
depends =
	wheel
	sdist
package = skip
commands = 
   twine upload dist
```
