### ISSUE TITLE
tox 4: passenv can no longer use factors

### ISSUE THREAD

**Issue by mkoeppe** [tox-dev/tox#2718]
My tox.ini files are affected by a change to the parsing of `passenv` in tox 4: 
I can no longer use factors to conditionalize which environment variables are passed:
```
passenv =
    sagepython, sagewheels:  SAGE_VENV
    sagewheels:              SAGE_SPKG_WHEELS
```
(from https://github.com/sagemath/sage/blob/develop/pkgs/sagemath-categories/tox.ini#L29)

_Originally posted by @mkoeppe in https://github.com/tox-dev/tox/discussions/2699#discussioncomment-4403536_

**Comment by gaborbernat** [comment]
PR to fix it welcome.

**Comment by jayaddison** [comment]
Hi @mkoeppe - from some local testing, I think that factors are still supported for `passenv` -- what is no longer supported is multiple factors (or multiple variables) within a single line.

So a refactor like this should work:

```ini
passenv =
    sagepython:              SAGE_VENV
    sagewheels:              SAGE_SPKG_WHEELS
    sagewheels:              SAGE_VENV
```

With `tox` v4 you can run `tox config -k passenv` to see what environment variables will be passed through for each environment (and/or filter the results using `-e <environment-name>`)

(somewhat similar functionality is available in `tox` v3 by using `tox --showconfig`)

**Comment by mkoeppe** [comment]
Thanks a lot for diagnosing and fixing this!

**Comment by gaborbernat** [comment]
`sagepython,sagewheels:  SAGE_VENV` would have worked also as a temp workaround.

**Comment by gaborbernat** [comment]
I had to reopen because my fix broke:

```
commands =
    pytest {posargs: \
      tests --durations 5 --run-integration}
```

Now our options are to mark this as an expected breaking change or do more complicated filter factor expression matching... than our current regex.
