### ISSUE TITLE
tox4: Unable to run env called `run`

### ISSUE THREAD

**Issue by sdatko** [tox-dev/tox#2728]
## Issue

I have tox environment called `run` I use to run some commands inside virtual environment where my project is installed (i.e. conveniently testing CLI of the development builds) and since tox version 4.0 it fails with error.

As I can see, there were subcommands now introduced to tox – and apparently the `run` is being intercepted from the `-e`. This is not the correct behavior.

## Environment

Provide at least:

- OS: Arch Linux (up to date)
- `pip list`

```console
Package       Version
------------- -------
cachetools    5.2.0
chardet       5.1.0
colorama      0.4.6
distlib       0.3.6
filelock      3.8.2
packaging     22.0
pip           22.2.2
platformdirs  2.6.0
pluggy        1.0.0
pyproject_api 1.2.1
setuptools    63.2.0
tomli         2.0.1
tox           4.0.11
virtualenv    20.17.1
```

## Output of running tox

```console
[sdatko@polluks tox]$ tox3 -e run -- echo 'I am in venv'
run recreate: /home/sdatko/Development/tox/.tox/run
run run-test-pre: PYTHONHASHSEED='350351148'
run run-test: commands[0] | echo 'I am in venv'
I am in venv
__________________ summary __________________
  run: commands succeeded
  congratulations :)
```
```console
[sdatko@polluks tox]$ tox3 -e other -- echo 'I am in venv'
other create: /home/sdatko/Development/tox/.tox/other
other run-test-pre: PYTHONHASHSEED='1845399330'
other run-test: commands[0] | echo 'I am in venv'
I am in venv
__________________ summary __________________
  other: commands succeeded
  congratulations :)
```
```console
[sdatko@polluks tox]$ tox4 -e run -- echo 'I am in venv'
usage: tox run [-h] [--colored {yes,no}] [--exit-and-dump-after seconds] [-c file] [--workdir dir] [--root dir] [--runner {virtualenv}] [-v | -q] [-e ENV | -m label [label ...] | -f factor [factor ...] | --skip-env re] [--result-json path]
               [-s [v]] [-n] [-b] [--installpkg INSTALL_PKG] [--develop] [--hashseed SEED] [--discover path [path ...]] [--no-recreate-pkg] [--skip-pkg-install] [--version] [--no-provision [REQ_JSON]] [--no-recreate-provision] [-r]
               [-x OVERRIDE]
tox run: error: argument -e: expected one argument
```
```console
[sdatko@polluks tox]$ tox4 -e other -- echo 'I am in venv'
other: commands[0]> echo 'I am in venv'
I am in venv
  other: OK (0.13=setup[0.13]+cmd[0.00] seconds)
  congratulations :) (0.23 seconds)
```

## Minimal example

If possible, provide a minimal reproducer for the issue:

The `tox.ini` file:

```console
[tox]
env_list = py310
skipsdist = True

[testenv]
allowlist_externals = echo
commands = echo default

[testenv:run]
commands = {posargs}

[testenv:other]
commands = {posargs}
```

**Comment by gaborbernat** [comment]
I'm not sure this can be solved. Just use the run subcommand instead of reallying on tox to fallback to legacy mode?

**Comment by sdatko** [comment]
> I'm not sure this can be solved. Just use the run subcommand instead of reallying on tox to fallback to legacy mode?

So, let's please clarify this, because I originally missed that the `tox` command line interface has changed as it is not listed in FAQ under [CLI arguments changed](https://tox.wiki/en/latest/faq.html#tox-4-cli-arguments-changed), but a little below under [New features in tox 4](https://tox.wiki/en/latest/faq.html#new-features-in-tox-4) (and as I was not really interested in what's new when diagnosing the issue, I missed this).

With the current new implementation of command line interface, the are more things that IMO should come to [disallowed env names](https://tox.wiki/en/latest/faq.html#tox-4-disallowed-env-names) – the same behavior occurs for all other new CLI commands, such as:
```console
[sdatko@polluks zuul-jobs-board]$ tox4 -e config
usage: tox config [-h] [--colored {yes,no}] [--exit-and-dump-after seconds] [-c file] [--workdir dir] [--root dir] [--runner {virtualenv}] [-v | -q] [-k key [key ...]] [--core] [-e ENV | -m label [label ...] | -f factor [factor ...] |
                  --skip-env re] [-s [v]] [--develop] [--discover path [path ...]] [--no-recreate-pkg] [--version] [--no-provision [REQ_JSON]] [--no-recreate-provision] [-r] [-x OVERRIDE]
tox config: error: argument -e: expected one argument
```
```console
[sdatko@polluks zuul-jobs-board]$ tox4 -e list
usage: tox [-h] [--colored {yes,no}] [-v | -q] [--exit-and-dump-after seconds] [-c file] [--workdir dir] [--root dir] [--runner {virtualenv}] [--version] [--no-provision [REQ_JSON]] [--no-recreate-provision] [-r] [-x OVERRIDE]
           {run,r,run-parallel,p,depends,de,list,l,devenv,d,config,c,quickstart,q,exec,e,legacy,le} ...
tox: error: unrecognized arguments: -e
hint: if you tried to pass arguments to a command use -- to separate them from tox ones
```

While I agree this may have an impact only on minority of users, I can imagine people naming their environments like `run`, `config`, `depends` or `quickstart`, so this should be either highlighted somewhere (that's why I originally created this issue) or properly fixed – if `tox` promises to use legacy commands interface (is the "fallback to legacy mode" expected to stay there?).

**Comment by gaborbernat** [comment]
These env names are not disallowed; you can just not use the legacy endpoint for it:  `tox run -e run -- echo 'I am in venv'` will work.
