### ISSUE TITLE
Release tox 3.28.0 on PyPI

### ISSUE THREAD

**Issue by hroncok** [tox-dev/tox#2741]
Hello. Could you please release https://github.com/tox-dev/tox/releases/tag/3.28.0 on PyPI?

Thanks.

**Comment by gaborbernat** [comment]
Seems release failed here https://github.com/tox-dev/tox/actions/runs/3699381651

**Comment by gaborbernat** [comment]
Done now on rerurn https://pypi.org/project/tox/3.28.0/

**Comment by hroncok** [comment]
Thanks.
