### ISSUE TITLE
tox 4 does not support factor all conditionals as 3

### ISSUE THREAD

**Issue by dataflake** [tox-dev/tox#2747]
We use factors to differentiate test setups like this:

```
[testenv]
...
commands_pre =
    py27,py35: DO X
    !py27,!py35: DO Y
...
```

This worked fine until version 4.0.13. Now the `py27` and `py35` environments match both the first and second condition, both `commands_pre` are run.

## Environment

Provide at least:

- OS: macOS
- Python: 3.8.15
- `pip list` of the host Python where `tox` is installed:

```console
$ bin/pip list
Package            Version
------------------ ---------
bleach             5.0.1
build              0.9.0
cachetools         5.2.0
certifi            2022.12.7
chardet            5.1.0
charset-normalizer 2.1.1
check-manifest     0.49
colorama           0.4.6
commonmark         0.9.1
distlib            0.3.6
docutils           0.19
filelock           3.8.2
idna               3.4
importlib-metadata 5.1.0
jaraco.classes     3.2.3
keyring            23.11.0
more-itertools     9.0.0
packaging          22.0
pep517             0.13.0
pip                22.3.1
pkginfo            1.9.2
platformdirs       2.6.0
pluggy             1.0.0
py                 1.11.0
Pygments           2.13.0
pyproject_api      1.2.1
readme-renderer    37.3
requests           2.28.1
requests-toolbelt  0.10.1
rfc3986            2.0.0
rich               12.6.0
setuptools         65.6.3
six                1.16.0
tomli              2.0.1
tox                4.0.13
twine              4.0.2
typing_extensions  4.4.0
urllib3            1.26.13
virtualenv         20.17.1
webencodings       0.5.1
wheel              0.38.4
zc.buildout        3.0.1
zipp               3.11.0
```

**Comment by gaborbernat** [comment]
This change is not just 4.0.13; it's any 4.0 version; the reporting claims otherwise but I get the same behavior with 4.0. I'm surprised this worked in tox 3 because we use the , as an OR operator... So py27,py35 means the environment is py27 or py35, so we match. Then !py27,!py35 means not py27 or not py35, so both lines are true. What would you expect the second conditional to explode to?

**Comment by gaborbernat** [comment]
A PR trying to address this regression would be welcomed.

**Comment by dataflake** [comment]
The specific expression we used, `!py27-!py35`, worked with tox 4.0.12 and broke with 4.0.13. I tested this manually today.

Can you suggest an expression hat works with tox 4.0.13 and up that means "environment is NOT py27 AND NOT py35"?

**Comment by gaborbernat** [comment]
My test shows it doesn't work with 4.0.12 🤔 PR welcome. I don't plan to work on this.

**Comment by frenzymadness** [comment]
I can confirm this bug. Fox example zope.event uses:
```
commands =
    zope-testrunner --test-path=src {posargs:-vc}
    !py27-!pypy: sphinx-build -b doctest -d {envdir}/.cache/doctrees docs {envdir}/.cache/doctest
```
With tox 4.0.12:
```
$ tox -e py311 config -k commands
[testenv:py311]
commands =
  zope-testrunner --test-path=src -vc
  sphinx-build -b doctest -d /home/lbalhar/Software/zope.event/.tox/py311/.cache/doctrees docs /home/lbalhar/Software/zope.event/.tox/py311/.cache/doctest
```
With tox 4.0.13:
```
$ tox -e py311 config -k commands
[testenv:py311]
commands =
  zope-testrunner --test-path=src -vc
  '!py27-!pypy:' sphinx-build -b doctest -d /home/lbalhar/Software/zope.event/.tox/py311/.cache/doctrees docs /home/lbalhar/Software/zope.event/.tox/py311/.cache/doctest
```
`git bisect` says that this is the change: https://github.com/tox-dev/tox/commit/864332fb4cb8f32cd30b314db1d5f08e4ca65ce6

**Comment by frenzymadness** [comment]
To go a little bit deeper, this function

https://github.com/tox-dev/tox/blob/9972a82ceba40ca11573f668bdc38abafbe57486/src/tox/config/loader/ini/factor.py#L70-L81

raises `ValueError` because, from the example above, the `!py27-!pypy` does not fully match the `r"!?[\w._][\w._-]*"` regex – it stops on the second exclamation mark after the dash.

**Comment by dhomeier** [comment]
Confirmed as well, with 4.0.13 and 4.0.14 astropy jobs are failing on
https://github.com/astropy/astropy/actions/runs/3733576067/jobs/6334552302#step:9:47
