### ISSUE TITLE
Ability for AND combination of factors on command line.

### ISSUE THREAD

**Issue by icemac** [tox-dev/tox#2752]
## What's the problem this feature will solve?

I want to select multiple factors `and` combined.
Using `tox 3` and `tox-facor` together I was able to have environments like this:
`py{37,38,39}-{wsgi,plonetesting,grok}-{chrome,ff,edge}`
And use `tox -f py37-ff` to run the following environments:

* py37-wsgi-ff
* py37-plonetesting-ff
* py37-grok-ff

Using `tox >= 4` and the integrated factor selector I seem to have to call:
`tox -f py37 -f ff` but this combines the factors with `or`, so it runs all combinations.

## Describe the solution you'd like

I need a way to configure (multiple) `-f` switches to do an `and` combination of the selected factors.

## Alternative Solutions

Currently I see no other solution than keeping to use `tox < 4` together with `fox-factor`.

**Comment by gaborbernat** [comment]
A PR is welcome 👍

**Comment by q0w** [comment]
It could be closed because of this fix https://github.com/tox-dev/tox/pull/2786?
