### ISSUE TITLE
Document which environment variables are passed through by default

### ISSUE THREAD

**Issue by jugmac00** [tox-dev/tox#2753]
Documentation for tox3 had https://tox.wiki/en/3.27.0/config.html#conf-passenv

Documentation for tox4 does not show the list any more

Also see https://github.com/tox-dev/tox/blob/6b1cc141aeb9501aa23774056fbc7179b719e200/src/tox/tox_env/api.py#L179-L204

**Comment by gaborbernat** [comment]
Also:

- https://github.com/tox-dev/tox/blob/main/src/tox/tox_env/python/api.py#L105-L120
- https://github.com/tox-dev/tox/blob/main/src/tox/tox_env/python/virtual_env/api.py#L93-L94

**Comment by gaborbernat** [comment]
For what's the best documentation is:

```
tox c -e py -k pass_env 
```

🤷 then, some hard-coded list in a webpage that's easy to become stale.

**Comment by gaborbernat** [comment]
@seyidaniels will try to tackle this :)
