### ISSUE TITLE
Tox shouldn't set `COLUMNS` unless provided by either `passenv` or `setenv`

### ISSUE THREAD

**Issue by posita** [tox-dev/tox#2756]
## Issue

Tox 4 infers `COLUMNS` from the environment and injects it into testing environments implicitly. It's not clear why it does this. If testers need `COLUMNS` set, or passed from the environment, they should provide it via `passenv` or `setenv`.

**Comment by jugmac00** [comment]
related to #2575

**Comment by posita** [comment]
Is there a specific use case that Tox is trying to serve by injecting `COLUMNS` even though it's not set by the inherited environment?

**Comment by gaborbernat** [comment]
This is on purpose to allow correct shutil getterm size ☺️ why is this an issue?

**Comment by posita** [comment]
Because `COLUMNS` can vary env to env, and an app/lib might have tests that provide a default where it's not set for (e.g.) width scaling when printing to dumb terms. For those who need `shutil` to work in tests, it seems like they should signal as such by making the appropriate tweaks to the env/Tox config. I don't know that injecting it should be the default for all users?

**Comment by gaborbernat** [comment]
> Also, I'm curious why the [fallback behavior of `shutil.get_terminal_size`](https://docs.python.org/3/library/shutil.html#shutil.get_terminal_size) (i.e,. to use [`os.get_terminal_size`](https://docs.python.org/3/library/os.html#os.get_terminal_size)) is insufficient for the cases folks care about?

Because before https://github.com/tox-dev/tox/issues/1773 was resolved a few days ago, the fallback solution did not work. People who do care about COLUMNS are few, and they can always work around it by doing:

```
set_env = 
	COLUMNS=80
```

If your test suite depends on a given value for that field, you should set it rather than hope the default is what you want.

**Comment by gaborbernat** [comment]
Closing per above.
