### ISSUE TITLE
Tox4: Django test suite database can not be recreated in Tox 4 (works in Tox 3)

### ISSUE THREAD

**Issue by antonpirker** [tox-dev/tox#2769]
## Issue

I want to update the test suite of a library from tox 3 to tox 4. I am running tox in parallel mode in Github actions.

Part of the test suite are Django tests that create a test Postgres database (that is supplied by a GitHub actions service docker container).

Somehow in tox 4 the creation of the test database fails. It fails only in Python 3.8 and above (3.7 and below still works)

Here is our working test suite with latest tox 3:
https://github.com/getsentry/sentry-python/actions/runs/3752739310/jobs/6375243340

And here is the failing tst suite with tox 4.0.16:
https://github.com/getsentry/sentry-python/actions/runs/3752701362/jobs/6375159457

I only changed the tox version, the rest is the same in the both examples. 

It seems that the Django test suite tries to create the test db although it is already existing (Normally the db is recreated if it is existing)

I have tried to debug this and find out what the originating problem is, but without success. 
As tox 4 is a complete rewrite it could be anything.

Has anyone any hints what this could be?
Is the way tox runs parallel tests totally different between tox 3 and 4?

Any help is greatly appreciated!

**Comment by gaborbernat** [comment]
A lot changed. Perhaps your fellow colleague and also tox maintainer @asottile can look into what's the problem ☺️

**Comment by antonpirker** [comment]
Thanks for the quick reply. Yes, everything is quite complicated in that repo. And good idea, I pinged Anthony in our internal slack if he can have a look.

**Comment by asottile** [comment]
I'm off until the new year but might take a look on stream

**Comment by asottile-sentry** [comment]
I reproduced this problem without `tox` -- seems that tox 4 just makes the race condition more likely (perhaps tests are more aligned than they were before) -- I'll put more details on the sentry side but this isn't a tox issue
