### ISSUE TITLE
ModuleNotFoundError on GitHub tox test run

### ISSUE THREAD

**Issue by rkishony** [tox-dev/tox#2783]
## Issue

When running tests on GitHub, I am getting the error message: 

```

Run python -m tox -- --junit-xml pytest.xml
py38: install_deps> python -I -m pip install pytest pytest-benchmark pytest-xdist
tox: py38
  py38: commands[0]> pytest tests/ --ignore=tests/lab_extension --junit-xml pytest.xml
  ImportError while loading conftest '/home/runner/work/quibbler/quibbler/tests/conftest.py'.
  tests/conftest.py:6: in <module>
      from matplotlib import pyplot as plt
  E   ModuleNotFoundError: No module named 'matplotlib'
  py38: exit 4 (0.87 seconds) /home/runner/work/quibbler/quibbler> pytest tests/ --ignore=tests/lab_extension --junit-xml pytest.xml pid=1849
  py38: FAIL code 4 (4.01=setup[3.14]+cmd[0.87] seconds)
  evaluation failed :( (4.10 seconds)
Error: Process completed with exit code 4.
```

Notably, this error occurs only with tox ver 4 (everything runs ok when using `pip install tox==3.28.0`)

## Environment

This happens on GitHub. 

See here:
https://github.com/Technion-Kishony-lab/quibbler/actions/runs/3792710874/jobs/6449140682#step:5:19

**Comment by gaborbernat** [comment]
Please follow the template, we requested the output of `tox -rvv`. Also please show the content of `.tox/py38/.tox-info.json`.

**Comment by gaborbernat** [comment]
Closing due to lack of more info.

**Comment by rkishony** [comment]
Hi @gaborbernat, sorry i missed your earlier comments. the error appears during automated tests on GitHub. So I am unsure how to provide the requested `tox -rvv` and `.tox/py38/.tox-info.json`. would appreciate your kind guidance.
