### ISSUE TITLE
Bug with poetry and overlapping extras

### ISSUE THREAD

**Issue by dconathan** [tox-dev/tox#2791]
## Issue

I'm not sure if this is a poetry bug or a tox bug, but I figured I'd start here.  The issue seems to be with how:
https://github.com/tox-dev/tox/blob/c83819262b4b739899af8a0bd7b6f32442344e4a/src/tox/tox_env/python/virtual_env/package/util.py#L31
is parsing extras that fall into multiple extra groups.  That is if you have the same requirement in 2+ extra groups, poetry will e.g., produce the line:

```
Requires-Dist: filelock (>=3.9.0,<4.0.0) ; extra == "extras1" or extra == "extras2"
```
in the `PKG-INFO`

Then when `tox` is run with e.g., `extras = extras1`, you get:

```
py-extras1: install_package_deps> python -I -m pip install 'filelock<4.0.0,>=3.9.0; or extra == "extras2"'
...
pip._vendor.packaging.markers.InvalidMarker: Invalid marker: 'or extra == "extras2"', parse error at 'or extra'
```

## Environment

Provide at least:

- OS: macos
- `pip list` of the host Python where `tox` is installed:

```console
./.venv/bin/pip list
Package       Version
------------- -------
cachetools    5.2.0
chardet       5.1.0
colorama      0.4.6
distlib       0.3.6
filelock      3.9.0
packaging     22.0
pip           22.3.1
platformdirs  2.6.2
pluggy        1.0.0
pyproject_api 1.2.1
setuptools    65.5.0
tox           4.1.0
virtualenv    20.17.1
```

## Minimal example

I've created a minimal poetry project that reproduces this bug: https://github.com/dconathan/poetry-tox-bug

**Comment by dconathan** [comment]
For what it's worth - I tried taking poetry out of the equation and using the `setup.py` that poetry created and everything works as expected...

**Comment by q0w** [comment]
```diff
--- a/src/tox/tox_env/python/virtual_env/package/util.py
+++ b/src/tox/tox_env/python/virtual_env/package/util.py
@@ -45,10 +45,9 @@ def extract_extra_markers(deps: list[Requirement]) -> list[tuple[Requirement, se
                 extra_markers.add(marker_value.value)
                 del markers[_at]
                 _at -= 1
-                if _at > 0 and (isinstance(markers[_at], str) and markers[_at] in ("and", "or")):
+                if _at >= 0 and (isinstance(markers[_at], str) and markers[_at] in ("and", "or")):
                     del markers[_at]
                 if len(markers) == 0:
                     req.marker = None
-                break
         result.append((req, extra_markers or {None}))
     return result
```
Why it breaks loop when finding first extra

**Comment by gaborbernat** [comment]
Probably because we did not expect these to have more than one. PR welcome with test.

**Comment by gaborbernat** [comment]
https://github.com/tox-dev/tox/pull/2792/files

**Comment by dconathan** [comment]
@gaborbernat  @q0w  FYI I am still seeing this bug when a dependency falls into >2 groups.  My repo reproducing the bug has been updated.

```
Requires-Dist: filelock (>=3.9.0,<4.0.0) ; extra == "extras1" or extra == "extras2" or extra == "extras3"
```
...
```
python -I -m pip install 'filelock<4.0.0,>=3.9.0; or extra == "extras3"' pid=16740
...
pip._vendor.packaging.markers.InvalidMarker: Invalid marker: 'or extra == "extras3"', parse error at 'or extra'
```

**Comment by gaborbernat** [comment]
PR welcome.
