### ISSUE TITLE
Regression for usage of pip options

### ISSUE THREAD

**Issue by Dunedan** [tox-dev/tox#2814]
## Issue

Since version 4.0 tox fails when encountering pip options as part of the dependencies.

The following example works fine with tox <4.0, but doesn't work with tox >=4.0 anymore.

```
$ cat requirements.txt
--no-binary pydantic
$ cat tox.ini 
[tox]
envlist = py3

[testenv]
deps = -r requirements.txt

allowlist_externals = echo

commands = echo "hello world"
$ tox --version
4.2.1 from /home/user/.local/lib/python3.10/site-packages/tox/__init__.py
$ tox -r
py3: remove tox env folder /dir/.tox/py3
py3: failed with argument --no-binary: invalid choice: 'pydantic' (choose from ':all:', ':none:') for tox env py within deps
  py3: FAIL code 1 (0.22 seconds)
  evaluation failed :( (0.33 seconds)
```

**Comment by gaborbernat** [comment]
PR welcome https://github.com/tox-dev/tox/blob/main/src/tox/tox_env/python/pip/req/args.py#L36-L37

**Comment by ndparker** [comment]
Hi,

is there a way to use pip instead of the builtin parser, at least as a workaround? This is also a blocker for me.

Thanks,

**Comment by jugmac00** [comment]
You could probably use pip as a first entry in your `commands` section as a workaround or even use https://tox.wiki/en/latest/config.html#commands_pre

(Untested, as I am on mobile)

**Comment by gaborbernat** [comment]
> is there a way to use pip instead of the builtin parser, at least as a workaround? This is also a blocker for me.

A PR fixing this behavior would be the easiest IMHO 🤷

**Comment by gaborbernat** [comment]
Because that causes people to open issues that tox doesn't recreate environments when these are added. For tox to know if it needs to retrigger an environment recreation or not, it needs to understand these flags.

**Comment by q0w** [comment]
Ok, this https://github.com/pypa/pip/blob/main/src/pip/_internal/models/format_control.py needs to be added

**Comment by ndparker** [comment]
That was quick. Thanks, I'll give it a shot.

**Comment by stylight-circleci** [comment]
Hi,

unforutnately the fix doesn't include environment markers. For example, I have stuff like this in constraint files:

```
--no-binary pycurl; sys_platform == 'darwin'
```

It fails with
```
failed with unrecognized arguments: sys_platform == darwin for tox env py within deps
```

Should I open a new issue?

Thanks,

**Comment by q0w** [comment]
Yes, I did not implement the support of markers. I think, you should

**Comment by q0w** [comment]
@stylight-circleci 
you can add quotes like this
```
pydantic --no-binary="pydantic; sys_platfrom == 'darwin'"
```

**Comment by q0w** [comment]
env markers are not supported even without the binary option, is not it?
```
pydantic ; sys_platform == 'linux'
```

**Comment by q0w** [comment]
@gaborbernat what if parse only known args like
```diff
    def _parse_line(self, line: str) -> tuple[str, Namespace]:
        args_str, options_str = self._break_args_options(line)
        args = shlex.split(options_str, posix=sys.platform != "win32")
---     opts = self._parser.parse_args(args)
+++     opts, _ = self._parser.parse_known_args(args)
        return args_str, opts
```

**Comment by gaborbernat** [comment]
I still want to consider all other arguments, as we should recreate if these are impactful.

**Comment by q0w** [comment]
And how to ignore env markers for lines with pip options?

**Comment by q0w** [comment]
@stylight-circleci pip does not accept for no-binary/only-binary package names with env markers. They are ignored in pip
