### ISSUE TITLE
devenv not respecting specified path if usedevelop = true

### ISSUE THREAD

**Issue by schlamar** [tox-dev/tox#2815]
## Issue

devenv command does not create the virtual environment at the specified path if usedevelop = true is configured in tox.ini.

```console
>tox devenv -e py39 .venv
...
ROOT: created development environment under {cwd}\.tox\py39

>tox devenv -e py39
...
ROOT: created development environment under {cwd}\.tox\py39

```

## Environment

Provide at least:

- OS: Windows 10
- `pip list` of the host Python where `tox` is installed:

```console
python.exe -m pip list
Package       Version
------------- -------
cachetools    5.2.0
chardet       5.1.0
colorama      0.4.6
distlib       0.3.6
filelock      3.9.0
packaging     22.0
pip           22.3.1
platformdirs  2.6.2
pluggy        1.0.0
py            1.11.0
pyparsing     3.0.9
pyproject_api 1.3.0
setuptools    65.6.3
six           1.16.0
toml          0.10.2
tomli         2.0.1
tox           4.2.1
virtualenv    20.17.1
wheel         0.38.4
```

## Minimal example

See commands above.

tox.ini
```ini
[tox]
envlist = py39


[testenv]
commands = py.test {posargs}
usedevelop = True
deps =
    pytest


[testenv:py39]
basepython = python3.9-32

```

setup.py
```python
from setuptools import setup
setup(name='demo', version='1.0')
```

**Comment by gaborbernat** [comment]
I can't seem to replicate this. Can you please post these outputs with verbose mode on `tox devenv -vv`?

**Comment by schlamar** [comment]
Other machine without Python 3.9 so little changes but still reproducible.

tox.ini
```
[tox]
envlist = py310


[testenv]
commands = py.test {posargs}
usedevelop = True
deps =
    pytest
```

Command `tox devenv -e py310 -vv > log.txt 2>&1` [log.txt](https://github.com/tox-dev/tox/files/10345941/log.txt)

**Comment by schlamar** [comment]
Reproducible on WSL, too. With the smallest minimal example possible:

$ tox devenv
...
ROOT: created development environment under /mnt/c/Users/marcs/Desktop/tox-test/.tox/py

$ cat tox.ini
[testenv]
usedevelop = True

$ tox --version
4.2.2 from /home/marc/.local/lib/python3.10/site-packages/tox/__init__.py
```
