### ISSUE TITLE
Fix information about supported env Python versions

### ISSUE THREAD

**Issue by scop** [tox-dev/tox#2845]
## Issue

The information at https://tox.wiki/en/latest/user_guide.html#main-features about environment versions seems to no longer hold. It currently states

> cross-Python compatible: tox requires CPython 3.7 and higher, but it can create environments 2.7 or later

...but per the commentary in #2836 I read that at least 3.5 (which "2.7 or later" includes) is no longer supported.

**Comment by gaborbernat** [comment]
I think this is actually an upstream issue in https://github.com/tox-dev/pyproject-api

**Comment by gaborbernat** [comment]
Also, please remember that my comment was more in the spirit of fixes for old Pythons is community supported. We'll accept PRs for it; we'll not do the work for you.  So I guess deprecated Pythons are still supported, not tier 1 but tier 2 level for them.

**Comment by scop** [comment]
My experience with having these two issues closed so quickly (with the issues persisting) is not too welcoming, and as such also makes it hard to justify investing time in fixing them. It does not help raise general awareness either, and thus quite possibly lowers the chance to have someone else find and start working on them too.

This project quite probably has much more important and interesting things to work on, and in that sense it's very much understandable that these issues wouldn't end up being worked on by the core contributors any time soon, if ever. No problem with that here. But having the issues closed the way they were, in the state they are, was a surprise.

**Comment by gaborbernat** [comment]
We don't have a paid core team. So expecting things to be fixed by the core team is unrealistic.  This is very much a community project.

**Comment by scop** [comment]
At no point did I expect the core team or anyone in particular to fix the issues. My previous message above said that about the core contributors quite specifically. I might have looked into the issues myself at some point.

Closing issues so promptly makes it less realistic for _anyone_ to work on them. It could be necessary to keep the number of open issues the core contributors want to work on manageable, or there could be other reasons for doing that, I don't know. But it could also end up hurting the project, and might not convey the picture of an actual community project.
