### ISSUE TITLE
Can't use injected variables with variable substitution?

### ISSUE THREAD

**Issue by robmoss** [tox-dev/tox#2851]
## Issue

I want to use injected environment variables, such as `TOX_PACKAGE`, in command line arguments. But I cannot figure out how to make this work. For example, if I define the command `echo {env:TOX_PACKAGE}` , this runs `echo`. And if I define the command `echo $TOX_PACKAGE`, this runs `echo '$TOX_PACKAGE'` and the single-quotes prevent the variable from being expanded. Is there a way to achieve this?

## Environment

Provide at least:

- OS: Ubuntu 20.04
- `pip list` of the host Python where `tox` is installed:

```console
Package       Version
------------- -------
cachetools    5.2.0
chardet       5.1.0
colorama      0.4.6
distlib       0.3.6
filelock      3.9.0
packaging     22.0
pip           22.3.1
pkg_resources 0.0.0
platformdirs  2.6.2
pluggy        1.0.0
pyparsing     3.0.9
pyproject_api 1.2.1
setuptools    65.6.3
tomli         2.0.1
tox           4.2.6
virtualenv    20.17.1
```

## Output of running tox

Provide the output of `tox`:

```console
test: commands[0]> env
LANG=en_US.UTF-8
TERM=xterm-256color
PATH=XXXXX
PYTHONHASHSEED=2701630236
PIP_DISABLE_PIP_VERSION_CHECK=1
PYTHONIOENCODING=utf-8
TOX_ENV_NAME=test
TOX_WORK_DIR=XXXXX
TOX_ENV_DIR=XXXXX
VIRTUAL_ENV=XXXXX
COLUMNS=95
LINES=53
test: commands[1]> echo en_US.UTF-8
en_AU.UTF-8
test: commands[2]> echo '$TOX_ENV_NAME'
$TOX_ENV_NAME
  test: OK (0.04=setup[0.03]+cmd[0.00,0.00,0.00] seconds)
  congratulations :) (0.13 seconds)
```

## Minimal example

If possible, provide a minimal reproducer for the issue:

```console
[tox]
min_version = 4
envlist = test

[testenv:test]
allowlist_externals =
    echo
    env
commands =
    env
    echo {env:TOX_ENV_NAME} {env:LANG}
    echo $TOX_ENV_NAME
```

**Comment by gaborbernat** [comment]
What do you want to achieve here? Do you have a better example of the end goal?

**Comment by robmoss** [comment]
I'm trying to copy the package (`$TOX_PACKAGE`)  so that it can be archived and installed as a dependency for downstream packages in their CI pipelines, particularly when introducing breaking changes between released versions.

**Comment by gaborbernat** [comment]
`python -c 'import shutil, os;  shutil.copy(os.environ["TOX_PACKAGE"], "dest")`?

**Comment by robmoss** [comment]
Thank you, I was focused on trying to do with shell commands in `tox.ini` and it hadn't occurred to me to tackle it like this. I was starting from a solution I had for tox 3 that used `{distshare}`.
