### ISSUE TITLE
TOX_CONFIG_FILE overrides local config

### ISSUE THREAD

**Issue by kpfleming** [tox-dev/tox#2890]
## Issue

TOX_CONFIG_FILE is documented to be a way to specify a user-level configuration file, to set defaults to be used. There is a default for the configuration file as well, but the behavior differs when the file is automatically discovered vs. being explicitly specified.

In the examples below, the `A` and `B` outputs are correct, but the `C` output is not, even though TOX_CONFIG_FILE is set to point to the same file that is automatically used when it is not set.

## Environment

Provide at least:

- OS: Debian Bookworm
- tox version: 4.3.5 installed using `pipx`

## Minimal example

```shell
$ mkdir foo
$ cd foo
$ cat > tox.ini << EOF
[tox]

[testenv:foo]

[testenv:bar]

[testenv:baz]
EOF

$ tox list (A)
default environments:
py  -> [no description]

additional environments:
foo -> [no description]
bar -> [no description]
baz -> [no description]

$ mkdir $HOME/.config/tox
$ cat > $HOME/.config/tox/config.ini << EOF
[tox]
workdir=/tmp
EOF

$ tox list (B)
default environments:
py  -> [no description]

additional environments:
foo -> [no description]
bar -> [no description]
baz -> [no description]

$ export TOX_CONFIG_FILE=$HOME/.config/tox/config.ini

$ tox list (C)
default environments:
py  -> [no description]
```

**Comment by kpfleming** [comment]
Note: 'work_dir' is misspelled in the user-level config file in the example but the behavior does not change if it is spelled correctly.

**Comment by masenf** [comment]
confirmed, reproducible.

**Comment by masenf** [comment]
The workaround here is to specify

```TOX_CONFIG_FILE=path/to/override/config.ini tox -c ./tox.ini```

I believe the crux of the problem is that tox is overloading the name `config_file` in the parser:

https://github.com/tox-dev/tox/blob/7753e72528bd52f536ded9d734518bf3276a9225/src/tox/config/cli/parser.py#L328

☝️ here `config_file` refers to the _main_ `tox.ini`

https://github.com/tox-dev/tox/blob/7753e72528bd52f536ded9d734518bf3276a9225/src/tox/config/cli/ini.py#L28

☝️ here `config_file` refers to the override config

still unteasing the true root cause.

**Comment by masenf** [comment]
There's a fundamental incompatibility here, where tox implicitly looks for `TOX_{key_upper}`, and finds `TOX_CONFIG_FILE` as the main config file, but also explicitly looks for `TOX_CONFIG_FILE` and sets that as the "user config".

https://github.com/tox-dev/tox/blob/7753e72528bd52f536ded9d734518bf3276a9225/src/tox/config/cli/env_var.py#L23

I propose that we rename the user config envvar to `TOX_USER_CONFIG_FILE` and save `TOX_CONFIG_FILE` to refer to the _main_ `tox.ini`.

```
diff --git a/src/tox/config/cli/ini.py b/src/tox/config/cli/ini.py
index 8839f430..c1823a1d 100644
--- a/src/tox/config/cli/ini.py
+++ b/src/tox/config/cli/ini.py
@@ -19,7 +19,7 @@ DEFAULT_CONFIG_FILE = Path(user_config_dir("tox")) / "config.ini"
 
 
 class IniConfig:
-    TOX_CONFIG_FILE_ENV_VAR = "TOX_CONFIG_FILE"
+    TOX_CONFIG_FILE_ENV_VAR = "TOX_USER_CONFIG_FILE"
     STATE = {None: "failed to parse", True: "active", False: "missing"}
 
     def __init__(self) -> None:
```

With this change, passing `TOX_USER_CONFIG_FILE=path/to/override/config.ini tox` works _just fine_.

So the fix here could be as simple as renaming this conflicting variable and updating the configuration. Should I proceed @gaborbernat?

**Comment by gaborbernat** [comment]
Yeah please.

**Comment by kpfleming** [comment]
@masenf Thank you for tracking this down. The root cause seems so obvious in hindsight :-)
