### ISSUE TITLE
Tox 4.x.x is failing on Apache Beam GHA

### ISSUE THREAD

**Issue by AnandInguva** [tox-dev/tox#2892]
## Issue

Hi, in Apache Beam, we use tox to run Python unit tests. We use `setup.py`[1] for the package dependencies. As part of `python setup.py sdist`, we first try to generate proto files, and then create the tar file.

This workflow worked without any error in the tox 3.x.x. When tox created the package, it used to build protos and then successfully create and install the apache beam sdist.

But with 4.x.x, tox fails during proto generation. 

Workaround: If we manually run protos before tox command, everything works as expected.  Tox 4.x suggests that it uses PEP 517, 518 behavior to build the sdist and also all builds are isolated builds. Could anyone of this be the issue?

[1] https://github.com/apache/beam/blob/master/sdks/python/setup.py
[2] https://github.com/apache/beam/blob/master/sdks/python/tox.ini

## Environment
Windows, mac, ubuntu
Provide at least:

- OS: ubuntu
- `pip list` of the host Python where `tox` is installed:

```console

```

## Output of running tox
```
Run tox -c tox.ini run -e py38
py38: install_deps> target/.tox/py38/bin/python /home/runner/work/beam/beam/sdks/python/target/.tox/py38/bin/pip install --no-cache-dir --retries 10 -r build-requirements.txt
.pkg: install_requires> python -I -m pip install 'setuptools>=40.8.0' wheel
.pkg: _optional_hooks> python /opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_sdist> python /opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: freeze> python -m pip freeze --all
.pkg: pip==22.3.1,setuptools==65.6.3,wheel==0.38.4
.pkg: prepare_metadata_for_build_wheel> python /opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: build_sdist> python /opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
py38: install_package_deps> target/.tox/py38/bin/python /home/runner/work/beam/beam/sdks/python/target/.tox/py38/bin/pip install --no-cache-dir --retries 10 'cloudpickle~=2.2.0' 'crcmod<2.0,>=1.7' 'cryptography>=36.0.0' 'dill<0.3.2,>=0.3.1.1' 'fastavro<2,>=0.23.6' 'fasteners<1.0,>=0.3' 'freezegun>=0.3.12' 'grpcio!=1.48.0,<2,>=1.[33](https://github.com/apache/beam/actions/runs/3993777085/jobs/6850802929#step:6:34).1' 'hdfs<3.0.0,>=2.1.0' 'httplib2<0.22.0,>=0.8' 'hypothesis<=7.0.0,>5.0.0' 'joblib>=1.0.1' 'mock<3.0.0,>=1.0.1' 'numpy<1.23.0,>=1.14.3' 'objsize<0.7.0,>=0.6.1' 'orjson<4.0' 'pandas!=1.5.0,!=1.5.1,<1.6,>=1.0; python_version < "3.10"' 'pandas!=1.5.0,!=1.5.1,<1.6,>=1.4.3; python_version >= "3.10"' 'pandas<2.0.0' 'parameterized<0.9.0,>=0.7.1' 'proto-plus<2,>=1.7.1' 'protobuf<4,>3.12.2' 'psycopg2-binary<3.0.0,>=2.8.5' 'pyarrow<10.0.0,>=0.15.1' 'pydot<2,>=1.2.0' 'pyhamcrest!=1.10.0,<2.0.0,>=1.9' 'pymongo<4.0.0,>=3.8.0' 'pytest-timeout<3,>=2.1.0' 'pytest-xdist<3,>=2.5.0' 'pytest<8.0,>=7.1.2' 'python-dateutil<3,>=2.8.0' 'pytz>=2018.3' 'pyyaml<7.0.0,>=3.12' 'regex>=2020.6.8' 'requests-mock<2.0,>=1.7' 'requests<3.0.0,>=2.24.0' 'scikit-learn>=0.20.0' 'sqlalchemy<2.0,>=1.3' 'tenacity<6.0,>=5.0.2' 'testcontainers[mysql]<4.0.0,>=3.0.3' 'typing-extensions>=3.7.0' 'zstandard<1,>=0.18.0'
py38: install_package> target/.tox/py38/bin/python /home/runner/work/beam/beam/sdks/python/target/.tox/py38/bin/pip install --no-cache-dir --retries 10 --force-reinstall --no-deps /home/runner/work/beam/beam/sdks/python/target/.tox/.tmp/package/1/apache-beam-2.46.0.dev0.tar.gz
Processing ./target/.tox/.tmp/package/1/apache-beam-2.46.0.dev0.tar.gz
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
py38: exit 1 (1.22 seconds) /home/runner/work/beam/beam/sdks/python> target/.tox/py38/bin/python /home/runner/work/beam/beam/sdks/python/target/.tox/py38/bin/pip install --no-cache-dir --retries 10 --force-reinstall --no-deps /home/runner/work/beam/beam/sdks/python/target/.tox/.tmp/package/1/apache-beam-2.46.0.dev0.tar.gz pid=1882
.pkg: _exit> python /opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      INFO:root:out_files : []
      INFO:root:proto_files : []
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line [34](https://github.com/apache/beam/actions/runs/3993777085/jobs/6850802929#step:6:35), in <module>
        File "/home/runner/work/beam/beam/sdks/python/target/.tox/py[38](https://github.com/apache/beam/actions/runs/3993777085/jobs/6850802929#step:6:39)/tmp/pip-req-build-5g6a[46](https://github.com/apache/beam/actions/runs/3993777085/jobs/6850802929#step:6:47)8d/setup.py", line 180, in <module>
          generate_protos_first()
        File "/home/runner/work/beam/beam/sdks/python/target/.tox/py38/tmp/pip-req-build-5g6a468d/setup.py", line 150, in generate_protos_first
          gen_protos.generate_proto_files()
        File "/home/runner/work/beam/beam/sdks/python/target/.tox/py38/tmp/pip-req-build-5g6a468d/gen_protos.py", line [47](https://github.com/apache/beam/actions/runs/3993777085/jobs/6850802929#step:6:48)9, in generate_proto_files
          raise RuntimeError(error_msg)
      RuntimeError: Not in apache git tree, unable to find proto definitions.
      ****************************************
      ****************************************
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
  py38: FAIL code 1 (46.38 seconds)
  evaluation failed :( (46.[54](https://github.com/apache/beam/actions/runs/3993777085/jobs/6850802929#step:6:55) seconds)

Error: Process completed with exit code 1.

Passing GHA with tox 3.x.x: https://github.com/apache/beam/actions/runs/3992455449/jobs/6848314768
```
Provide the output of `tox -rvv`:

```console
https://github.com/apache/beam/actions/runs/3998477042/jobs/6861175330

```

## Minimal example
on a fresh evn
```
apt update
apt install git
git clone https://github.com/AnandInguva/beam.git
cd beam/sdks/python
git checkout update_tox
`pip install -r build-requirements.txt`
`pip install tox`
tox -c tox.ini run -e py39
```

If possible, provide a minimal reproducer for the issue:

```console

```

**Comment by gaborbernat** [comment]
Hey man providing the output of the failure is mandatory for any troubleshooting.

**Comment by AnandInguva** [comment]
Hi yes, give me sometime. I am running them again . I will update the bug and ping again.

**Comment by AnandInguva** [comment]
While running sdist, you can see that the proto files and out files are visible. I logged them in the console(Search out_files and proto_files). Then these are written to tar.gz file. But when tox installs the sdist, it fails. 

https://github.com/apache/beam/actions/runs/3998477042/jobs/6861175330

**Comment by gaborbernat** [comment]
Feels like a setuptools issue, what is the content of  /home/runner/work/beam/beam/sdks/python/target/.tox/.tmp/package/1/apache-beam-2.46.0.dev0.tar.gz

**Comment by AnandInguva** [comment]
It is the source dist of Apache beam version 2.46.0.dev.

**Comment by gaborbernat** [comment]
That wasn't my question, does it contain the files needed to build a wheel? The failure message suggest not.

**Comment by gaborbernat** [comment]
1. `python setup.py sdist`
2. extract sdist to a fresh folder
3. `python setup.py bdist_wheel`

As long as this does not pass, tox will not either. Likely a setuptools configuration issue, not related to tox at all.

**Comment by AnandInguva** [comment]
> That wasn't my question, does it contain the files needed to build a wheel? The failure message suggest not.

It should be. We use cibuildwheel to build wheels.


> 1. `python setup.py sdist`
> 2. extract sdist to a fresh folder
> 3. `python setup.py bdist_wheel`
> 
> As long as this does not pass, tox will not either. Likely a setuptools configuration issue, not related to tox at all.

The workflow was working on tox 3.x but it fails with tox 4.x. I checked the versions of the packages installed, they are all same.

**Comment by gaborbernat** [comment]
> The workflow was working on tox 3.x but it fails with tox 4.x. I checked the versions of the packages installed, they are all same.

If you enabled isolated builds, your workflow was already broken with v3 - https://tox.wiki/en/legacy/config.html#conf-isolated_build. It works with the old setuptools interfaces, which are no longer supported post-PEP-517 and PEP-518 being accepted (since 2015 or so). tox 4 just removed support for this long deprecated interface, hence the failure triggered by tox 4.

**Comment by gaborbernat** [comment]
Likely the issue is that you depend on modules from the setup.py cwd to be import-able.  This only happened to work by chance because python adds the scripts location to sys.path. If you depend on this behavior you should add the script path to sys.path, e.g. https://github.com/python/mypy/blob/master/setup.py#L15 otherwise this import https://github.com/apache/beam/blob/master/sdks/python/setup.py#LL149C2-L149C2 has no chance of working.

**Comment by AnandInguva** [comment]
> Likely the issue is that you depend on modules from the setup.py cwd to be import-able. This only happened to work by chance because python adds the scripts location to sys.path. If you depend on this behavior you should add the script path to sys.path, e.g. https://github.com/python/mypy/blob/master/setup.py#L15 otherwise this import https://github.com/apache/beam/blob/master/sdks/python/setup.py#LL149C2-L149C2 has no chance of working.

This could not be the case since the error happens after the import. I will try to reproduce with isolated build on tox 3.x

**Comment by gaborbernat** [comment]
Likely because the bug is in https://github.com/apache/beam/blob/master/sdks/python/gen_protos.py#L561 then
