### ISSUE TITLE
Tox 4.4.0: Unnamed requirements are not allowed as constraints

### ISSUE THREAD

**Issue by mikegrima** [tox-dev/tox#2897]
## Issue

Hello!

I have noticed a very recent issue with the latest Tox release (4.4.0) that is not present in 4.3.5. Whenever running `tox`, I get a bizarre error when installing dependencies where it complains about constraints. I have not defined any so I don't know why this error is happening.  I'm running Python 3.9.

## Environment

This happens on GitHub runners and also on my Mac.

```
% pip list
Package       Version
------------- -------
cachetools    5.3.0
chardet       5.1.0
colorama      0.4.6
distlib       0.3.6
filelock      3.9.0
packaging     23.0
pip           22.0.4
platformdirs  2.6.2
pluggy        1.0.0
pyproject_api 1.5.0
setuptools    58.1.0
tomli         2.0.1
tox           4.4.0
virtualenv    20.17.1
```

## Output of running tox

```console
% tox
py39: install_deps> python -I -m pip install '.[tests]'
.pkg: install_requires> python -I -m pip install setuptools
.pkg: _optional_hooks> python '/my/code/path/venv/lib/python3.9/site-packages/pyproject_api/_backend.py' True setuptools.build_meta
.pkg: get_requires_for_build_sdist> python '/my/code/path/venv/lib/python3.9/site-packages/pyproject_api/_backend.py' True setuptools.build_meta
.pkg: prepare_metadata_for_build_wheel> python '/my/code/path/venv/lib/python3.9/site-packages/pyproject_api/_backend.py' True setuptools.build_meta
.pkg: build_sdist> python '/my/code/path/venv/lib/python3.9/site-packages/pyproject_api/_backend.py' True setuptools.build_meta
py39: install_package_deps> python -I -m pip install PyJWT cloudaux cryptography requests retry slack-bolt '-c/my/code/path/.tox/py39/constraints.txt'
DEPRECATION: Constraints are only allowed to take the form of a package name and a version specifier. Other forms were originally permitted as an accident of the implementation, but were undocumented. The new implementation of the resolver no longer supports these forms. A possible replacement is replacing the constraint with a requirement. Discussion can be found at https://github.com/pypa/pip/issues/8210
ERROR: Unnamed requirements are not allowed as constraints

py39: exit 1 (0.32 seconds) /my/code/path> python -I -m pip install PyJWT cloudaux cryptography requests retry slack-bolt '-c/my/code/path/.tox/py39/constraints.txt' pid=70956
py39: FAIL ✖ in 14.78 seconds
lint: install_deps> python -I -m pip install '.[tests]'
lint: install_package_deps> python -I -m pip install PyJWT cloudaux cryptography requests retry slack-bolt '-c/my/code/path/.tox/lint/constraints.txt'
DEPRECATION: Constraints are only allowed to take the form of a package name and a version specifier. Other forms were originally permitted as an accident of the implementation, but were undocumented. The new implementation of the resolver no longer supports these forms. A possible replacement is replacing the constraint with a requirement. Discussion can be found at https://github.com/pypa/pip/issues/8210
ERROR: Unnamed requirements are not allowed as constraints

lint: exit 1 (0.31 seconds) /my/code/path> python -I -m pip install PyJWT cloudaux cryptography requests retry slack-bolt '-c/my/code/path/.tox/lint/constraints.txt' pid=71034
.pkg: _exit> python '/my/code/path/venv/lib/python3.9/site-packages/pyproject_api/_backend.py' True setuptools.build_meta
  py39: FAIL code 1 (14.78 seconds)
  lint: FAIL code 1 (12.69 seconds)
  evaluation failed :( (27.51 seconds)
```

## Additional Details
I'm making use of `pyproject.toml`. I have a flat `requirements.txt` file with:
```
[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
```
In `tox.ini`, I have:
```
[testenv]
deps =
    .[tests]
commands =
    pytest --cov MYPROJECT --cov-report term-missing MYPROJECT/ -n auto {posargs}
```

Reverting back to 4.3.5 resolves the issue.

**Comment by gaborbernat** [comment]
Cc @masenf

**Comment by masenf** [comment]
@gaborbernat i raised pr #2899 to set the chicken switch to false by default so that these edge cases don't break for people

**Comment by masenf** [comment]
There are a few issues that need to be addressed with the new constrain deps feature:

* I think `PythonDeps.unroll` is maybe not unrolling this `.[extra]` specification. I hadn't seen that before, and we don't have a test in place for that.
* if possible, tox should check the constraint file that it generates for validity... if it's not a valid file, then it shouldn't be used, but the user should be warned about it.

I'm pretty sure #2898 could be considered a duplicate of this one, and we can track this for the real fix after the workaround patch goes in.

**Comment by zzzeek** [comment]
for now I'm going forward turning off this feature with `constrain_package_deps=false`.   it's not clear to me what would be useful about it

**Comment by masenf** [comment]
> it's not clear to me what would be useful about it

It solves the longstanding issue described in #513. Essentially, if the tox.ini file says to install some requirement, this feature prevents the package's own requirements from overriding that.

**Comment by mikegrima** [comment]
Per the other thread, setting `constrain_package_deps = False` in `tox.ini` resolves?

**Comment by masenf** [comment]
@mikegrima that is correct; also tox-4.4.1 is about to be published which has `constrain_package_deps = False` as the default

**Comment by pllim** [comment]
This threw me off the loop. I thought it was `pip` (https://github.com/pypa/pip/issues/11749) and then I found this issue. Thanks for opening this issue and provide a workaround!

**Comment by pllim** [comment]
I can confirm that the latest release fixed this problem. Thanks for the quick turnaround!

**Comment by mikegrima** [comment]
The latest tox fixes the issue. Going to close this out. Thank you all for the fast turnaround!
