### ISSUE TITLE
Disable parallel spinner via environment variable

### ISSUE THREAD

**Issue by sirosen** [tox-dev/tox#2918]
## What's the problem this feature will solve?

Just as `TOX_PARALLEL_NO_SPINNER` in 3.x and `--parallel-no-spinner` today, being able to conditionally disable the spinner in CI is useful.

As a related note, I realized this no longer works while trying out a new GitHub Actions feature. The `setup-python` action has recently added the ability to install multiple pythons on a single worker. `tox p` invocations in that particular CI service may increase now that this is supported.

The basic use-case is some script or other usage which wraps `tox p`, which therefore needs to support local dev and CI. e.g. `make test` which does some setup, runs `tox p`, and then does some teardown.

## Describe the solution you'd like

I think it might be nice to base this off of the semi-standard `CI` environment variable, rather than a custom env var. That would make `tox p` appear to "magically" work correctly for most naive users, and it is simple enough to still be easy to document.

## Alternative Solutions

There are lots of easy ways to do this with the CLI option as a user, but you need to know to do it.

## Additional context

I don't believe that any other part of `tox run-parallel` behavior is specific to CI situations, so the spinner may deserve this special treatment.

I am more than happy to put in a PR, if the idea or something similar seems good.

**Comment by gaborbernat** [comment]
PR welcome.

**Comment by tushar-deepsource** [comment]
@gaborbernat more specifically, is it OK to just add back `TOX_PARALLEL_NO_SPINNER` to 4.x?

**Comment by gaborbernat** [comment]
```
env TOX_PARALLEL_NO_SPINNER=1 tox p -e py310,py311
```

works for me.

**Comment by sirosen** [comment]
Thanks for taking care of this (I forgot :grimacing: )!
