### ISSUE TITLE
tox/docs/config.rst - temp_dir possible change

### ISSUE THREAD

**Issue by jugmac00** [tox-dev/tox#2931]
### Discussed in https://github.com/tox-dev/tox/discussions/2930

<div type='discussions-op-text'>

<sup>Originally posted by **thecesrom** March  2, 2023</sup>
Hello,

In one of my projects where I ran `tox` I got an error from the IDE I was using saying that `.tmp` was not valid, and it turned out that it was referring to `.tox/.tmp`.

When I wanted to change the default name for `temp_dir` via `tox.ini` I noticed a potential mistake in the docs.

I've forked this repo and this is the `diff` for the change I might propose in a PR if it turns out I'm right.

```sh
$ git diff
diff --git a/docs/config.rst b/docs/config.rst
index adc7863..3804acd 100644
--- a/docs/config.rst
+++ b/docs/config.rst
@@ -174,7 +174,7 @@ Core
 
 .. conf::
    :keys: temp_dir
-   :default: {tox_root}/.tmp
+   :default: {work_dir}/.tmp
 
    Directory where to put tox temporary files. For example: we create a hard link (if possible, otherwise new copy) in
    this directory for the project package. This ensures tox works correctly when having parallel runs (as each session
```

>`tox_root` `toxinidir`
>
>The root directory for the tox project (where the configuration file is found).

While...

>`work_dir` `toxworkdir` with default value of `{tox_root}/.tox`

So as my `diff` shows, I believe the docs should be modified.</div>

**Comment by gaborbernat** [comment]
I think this has been addressed now.
