### ISSUE TITLE
Specify environment variable for individual commands

### ISSUE THREAD

**Issue by vashek** [tox-dev/tox#2957]
## What's the problem this feature will solve?

If I need to set an environment variable for a single test command, there seems no simple or obvious way to do that. For example, this doesn't work in Windows:
```
commands = 
    set DB_TYPE=PGSQL
    pytest ...
    set DB_TYPE=MSSQL
    pytest ...
```
And presumably this:
```
commands = 
    export DB_TYPE=PGSQL
    pytest ...
    export DB_TYPE=MSSQL
    pytest ...
```
or this:
```
commands = 
    DB_TYPE=PGSQL pytest ...
    DB_TYPE=MSSQL pytest ...
```
wouldn't work on Linux.

## Describe the solution you'd like

Ideally, this would work on any platform to set (one or more) variable(s) just for the one command:
```
commands = 
    DB_TYPE=PGSQL pytest ...
    DB_TYPE=MSSQL pytest ...
```

Or, alternatively, variables could be set for all subsequent commands like this:

```
commands = 
    DB_TYPE=PGSQL
    pytest ...
    DB_TYPE=MSSQL
    pytest ...
```

## Alternative Solutions

What I did, for now:
```
commands =
    -mkdir test-reports
    python -c "import os, sys; os.environ['DB_TYPE']='PGSQL'; sys.exit(os.system('pytest -k sql --junitxml=test-reports/pytest-PGSQL-{env_name}.xml'))"
    python -c "import os, sys; os.environ['DB_TYPE']='MSSQL'; sys.exit(os.system('pytest -k sql --junitxml=test-reports/pytest-MSSQL-{env_name}.xml'))"
```
It works (at least on Windows, haven't yet tested on Linux) but is... unwieldy.

**Comment by gaborbernat** [comment]
Any reason why they shouldn't be in separate test environments instead? The suggested syntax is definitely a no go as it wouldn't be backwards compatible.

**Comment by vashek** [comment]
The only reason, really, is having one fewer environment (and therefore a faster build and less wasted space), and a cleaner/shorter/more readable tox.ini.

As for the backwards incompatibility: true, if someone has an executable with an equals sign in the filename. Perhaps it could be made optional, or some completely new syntax could do the trick, like `setenv-for-command-1: VAR=NAME`...

Admittedly I'm not very experienced with tox. Maybe this is misguided. I do find it weird that noone else is missing this in tox v4.4; maybe there's a reason for that. :)

**Comment by gaborbernat** [comment]
I would make the argument that this kind of complicated obfuscation of setting the environment variables per command actually makes the configuration harder to read. Not easier. Just because it's shorter doesn't mean it's easier to read, often time actually the opposite is the case. As far as space wasting goes, that's true, but I don't think it matters that much. Space is cheap nowadays.

**Comment by gaborbernat** [comment]
In conclusion, I think feel free to add this functionality as the plugin. However, we don't plan to add this to the core for now. Instead of recommend to people to split their commands two different environments.
