### ISSUE TITLE
4.4.7 is missing from the changelog

### ISSUE THREAD

**Issue by hauntsaninja** [tox-dev/tox#2973]
https://pypi.org/project/tox/4.4.7/
https://tox.wiki/en/latest/changelog.html

**Comment by masenf** [comment]
Since 4.4.7 was "just a doc change", it's full payload was merged without any change log requirements

https://github.com/tox-dev/tox/compare/4.4.6...4.4.7

**Comment by hauntsaninja** [comment]
Thanks! Sorry, I should have just looked up the diff :-)
