### ISSUE TITLE
devenv feature does not recognize "skipdist = true" in tox.ini

### ISSUE THREAD

**Issue by baka91** [tox-dev/tox#2977]
## Issue

"tox d test_env" fails, when trying to create the devenv for a python application that isn't intended for distribution (has no setup.py and not setup.cfg), because it does not recognize the "skipdist = true" parameter inside the tox.ini file.

## Environment

- OS: Windows 11 Pro (Version: 22H2)
- `pip list` of the host Python where `tox` is installed:
cachetools    5.3.0
chardet       5.1.0
colorama      0.4.6
distlib       0.3.6
filelock      3.10.7
packaging     23.0
pip           23.0.1
platformdirs  3.2.0
pluggy        1.0.0
pyproject_api 1.5.1
setuptools    67.6.0
tomli         2.0.1
tox           4.4.8
virtualenv    20.21.0
wheel         0.38.4

- tox.ini
[tox]
envlist = lint,type,test
skipdist = true

[testenv]
basepython = py310: python3.10

```console
tox d test_env
```

## Output of running tox
py: packaging backend failed (code=error: Multiple top-level packages discovered in a flat-layout: ['stubs', 'quick_env', 'mediabrowser']

Provide the output of `tox -rvv`:

```console

```

## Minimal example

If possible, provide a minimal reproducer for the issue:

```console
pip install tox
tox d test_env
```

**Comment by baka91** [comment]
Using tox with a manually created virtual environment works as intended.
Just when I try to use this practical devenv feature I encounter issues.
I'm completely new to tox, but from what I understand from the error log, tox tries to install my local files as an editable package and fails.
Since I'm trying to develop a python application and not a package for distribution I thought I would not need a setup.py and setup.cfg.

**Comment by gaborbernat** [comment]
The `devenv` feature is for libraries. Applications don't need a developer environment, and can use the test environment directly instead.

**Comment by baka91** [comment]
> The devenv feature is for libraries. Applications don't need a developer environment, and can use the test environment directly instead.

I didn't know that, but I still don't fully understand to be honest.
Isn't it generally recommended to work inside a virtual environment?
Especially if you work on multiple projects/applications at the same time?

**Comment by gaborbernat** [comment]
Personal preference utlimately.
