### ISSUE TITLE
Support for negative entries in `-e`

### ISSUE THREAD

**Issue by masklinn** [tox-dev/tox#3004]
## What's the problem this feature will solve?

When [using different envs for different tasks](https://tox.wiki/en/latest/user_guide.html#configuration), if all of them support posargs the posargs become difficult to use, as they'll never be compatible with every command.

But assuming the most common environments are the "normal" generative testing envs (aka those running pytest or something along those lines) selecting only those is a bit of a chore, as — as far as I know — `-e` does not support globbing.

So with the (official) example above, if one wants to run the test suite with tweaks one has to explicitely list the envs:

    $ tox r -e py38,py39,py310,py311 -- --count 5 -k <some-marker>

things get worse when also testing with alternate impls e.g.

    $ tox r -e py38,py39,py310,py311,pypy38,pypy39 -- --count 5 -k <some-marker>

## Describe the solution you'd like

For `-e` to support negative parameters, to remove from the default list e.g.

    $ tox -r -e '!lint,!type' -- --count 5 -k <some-marker>

would do essentially the same as above, just the other way around.

**Comment by masenf** [comment]
Typically I would use labels for this: https://tox.wiki/en/latest/config.html#labels

Or --skip-env: https://tox.wiki/en/latest/cli_interface.html#tox-run---skip-env

Are either of these workable in your use case?

**Comment by masklinn** [comment]
Oh yeah labels definitely look good, I'd *seen* them in the CLI doc but not really *noticed* them, if that makes sense, so it'd not clicked that I could define a label or five and use that as my filter.
