### ISSUE TITLE
Allow testing under both Python 3.6 and 3.12

### ISSUE THREAD

**Issue by encukou** [tox-dev/tox#3005]
## What's the problem this feature will solve?

As far as I can see, it is not possible to test under both Python 3.6 and 3.12.

There is no version of `virtualenv` that can create virtual environments for both Python 3.6 and 3.12. 
tox uses virtualenv via import and you can have only one version per interpreter, so, it is not possible to create both environments in a single installation/invocation of tox.

## Describe the solution you'd like

Several solutions come to mind:
- Allow optionally stdlib `venv` rather than `virtualenv` for some test environments
- Allow optionally calling `virtualenv` as a subprocess, with the command being configurable
- Declare that tox doesn't support Python versions once they're no longer supported by python.org (or some other criterion)

## Alternative Solutions

It's possible to:
- Use two different installations of tox
- Use a patched version of virtualenv

## Additional context

A bit of previous discussion: https://github.com/pypa/virtualenv/pull/2548#issuecomment-1527278210

**Comment by gaborbernat** [comment]
https://tox.wiki/en/latest/faq.html#testing-end-of-life-python-versions

**Comment by hroncok** [comment]
The solution is no longer working with Python 3.15 environments: https://github.com/tox-dev/tox/issues/3656
