### ISSUE TITLE
platformdirs and poetry issues

### ISSUE THREAD

**Issue by Sengolda** [tox-dev/tox#3012]
## Issue

So basically I have both poetry and tox and this error comes up

## Environment

Provide at least:

- OS: `Linux Mint 21.1`
- `pip list` of the host Python where `tox` is installed:

```console
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tox 4.5.1 requires platformdirs>=3.2, but you have platformdirs 2.5.2 which is incompatible.
```

```console
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.4.2 requires platformdirs<3.0.0,>=2.5.2, but you have platformdirs 3.5.1 which is incompatible.

```

## Output of running tox

Provide the output of `tox -rvv`:
Wasn't able to install tox

## Minimal example
Wasn't able to install tox

**Comment by gaborbernat** [comment]
Those two have probably conflicting dependencies as pip says. Nothing we can do about this. Don't install them in the same envs, use pipx to separate their installation.
