### ISSUE TITLE
Android users usually dropping connection while downloading shared files

### ISSUE THREAD

**Issue by Alceris** [tox-dev/tox#3026]
I'm on a Windows 10 desktop, trying to send files to people that are on an Android device, and the overwhelming majority of times if those files are near 1 MB or larger, the connection gets inexplicably dropped in the middle of downloading and never at any other time, so the download ends up getting cancelled.

I can download files from them perfectly fine, and if they switch to a desktop or laptop they can download files from me perfectly fine, so far it's been an issue exclusive to Android.

**Comment by gaborbernat** [comment]
tox does not itself download anything. It uses pip to do so, therefore this is likely a pip issue.

**Comment by jugmac00** [comment]
The op probably referred to tox - the chat client, see https://tox.chat/.

**Comment by Alceris** [comment]
Oh crap, my bad, I didn't realize this was for something completely unrelated with the same name.
