### ISSUE TITLE
spurious SetuptoolsDeprecationWarning when run parallel

### ISSUE THREAD

**Issue by dotysan** [tox-dev/tox#3027]
## Issue

When running tox jobs in parallel, occasionally get a SetuptoolsDeprecationWarning.

This happens spuriously. And only seems to happen during environment creation.

I've completely deleted setup.py. And only running pyproject.toml and setup.cfg.

## Environment

Provide at least:

- OS: Ubuntu 20LTS in WSL
- `pip list` of the host Python where `tox` is installed:
```console
Package       Version
------------- -------
cachetools    5.3.1
chardet       5.1.0
colorama      0.4.6
distlib       0.3.6
filelock      3.12.0
packaging     23.1
pip           23.1.2
platformdirs  3.5.1
pluggy        1.0.0
pyproject_api 1.5.1
setuptools    67.8.0
tomli         2.0.1
tox           4.6.0
virtualenv    20.23.0
wheel         0.40.0
```

## Output of running tox

Provide the output of `tox -rvv`:

```console
ROOT: 127 D setup logging to DEBUG on pid 19886 [tox/report.py:221]
/home/curtis/src/honeybadger-python/.venv/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
...
```

If it occurs, it occurs immediately upon running tox and way before any per-env DEBUG messages.

## Minimal example

If possible, provide a minimal reproducer for the issue:

```console
python3.9 -m venv .venv
source .venv/bin/activate
pip install --upgrade pip setuptools wheel
pip install tox
tox --recreate --verbose --verbose --colored=yes run-parallel --parallel=auto --parallel-no-spinner --skip-missing-interpreters=false
```

Again, this only occurs spuriously and when I have multiple environments in parallel. `env_list = py3.{7,8,9}-dj{1,2.2}`

Maybe this is a bug in setuptools?

My biggest concern is the spurious nature of this issue. The whole point or running tox is to get deterministic behavior--which appears isn't happening!

**Comment by gaborbernat** [comment]
tox does not uses setuptools, so must be an issue with your project and or setuptools.

**Comment by dotysan** [comment]
OK thx. I'll run it down from pytest.

**Comment by dotysan** [comment]
FYI, in case anyone else stumbles across this. It's coming from the virtualenv runner. And only seems to appear under Python 3.9.

**Comment by adam-grant-hendry** [comment]
> And only seems to appear under Python 3.9.

Happens in Python 3.8 as well... :/
