### ISSUE TITLE
Docs request: linking env substitution docs in `set_env`'s docs

### ISSUE THREAD

**Issue by jamesbraza** [tox-dev/tox#3036]
## What's the problem this feature will solve?

[`set_env` option](https://tox.wiki/en/latest/config.html#set_env) supports environment variable substitution.

This capability is only mentioned in a separate portion of the docs: [Environment variable substitutions with default values](https://tox.wiki/en/latest/config.html#environment-variable-substitutions-with-default-values).

I only discovered the link thanks to https://github.com/tox-dev/tox/issues/491.

## Describe the solution you'd like

Can we link this substitution section within the `set_env` section?  Also, does it apply to `pass_env`?

**Comment by gaborbernat** [comment]
PR welcome with your suggestion ☺️
