### ISSUE TITLE
An environment variable indicating the tox worker number in --parallel

### ISSUE THREAD

**Issue by nedbat** [tox-dev/tox#3041]
## What's the problem this feature will solve?

When using `tox --parallel`, coverage writes a number of data files and tries to combine them.  But multiple processes are working in the same directory, creating a race condition.  If we had an environment variable that distinguished among the parallel workers, we could name the data files differently and avoid collisions.

Here are reports of the problem:
- https://github.com/nedbat/coveragepy/issues/1514
- https://github.com/nedbat/coveragepy/issues/1642

## Describe the solution you'd like

An environment variable called TOX_WORKER, a number for each worker, similar to pytest xdist's PYTEST_XDIST_WORKER.

**Comment by gaborbernat** [comment]
We already inject the talks environment name as an environment variable, any reason why that will not suffice?

**Comment by nedbat** [comment]
In this case, it looks like that will work.  I think it could be useful to have the environment variable anyway.

**Comment by gaborbernat** [comment]
tox environments are unordered so assigning numbers doesn't make sense, so for now I'll say no to such request. The name is a better identifier.
