### ISSUE TITLE
Pluggy version 1.1.0 yanked

### ISSUE THREAD

**Issue by ravikr1** [tox-dev/tox#3046]
## Issue

pluggy is one of the requirements for tox and the latest version of pluggy which is 1.1.0 has been yanked

## Environment

Provide at least:

- OS:

<details open>
<summary>Output of <code>pip list</code> of the host Python, where <code>tox</code> is installed</summary>

```console

```

</details>

## Output of running tox

<details open>
<summary>Output of <code>tox -rvv</code></summary>

```console

```

</details>

## Minimal example

```console

```

**Comment by gaborbernat** [comment]
We do not depend on 1.1 direclty, just 1.0. https://github.com/tox-dev/tox/blob/main/pyproject.toml#L58
