### ISSUE TITLE
If TOX_WORK_DIR is set, honor it.

### ISSUE THREAD

**Issue by jaraco** [tox-dev/tox#3050]
This issue is a revived feature request of #20.

In summary, I'd like tox to honor `TOX_WORK_DIR` as the default `tox.toxworkdir` if set, similar to the effect of adding

`toxworkdir={env:TOX_WORK_DIR:.tox}`

to the tox.ini file.

In #1653, I attempted to implement the feature, but failed to land it before resolving all of the issues.

I'd still like to see this feature implemented so that I don't have to carry this config in every tox file.

**Comment by gaborbernat** [comment]
PR welcome.

**Comment by jaraco** [comment]
I'll offer a $100 bounty to anyone able to get a PR merged for this feature.

**Comment by gaborbernat** [comment]
Isn't this already working?

```fish
❯ env TOX_WORK_DIR=.tox4 tox c -e py311 -k env_dir
[testenv:py311]
env_dir = /Users/bgabor8/git/github/tox/.tox4/py311
~/git/github/tox on  work-dir [$?⇡]
❯ env TOX_WORK_DIR=.tox3 tox c -e py311 -k env_dir
[testenv:py311]
env_dir = /Users/bgabor8/git/github/tox/.tox3/py311
```

**Comment by jaraco** [comment]
Yes! It does work.

It seems to have been fixed in the 4.0.0a2, so was fixed in the rewrite.

That's fantastic news. I'm a little ashamed I didn't think to re-check the assumption.

Would you like the bounty?

**Comment by gaborbernat** [comment]
Up to you, if you like the feature and would like to reward my rewrite effort feel free to use my GitHub sponsor account 👍no pressure though 👍

**Comment by jaraco** [comment]
I've been extremely impressed with the reliability and design of tox 4. Thanks for doing all that work.

**Comment by JohnVillalovos** [comment]
For anybody who is trying to run `tox` inside of `tox`. Meaning using `tox` to run `tox` in a different directory this can break things for you, if you use the same environment name in both `tox.ini`. As the lower level `tox` will be using the upper level's work directory.

Conditions for breakage:
  * The top-level `tox.ini` environment calls lower-level `tox.ini` environment of the same name. In my case they were both called "validate-dhcp"
  * The environments have different requirements. So my top-level environment only has a dependency on `tox` while the lower-level environment has different requirements.

My work around was to do:
```
  [testenv:validate-dhcp]
  allowlist_externals = env
  deps = tox
  change_dir = {toxinidir}/ci
  commands =
    env 'TOX_WORK_DIR=' tox -e validate-dhcp
```
