### ISSUE TITLE
Latest versions are not documented on tox.wiki

### ISSUE THREAD

**Issue by allanlewis** [tox-dev/tox#3053]
## Issue

tox.wiki purports to document all recent versions of Tox. However, the version list ends at 4.5.1; the latest at time of writing is 4.6.3.

## Environment

n/a

## Output of running tox

n/a

## Minimal example

n/a

**Comment by jugmac00** [comment]
Thanks for reporting. I can confirm this issue.

I have not set up projects to have documentation for each version before, but from reading the RTD documentation, it looks like there should be something set up in https://readthedocs.org/dashboard/tox/rules/ - but that is emtpy.

@gaborbernat Are you aware how this work?

**Comment by gaborbernat** [comment]
No idea. Seems these versions were built but not marked active. Added some rules here https://readthedocs.org/dashboard/tox/rules per https://docs.readthedocs.io/en/stable/guides/automation-rules.html, no idea why this worked and no longer does though.

**Comment by allanlewis** [comment]
So is this fixed? Or a "won't fix"? Will the docs be stuck at 4.5.1 forever?

**Comment by gaborbernat** [comment]
It should be fixed.

**Comment by gaborbernat** [comment]
<img width="689" alt="image" src="https://github.com/tox-dev/tox/assets/690238/9e889ae1-409f-4ed8-a586-7048d880f672">

**Comment by allanlewis** [comment]
Excellent, thanks! 👏👏👏
