### ISSUE TITLE
Stale egg-info used to build packages?

### ISSUE THREAD

**Issue by njiles** [tox-dev/tox#3071]
First of all, thanks for the great tool!

I'm not sure if this is an issue in tox, something that can be configured, or my misunderstanding of how tox and/or Python packaging work - I would appreciate some clarity.

When an egg-info directory is present, tox seems to use that to build the package, rather than generating afresh. This can mask issues during development (which is how we discovered this behaviour!): a previous working build leaves a 'good' egg-info directory in place; a developer makes some changes which should break the build (e.g. changing pyproject.toml, see MWE below); but tox does not catch these issues because it uses the 'good' egg-info directory rather than the 'bad' source.

Tested with Python version 3.9.16 and tox version 4.6.4. Tox used virtualenv 20.24.2, setuptools 67.8.0, wheel 0.40.0, and pip 23.1.2.

To reproduce:
1. Clone the MWE from https://github.com/njiles/tox-egg-info-demo and run `tox -r`. The test should pass.
2. Edit pyproject.toml to remove the `[tool.setuptools.package-data]` section (or change the "hello.txt" filename therein to something incorrect) and run `tox -r` again.
    * We expect the test to fail, as without the correct package-data configuration the hello.txt file should not be part of the package.
    * However, the test passes.
3. Remove the src/tox_egg_info_demo.egg-info directory and rerun `tox -r` (keeping the 'broken' pyproject.toml from step 2). Now the test fails with a FileNotFoundError as expected.

The outputs of `tox -rvvv` for steps 1, 2 and 3 are attached (too many characters to include in issue body!)
[step-1-output.txt](https://github.com/tox-dev/tox/files/12186005/step-1-output.txt)
[step-2-output.txt](https://github.com/tox-dev/tox/files/12186006/step-2-output.txt)
[step-3-output.txt](https://github.com/tox-dev/tox/files/12186007/step-3-output.txt)

**Comment by gaborbernat** [comment]
tox doesn't build your packages, in your case setuptools does here https://github.com/njiles/tox-egg-info-demo/blob/main/pyproject.toml#L4, so this is a setuptools issue.

**Comment by njiles** [comment]
Ah, so this isn't covered by tox's build isolation - that is just for packages and versions? Got it, thanks for the quick response 👍
