### ISSUE TITLE
tox quickstart: error: the following arguments are required: root

### ISSUE THREAD

**Issue by Vuizur** [tox-dev/tox#3084]
## Issue

I ran `tox quickstart` as described in https://tox.wiki/en/latest/user_guide.html.

and get the error `tox quickstart: error: the following arguments are required: root`.

It seems that either the default parameter that should select the current working environment seems to be broken or the documentation should be updated.

## Environment

Provide at least:

- OS: Windows 11

<details open>
<summary>Output of <code>pip list</code> of the host Python, where <code>tox</code> is installed</summary>

```console
Python version: 3.11
Packages: No idea, I installed with pipx
```

</details>

Thanks a lot for developing this super useful library!

**Comment by jugmac00** [comment]
The initial implementation was done in #1907.

**Comment by Tbruno25** [comment]
I'm happy to submit a PR for this.

Looking at the implementation, the `root` argument has `default=Path().absolute()`. 

Based on this, I think it's safe to assume that the `root` positional argument was intended to be optional?

**Comment by gaborbernat** [comment]
Yes 👍
