### ISSUE TITLE
[4.9.0] How to run `testenv` when `envlist` is non-empty?

### ISSUE THREAD

**Issue by PawelLipski** [tox-dev/tox#3092]
## Issue

I've got the following tox.ini: https://github.com/VirtusLab/git-machete/blob/master/tox.ini

```ini
[tox]
...
envlist = pep8,isort,pep8-check,mypy,vulture-check,sphinx-man,py-docs
...

[testenv]
...
```

Plain `tox` doesn't run tests (runs some other envs instead).

Under tox<=4.8.0, I could just run `tox -e testenv` (or even, `tox -e just-about-anything`) to get the `testenv` executed.

But under tox==4.9.0, `tox -e testenv` fails with:

```
ROOT: HandledError| provided environments not found in configuration file: ['testenv']
```

## Environment

Provide at least:

- OS (`sw_vers`): 
```
ProductName:		macOS
ProductVersion:		13.5
BuildVersion:		22G74
```

<details open>
<summary>Output of <code>pip list</code> of the host Python, where <code>tox</code> is installed</summary>

```console
Package                       Version   Editable project location
----------------------------- --------- ------------------------------------
alabaster                     0.7.13
altgraph                      0.17.2
Babel                         2.12.1
bump2version                  1.0.1
cachetools                    5.3.1
certifi                       2023.7.22
chardet                       5.2.0
charset-normalizer            3.2.0
colorama                      0.4.6
distlib                       0.3.7
docutils                      0.18.1
filelock                      3.12.2
future                        0.18.2
git-machete                   3.18.1
gitdb                         4.0.10
GitPython                     3.1.32
idna                          3.4
imagesize                     1.4.1
importlib-metadata            6.8.0
Jinja2                        3.1.2
macholib                      1.15.2
MarkupSafe                    2.1.3
packaging                     23.1
pip                           23.2.1
platformdirs                  3.10.0
pluggy                        1.2.0
Pygments                      2.16.1
pyproject-api                 1.5.3
python-slugify                4.0.1
requests                      2.31.0
setuptools                    58.0.4
six                           1.15.0
smmap                         5.0.0
snowballstemmer               2.2.0
Sphinx                        6.2.1
sphinx-rtd-theme              1.2.2     /Users/pawel_lipski/sphinx_rtd_theme
sphinxcontrib-applehelp       1.0.4
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.1
sphinxcontrib-httpdomain      1.8.1
sphinxcontrib-jquery          4.1
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
text-unidecode                1.3
tomli                         2.0.1
tox                           4.9.0
transifex-client              0.14.4
urllib3                       1.26.16
virtualenv                    20.24.3
wheel                         0.37.0
zipp                          3.16.2
```

</details>

## Output of running tox

<details open>
<summary>Output of <code>tox -rvv -e testenv</code></summary>

```console
ROOT: 232 E HandledError| provided environments not found in configuration file: ['testenv'] [tox/run.py:22]

```
</details>

**Comment by jugmac00** [comment]
Hey @PawelLipski,

running `tox -e testenv` or more specifically `tox -e somethingnotexisting` not erroring was a regression from the tox 3 -> tox 4 rewrite, see https://github.com/tox-dev/tox/issues/2858.

tox 4.9.0 fixed that regression.

Usually, you want to specify the Python version in the `testenv`, e.g. `py310`.

If you do not care about a specific Python version, and you want to use the same version as tox was installed with, you can use `py`.

```
tox -e py
```

I had a quick look in our documentation and I could not find that documented, but certainly searching for `py` does not give decent results.

I want to keep this issue open until I had time to have a closer look in our documentation or add a paragraph about the usage of `py`.

**Comment by PawelLipski** [comment]
😯 wow good to know, I've never seen such usage indeed! thanks

**Comment by mikegrima** [comment]
I just got burned by this. My project (https://github.com/gemini-oss/starfleet/blob/main/tox.ini) would have tests on GitHub actions run with the following command that used to work on older tox versions: `tox -e test,cloudformation,mkdocs`. 

The latest Tox version requires: `tox -e py,cloudformation,mkdocs` instead.
