### ISSUE TITLE
Provide a way to upgrade packaging tools before installation of dependencies

### ISSUE THREAD

**Issue by Bengt** [tox-dev/tox#3098]
## What's the problem this feature will solve?

I am trying to install or upgrade the usual packaging tools pip, setuptools and wheel before installing any packages my application actually uses. Currently, the deps stage gives me a way of installing them at the same time as my package's dependencies. This is not sufficient, as some packages are distributed as wheels, which means that wheel has to be installed beforehand. As I am running tox on multiple systems, including in various Docker images in my continuous integration pipelines, I cannot assume that wheel is preinstalled in a sufficiently recent version on the operating system level.

## Describe the solution you'd like

I would like a way to specify such foundational requirements that are needed for installing payload packages. I would suggest naming it `deps_pre`.

A real-world use case would use run in a minimal python image that does not include wheel and use tox to setup an environment for a Python package where one of the dependencies is provided as a wheel. With the current solution, wheel might be scheduled to be installed after the package requiring it, so that the installation fails. With the additional stage, users could ensure that the wheel package is installed before trying to install the wheel of the other package.

## Alternative Solutions

As a workaround, one can define a distribution using a setup.py or pyproject.toml and list requirements that require wheel that way. These requirements are installed after tox' `deps` requirements, so the installation of packages provided as wheels always succeeds. However, since not all Python packages are intended to be installed, packaging them as a distribution is extra effort, misleading and all around a bad solution.

## Additional context

This has bitten me multiple times already, but I am only reporting it now, because I have the time to look for a more proper solution. I hope I am wrong in that there is no nice solution for this use case in tox and that I will be pointed to it in the course of the discussion here.

**Comment by gaborbernat** [comment]
You should use https://peps.python.org/pep-0518 to provision your package dependencies.

**Comment by gaborbernat** [comment]
For upgrading pip you can use https://tox.wiki/en/4.9.0/faq.html#customizing-virtual-environment-creation
