### ISSUE TITLE
Tox silently ignores environment builder error

### ISSUE THREAD

**Issue by f3flight** [tox-dev/tox#3104]
## Issue

I've reported this issue here as well - https://github.com/pdm-project/tox-pdm/issues/43

I'm using tox-pdm plugin.

Reproduction: https://github.com/f3flight/tox-pdm-silent-failure-issue
Steps after cloning:
```
python3 -m venv venv
. venv/bin/activate
pip install tox pdm tox-pdm
tox
```

Output:
```
(venv) [dsutiagi@dsutiagi-ld3 tox_pdm_bug]$ tox
py311: > pdm sync --no-self --group test
.pkg: install_requires> python -I -m pip install setuptools wheel
.pkg: _optional_hooks> python /home/dsutiagi/Temp/tox_pdm_bug/venv/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: get_requires_for_build_sdist> python /home/dsutiagi/Temp/tox_pdm_bug/venv/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: build_sdist> python /home/dsutiagi/Temp/tox_pdm_bug/venv/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
py311: install_package_deps> python -I -m pip install 'pyyaml>=6.0'
py311: install_package> python -I -m pip install --force-reinstall --no-deps /home/dsutiagi/Temp/tox_pdm_bug/.tox/.tmp/package/1/helloworld-0.0.0.tar.gz
py311: commands[0]> pytest test.py
py311: exit 2 (0.01 seconds) /home/dsutiagi/Temp/tox_pdm_bug> pytest test.py
.pkg: _exit> python /home/dsutiagi/Temp/tox_pdm_bug/venv/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
  py311: FAIL code 2 (13.34=setup[13.33]+cmd[0.01] seconds)
  evaluation failed :( (13.45 seconds)
```

As you can see, there's an error but there is no error message, or rather, the error message is confusing (exit 2) - tox tries to run "pytest" while in fact pdm failed so there's no pytest and no point in even trying this command.

If tox is run with debug level verbosity (-vv), only then we can see the error:
```
...
py311: 321 W > pdm sync --no-self --group test [tox/tox_env/api.py:427]
[ProjectError]: Lock file does not exist, nothing to install
...
```

I think this behavior is suboptimal and some change needs to be introduced so that pdm failure bubbles up and prevents env from continuing execution and reaching commands, and error should be displayed w/o any -v flags. Right now this error is put into "_hidden_outcomes": https://github.com/tox-dev/tox/blob/release-4.10.0/src/tox/tox_env/api.py#L440 so I think that's part of the issue, but I'm not confident as I'm no good in tox internals.

## Environment

- OS: CentOS7, Python 3.11 (same on 3.10), latest tox, pdm, tox-pdm

**Comment by gaborbernat** [comment]
I think this is a plugin error. If they encounter an error that's show stopper they should raise HandledError.
