### ISSUE TITLE
Append AR to _default_pass_env

### ISSUE THREAD

**Issue by adelplanque** [tox-dev/tox#3141]
Since passenv doesn't work during build phase, add AR to _default_pass_env: https://github.com/tox-dev/tox/blob/main/src/tox/tox_env/api.py#L205

Some builds needs to define AR=gcc-ar in order to allow link time optimisation.

**Comment by gaborbernat** [comment]
https://tox.wiki/en/4.11.3/upgrading.html#packaging-configuration-and-inheritance
