### ISSUE TITLE
GraalPy support

### ISSUE THREAD

**Issue by kurtmckee** [tox-dev/tox#3148]
## What's the problem this feature will solve?

The GitHub action `actions/setup-python` has recently merged [a PR to support GraalPy](https://github.com/actions/setup-python/pull/694) (note that this support hasn't been released yet -- to access it, I think it's still necessary to reference `actions/setup-python@main` in a CI workflow).

GraalPy will be the third interpreter type available when running jobs in GitHub CI, and I'd like to have a way to test it alongside CPython and PyPy, as a defined tox environment.

## Describe the solution you'd like

I'd like to be able to specify GraalPy as a target interpreter for a tox environment.

Their version scheme appears to differ from CPython and PyPy -- in GitHub it's referenced as "graalpy-23.0"...it seems they currently target Python 3.10 as the language version.

## Alternative Solutions

I haven't tried anything to resolve this. I imagine (but haven't tested!) that manipulating the `$PATH` might allow tox to only see the GraalPy `python` executable.

**Comment by gaborbernat** [comment]
This sounds like something that should live as a plugin first until gets wide adoption.
