### ISSUE TITLE
Output of tox -lav is barely user readable (list all environments with description)

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox#3175]
## Issue

Since tox v4, the output of `tox -lav` and also `tox -lv` become hardly readable due to the extra logging implied by `-v`. Because `-v` is also needed in order to list descriptions, user is forced to look at something like below.

## Output of running tox

![](https://sbarnea.com/ss/Screen-Shot-2023-12-15-11-44-28.13.png)

<details open>
<summary>Output of <code>tox -rvv</code></summary>

```console
tox -lv 
default environments:
ROOT: find interpreter for spec PythonSpec(path=/Users/ssbarnea/.asdf/installs/python/3.12.0/bin/python3.12)
ROOT: proposed PythonInfo(spec=CPython3.12.0.final.0-64, exe=/Users/ssbarnea/.asdf/installs/python/3.12.0/bin/python3.12, platform=darwin, version='3.12.0 (main, Oct  4 2023, 16:44:35) [Clang 15.0.0 (clang-1500.0.40.1)]', encoding_fs_io=utf-8-utf-8)
py   -> Run pytest under /Users/ssbarnea/.asdf/installs/python/3.12.0/bin/python3.12 (/Users/ssbarnea/c/a/ansible-creator/.tox/py/bin/python)
ROOT: find interpreter for spec PythonSpec(path=/Users/ssbarnea/.asdf/installs/python/3.12.0/bin/python3.12)
ROOT: proposed PythonInfo(spec=CPython3.12.0.final.0-64, exe=/Users/ssbarnea/.asdf/installs/python/3.12.0/bin/python3.12, platform=darwin, version='3.12.0 (main, Oct  4 2023, 16:44:35) [Clang 15.0.0 (clang-1500.0.40.1)]', encoding_fs_io=utf-8-utf-8)
lint -> Enforce quality standards under /Users/ssbarnea/.asdf/installs/python/3.12.0/bin/python3.12 (/Users/ssbarnea/c/a/ansible-creator/.tox/lint/bin/python)
docs -> Builds docs
```
</details>

I guess that this is a little bit of a side effect of the changes made combined with the attempt to keep the backwards compatibility of the cli arguments, but clearly we should do something to make the output human friendly.

The fact that the logging entries are more visible than the real output makes it even worse. 

While me as a heavy tox user can live with that downside the real challenge is when I introduce other people to tox and they ask how to see which environments are available... and at that point I am bit forced to make use of shell stderr redirection to get something readable out of it.

**Comment by gaborbernat** [comment]
Did you try using just tox l? You know the dedicated subcommands?

**Comment by ssbarnea** [comment]
I am ashamed that I did not know that. I guess it could prove useful to add a warning for each legacy command, reminding users to switch to new ones. More than a decade of tox did build some muscle memory which is quite hard to change. BTW, thanks and have a nice new year!
