### ISSUE TITLE
extend_env setting

### ISSUE THREAD

**Issue by AiyionPrime** [tox-dev/tox#3240]
## What's the problem this feature will solve?

I'm not sure if I'm simply overlooking it, but it appears the `setenv` setting overwrites itself in child elements:

```ini
[tox]
envlist = py38, lint

[testenv]
setenv =
    MY_VARIABLE = my_value
commands =
    python my_script.py

[testenv:child]
setenv =
    ANOTHER_VARIABLE = true
commands =
    python my_script.py
```

I'm looking for an option to have multiple children to testenv, of which some use `setenv` to configure their environment.
I need MY_VARIABLE in all of them, but the invokation of `setenv` in children does overwrite the one from testenv.

## Describe the solution you'd like

I'd like to find a clean way to extend the `setenv` from the parent.
My first thought was an `extend_env` setting.

My realworld problem is setting an environment variable for our company pypi for all envs, without duplicating the setting in all envs, which use `setenv` themselves.

## Alternative Solutions

Maybe there's a way to define the environment variable in a dedicated file and import it in all stages. That would duplicate the import, but at least not the setting with the address itself.

```python
COMMON_ENV = {
    'MY_VARIABLE': 'my_value'
}
```

```ini
[tox]
envlist = py38, lint

[testenv]
setenv =
    {[common]COMMON_ENV}
commands =
    python my_script.py

[testenv:lint]
setenv =
    {[common]COMMON_ENV}
    ANOTHER_VARIABLE = true
commands =
    python my_script.py
```

## Additional context

Just ask, I'll gladly provide it :)

**Comment by gaborbernat** [comment]
This is expected behavior. What you want can be expressed as:
```ini
[testenv]
set_env =
    MY_VARIABLE = my_value

[testenv:child]
set_env =
    {[testenv]set_env}
    ANOTHER_VARIABLE = true
```

**Comment by AiyionPrime** [comment]
Thank you!
