### ISSUE TITLE
`tox devenv`: Integration with running virtualenvs

### ISSUE THREAD

**Issue by chrysle** [tox-dev/tox#3301]
## What's the problem this feature will solve?

This is really just out of laziness; I've got the `pyenv-virtualenv` plugin configured and am running a PyEnv-managed virtual environment, and when I run `tox devenv`, it creates a new virtualenv in my current working directory, which I find a bit unpractical.

## Describe the solution you'd like

Could `tox devenv` detect any running virtual environment and create its developer environment within the same? Probably via a flag?

## Alternative Solutions

Of course I can always pass it the path as a positional argument.

**Comment by gaborbernat** [comment]
This is by design and cannot be changed, you can try to alter it via plugin but I wouldn't recommend it.

**Comment by chrysle** [comment]
May I ask why?

**Comment by gaborbernat** [comment]
Because tox environments are meant to be exclusively managed by tox, and not shared with either other envs or user managed envs.

**Comment by chrysle** [comment]
All right, thanks for the clarification.
