### ISSUE TITLE
Tests of tox itself require a lot of disk space

### ISSUE THREAD

**Issue by ziima** [tox-dev/tox#3308]
## Issue

Running the tests of the tox itself I run into `No space left on device` because I run out of space in `/tmp`. When I added `--basetemp={envtmpdir}` to the tox's `tox.ini`, I was able to observe that the temporary directory reached the size of 3.3 GB. It seems that temporary files are not removed during the test run, but only at the end of the run. I suggest to make tmp cleaning more aggressive and wipe used files right away.

## Environment

Provide at least:

- OS: Debian testing 6.8.12-1

Tested with tox 4.11.4 and or `main` branch.

## Minimal example

```console
tox run -e py312
# or
python3 ./src/tox/__main__.py run -e py312
```

**Comment by gaborbernat** [comment]
PR welcome.

**Comment by kemzeb** [comment]
Duplicate of #3278

**Comment by ziima** [comment]
Missed that. Thanks.
