### ISSUE TITLE
Set --parallel-no-spinner if in CI

### ISSUE THREAD

**Issue by ziima** [tox-dev/tox#3318]
## What's the problem this feature will solve?

`--parallel-no-spinner` is fairly required for CI runs to prevent the spinner from messing the output. It seems reasonable to set the flag on by default if CI is detected.

## Describe the solution you'd like

Set the `--parallel-no-spinner` default based on `is_ci()` utility.

## Alternative Solutions

No alternatives.

## Caveats
There's no `--parallel-spinner` which would force the spinner if it was disabled by the CI detection. `TOX_PARALLEL_NO_SPINNER=0` should still work in those (hopefully rare) cases.

**Comment by gaborbernat** [comment]
A pull request in this regard would be accepted.
