### ISSUE TITLE
Prefer `tox.toml` over `tox.ini` if both exist

### ISSUE THREAD

**Issue by webknjaz** [tox-dev/tox#3435]
So during migration of my repos to a new laptop I accidentally ended up with a tox repo checkout having an old `tox.ini` on disk. When I was trying out `tox r`, it was yelling at me about some CLI args that `pytest` didn't recognize.
It took me some time to see that `tox l` outputs envs from `tox.ini` and not `tox.toml`.

Action items:
* [ ] Decide whether to warn or error out if two definitions exist
* [ ] Make the TOML definition take precedence

**Comment by gaborbernat** [comment]
duplicate issue of https://github.com/tox-dev/tox/issues/3402
