### ISSUE TITLE
[docs] Obsolete documentation still available at http://codespeak.net/tox/

### ISSUE THREAD

**Issue by bittner** [tox-dev/tox#368]
Doing a [Web search (with DockDuckGo)](https://duckduckgo.com/?q=tox+testing+less+verbose) today I found a 2010 tox documentation, which probably should not be online anymore.

- http://codespeak.net/tox/ (listed with https in the search results)

Can you take this website offline or, better, have it redirect to the current documentation, please?

**Comment by hpk42** [comment]
Thanks for caring to report!  I removed the docs and added a redirect.
