### ISSUE TITLE
[Github admin] Add detox label

### ISSUE THREAD

**Issue by tomviner** [tox-dev/tox#370]
Now that https://bitbucket.org/hpk42/detox/pull-requests/5/tox-has-moved-to-github/diff is merged, the **detox** long_description says:

> Please file issues as "tox" issues using the "detox" label
>
>     https://github.com/tox-dev/tox/issues

Please can we create this "detox" label here in this repo.

**Comment by RonnyPfannschmidt** [comment]
done

**Comment by tomviner** [comment]
:+1:
