### ISSUE TITLE
Add `--envdir` flag to print envdir for an environment

### ISSUE THREAD

**Issue by Daenyth** [tox-dev/tox#379]
This would make it easier to manually activate the virtualenv for a tox environment. Currently you can do this but it's not so memorable:

```
source $(tox -e envname --showconfig | awk '/envdir/ { print $3 }')/bin/activate
```

Possible interfaces would be:

```
eval `tox --envdir envname`  # prints out 'source path/to/env/bin/activate'

source `tox --envdir envname`/bin/activate # print out the root

source `tox --envdir envname` # print out 'path/to/env/bin/activate'
```

Of these I like the `eval` interface the best, though perhaps it would be better as `tox --activate envname`

**Comment by hpk42** [comment]
what about ``tox -e envname --showconfig envdir``.  IOW, some way to select what config value should be shown?

**Comment by Daenyth** [comment]
That's potentially confusing if you need to distinguish between arguments
to showconfig vs a new positional argument for the case where you want to
show all

On Wed, Oct 12, 2016, 3:57 PM holger krekel <notifications@github.com>
wrote:

what about tox -e envname --showconfig envdir. IOW, some way to select what
config value should be shown?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tox-dev/tox/issues/379#issuecomment-253320799>, or mute
the thread

**Comment by hpk42** [comment]
At least i'd like to have "--show-envdir" so that:

    tox --show-envdir  # would show all envdirs for all listed envs  (not useable for eval)
    tox -e py27 --show-envdir # would only show this particular envdir (useable for eval)

because without the show it looks as if we are setting things (see also "tox --workdir").

Happy to review and merge a PR that implements the above.

**Comment by Daenyth** [comment]
That's reasonable. I'll see what I can do

**Comment by obestwalter** [comment]
Closed PR (due to lack of time finishing it) could be used as a starting point, if anyone wants to pick that up.

**Comment by gaborbernat** [comment]
Hmmm; IMHO tox should be used mostly via invocation (to ensure dependencies are correct, latest build installed, etc). Activating the virtualenv in such a way seems to me a road where we no longer can enforce sanity checks; so I would consider it a bad practice. As such I'll close this now as won't fix.
