### ISSUE TITLE
Windows testing with AppVeyor

### ISSUE THREAD

**Issue by nicoddemus** [tox-dev/tox#386]
Setup windows testing for tox.

Oh I was going to assign this to myself but I just realized I'm not a maintainer here. 

I hope to get to this later today.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus what perms do you need?

**Comment by nicoddemus** [comment]
Do we have a user similar to @pytestbot? I will probably need access to it to enable AppVeyor for `tox-dev/tox`.

**Comment by RonnyPfannschmidt** [comment]
yes we do, i just tried to enable AppVeyor via my own user, and all i leaned is that the AppVeyor ux is rigged against its users - i can send you a encrypted mail with the credentials if you send me a public key

**Comment by The-Compiler** [comment]
FWIW I got 10 GitHub mails telling me that the tox-dev org has approved an application I use :wink:

**Comment by RonnyPfannschmidt** [comment]
so it includes harassment ^^ but no actual functionality

**Comment by RonnyPfannschmidt** [comment]
I enabled the build

**Comment by nicoddemus** [comment]
Thanks @RonnyPfannschmidt! Which account did you use? I tried https://ci.appveyor.com/project/tox-dev/tox and https://ci.appveyor.com/project/tox/tox.

**Comment by RonnyPfannschmidt** [comment]
atm my own, i suppose i need to set a team thing up?

**Comment by nicoddemus** [comment]
Not entirely sure, TBH I didn't read the [documentation](https://www.appveyor.com/docs/team-setup/#understanding-relationship-between-github-team-and-appveyor-role) thoroughly. 😬

**Comment by RonnyPfannschmidt** [comment]
reopening until perms are solved

**Comment by nicoddemus** [comment]
OK, thanks.

**Comment by hpk42** [comment]
What is missing exactly now to close this appveyor support issue?  I added @nicoddemus to tox-dev admins FWIW.

**Comment by nicoddemus** [comment]
Closing as I don't think there's anything else to do here.
