### ISSUE TITLE
Unable to access system packages

### ISSUE THREAD

**Issue by chrisspen** [tox-dev/tox#390]
I'm using tox from inside a Travis-CI vm to run some unittests. However, even with the `sitepackages = True` in my `[testenv]` section, as [outlined in the docs](http://tox.readthedocs.io/en/latest/config.html#confval-sitepackages=True|False), the unittests fail, complaining that they can't import packages that are installed via `apt-get` into Python global site-packages.

I've confirmed the version of Tox installed within Travis is the current 2.4.1.

Am I using Tox incorrectly, or is this a bug in Tox/Travis or elsewhere?

[This](https://github.com/chrisspen/reinforce/blob/master/tox.ini) is my tox config.

See the full error message [here](https://travis-ci.org/chrisspen/reinforce).

**Comment by The-Compiler** [comment]
Can you add lines to show `which tox` and `python -c "import matplotlib"` outside of tox in your build?

**Comment by RonnyPfannschmidt** [comment]
@chrisspen i suspect the travis python versions are explicitly detached from the system version,
thus apt-get cant provide them with packages

**Comment by chrisspen** [comment]
@The-Compiler 

    $ which tox
    /home/travis/virtualenv/python2.7.12/bin/tox

    $ python -c "import matplotlib"

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

    ImportError: No module named matplotlib

**Comment by chrisspen** [comment]
@RonnyPfannschmidt 

Sadly, it looks like you may be right.

https://docs.travis-ci.com/user/languages/python/#Travis-CI-Uses-Isolated-virtualenvs

Which sucks, because this means Travis can't be used to test any Python code that uses Scipy/Numpy or any other large C library.

**Comment by nicoddemus** [comment]
FWIW, `pytest-qt` uses a script which symlinks the PyQt from the system-wide installation into the virtual environment created by tox (courtesy of @The-Compiler): https://github.com/pytest-dev/pytest-qt/blob/master/scripts/link_pyqt.py

I think it is possible to use the same technique.

**Comment by hpk42** [comment]
Anyone up for adding a little example to ``examples.txt`` and ``example/travis.txt`` linking to this script @nicoddemus just posted?   I am happy to merge a respective PR.  closing this issue here.

**Comment by chrisspen** [comment]
I discovered a much simpler solution. Most large packages have binary version that can be installed using Pip's `--only-binary` option. So, to install numpy without compiling it, just use this install_command:

    install_command=pip install --only-binary=numpy {opts} numpy {packages}
