### ISSUE TITLE
Ability to add args on how virtualenv is created

### ISSUE THREAD

**Issue by saily** [tox-dev/tox#393]
Last week `setuptools` released a brown-bag release `28.7.0`. See: https://github.com/pypa/setuptools/issues/833

I was able to work around this issue for all my `pip` installations which had hard unpinned dependencies to setuptools by just installing older version before other requirements. 

But I couldn't get it work with tox, the only way was bypassing tox and running `py.test` manually. If `tox` is started it will also create a new virtualenv in `.tox` directory and install latest `setuptools` into it. So we should discuss how to workaround the hard setuptools dependency.
- Add an option to pass parameters as `--no-setuptools` to the virtualenv command which creates a `.tox/*` environment.
- Give some possibility to hook in `pre_commands` like travis, gitlab-ci, etc. use to pre-execute some commands.

**Comment by hpk42** [comment]
we could introduce a new ``create_env`` ini option similar to the ``install_command`` one.   Happy to review  a PR to that effect (including docs and tests).

**Comment by gaborbernat** [comment]
The suggested solution is to use environment variables to alter virtualenv behaviour.
