### ISSUE TITLE
{envtmpdir} not created by default, unless already present

### ISSUE THREAD

**Issue by manueljacob** [tox-dev/tox#399]
`{envtmpdir}` is not created by default. However if it's already present, it's deleted and recreated. This behavior is possibly confusing.

An example:

1.
    - Currently, on the very first tox run, the envtmpdir is not existent.
    - In this example a command creates the envtmpdir; it succeeds.
2.
    - On the second run, tox clears (i.e. deletes and recreates) the envtmpdir.
    - The command, like in the previous run, tries to create the envtmpdir, but it fails because it's already existent.

I see two solutions to provide a consistent environment on each test run.

1. (Re-)create the envtmpdir before each tox run.
2. Delete the envtmpdir before each tox run, without recreating it.

Solution 1 would be more convenient, as it saves the user from manually adding a command to every testenv to create the directory. However a configuration using the `recreate` option could rely on that the envtmpdir never exists when run.

**Comment by nicoddemus** [comment]
I agree solution 1 seems to be the correct one.

The [documentation reads](http://tox.readthedocs.io/en/latest/config.html#confval-envtmpdir=path):

>envtmpdir=path
defines a temporary directory for the virtualenv which will be cleared each time before the group of test commands is invoked. default: {envdir}/tmp

So I would expect it to be available (and empty) for the commands to use.

**Comment by hpk42** [comment]
I agree -- we should create the tmpdir if it's not there.  Fancy a PR?  There's soon going to be the tox-2.5 release (maybe mid/end next week) btw :)

**Comment by hpk42** [comment]
fixed by @manuljacob's PR.  Thanks!
