### ISSUE TITLE
log stdout output

### ISSUE THREAD

**Issue by techtonik** [tox-dev/tox#405]
It is not convenient to redirect output from tox every time when a test log is needed. Would be nice if `tox` could create output log automatically.

I may do PR, but no ETA.

**Comment by The-Compiler** [comment]
You are a few hours too late, see #403 :wink:

**Comment by techtonik** [comment]
@The-Compiler not sure how these two are related. How to create test output log with `tox`?

**Comment by The-Compiler** [comment]
Ah, I thought you were talking about tox' output redirection. I'm not sure why such a feature would be useful though, or how it'd be more convenient than redirecting via your shell - could you elaborate?

**Comment by techtonik** [comment]
To compare logs between Python versions, I need to manually rerun `tox` for every version with redirection. This is inconvenient also for remote CI. I'd prefer to see both output and download output logs in case of error.
