### ISSUE TITLE
tox-quickstart has unreasonable tiers for interpreter

### ISSUE THREAD

**Issue by rogalski** [tox-dev/tox#408]
Suggested tiers in interactive session of tox._quickstart are currently:
- py27
- py27, py33
- [all] (but e.g. pypy3 is missing]
- select one by one

With py33 being clearly outdated, these default does not seem reasonable.

I'd expect something more along lines:
- latest py2
- latest py3
- latest py2 and latest py3
- all known (so py2x, py3x, pypyx and jython)
- select one by one

With default being either 3 of 4.

Two possible questions are:
- should nightly (py36, py37) be included in some (maybe one selected) tier?
- how to write tests for quickstart in a way that modifying available tiers (e.g. adding new interpreter or removing outdated one) does not break them completely due to mocked input being unsynchronized with actual code.

**Comment by hpk42** [comment]
good questions and suggestions.  I think just upping some versions (py33 -> py35 or at least py34) makes sense.  also we probably don't want to suggest py26 anymore, not sure about py36 but pypy and pypy3 would be nice for sure.  Happy also about incremental PRs.

**Comment by kmike** [comment]
Current setuptools doesn't work with current pypy3, it can be a problem.

**Comment by obestwalter** [comment]
@kmike I don't think that your comment relates to `tox-quickstart` but thanks for bringing this topic to attention as we can close this now.

tox quickstart should use a reasanably current set of interpreters now due the code looking like this now

https://github.com/tox-dev/tox/blob/master/src/tox/_quickstart.py#L158-L169

https://github.com/tox-dev/tox/blob/master/src/tox/constants.py#L39

... which we'll hopefully keep current.

Closing this now. Please open a new issue with a concrete description of the problems you are sseing with pypy3 - thank you :bowing_man:.
