### ISSUE TITLE
Use "current python" as default even when configs for other pythons exist

### ISSUE THREAD

**Issue by jaraco** [tox-dev/tox#409]
Consider this simple tox.ini:

```
[tox]
skipsdist = True

[testenv]
commands = python -V
```

Running it with any python will use that Python as the default for the environment:

```
$ python -m tox
python installed: 
python runtests: PYTHONHASHSEED='203100270'
python runtests: commands[0] | python -V
Python 3.6.0b3
________________________________________________________________________________ summary ________________________________________________________________________________
  python: commands succeeded
  congratulations :)
```

But let's say you have a special configuration needed when running under Python 2.7, so you add the following:

```
cat >> tox.ini
[testenv:py27]
setenv = FOO=bar
```

Now running the exact same command as before results in different behavior.

```
$ python -m tox 
py27 installed: You are using pip version 8.1.2, however version 9.0.1 is available.,You should consider upgrading via the 'pip install --upgrade pip' command.
py27 runtests: PYTHONHASHSEED='1551315588'
py27 runtests: commands[0] | python -V
Python 2.7.12
________________________________________________________________________________ summary ________________________________________________________________________________
  py27: commands succeeded
  congratulations :)
```

I'd like a way to specify in the `tox.envlist` to use `<current>` or some other indicator to restore the behavior when no environments are specified.

Is there a way to accomplish that without changes to tox? If not, would you consider supporting a special value for envlist that elects this behavior?

**Comment by RonnyPfannschmidt** [comment]
tox -e py / tox -e python should work that way as a workaround

i believe the behavior you noted seems unintentional and may be a mistake - @hpk42 any idea?

**Comment by jaraco** [comment]
I've been using `tox -e python` as a workaround...

Hmm, specifying 

```
[tox]
envlist = python
```

Seems to have the same effect. I was worried that by specifying simply `python`, that would somehow not work if I tried to invoke `python3.5 -m tox`, but I see now that in these default scenarios, `python` is always the name of the environment created/used.

Therefore, `envlist = python` might be just the indicator I'm seeking.

**Comment by jaraco** [comment]
Indeed, that works wonders. Thanks for helping me gain a different perspective.
