### ISSUE TITLE
Can a tox environment use platform specific folders for the virtual environments?

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox#411]
I know that this may sound like a corner use case but here is the limitation that I was hit by: I tried to use tox to run tests across different platforms by using the shared folder. Soon I realised that I need to use something like `envlist = {py27,py34,py35}-{win,linux,darwin}` in order to isolate them.

Now there is only one problem with this approach: it breaks things like `tox -e py27` because if you do something like this, tox will **not** use the `.tox/py27-linux` folder. The workaround is to always be sure that you call tox with the full environment name which is a real PITA, especially as this may be from inside bash files, ci/travis/jenkins configuration files.

Is there a solution for this or not really? I would not mind having something like `.tox/{platform}/{env}`.

**Comment by RonnyPfannschmidt** [comment]
@ssbarnea im not aware of platforms themselves being used as factors so far - adding something like it may require a change

**Comment by ssbarnea** [comment]
I am closing this as I consider the question answered and I doubt I will find time to work on a fix too soon. I have other bugs that to affect me in a more painful manner for the moment. 

I hope someone else will find this useful, who know we may fix this one at some point in the future.
