### ISSUE TITLE
state desired/required tox plugins and warn/fail on missing ones

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [tox-dev/tox#413]
tox should have a way to specify desired/required tox plugins for use with a tox.ini

use case i have in mind:

* create  `tox-linting` plugin  that handles checks for python 2/3 using flake8, rst-linter and/or other tools
* let that plugin add its own envs to the envlist
* make tox warn if its missing, potentially fail on CI if its not missing and unrelated environments are not selected

**Comment by gaborbernat** [comment]
This has been done via https://github.com/tox-dev/tox/pull/936

**Comment by RonnyPfannschmidt** [comment]
after review of the pr i disagree, #936 doesnt even solve half of this

**Comment by gaborbernat** [comment]
It has the fail/warn part. Plugins can freely modify the envlist so nothing do there. What else am I missing?

**Comment by RonnyPfannschmidt** [comment]
@gaborbernat all we have is **fail** - there is no warning mechanism, no running of working envs and i'm not sure if there is the plugin can add env`s to the envlist implemnted, so from my pov its not even half

**Comment by gaborbernat** [comment]
I don't think we should warn. If a dependency is missing a hard fail is the appropriate solution. While there's no plugin implemented I don't think there's any core changes needed for anyone to implement one.

**Comment by gaborbernat** [comment]
If no one does it in the meantime I'll implement one once https://github.com/tox-dev/tox/issues/998 is done.
