### ISSUE TITLE
Toxify/travisise important projects

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#414]
I just noticed that e.g. the requests library is not using tox/travis to run their tests. This is unacceptable (;)) and I will create a PR as soon as I get around to it.

Are there other important projects that need some tlc in that respect?

**Comment by jayvdb** [comment]
The maintainer has rejected Travis a few times, preferring to use their own
Jenkins server. IMO a .travis.yml is still useful, for others who can't
schedule builds on his CI server.

**Comment by obestwalter** [comment]
Hi @jayvdb - I see. They also have `tox.ini` in their .gitignore, which means at least some the devs use it, but they don't have it as part of the project. I am interested why that might be. Will investigate further.

**Comment by obestwalter** [comment]
Really curious to find out, why they have trouble to share a common tox.ini - might be clarified here: https://github.com/kennethreitz/requests/issues/3739

**Comment by jayvdb** [comment]
See
https://github.com/kennethreitz/requests/issues?utf8=%E2%9C%93&q=.travis.yml and
https://github.com/kennethreitz/requests/issues?utf8=%E2%9C%93&q=tox.ini

**Comment by obestwalter** [comment]
@sigmavirus24 thanks I looked thorugh the issues yesterday but admittedly not thoroughly enough. Sorry for the noise.

Kenneth wrote:
> I don't think having tox.ini is very useful, as we won't be using it in any official capacity. Use of tox.ini requires that every specified Python installation be available in order to be used effectively, which is quite difficult to do properly on most systems. This project shipped tox.ini long ago, but it was removed for a number of reasons. Tox is a wonderful local testing tool, and anyone is free to use it with Requests — that doesn't mean we need to provide the file, though. It adds (yet) another file to the root of the repository, which I would like to keep as clean as possible.

I think tox is a very good way of also documenting the tests and the steps needed to be taken manually otherwise to run tests. Nobody needs to install all the versions to work effectively with tox, so I can't quite follow, but that answerss my question. 

Mybe it was a stupid idea anyway to actively offer help to other project. Enough other stuff to do. So I'll close this.

**Comment by obestwalter** [comment]
FWIW requests has a very (albeit very rudimentary)  [tox.ini](https://github.com/requests/requests/blob/master/tox.ini) now :)
