### ISSUE TITLE
Eliminate testrun.org from code and docs?

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#416]
@hpk42 the test on testrun.org states that it can be taken over if anyone is interested in it. Toc docs are redirecting to readthedocs.io. Should I replace all references in code and documentation to the corresponding readthedocs.io location?

**Comment by hpk42** [comment]
yes, that makes sense, thanks!

**Comment by obestwalter** [comment]
Sphinx Makefile contains a target for pushing docs to testrun.org. I haven't looked into the readthedocs workflow yet, so I am unsure if and how to change this. I will keep this in for now until I know how stuff works.

Are there docs about how we build and publish the docs?

```
install: clean html 
	@rsync -avz $(BUILDDIR)/html/ testrun.org:/www/testrun.org/tox/latest
	@rsync -avz $(BUILDDIR)/html/ testrun.org:/www/testrun.org/tox/$(SITETARGET)
	#dev
    #latexpdf
	#@scp $(BUILDDIR)/latex/*.pdf testrun.org:www-tox/latest
```

**Comment by RonnyPfannschmidt** [comment]
@obestwalter readthedocs triggers on gh changes, we can just remove the make target
