### ISSUE TITLE
Old version reported on pypi.python.org

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#422]
This does not affect the version that is being installed with pip but only the version reported in the classic web frontend (2.3.2 vs 2.5.0). The new warehouse based frontend already reports the correct version. This is likely a teething problem due to the looming migration. 

@RonnyPfannschmidt - I went offline that evening on IRC and could not follow if you found something out about it. That's why I am opening this so it will not be forgotten.

**Comment by RonnyPfannschmidt** [comment]
@obestwalter it seems to be related to hidden/non-hidden properties behaving differently in the tools - i cant check since i am not a pypi maintainer (and don't want to be one)

**Comment by obestwalter** [comment]
@RonnyPfannschmidt o.k. thanks will have a look myself later then.

**Comment by hpk42** [comment]
i guess if we release a tox-2.5.1 it will be fixed automatically.

**Comment by obestwalter** [comment]
I am working my way into releasing tox for the first time and as part of that I had at look a the releases tab:

![tox-release-mix-up](https://cloud.githubusercontent.com/assets/263007/22222110/e088166a-e1b5-11e6-8cb9-69309eb4cac3.png)

I guesss this also has to do with 2.3.2 being reported as current release on the old pypi page? Anyway this won't be a problem anymore after the next release. This bugs me though, so does anything speak against me fixing this by deleting the tag and re-adding it with `GIT_COMMITTER_DATE` set to the original date of tagging to fix the release order in that tag?

**Comment by hpk42** [comment]
playing with git this way seems worth a try, haven't done something like this myself yet.

**Comment by obestwalter** [comment]
o.k. will fix this then and if it's only to calm my need for things being in order :)

**Comment by obestwalter** [comment]
Fixed with [tox 2.6.0](https://pypi.python.org/pypi/tox/2.6.0)
