### ISSUE TITLE
Tox returns 0 exit code despite the tests are failing

### ISSUE THREAD

**Issue by pokoli** [tox-dev/tox#424]
Although the test run worked correctly tox is exiting with 0 status code, which make travis think that the test passed but they not. Here is the sample output of travis: 

https://travis-ci.org/trytonspain/trytond-account_bank/jobs/183623809

And here is the tox definition: 

https://github.com/trytonspain/trytond-account_bank/blob/develop/tox.ini

I had tox 2.3.2 on my local machine and I didn't suffer the issue. I updated to latest version (2.5.1) and I can reproduce the issue now. 

Note that if I go back to version 2.3.2 again the error is still present, so I'm not sure if a tox error or another dependency one. 

Let me know if I can provide more information.

**Comment by pokoli** [comment]
Yes, the error is that our setup.py is returing 0 as exit code. 
I understand that's a separete issue and travis is working well. So I'm clossing this issue. 

Sorry for the noise

**Comment by cedk** [comment]
FYI, it is linked to https://github.com/pypa/setuptools/issues/891
