### ISSUE TITLE
Add `LANGUAGE` env var to default pass list

### ISSUE THREAD

**Issue by ulope** [tox-dev/tox#431]
Since tox 2.0.2 `LANG` is automatically passed to avoid Unicode(En|De)codeErrors. I've just now encountered a system (macOS) where `LANGUAGE` was used instead of `LANG`, again causing test breakage.

I would suggest to add `LANGUAGE` to the list of default pass variables.

**Comment by obestwalter** [comment]
Thanks for the report @ulope. Is that maybe a special configuration? I don't have a Mac here atm, but AFAIK mac uses the same `LANG` env vars like other UNIXES and Linux. Are there some official docs about this?

**Comment by ulope** [comment]
Yeah I hadn't seen it before either. 
According to [`man 7 locale`](http://man7.org/linux/man-pages/man7/locale.7.html) it applies to `LC_MESSAGES`.

It does affect Python's string handling however so I still think it would make sense to add it to the default "pass" list.

**Comment by pawelad** [comment]
Is anyone working on this feature?

**Comment by obestwalter** [comment]
Not that I know of. Go for it :)

**Comment by pawelad** [comment]
Should `LANGUAGE` be always allowed on both Unix and OS X or only on OS X?

**Comment by obestwalter** [comment]
AFAIK it's not used on Debian based systems. I'm on Arch Linux and there is also no `LANGUAGE`, so I would tend to say it's a Mac specific adjustment. It would be great if you could do some additional research about this before proposing an implementation.

**Comment by ulope** [comment]
It appears to be a standard feature: https://linux.die.net/man/7/locale (see section on `LC_MESSAGES`)

**Comment by pawelad** [comment]
It's not set on my OS X or my Ubuntu 16.04 _but_ it is in the `locale` manual so I think it should be safe to add it.

**Comment by pawelad** [comment]
Pull request: #486
