### ISSUE TITLE
Allow parallel execution of envs (merge or replace detox?)

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox#439]
This is more of an idea that would simplify parallel execution of tests using tox. Why not merging detox into tox?

I do see several benefits from this:
* better visibility
* simplify project management, they already share the same issue tracker
* easier to deploy
* more trust: detox project has last update from 2015 on pypi making people believe it may be abandonware, also the document page contain outdated links to bitbucket.
* once done, pypi admins can replace detox project with an alias to tox (they already did this for other projects).

As part of the proposed consolidation we can even trigger the parallel option via `-P` command line option.

**Comment by hpk42** [comment]
could you look into replacing the usage of eventlet/greenlets with plain threads with detox?  That's the main block from my point of view for integrating detox into tox as it would introduce a new maybe not fully stable dependency (not sure what the state of eventlet currently is and if it can be installed everywhere etc.).

**Comment by ssbarnea** [comment]
@hpk42 Thanks for the quick reply. Glad to hear that you don't have anything against it. I will have a look.

**Comment by davidism** [comment]
If this happens, I'd also like to be able to mark some tests as "synchronous" so that, for example, coverage collection only happens after all the parallel tests run.

**Comment by obestwalter** [comment]
I just saw in the README that detox only runs with 2.6 and 2.7 is this still true? This would have to be considered when merging also, depending on what the reason fro this is.

**Comment by Pawamoy** [comment]
Well detox is now tested against 2.7, 3.4, 3.5 and 3.6: https://travis-ci.org/tox-dev/detox, so maybe we could remove the note in detox's README.

**Comment by davidism** [comment]
I've installed and used it from Python 3 envs without issue.

**Comment by obestwalter** [comment]
Hi @hpk42,

README says:
> detox runs only on python2.6 and python2.7 (but supports creation of python3 and all environments supported of the underlying "tox" command)

is this still valid?

**Comment by nirs** [comment]
Running multiple processes should be easy without eventlet, just little more code.
Is it ok to depend on concurrent.futures, or we prefer to have no dependencies?

**Comment by ssbarnea** [comment]
I vote for using dependencies, if they are reliable and maintained, like those that are going to become part of future version of python.

detox works with most versions of python, the info is outdated.

**Comment by jfboismenu** [comment]
Has anyone started work on this? I’m open to taking a stab at it. I’d love to have everyone at work only tox and add support for environment dependency management so collection jobs (like collecting coverage from different builds into a single report) could be run after a subset of environments have been executed.

**Comment by obestwalter** [comment]
Hi @jfboismenu - thanks, have a go. I'd love to have this merged and as far as I know, nobody is working on this.

**Comment by ssbarnea** [comment]
Yeah, feel free to takeover this. Sadly I am too busy with other bugs to have time to implement this but if you raise a PR, I could help reviewing it. Thanks.

**Comment by gaborbernat** [comment]
The way I see detox will remain separate. That being said tox can/should get a parallel flag; however the implementation of this would have little to do with the current detox; instead would be an alternative.

**Comment by obestwalter** [comment]
Hi @gaborbernat, what would be different with the parallel flag? 

I would really like to see detox vanish into tox core, because as a free standing project it is de facto unmaintained. So when tox grows this parallel functionality I would propose that we mark detox as obsolete and unmaintained. See https://github.com/tox-dev/detox/issues/27

**Comment by gaborbernat** [comment]
A minimal viable implementation is now available under #439, anyone interested feel free to review and submit your thoughts.
