### ISSUE TITLE
Gather tox related projects into the tox-dev organization

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#445]
I think this would be nice for visibility and having all in one place. Searching for tox plugins or other related projects would then mean to just have a glimpse at [tox-dev](https://github.com/tox-dev).

- [ ] tox-battery (0.5)                   - Additional functionality for tox
- [ ] tox-bitbucket-status (1.0)          - Update bitbucket status for each env
- [ ] tox-cmake (0.1.1)                   - Build CMake projects using Tox
- [ ] tox-docker (1.0.0)                  - Launch a docker instance around test runs
- [X] tox-durations                       - duration of operations inside tox 
- [ ] tox-globinterpreter (0.3)           - tox plugin to allow specification of interpreter locationspaths to use
- [ ] tox-matrix (0.1.1)                  - Project for creating tox.ini files with multiple dependencies
- [X] tox-pip-extensions (1.1.0)          - Augment tox with different installation methods via progressive enhancement.
- [ ] tox-plus (0.0.1)                    - virtualenv-based automation of test activities
- [ ] tox-py-backwards (0.1)              - tox plugin for py-backwards
- [x] tox-pyenv (1.1.0)                   - tox plugin that makes tox use `pyenv which` to find python executables
- [ ] tox-pytest-summary (0.1.2)          - Tox + Py.test summary
- [ ] tox-run-command (0.4)               - tox plugin to run arbitrary commands in a virtualenv
- [ ] tox-setuptools (1.3.3)              - Tox integration with setuptools
- [X] tox-travis (0.8)                    - Seamless integration of Tox into Travis CI
- [ ] tox-virtualenv-no-download (1.0.0)  - Disable virtualenv's download-by-default in tox

**Comment by nicoddemus** [comment]
We can use [pytest's policy](https://github.com/pytest-dev/pytest/blob/master/CONTRIBUTING.rst#submitting-plugins-to-pytest-dev) as basis for tox, it has worked well for us.

**Comment by obestwalter** [comment]
I like that policy, but I instead of waiting for the authors to ask, I am taking more proactive approach inviting the plugin authors into the org. I think the plugins need more visibility and hope that much of the future development will actually rather happen in that area. Improving and extending the support for plugins will be something I will be concentrating on now for a while.

**Comment by obestwalter** [comment]
While we're at it: @AvdN how about moving the tox-globinterpreter here? :champagne:

**Comment by obestwalter** [comment]
Would also love to see tox-pyenv by @samstav here.

**Comment by obestwalter** [comment]
Please add other plugins that should get more love here and ping their authors.

**Comment by obestwalter** [comment]
Welcome @ryanhiebert with tox-travis :D

**Comment by obestwalter** [comment]
I don't think we need this to be hanging around as an open issue. We have gathered quite a few plugins and should continue inviting interesting projects to join the org, but no issue needed for that.
