### ISSUE TITLE
package upgrades post virtualenv creation by default should be off

### ISSUE THREAD

**Issue by asottile** [tox-dev/tox#448]
In virtualenv 15, virtualenv by default attempts to upgrade pip, setuptools, and wheel while creating a virtualenv.  It does this by using whatever `PIP_INDEX_URL` is set (or doesn't at all if `--no-download` or `VIRTUALENV_NO_DOWNLOAD` is set).

In my ideal world, I'd love for tox to default to `VIRTUALENV_NO_DOWNLOAD=1`, but I can see why that may be surprising or not a popular choice (since it would differ from the choice made in pypa/virtualenv).  The main reason I want this is to have repeatable builds without being surprised by external factors changing / going down (pypi goes down pretty frequently! and setuptools upgrades pretty frequently (and breaks things too often)).

Since this is probably not reasonable, I think a good compromise would be to export `PIP_INDEX_URL=tox['indexserver']['default']` if provided -- this would solve our primary concern and ensure repeatable builds given the state of our index server.

**Comment by epu** [comment]
Thanks for filing this ticket. I have tests in some of my work that pin the version of six, and the uninstall of six to the older version caused my tox testenv deployment to fail. I hadn't figured out after pinning all my versions explicitly where the issue was happening, but the virtualenv creation itself was my next target. Setting the VIRTUALENV_NO_DOWNLOAD in my testenv environment fixed everything for me.

**Comment by asottile** [comment]
Here's some related issues:
- https://github.com/pypa/virtualenv/issues/1009
- https://github.com/pypa/setuptools/issues/947

**Comment by epu** [comment]
Thanks, now following along.

**Comment by asottile** [comment]
I made a plugin to turn virtualenv's behaviour off entirely: https://github.com/asottile/tox-virtualenv-no-download

**Comment by hynek** [comment]
Since Travis is currently on 🔥 due to a [setuptools ooops](https://github.com/pypa/setuptools/issues/1042), we might want to revisit this issue. :)

**Comment by obestwalter** [comment]
Any thoughts about getting that plugin into core?

**Comment by asottile** [comment]
I'd love to contribute it to core, currently the plugin is not configurable (always disabling the behavior), I'd imagine we would want some sort of way to toggle it in tox.ini?

I guess the main sticking point would be if tox is willing to choose a default of no download (despite the choice made in virtualenv) or not.

**Comment by obestwalter** [comment]
@asottile I agree - these points need to be clarified before we could get it in. 

I think we should try to respect the principle of least surprise. To me that would mean that default should be the same as in virtualenv with as good as a helpful error message, we can manage if something related to that goes wrong.

**Comment by asottile** [comment]
Yeah I'm going to try and see what I can do to change virtualenv's default too. At least for companies / enterprise, downloading is a pretty not great default (so there may continue to be a need for the plugin even when integrating this feature as a way to blanket change the default).

**Comment by gaborbernat** [comment]
So a year later, @asottile are we ready to make this into core; maybe with some flag of ``[tox] new_env_upgrade_pip_wheel_setuptools = False``?

**Comment by gaborbernat** [comment]
I'm fine with that. Do you have the availability to open a PR for it?

**Comment by asottile** [comment]
about to take a vacation -- might get to it but no promises 🎆 🎆 🎆

**Comment by gaborbernat** [comment]
Hehe, no problems if you don't get to it in the next two weeks I might give it a go. No worries and enjoy!

**Comment by obestwalter** [comment]
Have a nice vacation @asottile!

**Comment by gaborbernat** [comment]
@asottile can you pick this up now, or should I go ahead with it?

**Comment by asottile** [comment]
feel free to take this!

**Comment by gaborbernat** [comment]
Given this is a major change so to say moved this into the scope of ``3.5`` version.

**Comment by jaraco** [comment]
This ticket should also link to tox-dev/tox-venv#25, which promises to bring the auto-upgrade behavior to venv-based tox builds.
