### ISSUE TITLE
platform example

### ISSUE THREAD

**Issue by sashkab** [tox-dev/tox#449]
Hi,

 I've spent better part of the day to successfully combine three tox.ini's for different platforms from pre-tox 2.0 day into single multi-platform (macOS, Linux and FreeBSD) tox.ini. I created test project, which might be useful to share in examples, in order to better document `platform` keyword, as documentation is very sparse and few things I came up in example were just try and fail. 

I've got test repository at https://github.com/sashkab/ttt/, and here is content of the tox.ini:

```
[tox]
minversion = 2.4.0
envlist=py{27,36}-{linux,macos,freebsd}

[testenv]
platform=
       macos: darwin
       linux: linux
       freebsd: freebsd10

deps=
    freebsd: py==1.4.30
    linux,macos: py==1.4.32

whitelist_externals = echo

commands=
   linux,macos: echo "Hello, Posix"
   freebsd: echo "Hello, FreeBSD"
```

I'd add this to documentation myself, but I don't have much time now, and afraid will forget about this soon, but this might help someone save couple minutes or hours in the future.

Thanks.

**Comment by obestwalter** [comment]
@sashkab Thank you. I agree - the documentation definitely needs some TLC at some point. if you dont' get around to it right away, it's at least not lost and properly labelld already.
