### ISSUE TITLE
Regression since 2.5.0: empty commands section causes error

### ISSUE THREAD

**Issue by asottile** [tox-dev/tox#454]
We often use this pattern such that tox is creating our virtual environments for us:

## tox.ini

```ini
[tox]
skipsdist = true

[testenv:venv]
deps = pre-commit
commands =
```

## Under 2.4.1

I get (what I expect):
```
$ tox -e venv
venv recreate: /tmp/fo/.tox/venv
venv installdeps: pre-commit
venv installed: appdirs==1.4.0,aspy.yaml==0.2.2,cached-property==1.3.0,functools32==3.2.3.post2,jsonschema==2.6.0,nodeenv==1.1.2,packaging==16.8,pre-commit==0.12.2,pyparsing==2.1.10,PyYAML==3.12,six==1.10.0,virtualenv==15.1.0
venv runtests: PYTHONHASHSEED='2591024316'
___________________________________ summary ____________________________________
  venv: commands succeeded
  congratulations :)
```

## 2.5.0

This is an error:
```
$ tox -e venv
venv create: /tmp/fo/.tox/venv
venv installdeps: pre-commit
venv installed: appdirs==1.4.0,aspy.yaml==0.2.2,cached-property==1.3.0,functools32==3.2.3.post2,jsonschema==2.6.0,nodeenv==1.1.2,packaging==16.8,pre-commit==0.12.2,pyparsing==2.1.10,PyYAML==3.12,six==1.10.0,virtualenv==15.1.0
ERROR: Commands not specified. Please update relevant section of /tmp/fo/tox.ini
___________________________________ summary ____________________________________
ERROR:   venv: nothing to do
```

## workaround
A (kinda unfortunate) workaround is to do something like:

```ini
commands = python -c 'print("done!")'
```

**Comment by obestwalter** [comment]
Hi @asottile, that's corect. already identified [here](https://github.com/tox-dev/tox/issues/316#issuecomment-270795986), but we should have a proper bug for this. Closed the other one in favour of this.

**Comment by asottile** [comment]
Since this doesn't seem simple to fix, should we start by reverting #407?

The parser doesn't seem to differentiate between "missing" and "present but empty"

**Comment by obestwalter** [comment]
I think that's a good idea, as it is better not to have a regression than a broken new feature.

**Comment by asottile** [comment]
This was reverted in #456 -- perhaps the original issue should be reopened and this one closed?

**Comment by obestwalter** [comment]
Done. Thanks @asottile!
