### ISSUE TITLE
Warn user that PYTHONPATH is discarded if it is set.

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#458]
Since 2.4.0 we discard PYTHONPATH silently. The user should be warned if they have set it in there environment though as this can be a source of confusion otherwise.

This is likely very simple to implement and would be a good issue for new contributors.

**Comment by jarshwah** [comment]
Fixed by https://github.com/tox-dev/tox/pull/459

**Comment by obestwalter** [comment]
Thanks @jarshwah.
