### ISSUE TITLE
option to display a short documentation with envlist

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/tox#462]
Currently:

```bash
tox -l
py27
pylint
flake8
doc
```
Would it be possible to also display a short more verbose description for envs? E.g.:
```bash
tox -l
py27    run tests against Python 2.7 via pytest with coverage report
pylint   check code style with pylint
flake8  check code style with flake8
doc      generate documentation to build/doc with Sphinx
```

Thanks!

**Comment by obestwalter** [comment]
@gaborbernat interesting suggestion.

Just some remarks: it would have to be implemented in a way that it is optional and it would also have to work with [generated envs](http://tox.readthedocs.io/en/latest/config-v2.html#example-generating-and-selecting-variants).

**Comment by The-Compiler** [comment]
Something like this maybe?

```ini
[descriptions]
py36 = foo bar
pylint = description here
```

**Comment by gaborbernat** [comment]
@obestwalter totally agree. Naturally it can fallback to an empty description (same as we have now). And for the generated envs we probably just need to make possible env variables are usable in description too, not?

**Comment by obestwalter** [comment]
> we probably just need to make possible env variables are usable in description too, not?

Just to make sure, we don't misunderstand: I was not talking ebout environment variables, but about generated environments like described in the link. The names get generated by combining multiple factors together and I don't know how and if to integrate that into what you want to do, so I just mentioned it that it needs to be taken into account.

e.g. if you have:

    envlist={py27,py35}-{pylint,tests}

you will have four environments named `py27-pylint, py35-pylint, py27-tests, py35-tests` - how would you deal with descriptions for things like that?

**Comment by The-Compiler** [comment]
@obestwalter You could do so with my proposal above. The syntax could even allow for e.g. `*-pylint` as key.

**Comment by hpk42** [comment]
@The-Compiler 's example would describe factors and for displaying the description, we'd concatenate all descriptions in the same order as the env name consists of factors.

**Comment by asottile** [comment]
@The-Compiler I'd suggest `[tox-descriptions]` to keep it reasonably namespaced (other tools read from `tox.ini` as well).  Definitely like the idea though ++

**Comment by gaborbernat** [comment]
I will probably try to do this in the next weeks, feel free to assign it to me.

**Comment by obestwalter** [comment]
Thanks @gaborbernat - this will be in 2.7.0 coming out next friday if nothing bad happens :)
