### ISSUE TITLE
Run tox as a normal user but .tox gets created as root

### ISSUE THREAD

**Issue by mbaragiola** [tox-dev/tox#471]
I'm not sure this is a bug, but:

OS: Happends both on Fedora 25 and CentOS 7
`uname -a`
Linux lrc4.c570 4.9.13-200.fc25.x86_64 #1 SMP Mon Feb 27 16:48:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

`pip list`
Babel (2.3.4)
Brotli (0.5.2)
coverage (4.3.4)
defusedxml (0.5.0)
Django (1.10.5)
django-allauth (0.30.0)
django-cors-headers (2.0.2)
django-environ (0.4.1)
django-filter (1.0.1)
django-phonenumber-field (1.1.0)
django-redis-cache (1.7.1)
django-redis-sessions (0.5.6)
django-rest-auth (0.9.0)
djangorestframework (3.5.4)
djangorestframework-jwt (1.9.0)
drf-extensions (0.3.1)
dry-rest-permissions (0.1.8)
flake8 (3.3.0)
isort (4.2.5)
mccabe (0.6.1)
oauthlib (2.0.1)
olefile (0.44)
phonenumberslite (8.2.0)
Pillow (4.0.0)
pip (9.0.1)
pluggy (0.4.0)
psycopg2 (2.6.2)
py (1.4.32)
pycodestyle (2.3.1)
pyflakes (1.5.0)
PyJWT (1.4.2)
python3-openid (3.0.10)
pytz (2016.10)
redis (2.10.5)
requests (2.13.0)
requests-oauthlib (0.8.0)
setuptools (28.8.0)
six (1.10.0)
tox (2.6.0)
virtualenv (15.1.0)
wheel (0.29.0)
whitenoise (3.3.0)

As the title says, I run tox as a normal user but my .tox directory gets created as root:root. Most of the time this isn't a problem, but when trying to automate the process with Gitlab CI Runner, it can't remove it before/after a build, so it raises errors. I Googled and found nothing about it.

Thanks in advance!

**Comment by obestwalter** [comment]
Hi @mbaragiola,

tox is using [py.path.ensure](http://py.readthedocs.io/en/latest/_modules/py/_path/local.html#LocalPath.ensure) for creating directories. I can see no chown or any other user fiddling going on there.

I would hazard a guess, that there is a `su` or `sudo` somewhere in your toolchain.

What is the output if you run something like `whoami && tox && stat -c '%U:%G' .tox` in a tox project that not yet has created a `.tox` directory?

**Comment by mbaragiola** [comment]
Hello @obestwalter, when running `docker-compose -f dev.yml run django whoami` that inside the python:3.5 docker image I was running as root. So that's probably it. It's solved on Fedora but not on my CentOS VPS, but this is probably a configuration problem between docker and gitlab-runner. Thanks for the quick answer.

**Comment by obestwalter** [comment]
o.k. - thanks for the follow up :)
