### ISSUE TITLE
Use setuptools_scm for versioning

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#474]
This tool hooks into `setup.py` and provides versioning from e.g. git tags. This makes frequent releases less painful as there is no manual version setting in the sources necessary anymore as this is set and read from git tags.

The [default versioning](https://github.com/pypa/setuptools_scm#default-versioning-scheme) does already what we need for tox versioning.

**Comment by obestwalter** [comment]
@RonnyPfannschmidt not surprised about your thumbs up here ;) great little tool - thanks for that!

**Comment by obestwalter** [comment]
I wonder if we might run into this problem: [rtfd/readthedocs.org » bad interaction with setuptools_scm](https://www.bountysource.com/issues/33054081-bad-interaction-with-setuptools_scm). Just leaving this here as a reminder in case there are problems with building the docs.

**Comment by RonnyPfannschmidt** [comment]
@obestwalter it will help to just use pkg_ressoruces or the version files for then rtd usage

**Comment by Pawamoy** [comment]
Maybe [bumpversion](https://github.com/peritus/bumpversion) could be of interest here.

You can define in `.bumpversion.cfg` the files in which to search for version tags, and then use the command line tool to update them all at the same time.

It can as well commit the changes and create a git tag automatically.

Here is a typical configuration I use:

```ini
[bumpversion]
current_version = 1.0.3
commit = True
tag = True

[bumpversion:file:setup.py]
[bumpversion:file:src/app/__init__.py]
[bumpversion:file:docs/conf.py]
```

**Comment by obestwalter** [comment]
@Pawamoy thanks for the tip, but as setuptools_scm is the [pypa blessed](https://github.com/pypa/setuptools_scm) package to do that and our @RonnyPfannschmidt is the core dev I rather go with that :)

**Comment by RonnyPfannschmidt** [comment]
one of the reasons i created setuptools_scm and pushed it into pypa is this mess of editing and committing dozens and dozens of files of actual data just to create metadata - when one can just use metadata

**Comment by nicoddemus** [comment]
Just a note of warning about `bumpversion` that I just realized yesterday while creating a [conda recipefor it](https://github.com/conda-forge/staged-recipes/pull/2626): it seems to be largely unmaintained at moment, with lots of PRs sitting there without answer and the last commit to master being from [2015](https://github.com/peritus/bumpversion/commits/master).

**Comment by obestwalter** [comment]
> PRs sitting there without answer and the last commit to master being from 2015.

oh well, another case of maintainer burnout - or just loss of interest.
