### ISSUE TITLE
Add documentation for contributors

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#475]
* how to find things to do (help-wanted, projects)
* PR should have related issues?
* how to test stuff (general guidance, good examples)
* vagrant usage to test local changes in all supported interpreters
* Explain release process

**Comment by obestwalter** [comment]
Sources of inspiration:

* http://api.coala.io/en/latest/Developers/Newcomers_Guide.html
* http://cookiecutter.readthedocs.io/en/stable/contributor_guidelines.html
* https://guides.github.com/

**Comment by gaborbernat** [comment]
Closing this with https://github.com/tox-dev/tox/blob/master/CONTRIBUTING.rst .
