### ISSUE TITLE
link check fails to historic link

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#481]
While working on #474 which includes having to change the way the version is fetched I noticed that the `tox -e docs` link check throws an error due to an ancient link being broken:

    writing output... [  3%] announce/release-0.5

    (line   18) broken    http://codespeak.net/tox - 404 Client Error: Not Found for url: http://codespeak.net/tox
    writing output... [  7%] announce/release-1.0

How can one remedy that? I don't like to fiddle with historic documents, but I don't like tests being broken either.  Can I just quarantine it by removing the scheme?

**Comment by obestwalter** [comment]
fixed by recent docs improvements.

**Comment by gaborbernat** [comment]
I think as links become obsolete we should just transition them to be literals, even at the cost of changing historic documents :+1:

**Comment by obestwalter** [comment]
Yeah, I have a much more relaxed approach to these kinds of things after being on the proejct for a while now. The old docs are kept on readthedocs anyway nowadays so no need to make too much of a fuzz about it.
