### ISSUE TITLE
Drop the dot (py.test -> pytest)

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#484]
There are 41 occurrences of `py.test` in the code, many of which should be replaced by `pytest` - some need a closer look though. There seems to be mixed usage of pytest and py.test imports in the tests -I am pretty sure this is just for historical reasons.

**Comment by obestwalter** [comment]
@davehunt - shall we do that at the next sprint? :grin:

**Comment by davehunt** [comment]
> shall we do that at the next sprint?

I was actually thinking we could introduce a dot this time... `t.ox` anyone?

**Comment by nicoddemus** [comment]
🤣

**Comment by obestwalter** [comment]
Deal. Let me just fire up my p.y.t.h.o.n interpreter and we do this right now!
