### ISSUE TITLE
tox subcommands (`tox quickstart` etc.)

### ISSUE THREAD

**Issue by techtonik** [tox-dev/tox#487]
Resurrecting idea from closed #157.

Not all environments have `tox` in the PATH. In this case `tox` is invoked as `python -m tox`. But that makes tools like `tox-quickstart` inaccessible. #157 was specifically about adding `quickstart` as a command, but this can likely be extended with plugin to other testing needs.

For example, move from this:
```
#!python
usage: tox-script.py [-h] [--version] [-v] [--showconfig] [-l] [-c CONFIGFILE]
                     [-e envlist] [--notest] [--sdistonly] [--installpkg PATH]
                     [--develop] [--set-home] [-i URL] [-r]
                     [--result-json PATH] [--hashseed SEED] [--force-dep REQ]
                     [--sitepackages]
                     [args [args ...]]

positional arguments:
  args                additional arguments available to command positional
                      substitution
```
to this:
```
#!python
usage: tox [options] [subst [subst ...]]
       tox quickstart

positional arguments:
  subst                positional substitutions in the format '...'
```

**Comment by obestwalter** [comment]
Hi @techtonik, I also start leaning in that direction looking at the growing list of options and the many enhancement requests in the pipeline. There was a [commit](https://github.com/tox-dev/tox/commit/f2179b4101dbdd4dc6ce43eaa64cc9a89727a3d4) back in the dark ages that reverted the beginnings of a subcommand layout when @hpk42 did not know yet how many tentacles his simple tool woud grow over the years :) - maybe 7 years later we should reconsider?

But this needs good planning and thinking about backwards compatibility or maybe even thinking about breaking backwards compatibility and completely restructuring the command line layout in a 3.0 release ... so it would be nice to have an open discussion here about this.

**Comment by techtonik** [comment]
The ideal way I see it is to collect stats about actual options usage that will indicate a top 7 priority list for implementing subcommands. These most frequent subcommands will show up on `tox -h` with or without global options. The rest of subcommands should show up on `tox -h -v`, where `-v` stands for `--verbose`. I am inventing something new - this is how Mercurial `hg` interface works, and I am just stealing the best usability practice that I enjoy. The only missing part is stats collection.

**Comment by The-Compiler** [comment]
Would tox have more than, say, 10 subcommands or so? If not, I don't think it's needed to hide some of them.

**Comment by techtonik** [comment]
Oh yea, sorry. Was looking at my `pip` PR that hides global options and messed up the context of this issue. No need to hide anything right now, right. Just to figure out which commands are provided by which plugins.

**Comment by gaborbernat** [comment]
This now has been added with tox 4.
