### ISSUE TITLE
How to debug pytest plugin in PyCharm?

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/tox#488]
So tests invoking the tox command via ``_pytestplugin.py`` cannot be debugged because the debugger does not attach to the subprocess inside PyCharm. Is this the intended workflow?

**Comment by obestwalter** [comment]
I don't think there is an established workflow involving PyCharm. I also use PyCharm, but have not yet done any plugin debugging. Have you alreadfy tried to [attach to the process](https://www.jetbrains.com/help/pycharm/2016.3/attaching-to-local-process.html) explicitly as workaround?

**Comment by Pawamoy** [comment]
When you run tox, it installs the project in its sub virtualenv, and then the files executed are not the one you edit/debug in PyCharm. To debug tests I usually create a configuration in PyCharm that just run the command to test (like pytest with arguments), not tox. This way the current files are executed and debugged.

**Comment by gaborbernat** [comment]
Both choices are valid, I think this is something we should cover in our developer documentation.
