### ISSUE TITLE
tox may fail to execute scripts that are using shebang lines

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox#490]
It seems that if I try to execute a script that is using the standardized shebang line (`/usr/bin/env command`) tox will fail

I created a repository specially for reproducing this bug: https://github.com/ssbarnea/tox-shebang

The only requirement for reproducing seems to be not to have ansible already installed on your machine.

**Comment by asottile** [comment]
Most operating systems only allow a single argument in shebangs.

The shebang you have is `#!/usr/bin/env ansible-playbook -i localhost, -v`

Most systems will exec the following:

```
'/usr/bin/env' 'ansible-playbook -i localhost, -v'
```

Which ends up being just

```
'ansible-playbook -i localhost, -v'
```

And unless you have an executable named `'ansible -i localhost, -v'` (with spaces!), that's going to error.

The error I get trying to execute that in (or out) of tox is:

```
$ ./sample.yml 
/usr/bin/env: ‘ansible-playbook -i localhost, -v’: No such file or directory
```

**Comment by The-Compiler** [comment]
Yup, I get the same error @asottile mentioned when doing `./sample.yml` without tox involved.

**Comment by obestwalter** [comment]
@ssbarnea are we missing something or can we close this as invalid?

**Comment by ssbarnea** [comment]
I will close it by adding a note as someone else could waste a time too: don't forget that by default tox commands do not have any environment variables configured, unless you add `passend = *`.

**Comment by obestwalter** [comment]
There are some standart vars passed through though ... documented here: http://tox.readthedocs.io/en/latest/config.html?highlight=passenv#confval-passenv=SPACE-SEPARATED-GLOBNAMES

**Comment by ssbarnea** [comment]
@obestwalter Are there any reasons why `SSH_AUTH_SOCK HOME USER` vars are not included int the default list? The lack of them caused few problems, I believe I am not the only one.

**Comment by obestwalter** [comment]
> Are there any reasons why SSH_AUTH_SOCK HOME USER vars are not included int the default list?

I don't know any, othe than that the basic idea is to keep the number of env vars as small as possible and only add the ones that cause problems for many users?

I guess it's hard to strike the right balance between adding only necessary vars for the majority of use cases and not having a kitchen sink ...

**Comment by asottile** [comment]
`SSH_AUTH_SOCK` would be nice, heh.  We've added this to nearly 200 tox.ini files at $company

**Comment by ssbarnea** [comment]
@asottile Any reason why you didn't use the `*` magic value? Before making a PR to improve the default list I would like to gather some feedback regarding what is supposed to be avoided.

**Comment by asottile** [comment]
In a lot of situations, blanking the environment is a good feature (`passenv=*` was the tox1.x behaviour) as it gives more insurance that your tests aren't depending on system state.
