### ISSUE TITLE
How can I set a default value for missing environment variables?

### ISSUE THREAD

**Issue by brianbruggeman** [tox-dev/tox#491]
Also here: https://stackoverflow.com/questions/42982267/tox-set-default-values-for-missing-environment-variables

I've found that I would really like to use environment variables to control flow - especially when testing.  But I also would like to set a default behavior based on whether or not an environment variable is present.  In bash, I'd just use:  ${ENV_VAR:-default_value}, but I don't have that basic option in Tox (unless I missed it).  

Is there a way?

**Comment by obestwalter** [comment]
Hi @brianbruggeman yes, there is - and you almost guessed right. See [here](http://tox.readthedocs.io/en/latest/config.html?highlight=substitution#environment-variable-substitutions-with-default-values). 

I would be interested how you searched for this in the docs, so we can maybe improve the structure to make this easier to find. The important term to look for here is "substitutions".

**Comment by obestwalter** [comment]
It's dawning on me, that you might want to set the value of the environment variable itself if it is not set from the outside ... is that right?

**Comment by brianbruggeman** [comment]
Yes.

**Comment by brianbruggeman** [comment]
But I'm wondering if I can do something fancy...

```
[tox-env-identifier]
...
setenv
    VAR_NAME = {env:VAR_NAME:default_value}
...
```

**Comment by obestwalter** [comment]
Fixed the answer after understanding the question properly :)

**Comment by obestwalter** [comment]
Correct :)

**Comment by brianbruggeman** [comment]
Can I do something like this?

```
setenv = 
    SPARK_PYTHONPATH = {env:SPARK_PYTHONPATH:env:SPARK_HOME/python}
```

**Comment by obestwalter** [comment]
> setenv =
>    SPARK_PYTHONPATH = {env:SPARK_PYTHONPATH:env:SPARK_HOME/python}

AFAIK you can not access the content of env vars in setenv, you can only set them.

>  PYTHONPATH = {env:SPARK_PYTHONPATH}:{toxinidir}

I think the correct syntax would be `PYTHONPATH = {env:SPARK_PYTHONPATH:{toxinidir}}` but when I try this I get: `{env:HOME:/home/oliver/Dropbox/projects/tox/lab/mini}` as output of the env var, so the current substtution engine cannot handle that (or I am getting something wrong also).

If you start doing magic like this you can always add a thin wrapper to call your tests and do the extra magic there. This is not super elegant but that way you have full flexibility. You can take an ini file with some substitution magic only so far without creating a hideous monster.

**Comment by brianbruggeman** [comment]
In the case of the `PYTHONPATH` variable above, it already does explicitly what I want (concatenates SPARK_PYTHONPATH with the current toxini folder).  So I wasn't too concerned there.

But `SPARK_PYTHONPATH` is the real issue as it requires knowledge of the `SPARK_HOME` value to set a valid default value.  I completely empathize with trying to support recursive/layered structures like this...  And the truth is that I'm not sure any of the default configuration technologies really handle this kind of scenario:  ini, json, yaml, toml, etc.  But I'm finding this pattern more common now, and I'm going to need to figure out a better solution for it.  Requiring environment variables set to a specific value is not a great one.

Thank you for your help here!
