### ISSUE TITLE
detox may fail to run in parallel with shared environments: due to command logs

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox#502]
It seems that a `tox.ini` that looks like this may product problems, especially if you have many environments (real one has 6-7)
```
[tox]
envlist = py27,yamllint,flake8,ansible-lint,ansible-check,ansible-syntax-check
skipsdist = True

[testenv]
changedir = {toxinidir}
deps =
  -r{toxinidir}/requirements.txt
  ansible-lint
  flake8
  yamllint
whitelist_externals = bash

[testenv:flake8]
basepython=python2.7
envdir = {toxworkdir}/py27
commands =
    python -m flake8

[testenv:yamllint]
basepython=python2.7
envdir = {toxworkdir}/py27
commands =
    yamllint .
```

# What happens
The use may see something like this in the logs, an error that is more than confusing because it doesn't give many insights regarding what really happened.
```
10:28:47   File "/usr/lib/python2.7/site-packages/py/_error.py", line 85, in checked_call
10:28:47     raise cls("%s%r" % (func.__name__, args))
10:28:47 ENOENT: [No such file or directory]: open('/home/jenkins-slave/jenkins/workspace/x-unit-rhos-coreci/x/.tox/py27/log/flake8-0.log', 'r')
10:28:47 ERROR: invocation failed (exit code 1), logfile: /home/jenkins-slave/jenkins/workspace/x-unit-rhos-coreci/x/.tox/py27/log/ansible-lint-0.log
10:28:47 Traceback
```

A full log is available at https://gist.github.com/ssbarnea/04adfa17833586ba3ef5e761d18d2fbb

Interesting, I was not able to reproduce the same problem on MacOS, only on Linux and I believe that this may happen due to some concurrency conflicts caused by the way detox is logging the commands.

I checked the logs and none of them contains errors and I also tested with tox 2.3.1 and 2.6.0, same behaviour.

**Comment by ssbarnea** [comment]
For the moment I had to remove detox from the build slaves, at least when I added it to the build script I had the inspiration to do it via `which detox && detox || tox` approach.

**Comment by obestwalter** [comment]
Kamino closed and cloned this issue to [tox-dev/detox](https://github.com/tox-dev/detox/issues/19)
