### ISSUE TITLE
Hang when installing from git repository

### ISSUE THREAD

**Issue by The-Compiler** [tox-dev/tox#503]
When trying to recreate an environment with a git repository in its dependencies, at least on Windows (haven't tested on Linux), tox hangs.

Looking at the logs with `--verbose`, it's because pip is waiting for a confirmation to nuke the old repo:

```
Obtaining PyInstaller from git+https://github.com/xoviat/pyinstaller.git@qtweb#egg=PyInstaller (from -r C:\Users\florian\qutebrowser/misc/requirements/requirements-pyinstaller.txt (line 3))
  git clone in c:\users\florian\qutebrowser\.tox\pyinstaller\src\pyinstaller exists with URL https://github.com/The-Compiler/qutebrowser.git
  The plan is to install the git repository https://github.com/xoviat/pyinstaller.git
What to do?  (s)witch, (i)gnore, (w)ipe, (b)ackup 
```

Involved versions:

```
pip (9.0.1)
pluggy (0.4.0)
py (1.4.33)
setuptools (28.8.0)
tox (2.6.0)
virtualenv (15.1.0)
```

**Comment by obestwalter** [comment]
Looks like we need to define the [exists action option](https://pip.pypa.io/en/latest/reference/pip/#exists-action-option) to make this go away.

**Comment by The-Compiler** [comment]
Nice find! FWIW adding `install_command = pip install --exists-action w {opts} {packages}` to the `[testenv]` section works as a workaround.
