### ISSUE TITLE
Improve listenvs behaviour (list completely dynamic environments)

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#505]
#271 missed one possible way of creating environments (completely dynamic just by referencing it in testenv). 

    [tox]
    skipsdist = true
    
    [testenv]
    commands =
        dynamicenv: tox --version

`tox -a`:

    python

It shows only the `python` env which seems to be the standard environment if nothing is defined. This is surprising as IMO creating an env this way is perfectly valid and should behave the same as if I listed it in envlist ...

Expected behaviour would be:

`tox -a`:

    dynamicenv

**Comment by hpk42** [comment]
On Tue, Apr 18, 2017 at 08:23 -0700, Oliver Bestwalter wrote:
> #271 missed one possible way of creating environments (completely dynamic just by referencing it in testenv). 
> 
>     [tox]
>     skipsdist = true
>     
>     [testenv]
>     commands =
>         dynamicenv: tox --version
> 
> `tox -a`:
> 
>     python
> 
> It shows only the `python` env which seems to be the standard environment if nothing is defined. This is a surprising as IMO creating an env this way is perfectly valid and should behave the same as if I listed it in envlist ...

not sure it's a good idea.  if you allow implicit definitions of environments 
then it's harder to catch typos.  Right now we are not detecting them directly 
but you also can not specify them: "tox -e BLABLUB" gives you "unknown environment".

Moreover, "dynamicenv" might just be a factor and not a full environment name.

**Comment by gaborbernat** [comment]
how can that dynamic environment be even invoked?

**Comment by obestwalter** [comment]
> Right now we are not detecting them directly but you also can not specify them: "tox -e BLABLUB" gives you "unknown environment".

> Moreover, "dynamicenv" might just be a factor and not a full environment name.

o.k. two showstoppers then basically. Looks like we better put this to an early grave then ...

> how can that dynamic environment be even invoked?

The same way 'normal' environments are invoked: the example above woulde be invoked with `tox -e dynamicenv`.

**Comment by obestwalter** [comment]
> Moreover, "dynamicenv" might just be a factor and not a full environment name.

Just realized that this is not really a showstopper, as we are accounting for that already: you can attach a description to a factor, so this would be not a hindrance. Maybe there is hope ....

**Comment by gaborbernat** [comment]
another way we miss environments (I just found out is):

```ini
[tox]
envlist = py27

[testenv]
passenv = BAS_PROXY http_proxy https_proxy no_proxy
basepython = py27: python2.7
             magic: magic
```

here magic is not added :thinking:

**Comment by obestwalter** [comment]
That is the same thing though as the dynamicenv example (only defined in a different place). Basically you can create environments wherever just by referencing them.

**Comment by gaborbernat** [comment]
will take a look at why these are missing :+1:

**Comment by gaborbernat** [comment]
This now has been implemented with tox 4.
