### ISSUE TITLE
Foward NUMBER_OF_PROCESSORS environment variable by default

### ISSUE THREAD

**Issue by AndreLouisCaron** [tox-dev/tox#517]
Hi there!

In one project, I have a Python 2.7-only dependency that uses [`multiprocessing.cpu_count()`](https://docs.python.org/2/library/multiprocessing.html#multiprocessing.cpu_count) on Windows.  This has a hidden dependency on the `NUMBER_OF_PROCESSORS` environment variable.  This is quite confusing when porting this type of project into Tox.

**Note**: in Python 3.4+, this is API is superseeded by [`os.cpu_count()`](https://docs.python.org/3/library/os.html#os.cpu_count) which does not depend on this environment variable.

The case is a bit weak (Python up to 3.3 only, plus multiprocessing is not popular on Windows), but I feel like the standard library should work by default inside a Tox test environment.

I'm willing to work on a patch if you would accept such a contribution!

**Comment by obestwalter** [comment]
Hi @AndreLouisCaron We have a growing list of special cases and for one think that your argument that tox should work out of the box with standard library is a compelling one, to add that also.
