### ISSUE TITLE
[VAGRANT] build fails on Windows

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/tox#524]
the symbolic link file operation is not supported in this case, maybe add option to allow always-copy for the virtual env creation

**Comment by obestwalter** [comment]
@gaborbernat *sigh* I knew there would be trouble on Windows :)

AFAIK there is no developer documentation, so getting one started would be very appreciated.

**Comment by obestwalter** [comment]
@gaborbernat could you add the info about what to do on Windows right in the doc of the Vagrantfile? If and when we have a contributors guide we only have to provide the info about a Vagrantfile and if people want to use that they always find the current info right in there.

**Comment by gaborbernat** [comment]
Played around with this and in the end, decided not worth the investment. @obestwalter should we remove all Vagrant issues or you still plan to use it?

**Comment by obestwalter** [comment]
I also don't think it's worth the fuss. It's one of these things I tried, but are not really used by anyone (including me). They are only are a maintenance burden now. Opened a PR to remove this.
