### ISSUE TITLE
tox-docker seems something that should live under this organization

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/tox#530]
tox-docker (https://late.am/post/2017/05/21/introducing-tox-docker.html) seems like a nice project, maybe we should move it under tox-dev for increased visibility; and we could probably use a page in documentation about major tox plugins

**Comment by RonnyPfannschmidt** [comment]
@dcrosta is the author/owner of that project, so so unless there is buy in from him to the idea, this one is invalid ^^

**Comment by gaborbernat** [comment]
agreed, but having the plugins page still applies regardless :+1:

**Comment by RonnyPfannschmidt** [comment]
@gaborbernat true, please make a new issue for that as its orthogonal

**Comment by dcrosta** [comment]
I'd be honored to move the project to tox-dev. What do I need to do to help make this happen?

I've actually been meaning to find out how to get involved -- in particular, the plugin dev docs need a bit of help, there was a lot of trial-and-error involved in getting tox-docker to work. Just haven't found the time to learn how to contribute yet :)

**Comment by nicoddemus** [comment]
It seems `tox` could use a contributors guide similar to pytest's [CONTRIBUTING.rst](https://github.com/pytest-dev/pytest/blob/master/CONTRIBUTING.rst).

This in fact by itself would be a wonderful contribution by itself. 😉 

Do we have a policy in place for people to become `tox` contributors? If not we should definitely draft one.

**Comment by obestwalter** [comment]
> Do we have a policy in place for people to become tox contributors?

No policy I know of yet. Complete anarchy here still :)

@dcrosta about plugin dev - maybe a cookicutter plugin would be the way to go (I love executable documentation): https://github.com/audreyr/cookiecutter - here's the cookiecutter to create pytest-plugins as inspiration: https://github.com/pytest-dev/cookiecutter-pytest-plugin

About getting plugins into the org, have a look here: 
https://github.com/tox-dev/tox/issues/445

Yours would be the first then, but we have to start somewhere :)

**Comment by obestwalter** [comment]
@dcrosta how about it - shall we move your project into the org then?

**Comment by obestwalter** [comment]
@dcrosta - you should have an invitation to the org now and have permission to move your plugin here 🍾

**Comment by gaborbernat** [comment]
There's no actionable thing on our side. We've sent out the invitation it's up to @dcrosta if he wants to join the organization or not.

**Comment by obestwalter** [comment]
true.

**Comment by dcrosta** [comment]
Sorry all — this must have slipped out of my inbox long ago. I’m still interested in moving this to tox-dev. As far as I can tell, I don’t seem to be a member nor have a pending invite. Can someone re-invite me?

**Comment by gaborbernat** [comment]
@obestwalter I think only owners can do, so can you have a look?

**Comment by obestwalter** [comment]
done.

**Comment by dcrosta** [comment]
Should I give "plugin developers" or "maintainers" team access to the repo?

**Comment by obestwalter** [comment]
Hey @dcrosta, I would recommend to give all team members access if you have no objections.

**Comment by dcrosta** [comment]
https://github.com/tox-dev/tox-docker :D done

**Comment by obestwalter** [comment]
Shouting it out to the world! https://twitter.com/obestwalter/status/1019693195972763655

**Comment by dcrosta** [comment]
Do I have to do anything to grant other people publish permissions on PyPI? How does that work with this org?

**Comment by gaborbernat** [comment]
If you want the core maintainer team to be able to release you can add our role account ``toxdev``.

**Comment by dcrosta** [comment]
OK done. I'm going to do a quick minor release to update the docstring to point at the new github URL.

**Comment by gaborbernat** [comment]
Thanks!
