### ISSUE TITLE
tox incorrectly installs package at env creation time if its a dependency of the test tooling

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [tox-dev/tox#536]
happened in pytest-dev/py#130 - it was necessary to force a installation of py to get things working as the initial install seems to fail updating

in local tests the first run would fail, any subsequent run would pass with the changes

i suggest to always ensure the installation of the target package as followup of the installation

**Comment by RonnyPfannschmidt** [comment]
after review t dawned that installation should always happen with `pip install -U --no-deps` not just on recreate, else behaviour is inconsistent and broken

**Comment by obestwalter** [comment]
Hi @RonnyPfannschmidt 

> installation should always happen with pip install -U --no-deps

Do you mean as the standard install command? Wouldn't that break a lot of other things?

**Comment by RonnyPfannschmidt** [comment]
@obestwalter potentially - for backward compatibility something else might be needed

**Comment by gaborbernat** [comment]
Can you replicate this with tox 4? If so please post a reproducible and we'll reopen.
