### ISSUE TITLE
Add coverage reporting

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#540]
I am aware that there are different opinions about coverage, but to me it is a helpful data point, so I would like to add coverage reporting to our CI builds.

To me https://codecov.io looks good

* free for open source
* plays nicely with pytest/tox (https://github.com/codecov/example-python#testing-with-tox)
* browser extension to visualize coverage directly on Github
* PR coverage

**Comment by The-Compiler** [comment]
FWIW I use codecov for qutebrowser too and I'm quite happy with it.

**Comment by obestwalter** [comment]
Problem: A lot of the tests are run in a subprocess. There is a special wrapper class implementing that as [part of the pytest plugin](https://github.com/tox-dev/tox/blob/master/tox/_pytestplugin.py#L190). 

I am still in the process of learning about it and trying to find out how others are dealing with this. At the moment I am tempted to circumvent the proposed way described [here](https://coverage.readthedocs.io/en/coverage-4.4.1/subprocess.html ) and just bake it right into the wrapper by checking if this is a coverage run and then replacing the python invocation with a coverage run invocation. Don't know if good idea or stupid yet though.

**Comment by The-Compiler** [comment]
Why not use [pytest-cov](https://github.com/pytest-dev/pytest-cov) which takes care of subprocess coverage automagically?

**Comment by obestwalter** [comment]
Does it? Oh great. I wasn't aware of that. Thanks!

**Comment by obestwalter** [comment]
> This plugin produces coverage reports. It supports centralised testing and distributed testing in both load and each modes. It also supports coverage of subprocesses.

Wow - first sentence in the README :) I started reading through the coverage docs instead and from that angle it looks much more involved :)

**Comment by gaborbernat** [comment]
yeah I use pytest-cov for all my projects, works great :+1:

**Comment by obestwalter** [comment]
Could anyone help me debugging this: https://travis-ci.org/Avira/tox/jobs/270979197

> CoverageException: Can't combine line data with arc data

This does not occur locally on on CI.

Changes are here: https://github.com/Avira/tox/tree/%23540

**Comment by obestwalter** [comment]
Branch coverage would be nice but has a problem atm: https://github.com/pytest-dev/pytest-cov/issues/168

keeping this open until resolved.

**Comment by obestwalter** [comment]
Found a workaround for that (pass config file on command line), so we can close this.
