### ISSUE TITLE
Investigate pyc cleaning

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#560]
**from ISSUES.txt originally created by @hpk42**

see

http://lists.idyll.org/pipermail/testing-in-python/2012-October/005205.html

    Hi guys,

    I'm generally a pretty happy tox user, but recently I ran into something
    that appears to have generated a false positive. Apparently I misunderstand
    how tox works, because I figured this wouldn't be possible...

    Anyway, I removed a package (both the directory, the __init__.py and the
    module inside of it), re-ran the tests, and it worked fine. Later, when
    actually trying to run the code in the venv, it broke -- there was still
    something relying on importing that package but the tests didn't catch it.

    I honestly have no idea whatsoever how this happened. It's the first time
    I've seen this behavior, despite it not being the first package I pruned.

    I guess the way to fix this is by recreating the environment? That seems to
    have fixed the issue. I guess maybe in doing so I've also nuked any
    possibility of further diagnosing the problem; hopefully the above
    recollection is enough to ring a bell somewhere.

    cheers
    lvh

**Comment by obestwalter** [comment]
relevant parts of mail conversation:

> On Mon, Oct 15, 2012 at 10:05 -0400, Alfredo Deza wrote:
> > On Oct 15, 2012 9:51 AM, "Barry Warsaw" <barry at python.org> wrote:
> > >
> > > On Oct 15, 2012, at 11:11 AM, Marius Gedminas wrote:
> > >
> > > >FWIW zope.testrunner searches for and deletes stale pyc files by
> > > >default, prior to running the tests.
> > >
> > > This is a great feature which provides additional assurance that the tests
> > > you're passing are the ones you think you should be. ;)  Tox should do the
> > > same thing I think.
> > 
> > I disagree here. Tox is *not* a test runner.
> > 
> > Whatever is being used to run the tests should be in charge of (in this
> > case) removing pyc files.

> tox is, however, invoking test runners, so adding a general feature
> to remove pyc files is worthwhile to consider.  The question is
> where it should remove them exactly.

> best,
> holger

and ...

> --recreate is a good idea for a "does it really work" check 
> when deleting files / dirs i think because without it we rely on 
> distribute/distutils mechanics to do the proper thing when 
> re-installing a package including pyc file handling.  For my quick
> experiment it worked fine, however.

> best,
> holger

> --recreate is a good idea for a "does it really work" check 
> when deleting files / dirs i think because without it we rely on 
> distribute/distutils mechanics to do the proper thing when 
> re-installing a package including pyc file handling.  For my quick
> experiment it worked fine, however.
> best,
> holger

I would tend to close this as wontfix as I tend to agree with Alfredo (testrunner is responsible for that) and as Holger said - there is also `tox -r` which always starts from a clean slate, which is also what a standard CI run should do.

**Comment by gaborbernat** [comment]
I agree, this is out of scope of tox :+1:

**Comment by obestwalter** [comment]
Let's close this then. Enough other stuff todo ...
