### ISSUE TITLE
Support 2to3 configurations / test file postprocessing

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#561]
**from ISSUES.txt originally created by @hpk42**

Tests should be copied and transformed before being executed.
Setup a test definition::

    [testenv]
    testsrc=testing/**.py 
    commands=py.test {posargs}
    
    [testenv:py3*]
    use2to3 = True

would transform all specified test files for all py3 environments 
such that a subsequent test run::

    $ tox -e py25,py32 testing/test_hello.py

causes a transformation of the test files to prepare test runs on
Python3 interpreters.  The ``posargs`` specified files will be rewritten
to point to the transformed test files.

**Comment by The-Compiler** [comment]
Not sure if this is still relevant - almost everyone seems to have moved to using `six` and having polyglot python 2/3 code nowadays.

**Comment by obestwalter** [comment]
True. Would also vote for closing as wontfix.

**Comment by nicoddemus** [comment]
Same here, I vote to close as wontfix.
