### ISSUE TITLE
Export support for travis

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#562]
**from ISSUES.txt originally created by @hpk42**

look into ways to support integration of tox with travis.

- run tox from travis
- let tox read commands from travis config
- generate .travis.yml from tox.ini
- generate tox.ini from .travis.yml

For the last two, take a look at http://pypi.python.org/pypi/panci/

**Comment by The-Compiler** [comment]
[tox-travis](https://tox-travis.readthedocs.io/en/stable/) probably does this quite well already.

**Comment by obestwalter** [comment]
I also think that we can close this pretty quickly as a solved problem.

**Comment by RonnyPfannschmidt** [comment]
i had a general bad experience with tox-travis as a manual and error prone integration that gives bad to interpret results, i consider this unsolved

**Comment by obestwalter** [comment]
Another of my hopes crushed :D let's see then, if a hero turns up to solve this.

**Comment by thedrow** [comment]
@RonnyPfannschmidt We can deprecate tox-travis and provide our own implementation with hooks for different CI providers.

**Comment by ryanhiebert** [comment]
Tox-Travis does all the helpful things I typically need or can think of. But it doesn't do generation of files. I'm not necessarily opposed to creating such functionality in Tox-Travis, but I honestly don't think it's useful enough and I almost certainly will not be working on such a feature myself.

I'm obviously biased, and I think that Tox-Travis covers the necessary use-cases, and I want it, if possible, to expand to covering any use-case that would provide a significant utility to people. Still, I regularly find that people have use-cases that I've not thought of, so I might recommend waiting some amount of time to see if there's someone that has a point in opposition before closing it on my recommendation. If I were the one making the decision alone, I also would probably close this issue, but I also recognize that there are often perspectives that I don't totally understand.

**Comment by obestwalter** [comment]
Thanks @ryanhiebert - I really think that there is just not enough interest in this and I don't need it either. panci seems pretty abandoned also https://github.com/msabramo/python-panci/issues/21. But we can let it hang around open for a little longer to see if someone wants to work on this.

**Comment by obestwalter** [comment]
I really think we can close this now. All these proposed integrations written by @hpk42 many years ago sound really nice, but they are not necessary to integrate tox with Travis.

My personal experience with all kinds of CI platforms and tox is that it is usually not rocket science to get it to work if you understand how tox works and if you understand what your CI solution needs to run your tox environments (which is usually some Python with tox installed and nothing else). tox usually doesn't need to know about the platform it is run on to produce satisfying results. For more complex or tricky use cases, there is usually a solution I can figure out without having to touch the tox code base directly.

I think that tox core should stay completely agnostic to what kind of CI it is used on and any special handling should be done (if at all necessary) in a plugin or helper scripts completely outside of tox.

As for Travis specifically: [tox-travis plugin](https://github.com/tox-dev/tox-travis) is a thing. Use it and if you are not happy with it help improving it, or build your own plugin :)
