### ISSUE TITLE
Non-cached test dependencies

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#563]
**from ISSUES.txt originally created by @hpk42**

if there is a dependency on a URL whose content changes
the download-cache mechanism will prevent it from being reloaded.
Introduce a 'nocache:' prefix which will inhibit using the cache.
Also make and document a guarantee on the deps order so that
one can influence the exact configuration (e.g. use a dev-version
of some package which a later dependency or the original
package depends upon - i.e. deps should be installed first).

**Comment by gaborbernat** [comment]
I think this is more like a feature request to pass per package optional flags to the installer (e.g. pip). @obestwalter is it?
