### ISSUE TITLE
Test and make "in-pkg" tests work

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#564]
**from ISSUES.txt originally created by @hpk42**

it is common to put tests into pkg subdirs, possibly
even with an __init__.  See if/how this can be made
to work.  Maybe also re-consider how py.test does its
importing, maybe add a pytest_addsyspath(testmodule)
and look how nose does it in detail.

**Comment by The-Compiler** [comment]
I think this works already nowadays?

**Comment by obestwalter** [comment]
I do not quite get the meaning of this, so maybe @hpk42 can clarify or just close, if this is not relevant anymore.

**Comment by gaborbernat** [comment]
Given lack of activity, I'll close this as no longer needed.
