### ISSUE TITLE
Allow config overlays

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#565]
**from ISSUES.txt originally created by @hpk42**

You can specify wildcards in section titles.

    [testenv]
    testsrc=testing/**.py 
    commands=py.test {posargs}
    
    [testenv:py3*]
    use2to3 = True

    [testenv:py32]
    deps =
        ...

Configuration values are now looked up in a stricter-matches-first
manner: If environment "py32" is considered then first the 
section under py32, then py3*, then testenv.

**Comment by gaborbernat** [comment]
I would suggest closing this as won't do. Our current configuration is complex enough to avoid this, and would suggest moving to an inheritance based toml config that will allow doing this. @obestwalter what do you think?
