### ISSUE TITLE
tox does not reinstall updated dependencies when they are specified with -r

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox#566]
I think that is perfectly reasonable to to expect tox to install dependencies when the requirements files were updated.

At this moment tox is re-installing dependencies only if you touch the tox.ini file, but if they are stored outside and referred using `deps=-rrequirements.txt`, tox will just skip their installation and obviously fail.

The workaround is to remove the .tox folder but this induces other significant costs.

**Comment by The-Compiler** [comment]
Duplicate of #149.
