### ISSUE TITLE
Tox doesn't install requirement using extras

### ISSUE THREAD

**Issue by helderco** [tox-dev/tox#567]
In my `setup.py` I have:

```
setup(
    ...
    install_requires=[
        'django-constance[database]',
    ],
    ....
)
```

But tox isn't installing _django-constance_.

I use _Oh My Zsh_ in Mac Sierra, so:

```
$ pip install django-constance[database]         
zsh: no matches found: django-constance[database]

$ pip install 'django-constance[database]'       
Collecting django-constance[database]
  Using cached django_constance-2.0.0-py2.py3-none-any.whl
Collecting django-picklefield; extra == "database" (from django-constance[database])
  Using cached django_picklefield-1.0.0-py2.py3-none-any.whl
Installing collected packages: django-picklefield, django-constance
Successfully installed django-constance-2.0.0 django-picklefield-1.0.0
```

This also happens under bash, by the way, but maybe it has to do with some escaping issue?

I have tox 2.7.0.

**Comment by anthrotype** [comment]
I suspect this has to do with a regression in the latest setuptools 36.2.1 
https://github.com/pypa/setuptools/pull/1100#issuecomment-317332452

**Comment by obestwalter** [comment]
From my experience extras works fine, so I go with your hunch that this is a new upstream bug for now.

**Comment by helderco** [comment]
I confirm that updating setuptools to 36.2.2 fixes the issue.
