### ISSUE TITLE
CHANGELOG does not date releases

### ISSUE THREAD

**Issue by csfeathers** [tox-dev/tox#570]
CHANGELOG does not include the respective release dates (nor does the version rendered on Read the Docs).

I find release dates very helpful when reviewing changelogs, especially when catching up from several releases behind.

**Comment by obestwalter** [comment]
Hi @csfeathers - True. The release dates can be gmpsed from the [tag dates](https://github.com/tox-dev/tox/releases), but they also should be in the changelog.

I think we should do this from now on.

**Comment by obestwalter** [comment]
@csfeathers I would also merge a PR that fills in the missing dates for the old releases from the tag dates linked above, so we have it consistently.

**Comment by obestwalter** [comment]
fixed in 71006d854eca65ea194a3cc6240b85768b1ba7fb
