### ISSUE TITLE
Let skip_install override usedevelop instead of the other way around

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#571]
`skip_install` and `usedevelop` can be used together in the same environment but the behaviour is not documented. If both flags are `True` the package will be installed although `skip_install` is requested (see also discussion [here](https://github.com/tox-dev/tox/issues/270#issuecomment-320941011)).

The behaviour should be changed that `skip_install` overrides `usedevelop` as `usedevelop` is an option to choose the installation type if the package is installed and `skip_install` determines if it should be installed at all.

This is a somewhat breaking change of undocumented behaviour but I think this should be done to make the behaviour intuitively correct (but it should also be documented).

It should be also stated prominently in the changelog that this changed and how it can be fixed though. The documentation should be updated mention the behaviour when these two flags are used together.

**Comment by obestwalter** [comment]
docs still needed.

**Comment by gaborbernat** [comment]
This has been done with tox 4.
