### ISSUE TITLE
doc cleanup

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/tox#584]
So I've started cleaning up the documentation page; and found that we still have laying around all the announcement pages, but these are now also part of the changelog (effectively being present in two places). Can we just drop the announcement as they are? Or reference the announcement via include into changelog; but let's not have it twice.

**Comment by obestwalter** [comment]
Did you see this? http://tox.readthedocs.io/en/latest/announce/changelog-only.html

I thought we keep the existing announcements as historical documents, but have no strong opinion about this. They will be preserved on readthedocs for old versions anyway - even if they would be deleted.

**Comment by gaborbernat** [comment]
Yeah I saw that. Keeping it is fine, but then let's not copy it's content to the new change-log, but include it instead.

**Comment by obestwalter** [comment]
We dont't for quite a while already. The way we do releases at the moment, we do not copy anything. The changelog gets rendered into the long description to be displayed on pypi and that's it.

**Comment by gaborbernat** [comment]
what I meant is that https://github.com/tox-dev/tox/blob/master/CHANGELOG#L125 is the same as https://github.com/tox-dev/tox/blob/master/doc/announce/release-2.4.0.txt; we should have a single version of these lines inside the repository I think; if needed let's generate the changelog we create for pypi during build 👍 to avoid duplication, or just remove announcement stuff

**Comment by obestwalter** [comment]
Ah I see. Well that's just how it was done back then. What I meant was that since 2.5 this is not being done anymore and announcements have been quietly (and now loudly) retired. I am +0 for removing the old announcement documents. Let's see if anybody else has an opinion about this.

**Comment by gaborbernat** [comment]
@obestwalter I think this has been solved with 2.9.1 and the towncrier movement, not?

**Comment by obestwalter** [comment]
yup :)
