### ISSUE TITLE
Is it Tox or tox?

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#589]
In a simpler time I did not care, but know I realize I am not sure and I like consistency, which at the moment is not given. At the moment Tox and tox is used both e.g. in the [docs](http://tox.readthedocs.io/en/latest/). I would say it should be tox, just like e.g. pytest and devpi. 

Agreed?

I would update the docs then and try to use it consistently in all communication.

P.S. I know, I can be a bit of a pedant sometimes :)

**Comment by nicoddemus** [comment]
> Agreed?

Yes. 👍 😁
