### ISSUE TITLE
speed up running unit test suit

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/tox#613]
I find the unit tests way too slow; for comfort and speed of development I would like them to be <30s for one environment; we should investigate how we can achieve that! Here's what I get now locally:

```bash
tox -re py27  74.53s user 7.68s system 1% cpu 1:16:00.14 total
```

**Comment by obestwalter** [comment]
I was also wondering and had a look recently. slowest tests are the "systemtests" in test_z_commandline and most time is burnt in os.waitpid. Running with pytest-xdist -n 8 speeds the thing up and we can add that to the tox env also.

In the long run it might be a good idea to have a very good look at how tox tests itself and see how can streamline things and speed them up. I have a few ideas already and would love to tackle that soonish.

**Comment by obestwalter** [comment]
It 's also not strictly necessary to run your tests through tox:

    pytest -n 8 tests  

235.40s user 14.84s system 533% cpu 46.899 total

so only 15 seconds to shave of to get there :)

**Comment by gaborbernat** [comment]
I think new people will tend to use just the default for their contributions; so from that point of view I would prefer to have it run fast by default, so it's encouraged to run it.

**Comment by obestwalter** [comment]
> pytest-xdist -n 8 speeds the thing up and we can add that to the tox env also.

**Comment by gaborbernat** [comment]
also for me it takes longer, will need to investigate how come :+1: and some tests fail, maybe because I'm behind  a proxy:

```
3 failed, 293 passed, 3 skipped, 1 xfailed in 72.41 seconds
```

**Comment by obestwalter** [comment]
hmm, we have to play with that a bit then and find a good value that works reliably or make it configurable with a sane default. I tried `-n 4` on mine now and it is just as fast.

**Comment by gaborbernat** [comment]
I think it depends on the amount of cores, can use ``python -n auto`` to use the number of cores automatically; for me the same three tests fail locally: test_env_variables_added_to_pcall, TestCmdInvocation.test_version, TestToxRun.test_json

**Comment by obestwalter** [comment]
pytest -n auto: 53.93 seconds 

But everything succeeds. Interesting.

**Comment by obestwalter** [comment]
TestToxRun.test_json reuses example123 fixture together with the other tests in that class. Every bet that they get in each others way. Needs cleaning up.

**Comment by gaborbernat** [comment]
things get a lot slower on Windows, with all the virtualenv creations we're talking about 15s just the base virtualenv creation 👎 for each test within ``test_z_cmdline.py``

**Comment by obestwalter** [comment]
Do you have an idea how to speed things up without loosing coverage?

**Comment by gaborbernat** [comment]
I have a few, will need to play around with a few things, but first I need to understand all that's slow in detail. And of course dependent tests should be linked up together with fixtures or something similar.

**Comment by obestwalter** [comment]
Looks like, if you have a good go on those levels, you can shave of a lot of time already without having to change the test suite as such. 

My feeling at the moment is: we are all a bit in refactoring mode (style and replacement of internal contructs) ... getting the whole thing a bit into shape, so that we have a base zo build on for the next years. That's definitely a good thing, but while we are doing that we absolutely have to keep the test suite as such in tact - however slow it is. When that first refactoring phase is done and the refactored builds are out (first one will ship tomorrow - I had other stuff to do today, but I'll definitely ship the current state as rc tomorrow), then we can look at refactoring the test suite. What do you think?

**Comment by nicoddemus** [comment]
I think it is quite sensible to either do refactoring in the code or refactor in the test suite (to speed it up in this case), but not both at the same time.

@gaborbernat keep in mind that you don't need to run the entire test suite while developing, running two environments and linting/flake8 locally is enough IMHO (and what I do). The real test is on CI, and it is OK to let all environments be checked there.

**Comment by gaborbernat** [comment]
@obestwalter as long as we think things through of the changes we should be good; me personally I would prefer the other way around, a fast test suite would greatly help with refactoring. But I'll not be the obstacle for changes in the meantime, I expect speeding up things to take a few weeks (with my availability for this), so no rush here.

**Comment by gaborbernat** [comment]
I've played around with this last few days, and now I consider this a really hard one. I'll keep doing this, for me the tests are still unreliable locally on a VM :face_with_head_bandage:

**Comment by obestwalter** [comment]
Thanks for exploring this. I am not surprised that this is tricky.

**Comment by cryvate** [comment]
@gaborbernat, on your first point, we could change this by invoking virtualenv with the ``--no-download`` option (also settable by environment variable).

**Comment by RonnyPfannschmidt** [comment]
also there should be a easy way to do '-m not acceptance' for the casual testing

**Comment by gaborbernat** [comment]
A significant time is spent on virtual environment creation. An idea to speed up this is what pip does, instead of re-creating virtualenvs - create a session fixture and copy virtual environments. :+1:

**Comment by obestwalter** [comment]
> instead of re-creating virtualenvs - create a session fixture and copy virtual environments.

That sounds great!

**Comment by gaborbernat** [comment]
Ignore this for now, we'll get back to this later.

**Comment by gaborbernat** [comment]
I think we can close this for now. It's going to be an on-going effort.

**Comment by gaborbernat** [comment]
A heads up on this; the new faster virtualenv roughly cut our test suite runtime in half.
