### ISSUE TITLE
towncrier: update contributor guide and gh template

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#619]
Contributors can now use [towncrier](https://github.com/hawkowl/towncrier) to document their changes in a way that they get automatically integrated into the changelog (or stay as internal info for other devs) when the PR is merged. This should be documented [here](https://github.com/tox-dev/tox/blob/master/doc/developers.rst) and [here](https://github.com/tox-dev/tox/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

I have not yet worked with towncrier myself yet and I suggest we collect some experiences before we formalize this.

**Comment by obestwalter** [comment]
Maybe we should also add a contributors doc as GH is [ever so subtly encouragig us](https://github.com/tox-dev/tox/community).

**Comment by gaborbernat** [comment]
I agree adding contributors.

**Comment by obestwalter** [comment]
Quick reminder: we should also add info about that new pre-commit thingy that @asottile added :)

**Comment by obestwalter** [comment]
This is well documented now in the [PR template](https://github.com/tox-dev/tox/blob/master/.github/PULL_REQUEST_TEMPLATE.md) and being used for well over a year, so we can close this I'd say.
