### ISSUE TITLE
Release strategy now that the pace is picking up here ...

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#629]
I am very happy about the recent developments. The PRs keep coming in and there is a big focus on improving the health of the code and making it more maintainable in the long run 🍾 

There is always a danger though that we introduce new bugs and break implicit APIs due to lack of understanding why certain things are the way they are and knowledge who is using internal classes and functions against the advice not to rely on it. Rather than worrying about it, I suggest we do more frequent releases and make sure, we fix bugs that come from those refactorings as quick as possible.

So I suggest we make a new release 2.9 quite soon even if it has only one or two new features, but a lot of refactorings.

**Comment by asottile** [comment]
Seems fine to me!  Shall we draft a milestone and add some goals we should get to before crafting a release?

**Comment by obestwalter** [comment]
I was actually thinking that what we have right now plus the --version addendum is good for another release. Send an rc out tomorrow, wait a few days and then ship the full version.

**Comment by nicoddemus** [comment]
About release candidates, @obestwalter I read you mention somewhere that you don't think they are worth the effort?

**Comment by obestwalter** [comment]
Hi @nicoddemus - yeah, I was dithering a bit there. The main reason is that I am unsure how to handle the versioning and changelog regarding release candidates, now with the added complexity of using towncrier, but in the end those are petty details 99% and they'll be sorted over time. 

Having a handful of projects using release candidats as part of their CI setups will help catching the most obvious problems and even more important, they will be caught y peoplee who are not surprised by things breaking due to a chnage in tox, so I think sticking with this will be worth it in the long run.

**Comment by obestwalter** [comment]
I just uploaded 2.9.0rc1 the whole work flow is absolutely horrible at the moment and towncrier needs tweaking to make it work for us (old changelog entries are completely broken right now), but we'll get there. As soon as I have something that is not a complete catastrophe anymore, I will pour that into a release script with some proper docs and releases will be happening much more frequently.

**Comment by obestwalter** [comment]
Closing this as a release strategy is somehow evolving and further discussion can happen if necessary when doing actual releases (like for 3.0 recently).
