### ISSUE TITLE
Need option for not skipping missing interpreters

### ISSUE THREAD

**Issue by wsanchez** [tox-dev/tox#631]
I really like to have `skip_missing_interpreters = True` in my `tox.ini`, because I'm often working on machines that don't have every Python interpreter installed.

But it's a really bad idea in a CI scenario, because environments just pass without doing anything.

I'd love to see an option to set that value back to `False`, but there's only a CLI option for setting it to `True`… every flag really should have an opposite.

**Comment by obestwalter** [comment]
Hi @wsanchez, you could make the value dependent on an env var and get what you want this way.

    [tox]
    skip_missing_interpreters = {env:TOX_SKIP_MISSING_INTERPRETERS:True}

**Comment by asottile** [comment]
I for one think this is a good idea, patch incoming :)

**Comment by obestwalter** [comment]
I am -1 on this. Feels like command line argument inflation for something that is easily solvable with what we have.

**Comment by obestwalter** [comment]
I would rather introduce accepting an argument for `--skip-missing-interpreters` that behaves exactly like the configuration option. That would be a breaking change, but much cleaner.

**Comment by asottile** [comment]
Devils advocate: why even have the command line argument if you could do it with environment variables 😆

**Comment by asottile** [comment]
more seriously: I think we could change `--skip-missing-interpreters` to take an argument and preserve the existing behaviour if no argument is passed -- if that's a better option :)

```python
import argparse
import distutils.util

no_arg = object()


parser = argparse.ArgumentParser()
parser.add_argument(
    '--foo', default=no_arg, nargs='?', type=distutils.util.strtobool,
)
args = parser.parse_args()

if args.foo is no_arg:
    print('not present: false')
elif args.foo is None:
    print('old behaviour: true')
else:
    print(f'new behaviour {args.foo}')
```

```console
$ python3.6 test.py
not present: false
$ python3.6 test.py --foo
old behaviour: true
$ python3.6 test.py --foo=True
new behaviour 1
$ python3.6 test.py --foo=False
new behaviour 0
$ python3.6 test.py --foo=garbage
usage: test.py [-h] [--foo [FOO]]
test.py: error: argument --foo: invalid strtobool value: 'garbage'
```

**Comment by obestwalter** [comment]
Now we're getting somewhere :)

**Comment by The-Compiler** [comment]
That will break when there are arguments following:

```
python3.6 t.py --foo test.py
usage: t.py [-h] [--foo [FOO]]
t.py: error: argument --foo: invalid strtobool value: 'test.py'
```

**Comment by obestwalter** [comment]
TBH my feeling is anyway to try to simplify tox configuration instead of piling the features on, so I will stay with my -1 on this.

**Comment by The-Compiler** [comment]
Maybe tox should just have an `-o` option to override any ini option, like pytest has? With that, you could do `tox -o skip_missing_interpreters=True` but also e.g. `tox -o distdir=foo`, and maybe even `tox -o '[py35]basepython=python3.5`.

**Comment by obestwalter** [comment]
That sounds like a great direction to me.

**Comment by asottile** [comment]
Ooh that sounds like the best _option_.

If we wanted to make it generic perhaps something like this?

- `-o tox.skip_missing_interpreters=True`
- `--option testenv:py35.basepython=python3.5`

Or with brackets?

- `-o [tox]skip_missing_interpreters=True`
- `-o [testenv:py35]basepython=True`

**Comment by obestwalter** [comment]
I'd say we have good look at how pytest does this and ideally implement the exact same behaviour. I'm off to bed for now though. Wrestling with that horrible release workflow I concocted left me utterly drained.

**Comment by The-Compiler** [comment]
@asottile The syntax with brackets I proposed was inspired by the interpolation syntax in tox.ini where you'd use `{[testenv:py35]basepython}` as well, so I think it'd make sense to keep that syntax.

> EDIT: that argparse snippet above only fails on positional arguments afterwards -- it still does the right thing on options:

Right. It still means invocations which worked before will give a confusing error afterwards.

> I'd say we have good look at how pytest does this and ideally implement the exact same behaviour.

Note that pytest doesn't have to handle different config sections, it only has `[pytest]`.

**Comment by obestwalter** [comment]
closing in favour of #634 (and because it is possible without this option already as dexcribed in https://github.com/tox-dev/tox/issues/631#issuecomment-329531800).
