### ISSUE TITLE
Can't figure out Version Exception

### ISSUE THREAD

**Issue by mellena1** [tox-dev/tox#632]
Hi,

I think this is most likely more of a user-error problem on my part, but I didn't know where else to ask this question. I am trying to contribute to an OpenStack project, and they use tox for their tests. I have been trying to run these tests for the past few days but I'm stuck at this error. It says:

```
Traceback (most recent call last):
  File "/Users/andrewmellen/git-repos/python-jenkins/.tox/py35/lib/python3.5/site-packages/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/Users/andrewmellen/git-repos/python-jenkins/.tox/py35/lib/python3.5/site-packages/pbr/util.py", line 249, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/Users/andrewmellen/git-repos/python-jenkins/.tox/py35/lib/python3.5/site-packages/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/Users/andrewmellen/git-repos/python-jenkins/.tox/py35/lib/python3.5/site-packages/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/Users/andrewmellen/git-repos/python-jenkins/.tox/py35/lib/python3.5/site-packages/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/Users/andrewmellen/git-repos/python-jenkins/.tox/py35/lib/python3.5/site-packages/pbr/packaging.py", line 755, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name python-jenkins was given, but was not able to be found.
error in setup command: Error parsing /Users/andrewmellen/git-repos/python-jenkins/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name python-jenkins was given, but was not able to be found.
```

I checked the packaging.py file that it seems to be failing on and it seems like it looks for a METADATA file (which I don't have in the folder), and then checks git for a version. But I guess both are failing? I've tried other projects and I get the same error with those as well.

I'm assuming its just something I don't understand about Python's package system, as I'm fairly new to it.

Here is my pip freeze output:
```
pluggy==0.5.2
py==1.4.34
python-jenkins==0.4.15
tox==2.8.2
tox-pyenv==1.1.0
virtualenv==15.1.0
```

If anyone can help me get around this that would be awesome. Thanks!
\- Andrew

**Comment by obestwalter** [comment]
Hi @mellena1 - the python packaging ecosystem is a wondrous thing indeed :) - I don't know the pbr project, but I hink you could thave a look at this: https://roaet.com/2017/02/10/problem-with-pbr-and-sdist-tarball/ - but this is a wild guess from me looking around about this porblem for a few minutes, so I might be wrong. if this does not help, better check with the folks from the pbr project directly.

**Comment by mellena1** [comment]
Thanks for the tips @obestwalter. I came across that link earlier but had no luck. I could definitely see it being a git issue, I'll check with the pbr folks on that one. It's weird to me that it even needs to know the version of the package to run unit tests but what do I know? ¯\\_(ツ)_/¯

Thanks again for the quick response!

**Comment by obestwalter** [comment]
> Thanks for the tips @obestwalter.

You're welcome - it's hard to find your way through the jungle when you start off in a new ecosystem - so I hope I can at least point you in the right direction :)

> It's weird to me that it even needs to know the version of the package to run unit tests but what do I know?

That I can answer :) When you are running your tests through tox,  tox builds the package you are testing to and one or more [virtual environment](https://virtualenv.pypa.io/en/stable/userguide/#) is/are created. The package tests are executed in there to make sure the package works in all supported environments.

pbr is something that helps with specific needs of the Open Stack community for building and installing open stack packages and hooks right into the build machinery (which in Python is also a Python script at heart ([setup.py](https://docs.python.org/3/install/index.html)). The error you experienced must be something that goes wrong when tox is trying to build the package under test.

**Comment by mellena1** [comment]
> You're welcome - it's hard to find your way through the jungle when you start off in a new ecosystem - so I hope I can at least point you in the right direction :)

Very much so. A direction is all I need sometimes :)

> That I can answer :) When you are running your tests through tox, tox builds the package you are testing and one or more virtual environment(s). The package tests are executed in there to make sure the package works in all supported environments.
pbr is something that helps with specific needs of the Open Stack community for building and installing open stack packages and hooks right into the build machinery (which in Python is also a Python script at heart (setup.py). The error you experienced must be something that goes wrong when tox is trying to build the package under test.

@obestwalter Well thanks for the explanation! I'll have to do some more research into pbr as well.

As for my original problem, I ran the commands in a docker container and it worked fine first try, so it must be something with my local machine. I use [pyenv](https://github.com/pyenv/pyenv), so its possible it is something weird happening with that. I'll probably just run the tests in a container for now.

I'll close the issue now, if anyone randomly comes across this on Google comment and maybe I'll be around to have some insight still :).
