### ISSUE TITLE
tox needs a logo

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#639]
@hpk42 got the ball rolling last year and it is time that we bring this to a conclusion, so that we can get rid if that silly generic logo for our org :)

I link to the relevant discussions on the mailing list and invite everyone interested in this to join into the discussion on the [mailing list](https://mail.python.org/mm3/mailman3/lists/tox-dev.python.org/). 

[Jad Sarout](https://www.linkedin.com/in/jadsarout/) created some drafts and allowed us to build on them if we like, he has no time anymore to follow up on it himself. The discussion is [here](https://mail.python.org/mm3/archives/list/tox-dev@python.org/thread/VUPVDMUT26EKY4EKSMTWWUBFSSTVZ3PN/). 

Here are his drafts:

![img_20161030_193210](https://user-images.githubusercontent.com/263007/30606359-c487ec06-9d71-11e7-8869-96181c0401fc.jpg)

Thank you Jad!

Discussion round 2 is [here](https://mail.python.org/mm3/archives/list/tox-dev@python.org/thread/7UBSDD6JZCWAL56XZKZHAXNPHIMSOZZ6/). The drafts are by Gero (sorry do not have his full name yet) and are in this PDF: [tox-2017-06-01.pdf](https://github.com/tox-dev/tox/files/1315255/tox-2017-06-01.pdf) (**note**: the writing would need to be adapted to spelling tox all lowercase).
 
I also have an idea for a logo that is based on transpiling the flute from the pytest logo - for reference: ![pytest1](https://user-images.githubusercontent.com/263007/30607640-00aeb9f4-9d76-11e7-8d96-1df0154790ec.png)
And here is my horrible sketch. If someone who is into graphics (Gero?) would want to create something concrete from that I'd be thrilled :)

![img_0930](https://user-images.githubusercontent.com/263007/30606793-2ec20e02-9d73-11e7-8460-ffd43239cb0b.jpg)

I also really liked the [idea from Laura Creighton](https://mail.python.org/mm3/archives/list/tox-dev@python.org/message/4Q3YW6XFJ5CYQUF3D54NUGLF3DPGUFX6/) about that Jack in a box, but there is no draft for this:

> The first idea I had was for the 'box' to be a jack-in-the-box. And give the 'Jack' bouncing out of it a goat's head. Colour the box and dress the Jack the same cheerful colours that pytest uses.

[relevant context]: tox is short for "testing out of the box" :)

**Comment by Pawamoy** [comment]
I like when a logo is not only made of the letters of the product. The flute / road-sign / jack-in-a-box could be really nice, and you could have versions of the logo with and without Tox written below/aside.

Also, looking at the PDF, the 7th logo made me think about a beetle (don't know if you guys can put a meaning on that) or a turtle, and the 16th could look like a nail targetting a cross, helped by the circle if it was more encircling the T. The last one is too much like controllers buttons.

**Comment by Pawamoy** [comment]
I think you can draw a snake (python) head with the letters though, but it will need more talent than I got:

![tox_snake_head](https://user-images.githubusercontent.com/3999221/30608563-1c382c98-9d79-11e7-8108-48d3097fd669.png)

:v:

**Comment by gaborbernat** [comment]
I'm not sure we'll get availability for these; so maybe we should just go ahead with one of the ones we already have ready (sent out to the mailing list in round 2).

**Comment by obestwalter** [comment]
@hpk42  is in touch with Gero who could do some more design work. When I am back from London I wanted to see if we can get anywhere with this.

**Comment by ssbarnea** [comment]
Please make it look decent on favicon size, that's my #1 concern, I hate complex logos. 

Also avoid doing the kind of work Atlassian and JetBrains did with their re-branding ;)

**Comment by hazalozturk** [comment]
Hello! I came across this issue and wanted to contribute. Here are some prototypes. PTAL
![1](https://user-images.githubusercontent.com/26629308/32814645-305a7808-c97e-11e7-8703-6df81c19fc3d.png)
![2](https://user-images.githubusercontent.com/26629308/32814646-306c3908-c97e-11e7-9c86-4ef1dff32aae.png)
![3](https://user-images.githubusercontent.com/26629308/32814647-3079723a-c97e-11e7-88ff-a8ecee516e6c.png)
![4](https://user-images.githubusercontent.com/26629308/32814648-308846a2-c97e-11e7-847a-8d62bd34dd22.png)
![5](https://user-images.githubusercontent.com/26629308/32814649-3096ce5c-c97e-11e7-8f2e-5010cae8f74c.png)
![6](https://user-images.githubusercontent.com/26629308/32814650-30a2aeac-c97e-11e7-9a08-d5f9ec5b5018.png)
![7](https://user-images.githubusercontent.com/26629308/32814651-30b3d0ce-c97e-11e7-9cec-83af4e66a412.png)
![8](https://user-images.githubusercontent.com/26629308/32814652-30c498a0-c97e-11e7-8017-0c5f5a9f9bcf.png)
![9](https://user-images.githubusercontent.com/26629308/32814653-30d0f30c-c97e-11e7-9c2d-0ee988072fce.png)
![10](https://user-images.githubusercontent.com/26629308/32814654-30e9ccba-c97e-11e7-8a73-127e5728eb26.png)
![11](https://user-images.githubusercontent.com/26629308/32814655-30f72234-c97e-11e7-802c-9a8c92a91538.png)
![12](https://user-images.githubusercontent.com/26629308/32814656-310567e0-c97e-11e7-8fa0-5d9df8c3552c.png)
![13](https://user-images.githubusercontent.com/26629308/32814657-311287e0-c97e-11e7-817e-4c046e78d5cb.png)
![14](https://user-images.githubusercontent.com/26629308/32814658-31227326-c97e-11e7-9a88-fb1b4224e509.png)
![15](https://user-images.githubusercontent.com/26629308/32814659-31300180-c97e-11e7-8a1f-7819cb74d548.png)

**Comment by Pawamoy** [comment]
Love the 5th, 6th and 8th! But all are good anyway 😄

**Comment by RonnyPfannschmidt** [comment]
i like the first one and the last one

**Comment by gaborbernat** [comment]
I would accept the first one :+1: @hazalozturk nicely done

**Comment by nicoddemus** [comment]
I like the 1st and 6th. 😁 

Thanks @hazalozturk!

**Comment by hazalozturk** [comment]
Thanks! 
I would be more than happy to help with your webpage @gaborbernat

**Comment by gaborbernat** [comment]
@hazalozturk we have at the moment https://tox.readthedocs.io/en/latest/, but I think would be nice to move something similar to https://docs.pytest.org/en/latest/, naturally with our own colours and content; at least what I was thinking of 👍

**Comment by gaborbernat** [comment]
@hazalozturk created a PR for this already, however as most people were happy with option 1, I recommend let's give a try with that. We can come back later on if required.

**Comment by gaborbernat** [comment]
@hazalozturk do you have that it in SVG, and the raw format? thanks! :+1:

**Comment by hazalozturk** [comment]
@gaborbernat I just added the news fragment. Here is the [svg file](https://drive.google.com/open?id=1bx8Jwj15i9sctKMHqZk_ql97ZuXK9FDB ).
If you want me to commit the svg file to the repo I can do that as well. Thanks!

**Comment by RonnyPfannschmidt** [comment]
@hazalozturk please commit the svg file to the repo as well

in addition i think its only fair if we spin you a more prominent reference/thank you,
but personally i'm not sure what's a reasonable/well fit way to do that

**Comment by ssbarnea** [comment]
I think that the option 1 uses is likely to raise some question regarding use of male genre symbol (mars) on it. I doubt we want to open this pandora box and send a wrong message. See https://en.wikipedia.org/wiki/Gender_symbol

**Comment by RonnyPfannschmidt** [comment]
@ssbarnea thansk for the words of caution, but i don't think that will be a huge issue, my understanding is, that the direction is relevant

**Comment by hazalozturk** [comment]
@RonnyPfannschmidt I have committed the svg file to the repo 👍   In terms of reference, whichever is more convenient for you, is OK with me. This i my very first time contributing to an open source project so I leave it to your judgement 😁
@ssbarnea I think you have a good point. My intention to put the arrow was to imply that Tox makes testing fast.

**Comment by asottile** [comment]
Don't mean to bikeshed but the (chosen?) logo seems a little too close to "♂"

**Comment by hpk42** [comment]
FWIW i like many of @hazalozturk 's logo drafts, except the one with the arrow.

**Comment by obestwalter** [comment]
I also have the same problems with suggestion 1. My favorite from the current suggestions is 5.

@hazalozturk and other potential designers who want to supply some more suggestions. Gero sent us the indesign files for his suggestions if you want to work on them.

**Comment by obestwalter** [comment]
also: if the logo contains the name (which is does not have to be): tox is written **all lowercase**, so the logo should reflect that.

**Comment by obestwalter** [comment]
So the currently merged logo in the WIP docs is this: ![logo proposal](https://user-images.githubusercontent.com/26629308/32814645-305a7808-c97e-11e7-8703-6df81c19fc3d.png)

To get another perspective I just showed it to my wife (without telling her anything about it first) asking her to give mer her immediate gut reaction. She looked at it and immediately said: "This looks very sexual to me. It looks like the male symbol is penetrating that X" ... 

My suggestion for 2.10 (if we did not find a solution until then) would be that we first use a purely typographical logo and then improve on it/change it with later releases.

@hazalozturk do you think you can find some time to work on finding a solution with us?

**Comment by gaborbernat** [comment]
Fair enough, maybe one where we use all lowercase letters 😎

**Comment by obestwalter** [comment]
@gaborbernat all lower case is another thing - true.

FWIW I really like the idea @ssbarnea as well (but that should be all lowercase :)).

**Comment by vlcinsky** [comment]
Hi guys. First thing first: I like tox as a tool and it will work for me very well regardless of the logo.

Second thing: I am fine with the logo currently present in the WIP docs. Clean, working for me.

Anyway, as there is ongoing discussion about what it resembles, I did my short brainstorming about what concepts the logo could use.
# arrow-letters
Say "tox" to be clear about product name, show arrow to express we are target to reaching x.
![arrow-letters](https://user-images.githubusercontent.com/635911/34649675-00d95008-f3b4-11e7-8286-87169538ae93.jpg)


# farthing-bycicle-letters
tox is a vehicle allowing to go/run. letters t-o-x embeded.
![farthing-bicycle-letters](https://user-images.githubusercontent.com/635911/34649740-2af7460a-f3b5-11e7-90b3-18c9a48e23a9.jpg)


# farthing-bycicle-multi
Tox is a vehicle allowing to run tests on multiple python interpreters. This is my favourite one.
![farthing-bycicle-multi](https://user-images.githubusercontent.com/635911/34649674-00bc350e-f3b4-11e7-9342-ae995fdcc289.jpg)

# interwinded-letters
Focusing through O to target X and going there using tests T. The Target is not easy to reach, but is partially getting out.
![interwined-letters](https://user-images.githubusercontent.com/635911/34649673-009cdaa6-f3b4-11e7-9d0d-6b0c9d8ac775.jpg)

**Comment by hazalozturk** [comment]
I used all lowercase and colors derived from python's logo. I used 4 different fonts, let me know if you like any of them.
![tox1 svg](https://user-images.githubusercontent.com/26629308/34653367-eaa5f606-f3b8-11e7-8291-130fddfdd8ae.png)
![tox2 svg](https://user-images.githubusercontent.com/26629308/34653368-eab533fa-f3b8-11e7-88d4-11ebadaaf06f.png)
![tox3 svg](https://user-images.githubusercontent.com/26629308/34653369-eaca6284-f3b8-11e7-87b7-c31a3e373fa5.png)
![tox4 svg](https://user-images.githubusercontent.com/26629308/34653370-eadfc962-f3b8-11e7-95d2-181462f4f247.png)

**Comment by gaborbernat** [comment]
I fancy the second one 👍 would gladly go with that!

**Comment by hazalozturk** [comment]
@obestwalter and @gaborbernat if second one is the final decision, I can go ahead and create another PR replacing the old one?

**Comment by gaborbernat** [comment]
@hazalozturk  I find it a definite improvement, so let's go ahead I would say. Please provide png, svg and fav-icon version of it :+1:  if it's possible.  Thank you very much!

**Comment by obestwalter** [comment]
Thanks @hazalozturk!

**Comment by obestwalter** [comment]
Well, we have a logo now and nothing terrible happened for a while, so I guess we can close this.
