### ISSUE TITLE
allow tox to reject invalid or unexpected target parameters

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox#646]
Currently tox will try to create any unexpected target environment even if the user makes a typo. We would like to be able to have an option that will make tox return an error on unknown environments.

Because this may break some setups I suspect that the correct implementation would be to add add a tox.ini config item that would enable this behaviour, like `enforce_envlist=True`

## Expected behaviour
```
tox -e foobar
# same for TOXENV=foobar
Invalid foobar environment
exit code: 1
```

**Comment by cryvate** [comment]
I get

    tox -e asdf
    ERROR: unknown environment 'asdf'
    exit code: 1

with nothing being created on tox 2.8.0 and 2.9.1. This looks like your expected behaviour?

**Comment by ssbarnea** [comment]
@cryvate this sounds like good news to me. No more typos in environment name! A good reason to bump tox.

**Comment by cryvate** [comment]
@ssbarnea: it seems that this was added/changed in version 1.8.1. I think this can be closed.

**Comment by The-Compiler** [comment]
Assuming this is fixed then! FWIW this has been the behaviour for as long as I can remember using tox :wink:
