### ISSUE TITLE
Installation failures with setuptools 34 & 35

### ISSUE THREAD

**Issue by rpkilby** [tox-dev/tox#656]
This is a continuation of tox-dev/tox-travis#76. 

Travis's python 3.4 environment ships a broken version of setuptools (more details in the tox-travis issue). When upgrading dependencies that setuptools itself depends on (such as six in this case) a race condition may occur where the package temporarily does not exist, causing the installation to fail.

**Comment by cryvate** [comment]
We can prevent the problems on the travis build by replacing ``pip install --pre -U tox`` with ``pip install setuptools && pip install --pre -U tox`` as suggested in this thread. This is what we do at work as well: having old versions of setuptools can get you into gnarly problems...
