### ISSUE TITLE
Allow space after '-r' option in deps configuration file

### ISSUE THREAD

**Issue by cryvate** [tox-dev/tox#658]
I was cleaning up a ``tox.ini`` and attempted to change:

    [testenv]
    deps = -rfoo.txt

to

    [testenv]
    deps = -r foo.txt

to make it more readable, however it tries to read `` foo.txt`` (with space at beginning, lost when formatted) which does not exist and this was unexpected. I propose it strips whitespace so it is closer to accepting the pip format, as suggested by the ``deps`` option help: "each line specifies a dependency in pip/setuptools format."

[``pip`` itself uses its own config parser.](https://github.com/pypa/pip/blob/62a695c4b905b503f7ff38c0d47cf0ea203853ea/src/pip/_internal/req/req_file.py#L130)

I would be happy to write a PR myself, this can be implemented by adding:

    if name.startswith('-r'):
        name = '-r' + name[2:].strip()

[after this line.](https://github.com/tox-dev/tox/blob/master/tox/config.py#L125).

**Comment by obestwalter** [comment]
Hi @cryvate - you can pass all kinds of args there not just -r and it is a bit of a hacky area, so I would suggest to have a proper look at how it works at the moment and think about how to do it correctly (without breaking backwards compatibility).

**Comment by cryvate** [comment]
Issue #73 has the same root cause, and so does issue #601
