### ISSUE TITLE
pre-commit fails on Windows for development

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/tox#661]
@asottile any ideas? 
 
```bash
C:\Users\berna\git\tox (speed)
λ pre-commit
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to C:\Users\berna/.cache\pre-commit\patch1509037495.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Restored changes from C:\Users\berna/.cache\pre-commit\patch1509037495.
An unexpected error has occurred: CalledProcessError: Command: ('C:\\Users\\berna\\.cache\\pre-commit\\repopaozpr92\\py_env-python3.6\\Scripts\\pip.exe', 'install', '.')
Return code: 2
Expected return code: 0
Output:
    Processing c:\users\berna\.cache\pre-commit\repopaozpr92

Errors:
    Exception:
    Traceback (most recent call last):
      File "c:\users\berna\.cache\pre-commit\repopaozpr92\py_env-python3.6\lib\site-packages\pip\basecommand.py", line 215, in main
        status = self.run(options, args)
      File "c:\users\berna\.cache\pre-commit\repopaozpr92\py_env-python3.6\lib\site-packages\pip\commands\install.py", line 335, in run
        wb.build(autobuilding=True)
      File "c:\users\berna\.cache\pre-commit\repopaozpr92\py_env-python3.6\lib\site-packages\pip\wheel.py", line 749, in build
        self.requirement_set.prepare_files(self.finder)
      File "c:\users\berna\.cache\pre-commit\repopaozpr92\py_env-python3.6\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
        ignore_dependencies=self.ignore_dependencies))
      File "c:\users\berna\.cache\pre-commit\repopaozpr92\py_env-python3.6\lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
        session=self.session, hashes=hashes)
      File "c:\users\berna\.cache\pre-commit\repopaozpr92\py_env-python3.6\lib\site-packages\pip\download.py", line 809, in unpack_url
        unpack_file_url(link, location, download_dir, hashes=hashes)
      File "c:\users\berna\.cache\pre-commit\repopaozpr92\py_env-python3.6\lib\site-packages\pip\download.py", line 686, in unpack_file_url
        shutil.copytree(link_path, location, symlinks=True)
      File "c:\users\berna\.cache\pre-commit\repopaozpr92\py_env-python3.6\lib\shutil.py", line 359, in copytree
        raise Error(errors)
    shutil.Error: [('C:\\Users\\berna\\.cache\\pre-commit\\repopaozpr92\\testing\\resources\\broken_symlink', 'C:\\Users\\berna\\AppData\\Local\\Temp\\pip-hxrt6p7o-build\\testing\\resources\\broken_symlink', 'symbolic link privilege not held'), ('C:\\Users\\berna\\.cache\\pre-commit\\repopaozpr92\\testing\\resources\\working_symlink', 'C:\\Users\\berna\\AppData\\Local\\Temp\\pip-hxrt6p7o-build\\testing\\resources\\working_symlink', 'symbolic link privilege not held')]


Check the log at C:\Users\berna/.cache\pre-commit\pre-commit.log
```

because of this I cannot run tox -e fix-lint

**Comment by asottile** [comment]
Interesting, this might be due to the `.gitconfig` -- I also made some fixes here recently and we might just need to bump up versions, let me craft a PR and see if that fixes it

**Comment by gaborbernat** [comment]
see also https://ci.appveyor.com/project/RonnyPfannschmidt/tox/build/1.0.483/job/5o4tupnis44nuum1 with another strange error 🤔 related to this without any meaningful error message

**Comment by asottile** [comment]
This should handle the first things: https://github.com/tox-dev/tox/pull/662

As for the second, I *thought* this handled that, but perhaps not: https://github.com/pre-commit/pre-commit/blob/master/CHANGELOG.md#120 ("add `ctypes` for health checks")

**Comment by asottile** [comment]
The second problem can be worked around by blowing away the appveyor cache -- I'll look into a better fix for it

**Comment by asottile** [comment]
#662 definitely solves the symlink problem, as for the other problem I'll look into it further -- it has to do with upgrading system python3.6 and invalidating the virtualenv cache.  There's a solution implemented which works well for linux but it seems there's some missing bits on windows: https://github.com/pre-commit/pre-commit/issues/645

Thanks for bringing this to my attention!  I definitely don't exercise edge cases on windows as often as I do on linux.

**Comment by asottile** [comment]
Found it!  That log above is using `pre-commit==1.0.1`, this bug was fixed in `1.2.0`!

**Comment by asottile** [comment]
Also upgraded pre-commit (to address the second thing) here: https://github.com/tox-dev/tox/pull/662/commits/eaf24e13063b3526ad929a262e88ab66a234cd39

**Comment by gaborbernat** [comment]
@asottile another problem here is that here's what's happening with windows:

``C:\Users\berna\git\tox\~\.cache\pre-commit``

Surely you wanted home folder here not?

**Comment by gaborbernat** [comment]
also even after upgrading to 1.3.0:

```
fix-lint runtests: commands[2] | pre-commit run --all-files
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: FileNotFoundError: [Errno 2] No such file or directory: '~\\.cache\\pre-commit\\repoybcyzw2e\\py_env-python3.6\\.install_state_v1staging'
Check the log at ~/.cache\pre-commit\pre-commit.log
ERROR: InvocationError: 'C:\\Users\\berna\\git\\tox\\.tox\\fix-lint\\Scripts\\pre-commit.EXE run --all-files'
```

**Comment by gaborbernat** [comment]
@asottile I've decided to try to run pre-commit CI on my machine, and here's what I get:
 ``78 failed, 353 passed, 6 skipped, 12 xfailed, 6 xpassed, 62 error in 185.08 seconds`` 

that explains I suppose why things fail with tox.

**Comment by asottile** [comment]
We do [test against windows](https://github.com/pre-commit/pre-commit/blob/master/appveyor.yml), the failures you're seeing are likely related to git configuration (and hopefully just output mismatches!) -- I do have a fix for tox though, there's a `passenv` needed so windows will `os.path.expanduser` correctly: #667

**Comment by gaborbernat** [comment]
@asottile not sure yet, for now I've stumbled first into git and gpg password issues - see https://github.com/pre-commit/pre-commit/pull/649

**Comment by asottile** [comment]
@gaborbernat I've documented the `passenv` here: https://github.com/pre-commit/pre-commit.github.io/pull/144

**Comment by asottile** [comment]
@gaborbernat forgot to circle back, is this working for you again?

**Comment by gaborbernat** [comment]
yeah, that made it work 🆗

**Comment by asottile** [comment]
🎉
