### ISSUE TITLE
followup to #662 - Fix E741 (flake8)

### ISSUE THREAD

**Issue by asottile** [tox-dev/tox#663]
I've temporarily turned this off in #662 such that we can get our build back to green.

We should go through and fix E741 (ambiguous variable name) -- the variable name in question appears to be `l` (and I agree, I have no idea what it means!)

**Comment by obestwalter** [comment]
ah, that's new and I guess it is there because l and 1 can be confused if you use a bad font or something.

**Comment by cryvate** [comment]
I am happy to have a look at this if no-one is working on it yet?
