### ISSUE TITLE
Wheels not cached on package downloading

### ISSUE THREAD

**Issue by umax** [tox-dev/tox#666]
Hi!

We try to speed up our GitLab jobs by caching packages. Imagine, we have the following tox config:
```
[tox]
envlist =
    py36-isort
skipsdist = true

[testenv]
install_command =
    pip install --cache-dir={env:PIP_CACHE_DIR} {opts} {packages}
commands =
    isort: isort --check-only --diff --recursive .
deps =
    isort: isort
```
Let's say, that PIP_CACHE_DIR is /tmp/pip-cache

```
$ ls /tmp/pip-cache
$
$ PIP_CACHE_DIR=/tmp/pip-cache tox -vv -e py36-isort
```
tox log:
```
...
py36-isort installdeps: isort
....
/Users/max.usachev/projects/test-tox/.tox/py36-isort/bin/pip install --cache-dir=/tmp/pip-cache isort
Collecting isort
  Downloading isort-4.2.15-py2.py3-none-any.whl (43kB)
    100% |████████████████████████████████| 51kB 192kB/s
Installing collected packages: isort
Successfully installed isort-4.2.15
....
```
Ok, let's see what we have in /tmp/pip-cache:
```
$ ls /tmp/pip-cache
$ http
```
As you can see, there is no downloaded wheel inside dir. If I repeat tox command again, isort package will be downloaded again.
I have tried to install isort using raw `pip install --cache-dir` command and it works like expected - the first time package (wheel) downloaded and stored in cache dir. The second time cached package used instead of downloading it again.

Yes, there is a hack: install isort package manually using command option, but it's wrong way I suppose:
```
[tox]
envlist =
    py36-isort
skipsdist = true

[testenv]
commands =
    isort: pip install --cache-dir={env:PIP_CACHE_DIR} isort
    isort: isort --check-only --diff --recursive .
```

Thanks!

**Comment by asottile** [comment]
Instead of customizing the `install_command`, can you instead tell your jobs to cache `~/.cache/pip` such [as this](https://github.com/pre-commit/pre-commit/blob/9e193f7fc8368f2ee707307235f503d3f6e492d2/.travis.yml#L32)

Also note that when a wheel is on pypi (such as the case for `isort`) it will not show up in pip's wheel cache, but instead inside the `http` cache (in an unreadable format sadly).

So I believe this is actually not a bug, but a misunderstanding of the upstream pip behaviour :)

I also see it being cached:

```
$ C:\Users\Anthony\AppData\Local\Temp\foo\tox\herp\.tox\py36-isort\Scr
ipts\pip.EXE install --cache-dir=womp isort
Collecting isort
  Using cached isort-4.2.15-py2.py3-none-any.whl
Installing collected packages: isort
Successfully installed isort-4.2.15
```

**Comment by umax** [comment]
Hi! Sorry, the problem was related to our local PYPI index, not related to `tox`: https://www.jfrog.com/jira/browse/RTFACT-13856
