### ISSUE TITLE
--result-json does not respect --skip-missing-interpreters-option

### ISSUE THREAD

**Issue by r2dan** [tox-dev/tox#672]
When executing tox with --result-json and --skip-missing-interpreters-option, the latter seems not to be reflected in the generated json file. Please find the sample project attached below:
[missing_interpreters.tar.gz](https://github.com/tox-dev/tox/files/1474831/missing_interpreters.tar.gz)

To reproduce the issue simply invoke:

`tox --skip-missing-interpreters --result-json toxreport.json`
Tox main process exits with return code 0, but in toxreport.json file user can see the following:
```
"python": {
  "setup": [
  {
    "command": [
    "setup virtualenv"
    ],
    "output": "InterpreterNotFound: xyz_unknown_interpreter",
    "retcode": "1"
   }
   ]
}
```
In my opinion retcode here should be changed to 0 if --skip-missing-interpreters option is explicitly used.

**Comment by obestwalter** [comment]
Hi @r2dan thanks for the report. Having a test reproducing this would also be great.

**Comment by r2dan** [comment]
Sorry for a long radio silence - the test (and PR) is ready. Thanks!
