### ISSUE TITLE
# ERROR: toxini file 'tox.ini' not found - Linux Fedora 27

### ISSUE THREAD

**Issue by Fedorian** [tox-dev/tox#676]
Hi every one,
Thanks for looking into this ...
I got a message # ERROR: toxini file 'tox.ini' not found 
Some days ago I have upgraded my Linux Fedora 26 operating system to Linux Fedora 27.
I've installed several programs. I can watch videos with VLC or with Netflix (under Google Chrome). With Opera too. Seems everything is ok. After installing Skype I decided to install too qTox.
There used to be a repo file at https://download.opensuse.org/repositories/home:antonbatenev:tox/Fedora_26/home:antonbatenev:tox.repo but it seems it has disappeared.
It seems there's no repo file at all in the world, now, for this installation.
I tried to follow instructions at this page : https://github.com/qTox/qTox/blob/master/INSTALL.md#fedora-git
It did not work. "Can not find toxcore".
So ... I found this. https://pkgs.org/download/python2-tox
I downloaded that file and launched a dnf install. Here a copy paste of my commands
dnf install python2-tox-2.7.0-1.fc26.noarch.rpm 
dnf install tox
tox &
# ERROR: toxini file 'tox.ini' not found
tox --version
2.7.0 imported from /usr/lib/python3.6/site-packages/tox/__init__.py
SO ... How to solve this ? ... Would anyone have such a tox.ini that I can use ? 
Thanks a lot you all.

**Comment by RonnyPfannschmidt** [comment]
the python tox project is completely unrelated to the tox p2p system

python tox is a ci/testing tool and needs of coruse its configuration  file locally
