### ISSUE TITLE
move tox-venv to tox-dev

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/tox#678]
For this first @obestwalter should invite @rpkilby to the organization.

@obestwalter maybe we should have a separate organization for plugins :thinking: 

Thanks!

**Comment by obestwalter** [comment]
Invitation is out - welcome @rpkilby.

**Comment by rpkilby** [comment]
Hi all - I've looked over the [submission checklist](https://github.com/tox-dev/tox/blob/master/CONTRIBUTING.rst#submitting-plugins-to-tox-dev), and everything should be in order.

- [x] PyPI presence with a setup.py that contains a license, tox- prefixed name, version number, authors, short and long description.
- [x] a tox.ini for running tests using tox.
- [x] a README.txt describing how to use the plugin and on which platforms it runs.
- [x] a LICENSE.txt file or equivalent containing the licensing information, with matching info in setup.py.
- [x] an issue tracker for bug reports and enhancement requests.
- [x] a changelog

If everything is in order, I'll go ahead and transfer to tox-dev.

**Comment by gaborbernat** [comment]
Go ahead.

**Comment by rpkilby** [comment]
All done 😄
