### ISSUE TITLE
pip upgrade support + better support for using `python -m pip` as the installer command

### ISSUE THREAD

**Issue by jurko-gospodnetic** [tox-dev/tox#701]
Default installation command used by `tox` actually runs pip's setuptools based runner executable (`pip.exe` on Windows), which then can not be removed or replaced while actively running on Windows.

A way towards a solution to this is to use a different installer command - `{envpython} -m pip install {opts} {packages}`, which should have the same effect but not use any executables to be replaced by a pip upgrade.

The main part of this is a relatively straightforward change, with just a bit of tweaking done on the test suite to adjust it to this change.

However, that runs into a bit of a problem with a slight difference between running `pip.exe` and `python -m pip`. The former adds the script folder to the Python path (`venv/Scripts` on Windows), while the latter adds the current working folder.

Unfortunately, adding the current working folder to the Python path is currently a big no-no for `tox`, As `tox` typically does its work from the target project's root folder, i.e. folder containing the  project's `tox.ini` configuration file, that means that this places that project root folder on the Python path for any Python processes run by `tox` in any of its Python environments, And since `tox`
in a typical project configuration also creates the project packages' `.egg-info` folders in that same project folder, that causes Python processes run by `tox` to automatically consider those packages as already installed in the target Python environment. This in turn makes various `pip` operations related to those packages fail, even their basic installations to various `tox` managed Python environments.

One way to work around this is to not hold our package sources in the root folder, but move them deeper to some `src` folder, which would make the `.egg-info` folders also be generated down in that `src` folder. This does avoid the problem, and can possibly be used for projects like those set up inside `tox`'s test suite, but does not seem feasible for general projects using `tox` out there in the wild which might really want to store their package folders directly inside their root project folder (and that is the typical suggested project structure).

Another way to work around it is to make tox not run its commands from the folder containing the `tox.ini` configuration file, but some temporary folder, e.g. `.tox` or `.tox/run-from-here`.

I can prepare a pull request for it but I assume the issue has come up before and someone must have had a good reason for not doing something like this before, so I'd like to hear what others think about this latter aproach? Anyone see any potential issues with it?

**Comment by gaborbernat** [comment]
I think this has been fixed for now via switching to python -m tox. If not please say and I'll reopen.
