### ISSUE TITLE
Toxic does not go online.

### ISSUE THREAD

**Issue by a0000000** [tox-dev/tox#704]
(My English, is not good.)

### OS:
Devuan Jessie 1.0.0 i386
(https://files.devuan.org/devuan_jessie)

(Terminal: `lxterm`)

### Toxic and libqrencode3 install:
https://pkg.tox.chat/debian/pool/release/t/toxic-no-x11/toxic-no-x11_0.8.1-299_i386.deb
`apt-get install libqrencode3`
`dpkg -i toxic-no-x11_0.8.1-299_i386.deb`

### Toxic start (without `~/.config/tox/`):
`toxic`
Toxic does not go online.

### Toxic start with `--debug` (without `~/.config/tox/`):
`toxic --debug`
Toxic write:
`HTTPS lookup error (libcurl error 7)`
`update_DHT_nodeslist() failed with error -2`
`nodeslist load error: file empty.`

--

If toxic run, and then one starts utox, goes toxic online.
Besides, becomes `~/.config/tox/toxic_profile.tox` bigger.
But I think, then this is, a faulty connection.

--

Before some days, toxic still generated `toxic_profile.tox`, which went go online.
With an old `toxic_profile.tox`, toxic still goes online.
But now, toxic does not generate `toxic_profile.tox`, that goes online.

**Comment by gaborbernat** [comment]
you want https://github.com/JFreegman/toxic - this is not that 👍

**Comment by a0000000** [comment]
Oh, thanks.
