### ISSUE TITLE
tox finishes with 0 exit code even if tests failed

### ISSUE THREAD

**Issue by resurtm** [tox-dev/tox#714]
Travis CI build: https://travis-ci.org/resurtm/wvflib/jobs/316417919
Code, configuration, and tests: https://github.com/resurtm/wvflib

![image](https://user-images.githubusercontent.com/100198/33994615-6df73ff4-e105-11e7-8770-5e38570d2455.png)

**Comment by The-Compiler** [comment]
That's because your `coverage_wrapper.py` does so. Fix that, or use `pytest-cov` instead.

**Comment by resurtm** [comment]
@The-Compiler, oh! Thank you very much! ;-)
