### ISSUE TITLE
[FEATURE] Add support for `envreport` action to be pluggable

### ISSUE THREAD

**Issue by tonybaloney** [tox-dev/tox#725]
Requesting (and willing to submit a PR) that the plugin system support a hookimpl for the envreport action.

I'm developing a plugin for `Pipenv` https://github.com/tonybaloney/tox-pipenv using the hook implementation API in 2.9.1. 

So far it's working nicely, however as stated in the docs, the hook implementation options are not complete.

Whilst the default option for list_dependencies_command can be overridden at runtime, I want the plugin to be self-contained. Also, setting the configuration option when the plugin ignores it seems a little obtuse.

https://github.com/tox-dev/tox/blob/master/tox/config.py#L595-L599

**Comment by tonybaloney** [comment]
Raised PR with potential implementation

**Comment by asottile** [comment]
I think you can do this without needing new apis.  For example, here's how `tox-pip-extensions` sets the `install_cmd`: https://github.com/tox-dev/tox-pip-extensions/blob/a989ec95ef8f3c5e63bb809308cd4260f0690e76/tox_pip_extensions.py#L71
