### ISSUE TITLE
`_ispython3` fails on Windows

### ISSUE THREAD

**Issue by jaraco** [tox-dev/tox#733]
In [this comment](https://github.com/tox-dev/tox-venv/issues/1#issuecomment-355974943), I discovered that `VirtualEnv._is_python3` as [found here](https://github.com/tox-dev/tox/blob/1f328d1579d0fe1c09276113f038ab29e8fb475f/tox/venv.py#L152-L153) fails to detect Python 3 on Windows. It's using Unix-specific conventions to detect the Python version, so it returns False even when the venv is on Python 3.

**Comment by jaraco** [comment]
Or maybe it's a tox-specific convention (`basepython` of the toxenv).

**Comment by asottile** [comment]
This function is an unused private interface.  I'm going to remove it.  (`tox-venv` shouldn't be using it -- instead probably wants to do detection based on the current running python (is `venv` importable?))

**Comment by jaraco** [comment]
> instead probably wants to do detection based on the current running python (is venv importable?)

I [started a draft of this approach](https://github.com/jaraco/tox-venv/commit/1368a44a8d1c7f04f5d5a3a8004f21c003f323f1) as well, not realizing until I went to test it that it's not a viable approach because the 'current' python and the target environment python are two different animals, and in the case of venv, unlike virtualenv, it's not possible to invoke venv except from the target Python interpreter (you can't use venv on Py36 to create a venv for Py35).

> This function is an unused private interface.

It's possible tox-venv created this interface as a private interface with the expectation that it would eventually be incorporated into tox, so could rely on private interfaces.

I hope tox-dev/tox-venv#2 gets accepted, which also happens to remove the dependency on this private attribute.

**Comment by asottile** [comment]
Oh! I was under the impression `venv` was a full replacement for `virtualenv` -- guess not if it can't do cross-python.

It seems `_ispython3` was added in the initial check-in: https://github.com/tox-dev/tox/commit/881e39d526f47057f79419276e7f77932b930a17#diff-b1c88079cc7207ed72bd3e15d036abedR21

And made unused in https://github.com/tox-dev/tox/commit/9c36d093aa52808a742960b994f643d989ce465a

**Comment by rpkilby** [comment]
btw, I've updated tox-venv to use the method provided by @jaraco.

**Comment by asottile** [comment]
sweet, I'll go forth with removing the old method!
