### ISSUE TITLE
Add support for sdist command customization

### ISSUE THREAD

**Issue by danlamanna** [tox-dev/tox#737]
Sometimes it is desirable to build an sdist with distinct flags, such as specifying the output format (right now this is hardcoded as zip). It would be nice if `tox` supported a configuration option for `sdistargs` or `sdist_command` similar to other commands it runs. I would be willing to submit a PR given there's a clear consensus of the approach that should be taken.

**Comment by gaborbernat** [comment]
Can you detail why you want not zip?

**Comment by gaborbernat** [comment]
Can you detail why you want not zip?

**Comment by gaborbernat** [comment]
The plan here is that we use now pep 517, and that encourages passing flags via the config file, e.g. setup.cfg.
