### ISSUE TITLE
support for alternatives to pip installers: conda, rpm, deb

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox#747]
Tox is currently able to create and use test environments that based on virtualenvs and pip. Still, testing python code requires testing in different deployment scenarios which include
* testing without virtualenv (system)
* using conda installer (very common in data science)
* using system packages like (yum for rpms,  apt-get for debs)

All of these cover the same need: ability to install a set of dependencies needed for running the test.

I do understand that these use cases may be outside the basic scope of tox and that probably the best way to implement them would be via some tox plugins.

Still at this moment I am not aware about any sample plugin skeleton/template that can be used as a starting block for implementing this functionality.

For the moment I identified these areas as places where the tox behaviour would need to be altered in order to implement this feature:

* `deps` command, should not use pip
* commands like `pip ...` are quite common in tox.ini files, especially due to known bugs in deps.
* skipping creation of a virtualenv

Maybe another way to approach this issue would be to have fake pip wrapper which uses pip api but that does different things under the hood (like installing dependency using system packager).

**Comment by asottile** [comment]
fwiw, here's a plugin I've looked at before for installing debian packages: https://github.com/balabit/tox-debian-plugin

(I'm not saying this is necessarily a good idea -- installing apt packages _usually_ requires root and a big part of `tox`'s design is to do user-space installations).  I myself haven't used the package so I can't vet it's quality or functionality -- just that it exists.

It uses the [`tox_install_deps`](https://github.com/tox-dev/tox/blob/336f4f6bd8b53223f940fc5cfc43b1bbd78d4699/tox/hookspecs.py#L57-L80) hook iirc

**Comment by ssbarnea** [comment]
Thanks @asottile, i will test this plugin right away. If it works it would clearly be very easy to made one for rpm based distros.

**Comment by obestwalter** [comment]
Hi @ssbarnea, I would say this falls under the interpreter [diversiity project](https://github.com/tox-dev/tox/projects/3) so it's definitely out of scope for tox and supporting conda is a long standing issue.

> Still at this moment I am not aware about any sample plugin skeleton/template that can be used as a starting block for implementing this functionality.

I like that idea. If someine would create a https://github.com/audreyr/cookiecutter plugin to create tox plugins, we could take that into tex-dev.

**Comment by gaborbernat** [comment]
I think this has been solved by the downstream plugins.
