### ISSUE TITLE
Using the vector beach ball as graphical logo

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#748]
Hi @hazalozturk, thank you for your contribution of the tox logo. It is great to have someone volunteer design work and I hope you will stick around for a while to help us evolving our visual brand (I know buzzwords!) :)

I like the idea of using that ... vector beach ball ... wherever we need something purely graphical and ideally quadratic, like in the tox dev icon or as favicon.

I took the artistic freedom to use it for the tox-dev org icon (https://github.com/tox-dev) - hope this is o.k. for you. 

I would also suggest to use that ball to create a set of favicons (not vital, but the world seems to think that you need umpteenth versions of favicons to look cool on every device). I fed the docs url to a favicon checker and if you are interested you could contribute that set?

https://realfavicongenerator.net/favicon_checker?protocol=https&site=tox.readthedocs.io%2Fen%2Flatest%2F

**Comment by hazalozturk** [comment]
Hello @obestwalter , You are very welcome. 
I think the ball looks great as the tox-dev icon. I am glad that you used it.  
I will be around if you need any changes for the logo or any  other design related help. I also like the idea of using only the ball as favicon, so I will play around to see our options. Thanks for the favicon checker link. I will work on it whenever i have time(probably will be done later next week).

**Comment by rpkilby** [comment]
@hazalozturk If you're not aware, you can also use that site to generate the favicons. Should save you a lot of work of having to manually create the files.

**Comment by obestwalter** [comment]
That's done :)
