### ISSUE TITLE
How to deal with slow mac builds on Travis CI?

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#751]
@asottile mentioned this somewhere: the macOS build is super slow to start on Travis CI and has been for a long time. So maybe we can find a better solution for this? Are there other CI services free for FOSS we could do our macOS builds on for example?

**Comment by gaborbernat** [comment]
Not as far as I'm aware. Travis have a reasonably low number of Mac machines (as they are hard to set up), hence why it takes a long time to get into queue for one. Many projects out there marked the macOS as may fail, or removed it as such.

**Comment by obestwalter** [comment]
Completely switching it off would be a shame ... but in the worst case we might only activate it before releases and see if something broke on macOS.

**Comment by gaborbernat** [comment]
You can make it may fail, which means still run it but don't wait for it for build passed purposes. This way you could see historically what broke it, but don't get slowed down by it.

**Comment by asottile** [comment]
I'm not sure I see the value either, we currently don't have any darwin-specific code as far as I know?

**Comment by obestwalter** [comment]
If we support macOS, we should run the tests also on macOS. Given the messy world we live in, it is perfectly possible to break something on mac without writing any specific code for it. I guess setting it to mayfail will keep us in the know if something breaks without slowing the build down anymore.

**Comment by rpkilby** [comment]
fwiw, when initially working on #630, the macOS builds had errors not present in the other builds.

**Comment by obestwalter** [comment]
Closing this as it is solved good enough sonce we started allowing failures for macOS and not having to wait for the builds anymore. It's good that we have at least one active macOS user in @rpkilby to keep an eye in it :fireworks:
