### ISSUE TITLE
ERROR: No setup.py file found

### ISSUE THREAD

**Issue by evandrocoan** [tox-dev/tox#761]
I had renamed my https://github.com/evandrocoan/DebugTools `setup.py` to `setup` to stop the file `setup.py` being loaded by Sublime Text when installed as dependency. It works fine running `python setup install`.

I did not found a setting allowing to pass the the configuration file for the python installer. Only for `-c` to pass the `tox.ini` file.

Can a setting to be added to `tox.ini` like `pythonsetup = setup`?
```ini
[tox]
pythonsetup = setup
```

**Comment by obestwalter** [comment]
Hi @evandrocoan, this looks to me like a problem in sublime text, so I wouldn't know why this should be fixed by adding an option in tox.

**Comment by vlcinsky** [comment]
I agree with @evandrocoan. Creating an option in tox configuration which is not needed would be real issue. Keeping some things as widely agreed constants (e.g. name of file being `setup.py`) makes understanding the tool simpler. I would propose to close this issue.

**Comment by evandrocoan** [comment]
Loading every `*.py` file on the package root folder, is just how Sublime Text works. Notice it only loads `*.py` file on the root directory. If I move `setup.py` into a folder inside the package, then Sublime Text does not load it anymore. But if I move `setup.py` to a deep folder, `tox.ini` will also not find it. Why I cannot rename my `setup.py` to `cutesetup.py`, `s.py` or anything else? It already allows to use a different `tox.ini` file with the option `-c cutetox.ini`. But perhaps it is not required a new setting and I can use `skipsdist=true` and call manually `python setup install`

https://github.com/tox-dev/tox/blob/0fb3b7c6328134405bde00084eef2061ab827485/tests/test_quickstart.py#L310-L315

If I use this, it has the same effect
```ini
[tox]
envlist = py27,py34
skipsdist=true

[testenv]
whitelist_externals=*
commands =
    python setup install
    python tests/run_tests.py
```

As something like?
```ini
[tox]
envlist = py27,py34
pythonsetup=setup

[testenv]
whitelist_externals=*
commands =
    python tests/run_tests.py
```

**Comment by obestwalter** [comment]
@evandrocoan - yes I think this should have the same effect, I guess. Is that a known bug in sublime text, that you have to hide `setup.py` from it to be able to work properly?

**Comment by evandrocoan** [comment]
It is just how Sublime Text loads its packages which are `.py` files, then everything under the first folder level is loaded.

**Comment by rpkilby** [comment]
btw, SublimeText has the `folder_exclude_patterns` and `file_exclude_patterns` settings.

**Comment by evandrocoan** [comment]
Thanks, but that is for project files. On this case it is for their plugins loading (internal development stuff for Sublime Text plugins maintainers).

**Comment by obestwalter** [comment]
I woud propose to close this, as this is clearly a sublime text bug and @evandrocoan  already found a solution in tox to work aroud that bug.

**Comment by evandrocoan** [comment]
It is close a since a long time.

**Comment by obestwalter** [comment]
oops - stupid me ... sorry, I just saw your last answer and thought this is still being discussed.

**Comment by evandrocoan** [comment]
As I already have a working solution, with `skipsdist=true`, there is not need for further support by `tox`. However, I just would like to point out that, renaming `setup.py` to `setup` or anything else, will break the installation thorough [pypi.python.org/pypi](pypi.python.org/pypi) as the installer will search for `setup.py`.

**Comment by vlcinsky** [comment]
@evandrocoan yes, you are perfectly correct in that renaming `setup.py` into anything else is simply asking for bunch of problems everywhere.
