### ISSUE TITLE
Transfer tox-pipenv to tox-dev?

### ISSUE THREAD

**Issue by tonybaloney** [tox-dev/tox#771]
This is a question for the contributors to the Tox project.

Would you like me to transfer ownership of tox-pipenv to this organization?

https://github.com/tonybaloney/tox-pipenv

The project has started getting external contributors and PRs, so it's picking up a bit of momentum. The placement of pipenv in place of virtualenv as the "official" development environment tool means it shouldn't really live in my personal github org.

Happy to continue patching and developing the project if you want me to move it.

**Comment by obestwalter** [comment]
Hi @tonybaloney, we came up with a [few guidelines](https://github.com/tox-dev/tox/blob/master/CONTRIBUTING.rst#submitting-plugins-to-tox-dev) regarding that, if that sounds good to you and the plugin meets the requirements, we can do this. I will send you an invitation to our org and you can move the repo here, when it's convenient. Keep in mind that you will have to update some references and links in your setup, project descriptions and CI settings. In the guidelines there is also a doc link about how repo transferrals work and how to do this, in case you never did this before.

**Comment by tonybaloney** [comment]
Thanks oliver. Project looks to tick all of those boxes. I will double check everything beforehand.

**Comment by tonybaloney** [comment]
@obestwalter can you send the invite please? Then I can initiate the move

**Comment by obestwalter** [comment]
done :)

**Comment by tonybaloney** [comment]
done!

**Comment by obestwalter** [comment]
Welcome to the team :)
