### ISSUE TITLE
detox redirecting stdout to a log file

### ISSUE THREAD

**Issue by laurenyu** [tox-dev/tox#781]
I've noticed that when I use detox, instead of printing to the console like tox does, it instead saves the output in a file. Is there a way to have everything print out instead?

I've had this behavior on both an EC2 instance and a Mac

EC2 environment:
* GNU/Linux
* pip list:
aws-cfn-bootstrap (1.4)
awscli (1.14.9)
Babel (0.9.4)
backports.ssl-match-hostname (3.4.0.2)
boto (2.48.0)
botocore (1.8.13)
certifi (2018.1.18)
chardet (3.0.4)
cloud-init (0.7.6)
colorama (0.2.5)
configobj (4.7.2)
detox (0.11)
docutils (0.11)
ecdsa (0.11)
enum-compat (0.0.2)
enum34 (1.1.6)
eventlet (0.21.0)
futures (3.0.3)
greenlet (0.4.12)
idna (2.6)
iniparse (0.3.1)
Jinja2 (2.7.2)
jmespath (0.9.2)
jsonpatch (1.2)
jsonpointer (1.0)
kitchen (1.1.1)
lockfile (0.8)
MarkupSafe (0.11)
paramiko (1.15.1)
PIL (1.1.6)
pip (9.0.1)
pkginfo (1.4.1)
pluggy (0.5.2)
ply (3.4)
py (1.4.34)
pyasn1 (0.1.7)
pycrypto (2.6.1)
pycurl (7.19.0)
pygpgme (0.3)
pyliblzma (0.5.3)
pystache (0.5.3)
python-daemon (1.5.2)
python-dateutil (2.1)
pyxattr (0.5.0)
PyYAML (3.10)
requests (2.18.4)
requests-toolbelt (0.8.0)
rsa (3.4.1)
setuptools (36.2.7)
simplejson (3.6.5)
six (1.8.0)
teamcity-messages (1.21)
tox (2.8.2)
tqdm (4.19.6)
twine (1.10.0)
urlgrabber (3.10)
urllib3 (1.22)
virtualenv (15.1.0)
yum-metadata-parser (1.1.4)

Mac environment:
* Darwin Kernel Version 16.7.0
* pip list:
boto3 (1.6.15)
botocore (1.9.15)
detox (0.11)
docutils (0.14)
eventlet (0.22.1)
flake8 (3.5.0)
greenlet (0.4.13)
jmespath (0.9.3)
mccabe (0.6.1)
numpy (1.14.2)
pip (9.0.3)
pluggy (0.6.0)
protobuf (3.5.2.post1)
py (1.5.3)
pycodestyle (2.3.1)
pyflakes (1.6.0)
python-dateutil (2.6.1)
s3transfer (0.1.13)
setuptools (39.0.1)
six (1.11.0)
tox (2.9.1)
virtualenv (15.2.0)
wheel (0.30.0)

**Comment by obestwalter** [comment]
Hi @laurenyu, if I am not completely mistaken, this is because the output of all the parallel tox runs would cause a big muddle if printed directly to stdout.

**Comment by laurenyu** [comment]
Thanks for getting back to me!

Is there a way to at least have limited information printed out, e.g. when a test fails, which test and which run configuration it is?

**Comment by obestwalter** [comment]
TBH I don't really use detox myself, so I can't say :(

**Comment by obestwalter** [comment]
FWIW - maybe it is a good solution for you, if you tail the log files in a handful of consoles?

**Comment by laurenyu** [comment]
Unfortunately, that doesn't work for my particular use case (can only have one console output), but I'll find some workarounds. Thanks for your help!

**Comment by obestwalter** [comment]
o.k. - maybe leave this bug hanging around open for a while. There is a chance somebdoy else will have an idea how to deal with that :crossed_fingers:.

**Comment by obestwalter** [comment]
Kamino closed and cloned this issue to [tox-dev/detox](https://github.com/tox-dev/detox/issues/18)
