### ISSUE TITLE
Non working latest pip in combination with Jython

### ISSUE THREAD

**Issue by frenzymadness** [tox-dev/tox#782]
Hello.

I am trying to test really simple project [0] in Docker container based on the latest stable Fedora (27) [1].

The problem is that tox installs the latest pip into Jython virtual environment but the latest pip (9.0.3) and the latest Jython (2.7.1) are not compatible.

There is an issue in pip project [2] but from comments it seems that pip is not officially supported on Jython. There is also a bug in Jython bug tracker to solve pip incompatibility [3].

What I think would be best here is not to try to install the latest pip in Jython virtual environment and use pip which comes from Jython installed by `jython -m ensurepip`. What do you think about it? Is there any other way how can I pin pip version in tox virtual environment?

Thanks a lot for your work!

[0] https://github.com/frenzymadness/python-tox-example
[1] https://github.com/frenzymadness/fedora-python-tox/
[2] https://github.com/pypa/pip/issues/5121#issuecomment-376794089
[3] http://bugs.jython.org/issue2660

**Comment by gaborbernat** [comment]
Our jython support is best effort as we don't have any meaningful tests for it. And we only aim to run latest pip. If it does not work with pip 18.0 please reopen the issue but I'll close this now.
