### ISSUE TITLE
Unable to upgrade pip on Windows

### ISSUE THREAD

**Issue by jaraco** [tox-dev/tox#786]
I'd like to start testing some select projects against the pending pip 10 release. To do so, in rwt, I've added [this commit](https://github.com/jaraco/rwt/commit/5eebddbd8bdfa53ded6cc3c9944a33a121d46dde). Unfortunately, that leads to [this failure](https://ci.appveyor.com/project/jaraco/rwt/build/job/yh0xfkey0mecqsul) when running on Windows.

As a seasoned Windows user, I know exactly what's going on here. It's a longstanding weakness in Windows - it's difficult if not impossible to replace a file that's in use. And since pip.exe is in use, pip can't upgrade itself.

Fortunately, there's a workaround.

Instead of invoking `pip install`, use `python -m pip install`. As pip doesn't have any binary dependencies (shared libraries), all the modules will be loaded and their files closed immediately, allowing pip to upgrade itself. This technique also works on Unix-based systems so can be applied uniformally.

Is another workaround possible? preferable?

**Comment by jaraco** [comment]
I found another workaround in jaraco/rwt (referenced in the commit above) by creating a custom build command that first upgrades pip (using `python -m pip`), then installs everything else with the new pip.

**Comment by gaborbernat** [comment]
This has been done a while ago and released with 3.2.0
