### ISSUE TITLE
tox behavior is unclear when generative envdeclarations are used and a factor of an environment name is passed as envlist with -e.

### ISSUE THREAD

**Issue by tvalentyn** [tox-dev/tox#787]
Consider the following config: 
```
[tox]
envlist = {py27,py3}-lint 
...
```
There are only two valid environments:
```
tox --listenvs-all
py27-lint
py3-lint
```
However tox seems to happily accept: ```tox -e lint```. What is supposed to happen in this case? I would expect one of two behaviours: 

1. Fail. 
2. Same result as if I ran ``` tox -e py27-lint,py3-lint ```. 

None of the alternatives seems to be the case.
Steps to reproduce:
```
git clone https://github.com/apache/beam.git
cd beam/sdks/python 
tox -e lint
```

**Comment by gaborbernat** [comment]
In tox 4 users are allowed to run environments not in the tox file, so in this case the lint environment will be run.
