### ISSUE TITLE
Does not recreate env if extras change

### ISSUE THREAD

**Issue by blueyed** [tox-dev/tox#793]
When changing `extras` of a venv config it will not trigger recreation of the venv.

This is because `extras` is not stored in [CreationConfig](https://github.com/tox-dev/tox/blob/e603f78e8438eadfb5e4067868096e377d3556ca/tox/venv.py#L14), which is used to compare new vs. old/cached.

The easy fix is to add `extras` there (next to deps in some way), but the better fix would be to actually resolve `extras` into deps, so that it would also recreate the env if `extras_require` changes (in setup.py).

Related: https://github.com/tox-dev/tox/issues/149

tox 3.0.0rc3.dev17.

**Comment by gaborbernat** [comment]
This now has been fixed in tox 4.
