### ISSUE TITLE
detox: Print how many tests were run

### ISSUE THREAD

**Issue by melissachang** [tox-dev/tox#795]
When I run `tox`, I see:
```
Ran 1 test in 0.000s
```
`detox` doesn't show that line. Is that intentional?

Repro:
* Put into `tox.ini`:
```
[tox]
envlist = py27
skipsdist=True
[testenv]
commands=python test.py
```
* Put into `test.py`:
```
import unittest

class TestStringMethods(unittest.TestCase):

    def test_upper(self):
        self.assertEqual('foo'.upper(), 'FOO')

if __name__ == '__main__':
    unittest.main()
```
* Running `tox`:
```
py27 runtests: PYTHONHASHSEED='1989219226'
py27 runtests: commands[0] | python test.py
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
___________________________________ summary ____________________________________
  py27: commands succeeded
  congratulations :)
```
* But `detox` doesn't show # of tests. I don't know if no tests were run, or if test was run and passed.
```
py27 runtests: PYTHONHASHSEED='1498194232'
py27 runtests: commands[0] | python test.py
___________________________________ summary ____________________________________
  py27: commands succeeded
  congratulations :)
```

**Comment by obestwalter** [comment]
Hi @melissachang - all output above the summary line comes from what tox executes - not from tox directly. As detox runs several environments in parallel it collects the results in log files named like the environments in the tox workingdirectory (.tox in your project by default) (in your example case that would be `.tox/logs/py27`).

AFAIK (I am not using detox myself much) it does only output and not (yet) the normal output, so you have to check for details of successfull runs in the log.

**Comment by obestwalter** [comment]
Kamino closed and cloned this issue to [tox-dev/detox](https://github.com/tox-dev/detox/issues/26)
