### ISSUE TITLE
Configure coverage

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#802]
Until now we used the default settings. They can do with a bit of tweaking though.

**Comment by gaborbernat** [comment]
Can you detail what type of tweaking you recommend and why?

**Comment by obestwalter** [comment]
I introduced coverage last year without thinking much about what that means and I think it is helpful to get an idea about tests, but for me it is not something that should tell the contributor that their PR is bad, because it reduces coverage by 0.01% so this is what this issue is about.

* exclude _verlib.py as that is vendored in and not tested
* reduce precision
* round to nearest instead of rounding down
* Be o.k. with 95% coverage instead of creating some kind of pressure that we need 100%

See e.g. https://labs.ig.com/code-coverage-100-percent-tragedy

**Comment by obestwalter** [comment]
BTW - I committed the default settings first, so you can chck the changes directly: https://github.com/tox-dev/tox/pull/804/commits/281dca90064f0845d026615bbe743e9826585efb
