### ISSUE TITLE
`tox -e docs`: linkcheck very flaky

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#806]
This check is definitely useful and should be done regularly, but sadly is very flaky.

This is what I can think of:

* remove it from normal builds and make this check a part of the release, still having a regular check for dead links but having less flaky builds.
* wrap this step to be a proper test and introducing [pytest-rerunfailures](https://github.com/pytest-dev/pytest-rerunfailures) to the mix.
* run these checks every time but not fail, if dead links are detected (my least favorite appproach, because those tests tend to be ignored then)

**Comment by gaborbernat** [comment]
what about 3 and 1 together :smile:

**Comment by gaborbernat** [comment]
With the implementation of https://github.com/sphinx-doc/sphinx/issues/7388 I think this should be less of an issue, so I'll enable the check unconditionally on the rewrite branch and see where it goes.
