### ISSUE TITLE
master branch does not contain release 3.0.0

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/tox#808]
@obestwalter I think because you released and tagged the feature branch. This messes up our versioning because setuptools-scm still thinks master is 3.0.0rc3...

**Comment by obestwalter** [comment]
Yes, I also noticed that. I cherry picked the commit but did not move the tag. I will have to do some homework to figure out how to do that correctly. Might not be such a fantastic idea to have that release branch after all.

**Comment by gaborbernat** [comment]
Thinking through this I think this is in general limitation of feature branches. When creating release branches maybe we should in parallel mark the master alpha of next version: e.g. ``3.1a``?

**Comment by obestwalter** [comment]
This would be one way. I did not look into it further yet, but otherwise we'd actually have to move the tag from the branch to master, which then breaks the versioning on the branch and lies about what was the actual commit from which the release was cut.

**Comment by gaborbernat** [comment]
Yeah, that's why I would force creation of an alpha. CPython does it similarly.

**Comment by obestwalter** [comment]
I'd say let's use the alpha version approach then and let's tag 558f18b74e3ecfc203963165fcc8af15ba6673d4 - the cherry picked changelog update for 3.0 with 3.1a, ok?

**Comment by gaborbernat** [comment]
3.1 went out, let's leave it on the feature branch as it is :+1:
