### ISSUE TITLE
PyCon 2018 tox sprint

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#815]
I know that a few people want to sprint on tox and I was looking forward to participate remotely, but sadly my step father has just passed away suddenly, so I will be travelling home to support my mother and am not 100% sure how the next days will be, but I think I can use some distraction by being involved in some positive remote collaboration, so I will try my best to be available during sprint hours in Cleveland to assist the sprinters wherever I can.

Here is some information to help finding topics and org:

## Newcomers of all ages, sizes, colours and genders welcome :)

Some pointers to get started ...

### "Easy" issues

Some issues are labelled with a rough estimate of how hard this would be to implement or fix (easy/medium/hard), this should be taken with a grain of salt though, but maybe it is a good idea to check out the [easy tasks](https://github.com/tox-dev/tox/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Alevel%3Aeasy) for starters.

### Improve the documentation

tox could really use some friendlier documentation that helps newcomers to wrap their head around what it does. Especially the README could do with some good introductory examples and explanations. plugins should also be mentioned in the README already, because they become more and more important for tox (see #819).

### Projects

There are some [projects](https://github.com/tox-dev/tox/projects) grouping areas needing improvement, e.g. around [squashing bugs](https://github.com/tox-dev/tox/projects/1).

### Conda support for tox

There was also some interest working on [adding support for conda](https://github.com/tox-dev/tox/issues/273). I have that on my backlog and started a skeleton for the plugin already [here](https://github.com/tox-dev/tox-conda). Help would be very appreciated as I am not an active conda user myself and should not tackle that topic on my own due to that anyway.

## #pylib on IRC

I am usually not an avid chatter, but for the purpose of the sprint to have some realtime org, I will also be joining the #pylib channel on [freenode.irc](https://freenode.net/) (that is like Slack or [Gitter](https://gitter.im/tox-dev/Lobby), but old skool ([howto](https://freenode.net/kb/answer/chat))), but ideally the topical discussion should be focussed in the affected issues.

## Release after the sprint

There are some big refactorings with focus on future proofing and maintainability already merged since 3.0 and the aim is to do a 3.1 release with these refactorings and hopefully some bug fixes and new features shortly after the sprint.

Whatever you do: have fun at the sprints!

**Comment by gaborbernat** [comment]
@obestwalter Will do a release in the next days; just so we can test how well I'll get along with what we have.

**Comment by obestwalter** [comment]
Good idea - go on then and ping me if you have any questions.
