### ISSUE TITLE
Add automatic reformating of rst/md docs to pre-commit?

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#818]
One thing that could also use some automation, is the consistent formating of line breaks in rst/md doc text paragraphs. Is there a tool that does this, we could add as a pre-commit hook?

**Comment by gaborbernat** [comment]
@asottile any ideas for this?

**Comment by asottile** [comment]
I haven't worked with any tools that format markdown or rst -- it does seem like something the community at large would appreciate though!

**Comment by obestwalter** [comment]
I checked around a bit and there seems to be no such tool (yet), so I'll close this as a luxury item that we don't really need.
