### ISSUE TITLE
Improve the README

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#819]
The README is a bit terse and not a good starting point yet. I think it should already explain the most important concepts and have some good examples for basic usages showacsing some important functionality. A lot can be filched from the existing docs and edited for the README, I think.

Some things to mention:

* tox-quickstart
* plugins
* environment substitution
* posargs
* tox as CI frontend and developer task automation tool (not just for testing/packaging), e.g. build docs, pre-commit, etc.
* testing projects that don't even have a setup.py with `skipsdist`
* testing projects that don't build a package with `skispddist` + `usedevelop`
* ...

It could also be written in Markdown now, as the new https://pypi.org supports it.

**Comment by ssbarnea** [comment]
I would add a section about tox related projects, official and non-official ones, plugins or stanalone. This would be very useful for users, and also avoid cases where people would ask about features that are already provided by a 3rd tool or extension.

**Comment by gaborbernat** [comment]
I think we approved and merged the PR.
