### ISSUE TITLE
tox-flit support

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/tox#820]
requested by @warsaw 

pip will eventually add PIP-517 support, in the meantime users could use tox with flint by creating a plugin; this is a followup ticket to see how we can achieve that

**Comment by warsaw** [comment]
Actually, [flit](http://flit.readthedocs.io/en/latest/)

**Comment by gaborbernat** [comment]
So the idea would be to create a plugin for this, see http://tox.readthedocs.io/en/latest/plugins.html and let me know what else you need :-)

**Comment by gaborbernat** [comment]
Done via #954.

**Comment by alanjds** [comment]
@gaborbernat: I saw the PR #954 and still am wondering how to use tox with flit. Can you clarificate?

```sh
nondjango-storages alanjds$ tox -e py36
ERROR: No setup.py file found. The expected location is:
  /Users/alanjds/src/git/nondjango-storages/setup.py
You can
  1. Create one:
     https://packaging.python.org/tutorials/distributing-packages/#setup-py
  2. Configure tox to avoid running sdist:
     https://tox.readthedocs.io/en/latest/example/general.html#avoiding-expensive-sdist
```

**Comment by gaborbernat** [comment]
https://tox.readthedocs.io/en/latest/example/package.html#flit

**Comment by alanjds** [comment]
Oops. Sorry. Got it.
https://tox.readthedocs.io/en/latest/example/package.html#flit
