### ISSUE TITLE
python -m detox doesn't propagate returncode

### ISSUE THREAD

**Issue by alexrudy** [tox-dev/tox#825]
```
python -m detox -e my-failing-environment; echo "Exit code $?"
```

In https://github.com/tox-dev/detox/blob/master/detox/__main__.py the call to `main()` should be wrapped in a call to `sys.exit()`.

**Comment by gaborbernat** [comment]
Pls^opken this issue under the detox repo👌

**Comment by obestwalter** [comment]
It‘s ok - detox stuff belongs here also. It‘s a bit confusing I admit. We hope to merge detox into core.

**Comment by alexrudy** [comment]
The readme says to open it here (https://github.com/tox-dev/detox/blob/master/README.md) and issues are disabled on detox. Unfortunately, I can't seem to set the `detox` label here either.

**Comment by obestwalter** [comment]
Kamino closed and cloned this issue to [tox-dev/detox](https://github.com/tox-dev/detox/issues/17)

**Comment by obestwalter** [comment]
detox has its own issue tracker now :)
