### ISSUE TITLE
Improve --notest documentation

### ISSUE THREAD

**Issue by webknjaz** [tox-dev/tox#829]
- [x] a clear problem statement with an example

When running tox in CI there's often job step separation and failures in different kinds of stages are accounted differently. For example, in Travis CI its error/failure depending on whether the command is failing in install of script step.

- [x] suggested change with example

I'd like to see smth like `--skip-command` flag or smth like it for pre-populating env (installing deps), which I'd run in the `install` stage, and then I'd run normal tests, for which tox would reuse env created earlier.
This would help separate different logical steps of doing automatic testing in CI.

**Comment by obestwalter** [comment]
He @webknjaz, thanks for the suggestion. If I understand you correctly you are looking for the sadly undercocumented `--notest` flag, which skips running the commands?

**Comment by webknjaz** [comment]
oh.. looks like it. I'll tell more once get to testing it. thanks :)

**Comment by gaborbernat** [comment]
I myself don't entirely understand the use case. Let us know what you have a full example of what you're trying to achieve.

**Comment by webknjaz** [comment]
`.travis.yml`:
```yaml
install: tox --notest  # installs deps
script: tox  # runs tests
```
This is what I wanted and the suggestion works for me

**Comment by gaborbernat** [comment]
How would this manifest differently on Travis as opposed to not having the install phase? Is it purely for caching purposes?

**Comment by webknjaz** [comment]
It's (1) separate in log and (2) produces different type of build error on `install` step, than `script` step failures do. And also (3) sometimes there's spaghetti-like machinery script running tests and it's just less messy when done separately in other explicit step.
