### ISSUE TITLE
tox drops double quotes from executed commands output, making them confusing

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox#845]
Apparently when tox prints the executed commands it does not keep them in their original form and drops the double quotes, making them really confusing and invalid.

Content in tox.ini:
```
commands =
        bash -c "git ls-tree --full-tree --name-only -r HEAD plugins | grep -E '\.ya?ml$' | xargs -I FILE -n1 -P 4 ansible-lint --force-color -q -p -x $SKIPPED FILE"
```

Sample output:
```
ansible-lint runtests: commands[1] | bash -c git ls-tree --full-tree --name-only -r HEAD plugins | grep -E '\.ya?ml$' | xargs -I FILE -n1 -P 4 ansible-lint --force-color -q -p -x $SKIPPED FILE
```

As you can see the quotes that mark the bash command to be executed are lost, so if anyone tries to copy/paste the command, it will fail to run because what is printed on screen is invalid.

**Comment by gaborbernat** [comment]
Yeah, we need to fix that somehow. One thing mind you in general commands need to run both under Windows and Linux; so AFAIK we do some sanitizing on them. Will double check.

**Comment by asottile** [comment]
probably somewhere we're doing `' '.join(...)` and we need to `' '.join(pipes.quote(p) for p in ...)`
