### ISSUE TITLE
Tox Report exclude_lines

### ISSUE THREAD

**Issue by Ademord** [tox-dev/tox#846]
Hello!
I am trying to exclude code in the tox report, from what I gathered online I am trying to use the following in my **tox.ini** file:
```
[report]
exclude_lines=
    pragma: no cover
    pragma: ${MYSQL_TESTS} cover

```
But it doesn't seem to work, especially for the **environment variable** (spawning a docker container where I run all tests), for example **MYSQL_TESTS=NO**.

Could someone help me out please? Am i setting this wrong? On my code i have it something like

- for env. variable pragma, expecting the whole function/class to be excluded:
```
def foo(params):  # NO cover
    ...
```
- for normal pragma, expecting the whole function/class to be excluded:
```
def foo(params):  # no cover
    ...
```

**Comment by gaborbernat** [comment]
Are you talking about coverage report? Tox does not have a report section.

**Comment by Ademord** [comment]
Indeed! This report right here:

![screenshot 2018-06-13 10 02 18](https://user-images.githubusercontent.com/4501464/41337909-eb5286e2-6ef0-11e8-9813-d1ed895e4538.png)

The way I run my tests is:

```
[tox]
envlist = py36
setupdir = /app/src/

[testenv]
passenv = *

deps =
        --upgrade
        -r/app/src/requirements.txt
        -r/app/tests/requirements.txt

commands =
        nosetests -w /app/tests --with-xunit --xunit-file=/output/nosetests.xml \
            --with-coverage --cover-erase \
            --cover-package=adapters --cover-package=esm \
            --cover-min-percentage=70
        codecov -e TOXENV
```

**Comment by gaborbernat** [comment]
In this case, you'll need to contact the ``nosetests`` maintainer with the issue. You just use tox to invoke the tests, but tox does not generate the report and as such is out of the scope of this repository.
