### ISSUE TITLE
PEP-518 wheel support

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/tox#850]
We'll add PEP-518 support by exposing the following:

- option to replace ``python setup.py sdist`` with ``pip wheel`` to build packages,
- this builds wheel instead of ``sdist``,
- we'll install wheels inside environments instead of ``sdist``s. 

The benefit of doing this is that now users can specify their project dependencies for ``setuptools`` projects by using ``pyproject.toml``.

**Because sometimes ``sdist`` may be prefered and pip does not support building those yet; for now we'll expose it with an on-demand ``build = wheel`` tox config. By default ``build = sdist`` and this will keep doing ``python setup.py sdist``.** Once pip supports building ``sdist`` we'll replace ``python setup.py sdist`` with that command.

Will create the PR for this in the following days. 

Full PEP-517 support (e.g. flint, etc is tracked by https://github.com/tox-dev/tox/issues/573).

**Comment by rpkilby** [comment]
This may require changing some CLI and ini options. `--sdistonly`, `skipsdist`, and `sdistsrc` don't make as much sense given that we may be using wheels. Possibly add `--distonly`, `skipdist`, and `distsrc`, leaving the original for backwards compatibility?

**Comment by gaborbernat** [comment]
@rpkilby yeah I know, we'll need to shim them around. I would propose the word ``packaging`` instead of ``dist``.

**Comment by gaborbernat** [comment]
This has now been retired. The plan is to first trial wheel support via a plugin outside of the core.

**Comment by gaborbernat** [comment]
No immediate plans as they are other pressing core issues. I'll happily review it though and we'll host it under our organisation if you go ahead with it.

**Comment by rpkilby** [comment]
btw - I haven't pursued this any further yet. It's on my eventual todo list, but there are a lot of other things on my plate that have higher priority. For now, building the wheel outside of tox and using the `tox --installpkg` argument has been sufficient.

Note to self: complications mentioned in https://github.com/tox-dev/tox/issues/232#issuecomment-452686462.

**Comment by gaborbernat** [comment]
Done under https://github.com/ionelmc/tox-wheel

**Comment by rpkilby** [comment]
nice 👍
