### ISSUE TITLE
Environment variable substitution in tox.ini

### ISSUE THREAD

**Issue by cyberjoac** [tox-dev/tox#868]
Hi,
I'm trying to load environment variable in tox.ini as explained in the documentation.
```
[tox]
envlist = {env:PYTHON_ENV:27}
```
But without success. Is is possible to do variable substitution only in `[testenv]` part of the tox.ini ? 

Thanks !

**Comment by obestwalter** [comment]
Hi @cyberjoac, you are correct that this substitution does not work there. Subsitution is not fully generalized. It grew more on a per-need basis. There is an issue about this general thing here: https://github.com/tox-dev/tox/issues/97

What you are trying to do might be better accomplished to create an envlist with all the interpreters you want to support (e.g. `envlist=py27,py36`) and then choose them directly when calling tox, if you only want to use one (e.g. `tox -e py27`).

BTW: The envlist is creating factorized env names and these envlists are static in most simple scenarios. What ou can do is generate matrixes for different combinations of interpreters and activities (e.g. see [here](https://tox.readthedocs.io/en/latest/example/basic.html#compressing-dependency-matrix)).

**Comment by cyberjoac** [comment]
Thanks!

**Comment by gaborbernat** [comment]
What you want to achieve there is built in per https://tox.readthedocs.io/en/latest/config.html#confval-envlist=CSV.

``
[tox]
envlist = py27
```

You can then do:

```
TOXENV=py36 tox
```
