### ISSUE TITLE
3.1.0 release documentation remains raw

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/tox#879]
see https://pypi.org/project/tox/3.1.0/
![screenshot-pypi org-2018 07 08-21-58-34](https://user-images.githubusercontent.com/690238/42423879-12828ccc-82fa-11e8-808a-1a542dd0fb56.png)

**Comment by obestwalter** [comment]
Hi @gaborbernat, have a look at my old release script. There was a check in there that can prevent this.

**Comment by gaborbernat** [comment]
Seems this is because we have content that cannot be parsed by PyPi. Fixed it inside #883 Will release as a bugfix today ``3.1.1``.

**Comment by obestwalter** [comment]
Releasing a change that does not affect the code and only fixes meta data could be done as a post release instead of a patch release.
