### ISSUE TITLE
CI usage review

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/tox#888]
Travis.org uses the now deprecated Github Services API. There does not seem a webhook or Github App version of this. However, there's an option to move to travis.com - see https://docs.travis-ci.com/user/open-source-on-travis-ci-com/. 

An alternative is to migrate our dual CI (Travis+AppVeyor to Visual Studio Team Services used now by CPython). Having a single CI might help with automating the release operation (e.g. now we don't test that during release the CI passes on Windows).

**Comment by rpkilby** [comment]
Worth noting - it looks like CPython uses VSTS in addition to Travis+Appveyor. I'm not sure what the reason for this is.

**Comment by gaborbernat** [comment]
Mainly because VSTS is in trial phase over there. I've spent three hours trying to set up VSTS, and until now I only managed to conclude their documentation is really bad.

**Comment by obestwalter** [comment]
Oh dear ...

**Comment by gaborbernat** [comment]
So we've moved over to Azure Pipelines and we'll stay here for the time being. Full release automation still requires some additional work; but that's a different ticket (github release bot).
