### ISSUE TITLE
skip missing interpreters should be a toggle-able flag

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/tox#903]
It makes sense to set skip missing interpreters inside the tox file to ensure that users locally don't get failures for interpreters they don't have. In this cases, it should be still possible to override that and force not skipping missing interpreters in the CI environment for example.

**Comment by anthrotype** [comment]
Yeah, I like the idea of being able to set skip_missing_interpreters to false, but only when running in a CI environment. Maybe some command-line option or environment variable could be used to override the default setting in the tox.ini.

**Comment by gaborbernat** [comment]
Yeah, that was my thought too :+1: I might go for the command line version as that's more explicit I believe.

**Comment by gaborbernat** [comment]
@obestwalter the fact is ``--skip-missing-interpreters`` is often what people want, so they set it more often than not to true via the config (we do this ourselves). The problem is once this is set to true inside the config there's no way at the moment to unset it at invocation side. 

A simple use case of this is that if you set ``skip-missing-interpreters`` to true inside the config and then miss-configure your CI (so that a given Python is not available) the CI will succeed even though the tests could not be run (because you'll just fail). 

I think the root problem here is that skip missing interpreters should really default to true. And then have a flag of ``fail-on-missing-interpreters`` that the people can use in the CI env.  However, this would break our backward compatibility so what I envision is ``skip-missing-interpreters[=1]`` so that inside the CI people can do ``skip-missing-interpreters=0`` to force failure if a given Python is missing.

**Comment by obestwalter** [comment]
Now I understand - thanks. I like your solution also. Keeps the default, but would make the config setting overridable by the commandline then.
