### ISSUE TITLE
Differentiate between python environments in Junit Jenkins plugin

### ISSUE THREAD

**Issue by jhagege** [tox-dev/tox#911]
I am running two sets of pytest tests, one for py27 and one for py37 (inside tox framework if it can help)

The test results are saved in two files: test_27.xml and test_37.xml

I'd like to differentiate between the Python versions in the Jenkins interface.
Is there any way to do that with Junit Jenkins plugin ?

Maybe dynamically generate test names with python env as suffix ? 

Could you think of any workaround ?

Thanks !

![image](https://user-images.githubusercontent.com/7504908/42733595-4be69fa2-883c-11e8-968c-2f33e317568b.png)

**Comment by obestwalter** [comment]
Hi @jhagege, although there is a bit of historic special handling for Jenkins, tox is pretty much CI agnostic. 

I don't use Jenkins myself and have no idea what the Junit Jenkins plugin does, but I would assume that it is possible that you run the two environments as separate testruns, which would automatically result in two different test reports coming from different test jobs or whatever you call them in Jenkins. You would have two Jenkins "jobs" then (which also could run in parallel). One calling `tox -e py27` and the other calling `tox -e py37` and you would have it all neatly separated.

**Comment by jhagege** [comment]
That's a great option that I may use in the future.
In the meantime, I found on StackOverflow (https://stackoverflow.com/questions/41328882/change-pytest-testsuite-name-in-xml-report) another workaround (pytest-dependent):
`pytest ... -o junit_suite_name=my_suite`

Thanks !

**Comment by obestwalter** [comment]
I am glad, I didn't completely miss the mark here :)

Looking at that SO post, I dug a bit further about Jenkins + tox regarding pipelines and reporting and posted an answer that hopefully is helpful for others.
