### ISSUE TITLE
tox assumes all python installs have virtualenv

### ISSUE THREAD

**Issue by zsimic** [tox-dev/tox#928]
Currently, tox runs virtualenv via `python -m virtualenv ...`.

However, that assumes that virtualenv is installed with the python invoked, that is not always the case (for example: pythons installed via pyenv don't come with virutalenv).

This is annoying, and prevents tox from being packageable standalone (via pex for example), which is something I'd like to do.

A trivial solution for this is to employ the same technique as virtualenv itself uses: invoke virtualenv via `python path/to/virtualenv.py ...`

**Comment by zsimic** [comment]
Context on my side: I'm trying to make tox available to coworkers on OSX without the need to `sudo pip install tox` for several reasons, main one being that OSX doesn't come with `pip` (so one has to get pip first to even be able to `sudo pip install tox`...

To keep this short, to reproduce the problem I'm seeing is: try to package tox via pex (https://pypi.org/project/pex/), and then use the produced package. In your tox checkout folder, activate your dev env and run this:
```
pip install pex
pip --cache-dir dist wheel --wheel-dir dist .
pex --no-index --cache-dir dist --repo dist -ctox -otox tox '--python-shebang=/usr/bin/env python'
head -n1 tox
```

Now, you should have a standalone executable `./tox`, which will be ran by `/usr/bin/env python` (your current python).

Try to run `./tox` -> it will succeed if your current python has virtualenv, but will fail otherwise.
In my case:
- I installed tox via `sudo pip install tox`, so my system python has tox
- I use pyenv to install several versions of python
- if I try and package tox via pex as described, I get errors like this:
```
cmdargs: ['~/.pyenv/versions/3.6.6/bin/python', '-m', 'virtualenv', '--python', '/Users/zsimic/.newt-cache/pyenv/versions/3.6.6/bin/python', 'style']
~/.pyenv/versions/3.6.6/bin/python: No module named virtualenv
```

With my proposed change, this is not an issue anymore: my pex-packaged tox works great.

If you follow the code in virtualenv, you'll see that it is doing exactly that itself (it re-invokes itself with the right python version by re-executing its own file: https://github.com/pypa/virtualenv/blob/master/virtualenv.py#L667-L671)

As an aside, I'm working on a little tool that will make installing/upgrading python CLIs (such as tox, twine, ...) very easy: https://github.com/zsimic/pexy
You can easily get a pex package by adding this to your tox.ini (pexy is still early draft though, it'll be done when I have 100% test coverage)
```
[testenv:package]
changedir = {envdir}
deps = pexy
commands = pexy package {toxinidir}
```
Then:
```
tox -e package
ls -l .tox/package/tox
.tox/package/tox --version
head -n1 .tox/package/tox
```

**Comment by pganssle** [comment]
@zsimic If you already have `pyenv`, you shouldn't need to `sudo pip install` anything, because you can activate a `pyenv` environment and `pip install tox` there. Maybe I'm missing something.

**Comment by zsimic** [comment]
`pyenv` is great yes, and you could install into a pyenv python installation without sudo, but I don't want to do that for several reasons:
- I want to use `tox` from anywhere (not only folders that have the right pyenv python activated)
- I want to keep my pyenv installations pristine
- I want to be able to upgrade pyenv installed pythons any time, and not have to keep injexting tox into them...

Basically I need `tox` to be standalone (not bound to a particular python installation), be upgradable on its own pace, be automatically installable.

Like many companies, we have at my company a common tool that we use to build/test/publish our stuff. I want basically to automate `tox` installation via that tool...

Imagine typing `<tool> build` -> what `<tool>` does:
- auto-installs python, tox, etc... as needed (would apply to python projects only, but `<tool>` also supports java, go etc)
- keeps stuff up to date (ie: python installations via pyenv, tox, ...)
- "builds" the project itself (which in python's case would be more like packaging)

Currently we do indeed `python -m pip install -i ... tox` (with `python` coming from pyenv), that's actually great in docker (wouldn't bother changing it in docker), however on a dev laptop/workstation, I don't like it that much because I like to also be able to just run `tox` (and not always `<tool> tox` if you will...), so I'm looking for a way to auto-install tox standalone...

**Comment by gaborbernat** [comment]
Any updates on this @zsimic ?

**Comment by rpkilby** [comment]
I'm not sure if there's anything for us to do here. Per https://github.com/tox-dev/tox/pull/929#issuecomment-408941479, this is ultimately an issue with pex, and I don't think it's tox's responsibility to work around pex's issues.

**Comment by zsimic** [comment]
I've written this tool to allow me to get a standalone (self-upgradable) `tox`: https://pypi.org/project/pickley/

Works great now.
