### ISSUE TITLE
Tox should be able to detect interactive tty and alter some options based on this

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox#947]
It will be extremely useful if tox would allow users to detect an interactive tty and alter some execution options (like variables).

Example use case: adding `--pdb` to py.test arguments on interactive tty.

Any CI execution would run without an interactive TTY as this would be present only on developer terminal, a case where we may want to use an interactive debugger.

Now this is achievable using bash with something like
```
if [[ -t 1 ]]; then
  tox
else
  tox -- --pdb
fi
```
As you can see this is not only inconvenient but also creates more problems when you have multiple environments.

Reference: https://stackoverflow.com/questions/911168/how-to-detect-if-my-shell-script-is-running-through-a-pipe

**Comment by gaborbernat** [comment]
So basically you want optional command args where the condition would be is interactive TTY?

**Comment by ssbarnea** [comment]
Indeed. Maybe something like `{toxinteractive:--pdb}` could work? I am open to hear other suggestions.

**Comment by gaborbernat** [comment]
I accept that proposal.
