### ISSUE TITLE
PYTHONPATH of virtualenvironment created using tox

### ISSUE THREAD

**Issue by varungbt** [tox-dev/tox#950]
I have a tox.ini file

```
[testenv:py27]
deps= -r{toxinidir}/requirements.txt
setenv =
    PYTHONPATH = {toxinidir}{:}{toxinidir}/helpers
```
I ran the command tox and the virtualenv was created inside .tox/py27

When I activate the py27 environment

```
cd .tox/py7/bin
source activate 
py27 $ echo $PYTHONPATH < gives null>
```
PYTHONPATH is empty though the tox.ini has setenv with PYTHONPATH explicity set

Why is the PYTHONPATH setting itself to null?

**Comment by gaborbernat** [comment]
The ``tox.ini`` settings is only activated added if called via tox. ``tox -e py27`` would ensure that. This kind of out of place activation is not supported.
