### ISSUE TITLE
[BUG] [detox] detox seems to be skipping installation of extras

### ISSUE THREAD

**Issue by webknjaz** [tox-dev/tox#957]
I tried to replace tox with detox and got `pytest` not installed.
I do `detox --notest` and then `detox`, but I also tried running `detox` on my laptop without `--notest` step and behavior is still the same: `ERROR: InvocationError for command could not find executable 'pytest'`.

- [x] Minimal reproducible example or detailed description, assign "bug"
  https://github.com/cherrypy/cheroot/commit/733a772ad5cc18bd3ba86931441818a5face0ce8
- [x] OS and `pip list` output
  Travis CI: https://travis-ci.org/cherrypy/cheroot/jobs/423594044#L1642
  (but reproducible everywhere I tried)

**Comment by webknjaz** [comment]
cc @obestwalter @gaborbernat

**Comment by gaborbernat** [comment]
let's move this under https://github.com/tox-dev/detox/issues, thanks 👍

**Comment by webknjaz** [comment]
Readme says:

> Please file issues as "tox" issues using a "detox: " prefix in the issue title.

So I did :no_good_man:

**Comment by gaborbernat** [comment]
Nice spot there 👍 sorry for this but going ahead I would prefer to move detox issues over there.
