### ISSUE TITLE
Remove user mention from PR template?

### ISSUE THREAD

**Issue by asottile** [tox-dev/tox#959]
I'm not sure the best way to word this to make it clear what _to_ write -- as it is right now every PR pings [this user](https://github.com/superuser) which is probably not good :)

Maybe use some reserved user name? (@admin maybe?), escape the `@`?

**Comment by gaborbernat** [comment]
we just need to update to use the ``:user:`superuser```` format

**Comment by blueyed** [comment]
Done in https://github.com/tox-dev/tox/pull/965.

@gaborbernat 
Is this documented somewhere?  I assume this is a ReST/Sphinx extension?

**Comment by gaborbernat** [comment]
yes, it lives inside conf.py

**Comment by blueyed** [comment]
Cool, good to know.  Thanks!
Ref: https://github.com/blueyed/tox/blob/d8b97045e64e0734b04068102ec4dd3c380161a1/doc/conf.py#L104
