### ISSUE TITLE
Bug?: Tox on Travis sometimes refuses to install the pytest-django package

### ISSUE THREAD

**Issue by akx** [tox-dev/tox#961]
There's a perplexing situation in [this PR](https://github.com/andersinno/django-form-designer-ai/pull/32/files) where tox-3.2.1 refuses to install the pytest-django package in certain builds, see e.g. the second part of this [Travis build log](https://travis-ci.org/andersinno/django-form-designer-ai/jobs/427145472).

For the `py36-django20` environment, it happily runs

> `.tox/py36-django20/bin/python -m pip install Django>=2.0,<2.1 mysqlclient pytest-cov pytest-django xlwt`

but for `py36-django21` (and others; see the failing builds in Travis), it inexplicably runs

> `.tox/py36-django21/bin/python -m pip install Django>=2.1,<2.2 mysqlclient pytest-cov xlwt`

instead.

Since the testenv deps stanza looks like

```ini
[testenv]
deps =
    djcms34: django-cms~=3.4.5
    django111: Django>=1.11,<1.12
    django20: Django>=2.0,<2.1
    django21: Django>=2.1,<2.2
    mysqlclient
    pytest-cov
    pytest-django
    xlwt
```
([source](https://github.com/andersinno/django-form-designer-ai/blob/79e79069bb1c5d0eb8d51fea3e74257bc22cbafe/tox.ini#L16-L25)), I really can't wrap my head around why this would happen.

Everything works fine locally, of course...

```
using tox.ini: /foo/tox.ini
using tox-3.2.1 from /env/lib/python3.7/site-packages/tox/__init__.py
...
  /foo/.tox$ /env/bin/python3.7 -m virtualenv --python python3.6 py36-django21
...
  /foo$ /foo/.tox/py36-django21/bin/python -m pip install Django>=2.1,<2.2 mysqlclient pytest-cov pytest-django xlwt
...
  /foo$ /foo/.tox/py36-django21/bin/py.test -ra --cov form_designer --cov-report term --cov-report html form_designer
...
py36-django21 finish: runtests after 11.50 seconds
  congratulations :)
```

**Comment by akx** [comment]
Seeing the same problem with 3.1.3 (see [here](https://travis-ci.org/andersinno/django-form-designer-ai/jobs/430067362)).

An explicit `install_command` override, as suggested by @gaborbernat, also doesn't fix the issue.

**Comment by asottile** [comment]
I wonder if this is something `tox-travis` is doing?

**Comment by gaborbernat** [comment]
that well could be 🤔

On Sep 18, 2018 19:39, "Anthony Sottile" <notifications@github.com> wrote:

I wonder if this is something tox-travis is doing?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tox-dev/tox/issues/961#issuecomment-422463321>, or mute
the thread

**Comment by gaborbernat** [comment]
@akx can you try to replicate by installing ``tox-travis``?

**Comment by akx** [comment]
Sorry I'd left this hanging. Nope, installing `tox-travis` locally didn't replicate the issue. 😞

**Comment by akx** [comment]
For the time being, I worked around this by adding `pip install pytest-django` to the `commands =` section, but that's hardly an actual solution...

**Comment by gaborbernat** [comment]
@akx does this still happen?
