### ISSUE TITLE
Install local packages with requires

### ISSUE THREAD

**Issue by cristina0botez** [tox-dev/tox#973]
I'd like to be able to install a package in our dev stack BEFORE the other packages are being installed because their `setup.py` depends on this package.
I tried this using the [requires](https://tox.readthedocs.io/en/latest/config.html#confval-requires=LIST) config parameter, but it doesn't seem to support (relative) paths.
Am I using it wrong?
Let me know if there are any other solutions I could try.

**Comment by gaborbernat** [comment]
Requires only asserts for the existence of those packages in the tox host Python environment. If you want build dependencies for your project you want the isolated build and ``pyproject.toml``. If you want dependencies for other projects you should open PRs for them to include their build dependencies inside ``pyproject.toml`` and in the meantime, as a workaround use the ``deps`` to install them before installing the package itself. If these don't answer your question, please detail better what you want to achieve. 

https://tox.readthedocs.io/en/latest/config.html#confval-isolated_build=True|False(default)

**Comment by gaborbernat** [comment]
@cristina0botez does that solve your problem?
